### ISSUE TITLE
"quasar": "^1.9.16", memory leak, `QItem`, `QBtn`, `to` property

### ISSUE THREAD

**Issue by Lin84** [quasarframework/quasar#10005]
in our project we are using:
"quasar": "^1.9.16"
 "vue": "^2.6.10",
"vue-router": "^3.0.3",

During the investigation related to memory lead on IOS and Android,
we noticed, any page that render `QItem` or `QBtn` that using: `to` property for navigation, 
show big memory leak, for example: 

STR
1. create 2 pages 
2. on each page have only  button to navigate from what 1 page to the other and back, where we use `to`:
`<QBtn flat label="navigate" to="/some-route" />`

after like 10 navigation you probably will notice the increase in JS heap that got stuck in memory.
this image is from our project, where we tested using similar Step to reproduce as described above:
tested on Samsung J7
https://monosnap.com/file/MOA0u16MNu01Zv5nTS7SrBa6BPqSdt

in comparison this is result after we replace that `to` property with `@click` handler
https://monosnap.com/file/RSwHw1PxWHILEoCrSgPrALHzDBX6hn

**Comment by rstoenescu** [comment]
This is at best a leak in Vue Router v3. QBtn, QItem etc only use `this.$router.resolve(this.to)` and `this.$router.replace/push()` methods.

Please provide a minimal reproduction repo so the culprit can be investigated. Otherwise, it can be any of Vue, Vue Router, Quasar, any package that you are using or your own code at fault.

**Comment by pdanpdan** [comment]
Please reopen when you have a test case. Thank you.
