### ISSUE TITLE
Avoid hard-coded (text) colors

### ISSUE THREAD

**Issue by tvkit** [quasarframework/quasar#10014]
**Is your feature request related to a problem? Please describe.**
Unable to uniformly change text color in default "light" theme

**Describe the solution you'd like**
Use css vars instead of hard-coded color values within all Quasar components

**Describe alternatives you've considered**
Currently setting preferred color locally via _class/style_ attributes

**Additional context**
Generally, the documented _.body--light_ class is working well
```
.body--light {
  color: var(--light-text);
  background-color: var(--light-background);
}
```
Here's an example of a hard-coded text color within the QTable component
https://github.com/quasarframework/quasar/blob/e45f30a445384780674de8901953fbf6aaf1c732/ui/src/components/table/QTable.sass#L39

**Comment by rstoenescu** [comment]
Hi,

Those are the "default" colors, cause **we actually need some colors**, whatever they may be. When Dark mode is applied, it has some other default ones to match it.

However, when other colors are needed or customizing like you do, the developers should use class/style attributes and apply their necessary classes/style.

When it comes to "why don't we use .body--light/dark selectors" for these colors, then the answer is simple. If we use a more complex selector (.body--light .q-table__card) then it's harder to override the colors (you need an equivalent CSS rule instead of directly targeting .q-table__card). Furthermore, "bg-*" and "text-*" will stop working because their selectors are less specific than the `.body--light ...` ones.
