### ISSUE TITLE
The introduction of quadar in UMD mode does not explain how to introduce it in Vue project

### ISSUE THREAD

**Issue by e274426380** [quasarframework/quasar#10111]
Now I have a Vue project, which is packaged with webpack, but after loading CDN in index.html, I don't know how to import it in webpack.conf
I try add this code in webpack.conf.js
`module.exports = {
    externals: {
      'quasar':'Quasar',
    },
}`

**Comment by rstoenescu** [comment]
Hi,

If you have a project packaged with webpack (Quasar CLI or Vue CLI one?) then you don't need the UMD version. Just follow the Quasar CLI or the Vue CLI doc pages on our website...

**Comment by 625781186** [comment]
@rstoenescu 
I mentioned this question a long time ago.

[issues/8267](https://github.com/quasarframework/quasar/issues/8267)

You need to know why we use `UMD`?
Because UI libraries belong to scripts that rarely change , 
and it takes up most of the volume after build(as https://github.com/quasarframework/quasar/issues/8267#issuecomment-751926921).

So we need to use` webpack externals` to exclude it, and use CDN to `reduce the traffic` of the UI library.
When the project is updated and build ,we  needn't to package the UI library again.

**Comment by 625781186** [comment]
@e274426380 

[issues/8267](https://github.com/quasarframework/quasar/issues/8267)

The team never seemed to see this as a problem,
So while Quasar was well designed, I abandoned it in favor of Elementui
