### ISSUE TITLE
missing module error for blank electron project's build

### ISSUE THREAD

**Issue by maico910** [quasarframework/quasar#10269]
**Describe the bug**
I have created new electron project, and I'm getting this error when I try to build it:
![image](https://user-images.githubusercontent.com/24510745/127874404-6ee2f922-ef46-4822-938d-574d90726650.png)

**To Reproduce**
1. Create new quasar project: `quasar create <prooject_name>`
2. Add electron: `quasar mode add electron`
3. Build electron: `quasar build -m electron`

**Expected behavior**
Build new quasar electron project (without any edit) without error

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: 3.0.3

Quasar mode:
  - [x] Electron

Tested on:
  - [x] Electron

OS:
Node: `6.14.12`
NPM: tested in `14.17.4` and `12.22.1`
Electron: `13.1.7`

**Additional context**
My `quasar info` log

![image](https://user-images.githubusercontent.com/24510745/127875519-77492fce-cb4a-49bd-b580-69f3f7b4832c.png)

**Comment by ianlchapman-noodlelive** [comment]
This bug is also present on a totally empty install of Quasar. This is using the CLI version 1.2.1

**Comment by MatthewSH** [comment]
This is for Quasar 2.0.3 as a whole, I've gone ahead and created a bit more detailed issue on #10270 to go into specifics on the exact reasons but for now, if you run `npm install webpack@5.47.1 --no-save` it will allow you to keep working.

**Comment by rstoenescu** [comment]
Should work with "@quasar/app" v3.0.4.

I keep on explaining why deps are so strict: because we got burnt so much in the past by third-party libs doing breaking changes in non-major versions (yeah!) or introducing various bugs or regressions. We test the setup before we ship q/app so you won't have to and everything will just work out of the box.
However, this is a particular scenario. We can't pin webpack (due to some issues upstream) so in this case a new webpack version broke something in vue-loader...
