### ISSUE TITLE
Error during render TypeError: Invalid value used as weak map key - pinia vue store

### ISSUE THREAD

**Issue by dani17r** [quasarframework/quasar#10287]
pinia works fine in dev mode, but in quasar's dev -m ssr mode, the pinia store gives me this error:

----------------------------------------------------------------------------------------------------------------------------
[Vue warn]: [🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia?

const pinia = createPinia()
app.use(pinia)

This will fail in production.
[Quasar Dev Webserver] / -> error during render
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at useStore (/home/core17/Proyects/OjedaStore/node_modules/pinia/dist/pinia.cjs.js:921:23)
    at render-app.js:4727:97
    at /home/core17/Proyects/OjedaStore/node_modules/vue-router/dist/vue-router.cjs.js:1918:35
    at new Promise (<anonymous>)
    at /home/core17/Proyects/OjedaStore/node_modules/vue-router/dist/vue-router.cjs.js:1892:18
    at /home/core17/Proyects/OjedaStore/node_modules/vue-router/dist/vue-router.cjs.js:3309:65
--------------------------------------------------------------------------------------------------------------------------------
everything works fine, I have in "boot" a file for pinia with its app.use (pinia), but in ssr it seems not to take it.
![Screenshot_20210804_103816](https://user-images.githubusercontent.com/35787353/128200670-55add123-e1c5-4528-9812-13a07eedcbb2.png)
![Screenshot_20210804_103920](https://user-images.githubusercontent.com/35787353/128200795-180800b1-5d93-457b-b4dc-bef4bc608acc.png)

**Comment by hawkeye64** [comment]
@dani17r Did you forget to add `pinia` to the `boot` section in quasar.conf.js?

**Comment by yusufkandemir** [comment]
You would have to call `createPinia` inside the boot callback and properly enable the boot file(_By adding it to `quasar.config.js > boot`_). But, Quasar has first-party support for Pinia 💪 So, there is pretty much no reason to handle it manually. (_Unless you are progressively migrating from Vuex to Pinia, in which you can properly do by following my previous instructions_)

**Quasar CLI with Vite**: Since its first release
https://quasar.dev/quasar-cli-vite/state-management-with-pinia

**Quasar CLI with Webpack**: Since [`@quasar/app-webpack-v3.4.0`](https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-v3.4.0)
https://quasar.dev/quasar-cli-webpack/state-management-with-pinia
