### ISSUE TITLE
[Request] remove label and value dependencies on autocomplete list

### ISSUE THREAD

**Issue by nueko** [quasarframework/quasar#1037]
hi, i think the autocomplete will be better if we don't need to map the current list returned by server.
eg:
```json
// server data
{
"status": "success",
"data": [
{"name": "John",
"fullName": "John Doe",
"title": "CEO"
},
...
]
}
```

suggested component
```html
<q-autocomplete 
@search="search" 
@selected="selected" 
list="data"
label="fullName" 
value="name" 
sublabel="title"
>
</autocomplete>
```

**Comment by rstoenescu** [comment]
Hi,

The solution to this is to map data to the correct format. This can be done in app-land or in Quasar directly. Rather than adding complexity to Quasar, I'd suggest you just map the data to the required format. Doing this in Quasar does not add performance benefits and I can just see further requests for using dots in the new props. It just doesn't makes sense at the moment.

```js
originalData.map(item => ({label: item.fullName, ....}))
```
