### ISSUE TITLE
Hover property on QScrollArea component

### ISSUE THREAD

**Issue by bekmuradov** [quasarframework/quasar#10401]
Hi. Recently I upgraded my project from Q v1.15.23 to Q v2 with Vue 3.
In previous version I could access hover preperty of q-scrooll-area component like this `this.$refs.scrollArea.hover`
After update it doesn't seem to exist anymore. I am using it to autoscroll the text after certain amount of time. I tried to use mouseover/mouseleave events. When the user scrolls the text forward I have to determine the bottom offset of the text after which autoscroll should scroll. The problem is when the user scrolls backwards the autoscroll scrolls to the previous position on the text. When I had access to hover property of q-scroll-area component it worked as i wanted.

**Comment by yusufkandemir** [comment]
> In previous version I could access hover preperty of q-scrooll-area component like this this.$refs.scrollArea.hover
After update it doesn't seem to exist anymore.

First of all, I would like to clarify that it wasn't a documented API(_it was for internal use_), so this is not a breaking change. I would advise not using any undocumented/internal APIs unless you are ready to face the consequences when they get updated/removed.

In Qv2, `hover` is only controlled by `mouseenter` and `mouseleave` events(_see [the source code](https://github.com/quasarframework/quasar/blob/539fb6ba45fbe5eb3d81630854aa82b0ba96135b/ui/src/components/scroll-area/QScrollArea.js#L355-L411)_). So, you can easily re-create it on your own. If it's not enough for you, then you would need a different solution. Even if you had a way of accessing the internal `hover`, it wouldn't change anything since it would work the same way with your own state.
