### ISSUE TITLE
Q-tooltip doesn't appear continuously after quickly tapping on mobile platforms 

### ISSUE THREAD

**Issue by abnerwang06** [quasarframework/quasar#10414]
**Describe the bug**
Q-tooltip doesn't appear continuously after quickly tapping on mobile platforms.
Users have to tap continuously on the target element to keep appearing the tooltip on mobile platforms.
I found this bug only occurs after the quasar version 2.0.2.
It might relate to "fix(QTooltip): Fix delayHide function name in event listener" [#9987](https://github.com/quasarframework/quasar/pull/9987)

**Platform (please complete the following information):**
Quasar Version: 2.0.3
@quasar/app Version: 3.0.4

**Comment by MathieuTristan82** [comment]
Hello guys, I'm facing the same issue.
I don't know if it could help you but I get the desired behavior when loading the page in desktop mode and then swapping chrome debugger device to mobile (which force touch instead of click if the related config is set to "device-based").

**Comment by piperone** [comment]
@pdanpdan Is the fork from which you're referencing this issue meant to be merged with a Quasar-release at some point? I've been monitoring this issue because the way it is now, makes Qtooltip very difficult to use on iOS (only visible while continuously tapping + default location below triggering element = finger blocking the content). You've been committing to the fork since February, so I was just wondering if there's an ETA for an improved QTooltip. Thanks.

**Comment by piperone** [comment]
This issue persists today over two years later, so this issue should be reopened.
