### ISSUE TITLE
QInfiniteScroll add slot for no data

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar#10466]
**Is your feature request related to a problem? Please describe.**
Add slot when there is no data retrieve QInfiniteScroll to custom with empty state 

**Describe the solution you'd like**
Add slot when there is no data retrieve QInfiniteScroll to custom with empty state

**Comment by MatthewSH** [comment]
If you know you're done loading data, just call `done(true)` and then you just show a new element saying no more data is available to be loaded. It's already there as a general concept, you just have to implement it.

**Comment by nseb** [comment]
Hello ,
No I meant no data.
Example, I have a qinfinite for display news for a driver, but on first
call, there is no news for this driver, for me there is no data, is
different 'no more data'
Indeed, I could manage a boolean in the load function, but I find it
interesting to have maybe a dedicated mechanism and a dedicated slot in the
component

**Comment by MatthewSH** [comment]
I've updated my original comment like 3 times because I just simplified it down, heads up. 
The general concept already exists, just call `done(true)`. It will remove the event handler for the scroll event, never activate the loading again, and boom. Now you're at the "end" of your content.

The component itself is data agnostic, it doesn't know about the content it's displaying or what it's loading. It just knows that when a user scrolls past a certain point, call a method. That's it. You're asking to put business logic in a component that's a general use component.

Yes, you could implement a `done(true)` concept where it also displays an empty slot, but not everyone wants that and it's so easy to implement on the component that's using QInfiniteScroll that IMO it doesn't justify adding it.
I mean we're literally talking a `v-if` with a boolean that's toggled after you make a web call to get the next content and you know there's no more content left to get.
```javascript
done(true)
this.noMoreContent = true;
```
```html
<div v-if="noMoreContent">No more content</div>
```

I'm not sure what you're asking to have added to Quasar when it already provides everything you need to get the task in your example done. If you know you're calling `done(true)` then you know you have no more content to load....that `load` event will never fire, your calls will never be made again. I'm really not sure how the currently available functionality doesn't suit your workload.
