### ISSUE TITLE
quasar uses Electron Forge to implement code protection

### ISSUE THREAD

**Issue by zhuyifang** [quasarframework/quasar#10557]
**Is your feature request related to a problem? Please describe.**
When using quasar for electron packaging and publishing, I always feel frustrated with source code protection

**Describe the solution you'd like**
I hope that we can use Electron Forge's excellent code protection function to protect the quasar source code.

**Describe alternatives you've considered**
I have tried to use Electron Forge to package the web produced by quasar builde into an application, which is not bad, but it is not easy to debug, and the whole development process is not a process. Looking forward to some simple configuration in quasar.conf.js, then it can support the use of Electron Forge for packaging and publishing

**Comment by MatthewSH** [comment]
Can you provide a link to Electron Forge's code protection that you're reading? I've looked through and can't find anything on the website that talks about protection, obfuscation, or something of the sort.

**Comment by zhuyifang** [comment]
You are right, i understand wrong
The implementation of code protection is based on: https://github.com/herberttn/bytenode-webpack-plugin.
Ultimately point to:
https://github.com/bytenode/bytenode

But unfortunately bytenode-webpack-plugin does not support webpack5+

I am trying to implement code protection through afterCopy, but it has not been completely successful yet.

When using quasar to develop electron or other programs, the protection of source code should be a requirement of many people

If the official can achieve this, it will be great

**Comment by MatthewSH** [comment]
This seems like something that is not really a Quasar specific thing. You have the ability to add your own webpack plugins, to my understanding, via `extendWebpack`.
Since Quasar uses webpack 5, then bytenode-webpack-plugin will need to support webpack 5.
That's not managed by Quasar and I don't see why someone should take the time to add it just to have yet another thing to maintain within the ecosystem when there's already a solution (whether it's a good solution or not is irrelevant). 
I'd encourage you to dig into that plugin and contribute to help make it compatible with webpack 5 so you can help yourself and anyone else who wants to use it.

**Comment by pdanpdan** [comment]
Sorry, it makes no sense to add this in the framework - if you need it and find some way to do it then it's good, but it's not needed for the general use.
