### ISSUE TITLE
Qtable doesn't work virtual-scroll and pagination in docs

### ISSUE THREAD

**Issue by Nikitoring** [quasarframework/quasar#10566]
In docs https://quasar.dev/vue-components/table#example--virtual-scroll-and-pagination doesn't work pagination

https://user-images.githubusercontent.com/50715463/131953135-2eaa0b86-8c48-4ded-8cd6-ab37af889dc2.mp4

**Comment by MatthewSH** [comment]
Tracked it down to this line, partly...virtual scrolling still doesn't work:

https://github.com/quasarframework/quasar/blob/dev/docs/src/examples/QTable/VirtscrollPagination.vue#L10

Which was changed here:
https://github.com/quasarframework/quasar/commit/85c34b6bb372e2545e2c2d9dde4d7fb22a8f0d67#diff-4392b7bb61a43778d590338385ab7c08f4c02248d299f2a3c0fd86765b82f1aa

@rstoenescu would you mind chiming in on the changing of a v-bind sync to a v-model? It seems to work on the other places but not on this specific example with virtual scrolling with pagination together. Was it something specific to Vue3 or did something change? I haven't kept up with every single small change so I'm genuinely curious.
Specifically [this](https://quasar.dev/vue-components/table#example--masonry-like-grid) one. `v-model:pagination` works here. 

Also, side note...that example's virtual-scroll doesn't even work with the v-bind vs v-model. I haven't work with QTable's very much; I can dig into it to see more why that example is fully broken but may be worth pulling in someone a bit more experienced because there's probably a lot happening under the hood.

**Comment by metalsadman** [comment]
https://codepen.io/metalsadman/pen/ZEypbMq?editors=1010

**Comment by Nikitoring** [comment]
> https://codepen.io/metalsadman/pen/ZEypbMq?editors=1010

In Your solution virtual-scroll doesn't load next page values. If you delete virtual-scroll the table will work the same way

**Comment by metalsadman** [comment]
> > https://codepen.io/metalsadman/pen/ZEypbMq?editors=1010
> 
> In Your solution virtual-scroll doesn't load next page values. If you delete virtual-scroll the table will work the same way

wdym?
![qvirtscroll1](https://user-images.githubusercontent.com/31038838/132287518-a89278db-c48b-4607-80ee-2f04e4f93f76.gif)

**Comment by Nikitoring** [comment]
Sorry, I expected different virtual-scroll action like dynamic loads values

**Comment by MatthewSH** [comment]
Out of curiosity, if it doesn't automatically move to the next page then what's the point of virtual-scroll on that example? Unless I'm missing something regarding the usage of virtual-scroll.

**Comment by Nikitoring** [comment]
I think it's my mistake. I think it works like https://quasar.dev/vue-components/table#example--dynamic-loading-virtual-scroll with pagination counter. Example: my page is 50 rows, when i'm scrolling to 50 row virtual-scroll loads next 50 row and page equals 2
