### ISSUE TITLE
GridMasonry.vue

### ISSUE THREAD

**Issue by modemb** [quasarframework/quasar#10582]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
can make this vertical scroll also, 
**Describe alternatives you've considered**

**Additional context**

**Comment by modemb** [comment]
?

**Comment by pdanpdan** [comment]
Yes, that's exactly what I thought when I saw the content of the issue

**Comment by modemb** [comment]
Ok let me clarify a little, this grid masonry when you took off the pagination with more than 30 items for example, the scrolling will be horizontal, not vertical, I have tried to fix it myself since q1 without no successes.

So I was saying to add a css helper to make the scrolling horizontal also like tumblr

Let me know if you understand the issue please

**Comment by modemb** [comment]
Here is my site where I am trying to implement this https://suguffie.com

**Comment by pdanpdan** [comment]
Your container needs a fixed height, and it needs to be taller than your tallest column.

**Comment by modemb** [comment]
I have try all kind of sizes, but never work

How could you do that here?

https://quasar.dev/vue-components/table#example--masonry-like-grid

**Comment by ontwikkelfabriek** [comment]
@modemb 

> How could you do that here?
https://quasar.dev/vue-components/table#example--masonry-like-grid

What do you mean, I see a functional vertical scrolling `GridMasonry` (with more than 30 items). What would you like to see different?

**Comment by modemb** [comment]
> @modemb 
> 
> > How could you do that here?
> https://quasar.dev/vue-components/table#example--masonry-like-grid
> 
> What do you mean, I see a functional vertical scrolling `GridMasonry` (with more than 30 items). What would you like to see different? 
> 

I would like it to be like tumblr, infinite vertical scrolling, trying to implement it here suguffie.com

**Comment by ontwikkelfabriek** [comment]
@modemb @pdanpdan 

> I would like it to be like tumblr, infinite vertical scrolling, trying to implement it here suguffie.com

I don't really understand why they closed this feature request so soon. As far as I know, the q-table grid mode example is the only place where a masonry layout is implemented in Quasar.  Because of the current state of Q-table grid mode you cannot recreate an infinite/virtual/load-on-demand vertical scrolling masonry layout, like tumbler.com with Q-table. (Without pagination and an unknown or big number of items)

https://quasar.dev/vue-components/table#example--masonry-like-grid

 The masonry grid example made in Q-table component (with it's custom css) is unfortunately hard coded to only work with pagination on ( so you can set a hard `height`, fixed number of rows etc ).  Besides that the q-table component is not suitable for this kind of specific grid layout in its current state.  Because even if you can get it to work, eventually with enough items it will stop being usable because `virtual scrolling` is only functional in `table` mode, not `grid` mode. 

I did make a codepen to show that it is kind of possible ( if you don't have a huge number of items). To make the demo work I have set a fixed number of items and a corresponding fixed height for the grid. You could make it mode dynamic but that's up to you.... I would look for another approach that doesn't not use q-table.

https://codepen.io/ontwikkelfabriek/pen/yLXXLQY

Found this too, could be useful:
https://paulcollett.github.io/vue-masonry-css/demo/

**Comment by modemb** [comment]
> @modemb @pdanpdan
> 
> > I would like it to be like tumblr, infinite vertical scrolling, trying to implement it here suguffie.com
> 
> I don't really understand why they closed this feature request so soon. As far as I know, the q-table grid mode example is the only place where a masonry layout is implemented in Quasar. Because of the current state of Q-table grid mode you cannot recreate an infinite/virtual/load-on-demand vertical scrolling masonry layout, like tumbler.com with Q-table. (Without pagination and an unknown or big number of items)
> 
> https://quasar.dev/vue-components/table#example--masonry-like-grid
> 
> The masonry grid example made in Q-table component (with it's custom css) is unfortunately hard coded to only work with pagination on ( so you can set a hard `height`, fixed number of rows etc ). Besides that the q-table component is not suitable for this kind of specific grid layout in its current state. Because even if you can get it to work, eventually with enough items it will stop being usable because `virtual scrolling` is only functional in `table` mode, not `grid` mode.
> 
> I did make a codepen to show that it is kind of possible ( if you don't have a huge number of items). To make the demo work I have set a fixed number of items and a corresponding fixed height for the grid. You could make it mode dynamic but that's up to you.... I would look for another approach that doesn't not use q-table.
> 
> https://codepen.io/ontwikkelfabriek/pen/yLXXLQY
> 
> Found this too, could be useful:
> https://paulcollett.github.io/vue-masonry-css/demo/

Thanks bro, will be using this for now, but if you are in the quasar team, please can you add a virtual infinite scrolling Masonry table ?

thanks again for the codepen

**Comment by ontwikkelfabriek** [comment]
@modemb 

No, I am not a Quasar dev, more like a Quasar enthusiast trying to help people in the Quasar discussions section.

**Comment by MilosPaunovic** [comment]
> @modemb
> 
> No, I am not a Quasar dev, more like a Quasar enthusiast trying to help people in the Quasar discussions section.

Loving the `Quasar enthusiast` analogy 😄

**Comment by modemb** [comment]
> > @modemb
> > No, I am not a Quasar dev, more like a Quasar enthusiast trying to help people in the Quasar discussions section.
> 
> Loving the `Quasar enthusiast` analogy 😄

ah ok cheer
