### ISSUE TITLE
Quasar not found in 'quasar'  import/named

### ISSUE THREAD

**Issue by jhmen** [quasarframework/quasar#10655]
**Describe the bug**
When i use the eslint-plugin-import and I use `import {Quasar} from 'quasar'`, I am getting the error:
`3:10  error  Quasar not found in 'quasar'  import/named`.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.io/rstoenescu/pen/VgQbdx) or a jsFiddle (https://jsfiddle.net/rstoenescu/rmaodk0f) or a Codesandbox (https://codesandbox.io/s/github/quasarframework/quasar-codesandbox/tree/legacy-v1) and hit save then copy-

[Repo to reproduce](https://github.com/jhmen/quasar-import-test)

**To Reproduce**
With Repo:
1. Clone the [repo](https://github.com/jhmen/quasar-import-test)
2. Run `docker build .`

Without:
1. Create new Quasar v1 project `quasar create <folder name> --branch v1` 
2. Chose auto import, ESLint, Vuex, Axios, Vue-i18n,  Prettier and Yarn
3. Add the `eslint-plugin-import` as dev dependencie
4. Add the `eslint-plugin-import` to the .eslintrc.js file `plugins: [..., 'import']`
5. Add the rule `'import/named': 'error'`
6. Import in any file `import { Quasar } from 'quasar'`
7. Run `yarn run lint`

**Expected behavior**
ESLint should not failing

**Screenshots**
-

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: ^2.0.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows / Linux
Node: v14.17.0
NPM: 6.14.13
Yarn: 1.22.10
Browsers: -
iOS: -
Android: -
Electron: -

**Additional context**
I do not know if this is an issue from Quasar.

**Comment by yusufkandemir** [comment]
`Quasar` import is normally meant to be used with the Vue CLI plugin and UMD, I personally don't see a reason why you would want to use it when working with Quasar CLI. I think it's included in UMD and CommonJS builds, but not in ESM build. AFAIK Quasar CLI uses CommonJS versions because the CLI works in Node.js context and ES Modules are stable only from after Node v14, and since we still need to support v12, we can't use them everywhere yet. You can see #6476 for ESM project support. Anyways, in the end, we are using CommonJS modules, but because the `eslint-plugin-import` automatically picks up the ESM version when there is one, it can't resolve that specific import, and the authors of the library recommend [not using this rule when working with CommonJS](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/named.md#when-not-to-use-it).

So, you have some options:
 - Don't use that rule
 - Ignore the rule for that specific import statement
 - Don't import `Quasar` because there are better ways

On the other side, I don't have enough context but I think there is no harm in including `Quasar` in the ESM version too, and it's being included in Quasar v2. So, we can also export it, not just to make `eslint-plugin-import` happy, but that would also allow using it in ESM builds as well. So, I can PR that change, but I would need some context to be sure first.

**Comment by cyfung1031** [comment]
Update: my previous comments for v2 instead of v1

~~if you use  ES6 import, you shall have `import {useQuasar} from 'quasar'`~~
~~just like Vue, `import {createApp} from 'vue'`~~

~~`Quasar` is for `<script src="....."></script>`~~
~~you can also `import Quasar from 'quasar'` but it is not recommended.  (i.e. `Quasar.useQuasar` )~~

~~https://quasar.dev/vue-composables/use-quasar~~

**Comment by yusufkandemir** [comment]
@cyfung1031 this issue is labeled as v1 where `useQuasar` is not available. So, what you propose is only applicable to v2 and is not applicable here.

**Comment by rstoenescu** [comment]
The "import/named" rule is incompatible with Quasar's auto-import feature (where imports are getting translated to their actual files).
