### ISSUE TITLE
Splitters not working in Q2

### ISSUE THREAD

**Issue by CrawfordW** [quasarframework/quasar#10665]
Having trouble getting splitters to work in Quasar V2 - splitter content height is wrong, and can't move splitter divider.
Here are two codeSandbox demos with the same app code...
Quasar V1 that works: https://codesandbox.io/s/splitter-responsiveness-test-oneqn
Quasar V2 that does not: https://codesandbox.io/s/splitter-test-with-q2-17kl9

With the V1 demo, you can select  a different tab in each splitter, then move the splitters to see how everything is responsive.
With V2, the contents of the vertical splitter do not fill the page, and the horizontal splitter cannot be moved at all.

Clearly V2 has changed some things - I don't know if this is a bug, or just me not understanding something.
I'm stumped with this, and any help will be appreciated. This is really holding up my development since upgrading!

**Comment by yusufkandemir** [comment]
@CrawfordW your v2 sandbox is not working due to some basic linting errors. But I forked it and modified it a bit to investigate. The problem is related to assigning a dynamic style or something similar. If you take a closer look you will notice that the height style will not be applied to the splitter. But for example, instead of `:style="splitterHeightStyle"`, if you do `:style="splitterHeightStyle + ''"` or `:style="{ height: splitterHeight + 'px' }"`(_`splitterHeight` contains just the height as int_) it starts working. It sounds really weird and to be honest, I don't know the source of the problem. `style` is just passed along normally as it's not a prop, so it's not a Quasar thing.

You can see the working example [here](https://codesandbox.io/s/splitter-test-with-q2-forked-gscu1?file=/src/components/WorkSection.vue). I also modified it to use a template `ref` instead of querying the DOM and such, which is not really a good idea, but that didn't solve the problem.

**Comment by ontwikkelfabriek** [comment]
@CrawfordW 

Hi!

> https://codesandbox.io/s/splitter-test-with-q2-17kl9

The Qv2 sandbox is **not** working for me....

> This is really holding up my development since upgrading!

 On a side note, your app has a very complicated UI setup. Personally I would not have upgraded to Qv2 so soon. There're always little undocumented differences( apart from bugs) between major versions.

**Comment by CrawfordW** [comment]
Thanks yusufkandemir - I really appreciate the help.
ontwikkelfabriek, you're probably right - I should have waited. But I plan to build lots more components and wanted to get on the new version before there's even more stuff to upgrade.
