### ISSUE TITLE
q-img change src attribute will invoke two http requests

### ISSUE THREAD

**Issue by xjtju** [quasarframework/quasar#10743]
**Describe the bug**
I am not sure whether it is a real bug or not, but it will cause some unhappy user experience on some cases.

My english is not well, I try my best to expain the phenomenon as I can.

When I use q-img as captcha, clicking the img will send a request to the server for changing another captcha. I follow the standard demo of q-img, write a refresh method for CLICK event, and in the refresh script, just simply replace the src attribute of the q-img.  But I found that when clicking the q-img, the script will invoke two exact same http request, such as, /captcha?t=0.333325646466. I have checked the log of application server writting with Flask, It is clear that the web browser send two same request to the backend. For a static picture, this is not a problem, but for a DYNAMIC captcha, ONE click may generate two different captchas, that is the problem.

**To Reproduce**
If use Chrom DevTools, the reproduction is very esay.
1. Go to 'https://v1.quasar.dev/vue-components/img#usage'
2. Open DevTools, open network panel, disable brower cache, 
3. Click on 'CHANGE IMAGE' button
4. See the logs of DevTools, there are two same http requests

**Expected behavior**
I use pure vue and jquey to implement the same function respectively, both of them invoke one http request.

**Screenshots**
<img width="1492" alt="q-img-click" src="https://user-images.githubusercontent.com/16679044/133955288-01979cec-4a4a-4607-ac94-72be331ef541.png">

**Platform (please complete the following information):**
Quasar Version: V1.9+

**Comment by cyfung1031** [comment]
Interesting. It is the issue only in v1 but not v2.

~~The first network request is the original image while the second network request is the new image.~~

**Comment by hawkeye64** [comment]
@cyfung1031  I also noticed this is not an issue with v2

**Comment by rstoenescu** [comment]
QImg has been rebuilt from the ground up for Quasar v2 because IE11 support could be dropped. And this allowed us to make use of the newerer technologies that are available and also improve efficiency and performance along the way. Unfortately, due to IE11 support for Quasar v1 there is nothing much that can be done to improve QImg. The only way is to upgrade to Quasar v2.

**Comment by cyfung1031** [comment]
@rstoenescu 

I found that the problem is the computed `url`
As `currentSrc` is updated so the `url` is also updated
In `render()`, it call `__getImage()` and its ~`img`~ `div` DOM uses `this.url` instead of the decoded image.

Like the example in Quasar Docs, if the url is a dynamic resource, the DOM is not the same image as the decoded image.
