### ISSUE TITLE
[Request] Separate placeholders for datetime range

### ISSUE THREAD

**Issue by cedriccouret** [quasarframework/quasar#1075]
Hi,

would it be possible to set separate placeholders for a datetime range component ? Like "From" and "To".
When I set the placeholder option it appears on both inputs.

Thanks.

**Comment by rstoenescu** [comment]
Will do.

**Comment by cedriccouret** [comment]
Thanks a lot :-)

**Comment by rstoenescu** [comment]
Hi, In v0.15 this component has been removed, since it's very easy to just configure two QDatetime-s side by side. There's been a lot of requests regarding this component, and implementing all of them will just make it very inefficient. The workaround it's so easy that really, we don't need a QDatetimeRange.
