### ISSUE TITLE
Remove the black bar that always appears below(sometimes a second bar appear above as well) the Image Gallery Carousel

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#1076]
### Software version

Quasar: 0.14.4
OS: Linux Mint 18.2
Node: 8.8.1
NPM: 5.4.2
Browsers: Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Didn't get error
### What were you expecting?
Don't expect to see this bar
### What steps did you take, to get the error?
Created many Image Gallery Carousels and the black bar appear below all of them no matter if the images have equal or different heights and widths, it appears in the demo page as well http://quasar-framework.org/quasar-play/android/index.html#/showcase/media/image-gallery

**Comment by dlbass** [comment]
Seems like the black bar is the quick-view component. I was expecting to be able to hide it by adding `:horizontal-quick-view="false"`, but that doesn't work.

**Comment by rstoenescu** [comment]
Would you be so kind as to provide a PR? I am over my head with other areas at the moment. If not, it's ok, this will eventually get fixed.

**Comment by MohammedAl-Mahdawi** [comment]
@rstoenescu I spent many hours trying to get a not dirty way to fix this but unfortunately, I was not able to do so, if I found a way definitely I'll share it here.

**Comment by dlbass** [comment]
@MohammedAl-Mahdawi I can solve the issue by adding, can you confirm that this works for you:
```
.q-gallery-carousel {
  margin-bottom: -4px;
}
```
But, I haven't yet figured out where that extra 4px is coming from. The black we see turns out to be the background applied by `.bg-black` on the gallery carousel. I'll keep looking for the culprit, but maybe this can be a workaround, I don't think it is a fix.

**Comment by MohammedAl-Mahdawi** [comment]
@dlbass Thank you so much, unfortunately, it didn't work for me, I think it didn't wok because I have a content below the carousel as you can see [here](https://www.dropbox.com/s/nydq3shivf9tbmu/Selection_003.bmp?dl=0)

**Comment by dlbass** [comment]
@MohammedAl-Mahdawi Sorry about that... I was poking around in inspector when I found that workaround yesterday. I tried implementing it in my own project this morning, and found the same result as you. 

But, adding that CSS rule in my main 'App.vue' works. I think the rule doesn't work from a scoped style block in a page where we are calling for the carousel because it is nested too deeply.

Still looking for why this happens, but maybe that workaround will get you patched up for now.

**Comment by MohammedAl-Mahdawi** [comment]
@dlbass Thank you so much, I put it in 'App.vue' and in 'app.mat.styl' that I use for global styles and it didn't work, it works only if I removed everything from the page leaving the carousel alone.

**Comment by dlbass** [comment]
That's really strange. I'm lost, so I've tried to capture what my app looks like to see if maybe it will help you spot what's different in yours.
http://recordit.co/FspcGXgHmD

**Comment by MohammedAl-Mahdawi** [comment]
Hi @dlbass 

First of all, I want to thank you so much for all the effort and time that you spent while trying to help me.

Second, after trying to make `margin-bottom: -4px;` for all the element in my page here is what worked for me:

```
.q-carousel-inner {
  margin-bottom: -4px;
}
```

I put this code in `src/themes/app.mat.styl` file.
For anyone that trying to use this workaround please don't forget to enable this file first, for more information please read [this helpful page](http://quasar-framework.org/guide/quasar-theming.html) from Quasar guide.

All the best,
Mohammed

**Comment by MohammedAl-Mahdawi** [comment]
Hi @rstoenescu 
Hi @dlbass 

I just found the right way to solve this bug:

```
.q-gallery-carousel img{
    display: block;
}
```

@rstoenescu please implement it in your next build.

Regards,
Mohammed

**Comment by dlbass** [comment]
@MohammedAl-Mahdawi Nice catch! Just confirming that this works perfectly for me as well.

**Comment by rstoenescu** [comment]
Closing as code is ready in future v0.15.
