### ISSUE TITLE
QuasarRouteTab to be keep active even when in child route

### ISSUE THREAD

**Issue by jmcopeland** [quasarframework/quasar#10848]
### Discussed in https://github.com/quasarframework/quasar/discussions/10541

<div type='discussions-op-text'>

<sup>Originally posted by **eevan7a9** August 31, 2021</sup>
Hello Everyone,

I have a RouteTab that's active in route "/account"

```
    <q-route-tab
          class="full-width"
          align="start"
          active-class="active-route-tab"
          to="/account"
        >
          <div class="full-width>
            ....
            Users Name 
          </div>
    </q-route-tab>
```
but when I navigate to "**/account/profile**"  the active state is gone.

how can I keep the route tab active when in "**/account**" and "**/account/profile**" etc...

this is my **routes.js**

```
    const routes = [
      {
        path: "/",
        component: () => import("layouts/MainLayout.vue"),
        children: [
          {
            path: "",
            redirect: "freeboard",
          },
          {
            path: "account",
            component: () => import("src/pages/Account/Index.vue"),
            name: "account",
          },
          {
            path: "account/:id",
            component: () => import("src/pages/AccountDetails/Index.vue"),
            name: "accountDetails",
          },
        ]
      },
     ....
    ];
```</div>

**Comment by hawkeye64** [comment]
Use the `keep-alive` property with the QTabPanels component

**Comment by pdanpdan** [comment]
It's a regression from qv1

**Comment by rstoenescu** [comment]
Hi,

Pushed a commit to highly improve QTabs on picking the right QRouteTab.

**BUT**, the matter of fact is that for the "route is active" and "route is exact active" we must rely on Vue Router 4 (latest version for Vue 3).
And the way that you've defined your routes makes "/account" and "/account/:id" not in a relationship of parent-child, but siblings. And if they're siblings, a `<q-route-tab to="/account">` (or even a `<route-link to="/account">`) will not match when the current route is actually "/account/:id".

This behavior differs from Quasar v1 (with Vue 2 and Vue Router 3) because Vue Router 4 matches routes differently than Vue Router 3. We unfortunately need to adhere to Vue Router 4 specs so we can't overcome the scenario above.

## So what to do?
What you need to do is actually make "/account/:id" a child of "/account" and (most likely) wait for Quasar v2.1.3 (which contains my commit above).

**Comment by marwand** [comment]
If anyone is still wondering how to match child routes, here's how I got it working: with vue-router@4 and quasar@2.6

```
        {
        path: 'orders/:id?',
        children: [
          {
            path: '',
            name: 'orders',
            component: OrderList,
          },
          {
            path: ':id',
            name: 'orderDetail',
            component: OrderDetail,
          },
        ],
      },
```

Route tab template:
`
...
<q-route-tab content-class="tab-content" icon="storefront" :to="{ name: 'orders' }" label="Orders" no-caps />
...
`

**Comment by AntoineReibel** [comment]
> { name: 'orders' }

Thanks you it's work ! I have no idea why it's working and I'm surprise the :to="{ name: 'orders' }" is mandatory to make it work.

**Comment by alexandre-le-borgne** [comment]
A custom component to avoid vue reusing components when navigating from /orders/1 to /orders/2  for example. Support deep nesting.

```
<template>
  <router-view v-slot="{ Component }">
    <component :is="Component" :key="rootPath" />
  </router-view>
</template>

<script setup>
  import { computed, inject, provide } from 'vue'
  import { useRoute } from 'vue-router'

  const route = useRoute()

  const parentDepth = inject('routerViewParentDepth', -1)
  const depth = parentDepth + 1

  const rootPath = computed(() => {
    let rootPath = route.matched[depth]?.path || ''
    for (const param in route.params) {
      rootPath = rootPath.replace(':' + param, route.params[param] || '')
    }

    return rootPath
  })

  provide('routerViewParentDepth', depth)
</script>
```
