### ISSUE TITLE
Inconsistent initialization times for Screen plugin between SSR and SPA modes

### ISSUE THREAD

**Issue by sheldonbaker** [quasarframework/quasar#10922]
**Describe the bug**
When serving in SSR mode, the Screen plugin is initialized in the `onSSRHydrated` hook, which, for example, takes place after a component's `beforeRouteEnter` hook.

In SPA mode, the Screen plugin is initialized fairly quickly, and therefore has the right values set in time for use inside of `beforeRouteEnter`.

**Expected behavior**
The Screen plugin should have the browser's screen dimensions available at the same time, regardless of mode.

**Platform (please complete the following information):**
Quasar Version: v2.1.0
@quasar/app Version: v.3.1.2

Quasar mode:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
Hi,

This is has no technical solution. On the client, the screen plugin needs to match the SSR-server rendered content in order to successfully hydrate. When rendering on the server side there is no possibility to acquire the client's screen dimensions, so a default hardcoded value is being used. When rendering on client side (and coming from SSR) we thus intentionally delay (with as less time as possible, usually on the next tick) the screen dimensions acquisition so that only after Vue has been correctly hydrated can we then set the actual dimensions.
