### ISSUE TITLE
QSelect with behavior="dialog" not working inside QMenu

### ISSUE THREAD

**Issue by DaDuFan** [quasarframework/quasar#10948]
**Describe the bug**
When a QSelect with behavior="dialog" (the default for mobile) is placed inside a QMenu the selected option is not used.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/DaDuFan/pen/PoKoXVx

it is a modified version from https://quasar.dev/vue-components/menu

**To Reproduce**
1. Click on 'Account Settings'-Button
2. Click on the 'Mobile Problem' Select Box
3. Select an option e.g. '30'
4. See error: the value of the select is not changed
5. Try the same with the 'Mobile Problem' Select Box above the  'Account Settings'-Button. Both refer to the same variable.

**Expected behavior**
QSelect should hold the selected option

**Platform (please complete the following information):**
Quasar Version: v2.1.1 and older

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [X] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Linux, Android, iOS
Browsers: Chrome, Safari, Firefox

**Comment by metalsadman** [comment]
@DaDuFan because your click on the qselect dialog items are treated an outside click by the menu, then close event is fired first on the menu before it can fire on the qselect item hence why the model was not updated. what you can do is set the menu to `persistent` also use a ref then hide it manually in the inner qselect's update:model-value event. other way is to set `persistent` true/false based on when the inner qselect is showing its popup. see codepen https://codepen.io/metalsadman/pen/vYJEedv?editors=1010

**Comment by pdanpdan** [comment]
The same problem as in https://github.com/quasarframework/quasar/issues/10449
Problem in Click outside directive

**Comment by DaDuFan** [comment]
@metalsadman Thanks. Nice Solution.
I think it would be a good idea when the documentation had a hint with the base problem, and your solution.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.1.3
