### ISSUE TITLE
Make quasar starter kits easier to discover

### ISSUE THREAD

**Issue by julie777** [quasarframework/quasar#10945]
**Is your feature request related to a problem? Please describe.**
There is no single place where I can find a list of all the quasar starer kits I might use with ```quasar create.```

**Describe the solution you'd like**
Restructure the quasar-framework repo to make starter kits easier to find. The starter-kit prefix can be dropped for the repo name and for the option to create.
```
quasarframework/starter-kits
    /default
    /ui
    /web-extension
    /umd
    /pwa
    /etc
```
**Describe alternatives you've considered**

**Additional context**
This also makes it easy for ```quasar help create``` to display a list of possible starter kits, and a description from the first line of the readme for the kit.

**Comment by rstoenescu** [comment]
Hi,

I'll take the opportunity to make an official statement here.

It is not our intention to advertise for starter kits.

I created the [App Extensions](https://quasar.dev/app-extensions/introduction) to **replace** them, because starter kits easily become obsolete (or way out of date) while App Extensions can always be fresh (because they are always applied on top of an app, rather than creating the app itself too). App Extensions rule. Starter kits suck. App Extensions can easily be [discovered on the Quasar website](https://quasar.dev/app-extensions/discover).

We didn't remove the ability to create and use custom starter kits though, because there's no reason to do that. Maybe someone decides to make one for their personal purposes and he/she really knows what he/she's doing.

But in no way do we want to make starter kits more popular than App Extensions. There's a ton of Quasar starter kits out there which are way waaay out of date. Hardly can you find one up to date with latest specs. Our intention is always to provide the best experience for anyone wanting to be productive with Quasar. Kicking off an app with any third party starter kit is not the way to go and can cause a lot of pain -- pain which almost always translates to Quasar tickets saying "X doesn't works", only to find that it's misconfigured or out of date and coming from the third party starter kit (so not great that we lose time handling such tickets).

**The only starter kit to be used is the one official one, which is used by Quasar CLI with `quasar create` command. Period.** Unless you want to be set for trouble later down the road.

Furthermore, just to be clear for anyone reading this: the beauty of Quasar is that it only needs one starter kit to rule all of the Quasar modes (SPA, PWA, SSR, etc). Reading the description one might think that you need separate starter kits, which is far from the truth.
