### ISSUE TITLE
Quasar V2 In wetchat brower miss css?

### ISSUE THREAD

**Issue by ben8804** [quasarframework/quasar#10951]
When I upgrade to V2, my website in wetchat loss the css in the mobile light theme
the quasar.dev also has this problem

Wetchat Version 8.0.11
Picture1: in the mobile light theme 
[Picture1](http://cdn.ppy.cn/quasar/Picture1.jpg)
Picture2: in the mobile dark theme 
[Picture2](http://cdn.ppy.cn/quasar/Picture2.jpg)

Picture3: the system brower
[Picture3](http://cdn.ppy.cn/quasar/Picture3.jpg)

**Comment by rstoenescu** [comment]
I assume that you are referring to the "WeChat" in-app browser. Because there is no "Wetchat" browser?

But regardless, it's impossible for the CSS to be "missing" -- instead it's the WeChat app auto-tampering with the websites. And it seems that it's not doing a good job while at it.
It's not within Quasar's reach (or any other framework, for that matter) to inhibit whatever WeChat browser decides to change in the CSS of a website.

**Comment by ben8804** [comment]
> I assume that you are referring to the "WeChat" in-app browser. Because there is no "Wetchat" browser?
> 
> But regardless, it's impossible for the CSS to be "missing" -- instead it's the WeChat app auto-tampering with the websites. And it seems that it's not doing a good job while at it. It's not within Quasar's reach (or any other framework, for that matter) to inhibit whatever WeChat browser decides to change in the CSS of a website.

Thank you for your reply
But the quasar V1 did not has this problem @rstoenescu

**Comment by rstoenescu** [comment]
You can check and adjust your package.json > browserslist. This tells the compiler what CSS (and JS) features it can use otherwise it adds necessary polyfills or transforms the code accordingly. Something tells me the in-app browser of WeChat is not quite up to date with latest web standards, so adjusting the browserslist might fix your problem. Also, not sure if WeChat actually changed something in their code so that your Qv1 app also has the same problem (if you have your browserslist updated and containing entries like "last X versions" and you recompile and redeploy it). Just saying.

If you are to compare the Qv2 doc website with the Qv1 one, you should know that for Qv2 doc website we've removed support for a lot of old browsers. So it's not accurate to say "Qv2 does this wrong" based on the website itself.

**Comment by ben8804** [comment]
Thanks for reply
browserslist cann't fix the problem, I check that I use the Qv1 browserslist is the same as Qv2 browerslist
maybe the wetchat change something in the same css classname in the mobile light theme
