### ISSUE TITLE
[Feature Request] Allow aggregates in Datatable

### ISSUE THREAD

**Issue by fnicollier** [quasarframework/quasar#1102]
Hi,

First thanks for making such a great framework and being so responsive to my previous requests.

The current DataTable component is great but it is lacking in one area: showing things like totals in a footer. There aren't many Vue datatables that allow this but [Vuetiful's](https://github.com/andrewcourtice/vuetiful/blob/master/src/components/datatable/readme.md#aggregation) approach seems interesting. Aggregator methods are defined (min, max, total...) and configured to a column template. In the case of Quasar's DataTable perhaps passing the aggregator method and label at the column configuration could be a easy to use way to define these?

Thanks!

**Comment by rstoenescu** [comment]
Already implemented in future v0.15.

**Comment by marcelo-rebello** [comment]
Hi,
I looking for aggregate rows functionality and didn't find anything in the docs...
Is there any example or docs of how to use it?

**Comment by marcelo-rebello** [comment]
@smolinari I am aware that is possible to implement aggregates using named slots....
But is tedious and repetitive...
A table with last row (or column) showing aggregates is a  super common use case since Excel.
Quasar is an amazing framework with elegant solutions to lots of UI use cases... I just thought that includes (default?) aggregate columns or rows just passing a function or property would be a nice add-on to datatable component ( and is present in several other frameworks...)

**Comment by smolinari** [comment]
Why tedious and repetitive? You build out your own component with QTable in it one time. You just need to make your aggregation feature universal. 

Scott
