### ISSUE TITLE
QInput rules parameter has any type with Volar

### ISSUE THREAD

**Issue by jlucaso1** [quasarframework/quasar#11043]
**Describe the bug**
When I create an input with rules, the IDE (VSCode) show me this error:
`Parameter 'val' implicitly has an 'any' type.ts(7006)`
Example:
`<q-input
        v-model="model"
        label="Required Field"
        :rules="[(val) => (val && val.length > 0) || 'Field is required!']"
     />`

**Platform (please complete the following information):**
Quasar Version: 2.1.7
@quasar/app Version: 3.1.5

Thanks

**Comment by IlCallo** [comment]
Easy fix is to provide rules as functions instead of inlining them
Currently there's no way for TS to infer the val provided to the rule if you don't specify it manually, current tooling won't allow it but we'll keep an eye on this if in the future it will be possible (we know there's an ongoing effort from the Vue team on this)

**Comment by yusufkandemir** [comment]
Currently `rules` is `any[]`. With better type definitions for `rules` prop(_e.g. `string | (value: any) => (string | true)`_), we can get rid of the TS error, because we are going to explicitly type the parameter as `any`. We still can't infer the correct type as @IlCallo said, but at least we will have better type definitions.

**Comment by rstoenescu** [comment]
Enhancement will be available in Quasar v2.3.5
