### ISSUE TITLE
Non-props $attrs was bind into prop even though do not defined it in props

### ISSUE THREAD

**Issue by HoaiLee** [quasarframework/quasar#11057]
**Describe the bug**
- When I listen event `update:modelValue` (@update:modelValue="closeModal", closeModal I defined it as method). Then it will throw the warning `[Vue warn]: Invalid prop: type check failed for prop "onUpdate:modelValue". Expected Function, got Array`.

- The other issues, maybe the same with the issue above. I built and served by using `quasar build -d` -> `quasar serve`
Non-prop attrs (error, errorMessage,..) was bound into props even though I did not defined it in props.

**Expected behavior**
Non-props attrs should be in `$attrs`.

**Screenshots**
------- The first issue.
![Screen Shot 2021-10-21 at 17 32 09](https://user-images.githubusercontent.com/40382842/138260899-d1e37237-fd7a-4769-9876-d39fe0f1d812.png)
------- The second issue.
![The second Issue](https://user-images.githubusercontent.com/40382842/138260151-2bed8569-0e48-4e3c-ba97-2119d92b4b96.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: ^2.1.8

Quasar mode:
  - [x] SPA

Tested on:
  - [ ] SPA

OS: MacOS

**Comment by HoaiLee** [comment]
I supposed some types export by Quasar cause it
![image](https://user-images.githubusercontent.com/40382842/138261176-2667b04e-1a37-471a-9948-d2ae2b2f6dd0.png)

**Comment by rstoenescu** [comment]
Please create a codepen (https://codepen.quasar.dev) or fork a codesandbox (https://codesandbox.quasar.dev) so we can see what the code is.

Most likely this is not a Quasar bug, but the devil is in the details, so please help us understand more about your scenario so that we can take an action for Quasar if needed.

**Comment by ldiebold** [comment]
Was getting a similar error with `QTabs`. Could these problems be related?

Here's a reproduction with codesandbox
https://codesandbox.io/s/hardcore-sun-4kvbo?file=/src/pages/Index.vue

Note that I can only reproduce on codesandbox, not codepen. Guessing that's because it's a warning that will only show in developer mode.

**Comment by rstoenescu** [comment]
Hi All,

Very good catch! Fix will be available in Quasar v2.2.4.

`v-model` is syntactic sugar for `model-value="myModel" @update:model-value="val => { myModel = val }"`
Now when using `v-model` AND `@update:model-value` what Vue compiler does is it's setting onUpdate:modelValue to an Array with multiple handlers. But I've defined the type as Function instead of "Function OR Array".
