### ISSUE TITLE
[Request] Expose more SCSS variables

### ISSUE THREAD

**Issue by douglasg14b** [quasarframework/quasar#11191]
**Is your feature request related to a problem? Please describe.**

Currently the exposed variables list is small enough to not be handy for many use cases, requiring overriding the CSS in ways that can break during updates. Quasar is unnecessarily difficult to customize and style.

**Describe the solution you'd like**

More exposed variables, ideally on a component-by-component basis. A good example of comprehensive variables is https://vuetifyjs.com/en/features/sass-variables/

**Describe alternatives you've considered**

N/A

**Comment by rstoenescu** [comment]
We want to move away from Sass variables as much as possible and introduce native [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) which is why you we didn't invest time into Sass variables (and we won't). But this will come in Quasar v3, as v2 was intended to be just a port of Qv1 to Vue 3 (then it became much more, but that's another story).

However, Quasar's style (as is) is written in such a way to be really easy to customize in devland. Much easier than in other frameworks, despite the first impressions.

**Comment by douglasg14b** [comment]
@rstoenescu 

> However, Quasar's style (as is) is written in such a way to be really easy to customize in devland. Much easier than in other frameworks, despite the first impressions.

Can you explain?

**Edit:** *I was a bit frustrated when writing, rewrote to not be so sassy.*

The way I'm experiencing it is that it has to be customized the same as any other framework that doesn't provide many options there. Hunting through HTML, finding CSS classes in the DOM tree, overriding their styles, and praying they don't break next update (ie. class name changes, new structure, additional or removed styles...etc). This is slow, tedious, and error prone.

For example, making it so all inputs are much smaller and more compact (ie. for an information dense mobile app), has been a headache for a while now. Each time I turn around something unexpected is borked. It's a bit of a game a whack-a-mole.

Maybe I'm missing something or going about this the wrong way?
