### ISSUE TITLE
sourcing static image from q-btn lead to 404 GET error

### ISSUE THREAD

**Issue by kirianguiller** [quasarframework/quasar#11200]
**Describe the bug**
When I want to source a local static image (jpeg file in my case) from a Q-BTN, i get, during development, a GET 404 Not Found Error.

**Codepen/jsFiddle/Codesandbox (required)**
I wanted to create a codesandbox (only one of the three mentioned platform that can have a static files afaik), but I couldn't make it works.[ I opened an issue earlier today to signal this problem ](https://github.com/quasarframework/quasar/issues/11198)

Instead, here is a link to a minimal quasar app repo with the error I want to show : https://github.com/kirianguiller/quasarv2_qbtn_404_static_file

**To Reproduce**
```
git clone https://github.com/kirianguiller/quasarv2_qbtn_404_static_file
cd quasarv2_qbtn_404_static_file
npm install
./node_modules/.bin/quasar dev
```
And then, check the main page of the app to see the q-btn image problem

**Expected behavior**
The dev server should serve the static file (for me at this URL : http://localhost:8080/statics/random_image.jpeg) and the Q-BTN should have an image as an icon

**Screenshots**
Here is the mentioned button without the image : 
![image](https://user-images.githubusercontent.com/35531073/140040580-751fd6fb-7ad8-47ef-baf4-eae948d13b0d.png)

** Returned error **

```
Status404
Not Found
Version HTTP/1.1
Transferred 459 B (164 B size)
Referrer Policystrict-origin-when-cross-origin
```

**Platform (please complete the following information):**
Quasar Version: 2.0.0
@quasar/app Version: 3.0.0

Quasar mode:
  - [ X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ X ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: 14.18.1
NPM: 6.14.15
______

Thanks a lot for your help !

**Comment by rstoenescu** [comment]
Hi,

Incorrect usage. Please read the upgrade guide carefully.
But let's break down your current issue:

1. There is a /public folder. Use that instead of "src/statics" which has no meaning for Qv2 apps. Copy contents of src/statics to /public and delete src/statics.
2. Referencing the image should be: `icon="img:/random_image.jpeg"` and NOT `icon="img:../statics/random_image.jpeg"` (and especially NOT with a relative path when referencing a public asset); it's all explained in https://quasar.dev/quasar-cli/handling-assets

**Comment by kirianguiller** [comment]
Thank you for your answer ! It's saving me. It's working correctly now !

It's indeed written in the handling-assets page. But I can't find any reference of this `src/statics` becoming `public/` in [the quasar migration guide](https://quasar.dev/start/upgrade-guide).  And neither in the [vue3 migration guide](https://v3.vuejs.org/guide/migration/introduction.html#other-minor-changes). Do you know where it is referenced in the guide ? :)

Thanks again !

**Comment by rstoenescu** [comment]
"@quasar/app" v2 has changed that (src/statics to public). You might have missed it by upgrading directly from q/app v1 to v3.

**Comment by rstoenescu** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/4665641/140052538-b0a48819-0202-42ac-9429-9d0893cf3d92.png">

**Comment by kirianguiller** [comment]
Ah alright, this is the reason then. Sorry i kinda got confused by the distinction between quasar and quasar app.

Thanks again, all is working fine, and it's much clearer for me now :)

**Comment by HammadDogar** [comment]
Finally, I found the solution. Thanks @kirianguiller for the issue report and Thanks to you man @rstoenescu . The same case was done with myself that I upgrade from v1 to v3 that's why I missed the public folder thing in this.

**Comment by FahadWebDev** [comment]
Finally, I found the solution. I did find many issues related the "static files not found" but was not getting my answer and here I'm. Thanks @kirianguiller  for the issue report and Thanks to you man @rstoenescu  . The same case was done with myself that I upgrade from v1 to v3 that's why I missed the public folder thing in this.
