### ISSUE TITLE
Some issue with the message

### ISSUE THREAD

**Issue by tianhuat** [quasarframework/quasar#11211]
This is minor stuff: The actual script is .ts extension (typescript is used) but the console shows .js extension.
![image](https://user-images.githubusercontent.com/12793956/140296053-dea69ff4-6fe7-4127-b14c-cfd40b0f6f26.png)

**Comment by rstoenescu** [comment]
Hi,

Doesn't quite makes sense to generate a new page and not mention that you want it in TS format.
`quasar new page -f ts LoginPage` (notice `-f ts` === format TS)

So since the page is not generated in TS format, Quasar assumes that the router file is in "js" format also :)
But agreed, the CLI can be improved.

**Comment by rstoenescu** [comment]
Fix will be available in q/app 3.1.10
