### ISSUE TITLE
css-loader v6

### ISSUE THREAD

**Issue by LetFree** [quasarframework/quasar#11220]
css-loader v6 已经发布很久了，为啥不升级呢

**Comment by pdanpdan** [comment]
Hello. Please use English and respect the issue template.

**Comment by rstoenescu** [comment]
@LetFree 
Because it requires us to convert the config to Webpack's Asset Management, but we offer support (in quasar.conf.js) for webpack-chain which hasn't upgraded to the syntax for all the goodies of webpack 5. So we're stuck until webpack-chain makes progress. Moreover, the benefits of css-loader v6 are not that important.

**Comment by LetFree** [comment]
> @LetFree因为它要求我们将配置转换为 Webpack 的资产管理，但我们为尚未升级到 Webpack 5 所有好东西的语法的 webpack 链提供支持（在 quasar.conf .js）。因此，我们一直坚持到网络包链取得进展。此外，css-装载机 v6 的好处不是那么重要。

thanks~
