### ISSUE TITLE
Does anyone have an issue where occasionally you will navigate to a new route and be unable to scroll?

### ISSUE THREAD

**Issue by jdheeter** [quasarframework/quasar#1122]
Hi, I'll delete this post if not productive, had an issue registering on the forum.

I'm having an issue which is difficult to reproduce, but I would say it happens maybe 1 out of every 20 times I navigate to a new route.

I'm not able to determine if the issue is specific to Quasar or possibly vue-router.

After a router.push() to a new page I am sometimes unable to scroll (1 out of 20). It's as if the browser is unaware that the new page has a taller height. The view is simply locked at the top of the page. If I manually refresh the page then this issue resolves itself. It happens often during development, I haven't tried to reproduce the issue after building the project but I suspect it's not specific to dev mode.

Does this ring a bell for anyone?

**Comment by rstoenescu** [comment]
Hi,

Does this has to do with not closing the layout left/right side before navigating to a new route? Any repo I can take a look at?
Also, please contact me on Gitter if you were unable to create a new account on forum to sort it out. I've recently added some plugins to avoid automatic registration because we are now fighting spam a lot.
