### ISSUE TITLE
Quasar, Nuxt3 SSR: window is not defined

### ISSUE THREAD

**Issue by jlucaso1** [quasarframework/quasar#11281]
**Describe the bug**
The bug occurs when I try to implement any Quasar plugin.

**Codepen/jsFiddle/Codesandbox (required)**
[StackBlitz Sandbox](https://stackblitz.com/edit/nuxt3-quasar)

**Expected behavior**
Use Quasar plugins on client only.

**Example**
`nuxtApp.vueApp.use(Quasar, {
    plugins: ["Notify"]
  });`

**Full Error**
`window is not defined
  at $id_66d0eb88 (file:///D:/nuxt3-app/.nuxt/dist/server/server.mjs:1772:1154)`

**Platform (please complete the following information):**
Quasar Version: 2.3.1
OS: Windows 11
Node: 16.13.0

**Comment by rstoenescu** [comment]
We do not (yet) offer Nuxt support.

**Comment by angelhdzmultimedia** [comment]
It's a shame. Quasar seems to want to be exclusive and lock the users down to their ecosystem, instead of letting the user deciding what of its many tools to use. For example, if one only needs the UI, one could only use the components. 
They don't add Nuxt 3 support because they want you to use Quasar's SSR. And instead of promoting Vite Plugin, so you can use Quasar in a Vite project, they promote Quasar CLI + Vite the most.

I've been promoting Quasar a lot, but that reply, and all the time I've been trying to get Quasar to work in Nuxt... 
it's gonna make me move to Vuetify, which works nice for being in v3.0.0 beta... some hiccups here and there that I can ignore for now.

**Comment by pylvr** [comment]
> We do not (yet) offer Nuxt support.

do we now ?

**Comment by angelhdzmultimedia** [comment]
> > We do not (yet) offer Nuxt support.
> 
> do we now ?

Follow this thread: https://github.com/quasarframework/quasar/issues/11165#issuecomment-1464724201

There's already a non-official Quasar module for Nuxt 3. I'm using it.
