### ISSUE TITLE
q-input hide-bottom-space not working when failed to rules prop

### ISSUE THREAD

**Issue by leteu** [quasarframework/quasar#11282]
**Describe the bug**
q-input hide-bottom-space not working when failed to rules prop

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/leteu-the-sasster/pen/porZpaO

**To Reproduce**
1. focus input
2. focus out input
3. check bottom space

**Expected behavior**
hide bottom space when failed to rules prop

**Screenshots**
![image](https://user-images.githubusercontent.com/77822996/141229892-6975dedb-4979-4dc0-8051-f261c5eb928b.png)

**Platform (please complete the following information):**
Quasar Version: 2.3.1
@quasar/app Version: 3.2.0

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [x] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: window 10
Node:
NPM: 6.14.10
Yarn:
Browsers: Chrome 95.0.4638.69
iOS:
Android:
Electron:

**Additional context**

**Comment by metalsadman** [comment]
it's working fine per docs description.
![image](https://user-images.githubusercontent.com/31038838/141261710-bee3acda-cfed-46f8-9bd5-918c752c2d94.png)

since you are using `rules`, you can just hide the error message slot generated when there's an error in your validation using a class.
https://codepen.io/metalsadman/pen/wvqxXmN

alternative is to use external validation and set `error` prop of qinput manually.
