### ISSUE TITLE
FontAwesome Pro and uploaded icons with 'fak' prefix

### ISSUE THREAD

**Issue by joshuavachon25** [quasarframework/quasar#11312]
In the documentation for how to install FontAwesomePro (https://quasar.dev/options/installing-icon-libraries), there is one thing missing: how to use custom uploaded icons (https://fontawesome.com/v5.15/how-to-use/on-the-web/using-kits/uploading-icons) ?

Can someone help with that?

Thank you!

**Comment by hawkeye64** [comment]
It appears uploaded icons in Pro use `fak` prefix. QIcon needs to recognize this during parsing so the right icon can be used. 

I can add the parsing later today.

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.3.2.

**Comment by lianee** [comment]
Works well with the "fak" prefix. However, fontawesome is also using full prefixes (fa-solid instead of fas), and in the case of kits, the full prefix is "fa-kit" and it seems it is not parsed.
Would it be possible to add this full prefix in the parsing, like it is done for the various styles (solid, regular, light...)?
