### ISSUE TITLE
keyCode is depricated, however it is still used in docs

### ISSUE THREAD

**Issue by kostyfisik** [quasarframework/quasar#11378]
According to
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
usage of `keyCode` is deprecated due to know issues with support of layouts for languages other than English

However, it is still used in e.g. https://quasar.dev/vue-components/input#shadow-text and may be in many other places. Are there any good reason to keep it in docs? Or it should be updated with `keyboardEvent.code`?

**Comment by pdanpdan** [comment]
Code is not a good choice because it returns the physical key.
And for what the code checks (tab, ESC) the keyCode is consistent.
Despite the warning about deprecation that is there for so many years, and the problems with printable or composed characters, keyCode is supported in all browsers and for control characters works as expected.
