### ISSUE TITLE
QBtn with loading=true does not hinder form submission

### ISSUE THREAD

**Issue by sjones512** [quasarframework/quasar#11392]
The [documentation](https://quasar.dev/vue-components/button#controlling-the-button-for-form-submission) implies that setting the :loading prop of a QBtn will disable the form submission while loading is true.

This does not appear to be the case. 

Adding `console.log` statements to the `simulateSubmit` handler shows that the handler is called even if loading is true.  The documentation does not make it clear whether this should be handled in the handler, or should be handled for us by the `QBtn`.

**Comment by pdanpdan** [comment]
Nothing in the docs tells something like this.
Loading disables the button, not the submit method of the form.

**Comment by sjones512** [comment]
It says directly in the docs

" and to prevent the user repeatedly pressing the button"

Which is not the case. The cursor changes from a pointer to an arrow, but
it does not prevent multiple clicks.

**Comment by pdanpdan** [comment]
Hello. My bad, it's not an error in the docs, it's in the implementation, it's a regression from v1
If the button is `type="submit"` the button is not disabled or it's type is not changed to `button` when loading is active, so that a click on it triggers the form submit even if there is no `@click` on the button.

Thank you for insisting on this.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.3.3
