### ISSUE TITLE
Modal dont close

### ISSUE THREAD

**Issue by cgarnier** [quasarframework/quasar#1140]
### Software version

Quasar: 0.14.7
OS: linux
Node: 8+
NPM: 5+
Browsers: chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Modal never close

### What were you expecting?
Modal should close when i call its close() method

### What steps did you take, to get the error?
Add a modal to an app
```
// $vm is the modal vm
$vm.open()
$vm.close()
```
The modal wont close.
`$vm.toggleInProgress` stay on false.

**Comment by rstoenescu** [comment]
There is currently a delay when opening it. It's required because it tampers with window history in order to respond to "back" button (both on desktop and mobile). Calling open() and immediately after close() will not work because of the required delay.
However, open(() => close()) will. open/close() methods take a callback as parameter.

**Comment by cgarnier** [comment]
in fact, in dont call the both in a raw. I call it from the console or on a @click and the toggleInProgress stuck on true.

**Comment by cgestes** [comment]
I also experience this bug.

**Comment by cgarnier** [comment]
@rstoenescu you should reopen. I m not the only to expriencing this bug.

**Comment by rstoenescu** [comment]
@cgarnier Everything got re-worked on v0.15 (releasing mid-January), so don't think this should be reopened.
