### ISSUE TITLE
Quasar over vue cli type script support

### ISSUE THREAD

**Issue by otatar** [quasarframework/quasar#11491]
Hi there,

I have created a Vue3 app with typescript support using vue cli, and after that I have added quasar framework with: vue add quasar.

However when I try nom run dev:
`ERROR in src/main.ts:7:31
TS7016: Could not find a declaration file for module './quasar-user-options'`

is it possible to use quasar with vue 3 typescript without quasar cli?

**Comment by yusufkandemir** [comment]
Hi 👋 You didn't follow the issue template, it makes it harder for us to investigate and solve the issue. Also, since your issue is directly and only about Vue CLI Plugin, please use the correct repository: https://github.com/quasarframework/vue-cli-plugin-quasar

I went ahead and try to reproduce the issue, and confirmed that there is a problem. To solve it, you need to rename the file `/src/quasar-user-options.js` to `/src/quasar-user-options.ts`. If you have other problems with Quasar Vue CLI Plugin, please use the correct repository as I mentioned.
