### ISSUE TITLE
Have a plan to support `nativescript`? 

### ISSUE THREAD

**Issue by lichnow** [quasarframework/quasar#1152]
Hybrid app like "cordova" use webview for mobile app.But many mobile's (ios or android) api integration with browser is so slowly.If quasar integration `nativescript` ,it is will be a best frontend framework ^^

**Comment by rstoenescu** [comment]
Will take this into consideration, although the current funding on Patreon would need to rise so I can have more time for Quasar.

**Comment by joshtorres** [comment]
+1 for this :D

**Comment by imdanielpiva** [comment]
It would be really awesome.

**Comment by forgotpw1** [comment]
Yes. I have the same interest. There is a vue.js nativescript project that
seems to be building their own set of controls. It would be great if they
could just use the already amazing quasar controls or there is an option to
build to nativescript? There must be some fundamental difference between
nativescript and Cordova. What is the gap?

**Comment by mijzcx** [comment]
Something like a quasar generator. Upon entering command like.
>quasar -ns
Would translate templates (quasar components) into native-script components and would sit in nativescript folder, just like cordova.

Then tns to build into native-script.

Those Quasar components that has no associated nativescript component will remain in webview target for the meantime.

Nice to have this. +1

**Comment by intermundos** [comment]
Any news on this?
Would be the top tool for crafting front end.

**Comment by murbanowicz** [comment]
+1 
Any updates?

**Comment by forgotpw1** [comment]
@rstoenescu  This is interesting. https://github.com/nativescript-vue/nativescript-vue-webpack-template

The it allows for a 'template'  tag for 'web' and another one for 'mobile'. The later utilizes the nativescript tags/component, which are analogous to quasar components. 

Something like this would let us not worry about mapping quasar components to nativescript components, and, share the 'script' tags between quasar(pwa,spa, cordova) and nativescript-vue

Then it would just be linking up the nativescript-vue build tools in the quasar cli and directing a nativescript build to compile. 

There's probably more to it but this is one idea to narrow the gap between nativescript-vue and quasar

**Comment by rstoenescu** [comment]
If someone wants to give it a try and make a demo / proof of concept then please do. Currently focusing on finally shipping v1.0, otherwise we'll never reach it as more and more Quasar Modes are requested. Most probably don't realise the team size and that we're providing combined functionality of a UI component lib + CLI + PWA + Cordova + SSR -- the amount of work is already currently insane, this is why any help is greatly appreciated.

**Comment by eeerrrttty** [comment]
Hello! Quasar v1 is running and stable. What are the plans? Today we have react native on top trend because it's native integration, if quasar does it, it will be of course the top 1 trend. As vue is a hundred times easier then react, a lot of teams will start using quasar

**Comment by nothingismagick** [comment]
There are no plans to target nativescript on our roadmap. We have our hands
rather full at the moment investigating capacitor.

However if you want to build a proposal mode and PR core, I suppose we
would look at it, but every mode needs to not only be very carefully
planned, it also needs to be maintained.

Another approach might be to find the funding needed to pay the core team
to build and maintain this, but again - I am quite skeptical that we would
take on this burden - not the least because my understanding of
nativescript says that many quasar components won't work, and we have a
zero tolerance policy about introducing things into our ecosystem that are
not compliant with core. If I am wrong, please let me know.

**Comment by ajmakoni** [comment]
Hello quasar team, its been 2 years since this thread was closed. Are there any seconds thoughts yet on nativesript integration?

**Comment by matheusmacedoap** [comment]
Alguma novidade sobre essa integração?
