### ISSUE TITLE
Documentation for `build.publicPath` should mention about `vueRouterBase`

### ISSUE THREAD

**Issue by jmsuresh** [quasarframework/quasar#11676]
Someone trying to modify `publicPath` to get the SPA deployed using a framework such as django is going to need to modify `vueRouterBase` (most likely set it to `"/"`). It would be helpful if this tip is present in the documentation for `build.publicPath`.

**Comment by pdanpdan** [comment]
You mean this: https://quasar.dev/quasar-cli/quasar-conf-js#property-build ?
2 rows below publicPath

**Comment by jmsuresh** [comment]
Yes. Currently the content is as below:

publicPath | String | Public path of your app. By default, it uses the root. Use it when your public path is something else, like “<protocol>://<domain>/some/nested/folder” – in this case, it means the distributables are in “some/nested/folder” on your webserver.
-- | -- | --

**Comment by MilosPaunovic** [comment]
| Property   |      Type      |  Description |
|:----------|:-------------|:------|
| publicPath | String | Public path of your app. By default, it uses the root. Use it when your public path is something else, like “<protocol>://<domain>/some/nested/folder” – in this case, it means the distributables are in “some/nested/folder” on your webserver. |
| vueRouterBase |    String   |   Force vue router base with your custom value; configure only if you really know what you are doing, otherwise you can easily break your app. Highly recommended is to leave this computed by quasar/app. |
