### ISSUE TITLE
QScrollArea has zero height

### ISSUE THREAD

**Issue by ivanjaros** [quasarframework/quasar#11707]
If I don't specify height for the scroll area element, it will always have zero height. This is an example:
```<q-card class="shadow-8">
    <q-scroll-area style="height: 5rem;">
      <div class="row no-wrap">
        <div class="col q-pa-sm" v-for="i in [...Array(30).keys()]" :key="i">
          <div class="row">
            <div class="col">
              foo bar baz
            </div>
          </div>
        </div>
      </div>
    </q-scroll-area>
  </q-card>
```

Is this a bug or does it have something to do with the content I am putting into it, ie. does it work with grid? I just want to make **horizontally-scrolled** card.

Quasar 1.2.2

(there are more than one column where the foo bar baz is, this is just an example)

**Comment by pdanpdan** [comment]
Read the docs

**Comment by hawkeye64** [comment]
@ivanjaros typically I use a parent div around QScrollArea. I give that one width and height. Then on the QScrollArea, I use the class `fit`. Because QScrollArea is intended to be a scroll area, it can't make any assumptions about the height based on the content. It needs to know the height, either directly or indirectly via a parent.
