### ISSUE TITLE
Misleading statement in upgrade guide

### ISSUE THREAD

**Issue by fabriste** [quasarframework/quasar#11816]
I've started to upgrade my app to v2 and i found something in the documentation that could be misleading, right [here](https://quasar.dev/start/upgrade-guide#introduction) :  the text about composition API & option API says : `"[...]This does NOT mean that you can’t use the legacy Options API" `
Actually it have been said by the Vuejs team that the Option API is not a legacy nor will be deprecated as you can read below :

> Thorsten Lünborg in Vue 3: Data down, Events up (19-MAY-2020): https://www.vuemastery.com/blog/vue-3-data-down-events-up/
> 
> IMPORTANT: The composition API is additive, it’s a new feature, but it doesn’t and will not replace the good ole “Options API” you know and love from Vue 1 and 2. Just consider this new API as another tool in your toolbox that may come in handy in certain situations that feel a little clumsy to solve with the Options API.

> Ben Hong in Enjoy the Vue #48: "New in Vue 3: The Composition API" (19-JAN-2021): https://enjoythevue.io/episodes/48
> 
> [00:01:03] T: Yeah. Well, the first thing I remember hearing was that it was replacing the options API.
> [00:01:08] BH: Big disclaimer. That isn’t happening. Big disclaimer.
> [00:09:10] BH: [...] this is not something you need to go and rewrite your app in. [...] the composition API is not like, drop the options do composition. It's an additive thing that when you have a problem that it can solve, it's really great for that.
> 

And confirmed [here](https://github.com/vuejs/rfcs/pull/42) 

Is it possible to correct this sentence that could be misleading ?

**Comment by pdanpdan** [comment]
PR's are welcome

**Comment by rstoenescu** [comment]
@fabriste Once in a while there is a ticket that boils my blood. This is one of them.

How is it not legacy since if you read Vue 3's source code and look through its history you will see that the Options API was added after the Composition API. There are also code comments in Vue 3 which clearly state "legacy Options API". Furthermore, the Options API is the one being "additive" on top of the Composition API and can even be disabled if you turn off a flag. Options API is "translated" into Composition API, and Composition API is not under any flag.

But bottom line, "legacy" does not mean it's going to be removed in Vue 3. That is VERY obvious because this would mean a big breaking change. However, nothing is said about it for Vue 4/5/6/...

This is one hell of an irony. We're trying to set up developers for the right path (because anyway Composition API opens up a world of new possibilities) and we're being backlashed for it. Read Vue 3's source code if you don't believe me or reply to this ticket and I will offer direct links and screenshots.

**Comment by fabriste** [comment]
Hi @rstoenescu first of all chill out i've came with my arguments to the discussion, you bring yours and i'm open to the discussion, you learned me multiple thing about vue3 source code that i haven't read yet. I'm aware of the possibilities that bring Composition API, but i did not saw any announcements by the official vuejs team, saying that Option API would be legacy in the future so my statement is not totally wrong.
I'll be glad if you share those links & screenshot here.
