### ISSUE TITLE
Tooltip does not hide when you open menu or start dragging item

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#11810]
**Describe the bug**

Tooltip does not hide when you open menu or start dragging item

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**

https://codepen.io/ilyalyu/pen/YzrYRJB

**To Reproduce**
1. Go to above link
2. Wait for tooltip
3. Click on the button
4. See that tooltip did not disapper and even more - it is above menu

**Expected behavior**
Tooltip should hide on menu showing

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/70687432/147573789-00caf738-48a3-4741-bd96-de6affb081ab.jpg)

**Platform (please complete the following information):**

Codepen

**Additional context**

I would also want tooltip to hide when dragging with vuedraggable package.
I will provide repro repository for this if needed.

**Comment by pdanpdan** [comment]
There is no relation between the tooltip and a menu that will show up. There is no logical generic rule that we can think of that could create a relationship between them.
An tooltips have a higher z-index than menus, that is by design.
What you can do, if you know your specific case, is to use a model for the tooltip and hide it when the menu shows.
