### ISSUE TITLE
[Request]  DateTime Range component to have predefined time ranges (shortcuts)

### ISSUE THREAD

**Issue by neorganic** [quasarframework/quasar#1215]
Hello, would be great if  DateTime Range component had predefined time ranges (shortcuts), like last day, last week, last month, last 6 month, last year and/or it could be easily customized to set those predefined time ranges.

I currently want to convert my app to Quasar, but the only thing holding me is the lack of this feature. Thanks in advance !

![](https://i.imgur.com/RvSfZ7O.png)

**Comment by rstoenescu** [comment]
Hi,

This is outdated starting with v0.15. QDatetimeRange has been deprecated since two QDatetime-s can be used side by side with same effect. This way they can be configured much easier in user-space. Adding all requests regarding this component will make it highly inefficient. Since it's very easy to just configure two QDatetimes side by side, this component will be removed. Sorry for any inconvenience.
