### ISSUE TITLE
QDrawer cannot be initially set to true

### ISSUE THREAD

**Issue by Rolanddoda** [quasarframework/quasar#12220]
### What happened?

QDrawer initial value to `true` doesn't work.

### What did you expect to happen?

I expected the Drawer to stay open after refresh

### Reproduction URL

https://codesandbox.io/s/qdrawer-cannot-be-set-to-true-3k0fg?file=/src/App.vue

### How to reproduce?

1. Go the the reproduction link
2. Refresh the view
3. Observe that the Drawer auto-closes when instead should stay open

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

SPA Mode

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment]
`show-if-above`

**Comment by Rolanddoda** [comment]
@pdanpdan thank you for closing another issue without even trying to investigate, comment a good response or see if your solution actually works.

But guess what, it doesn't work! 

### So can you please open the issue again?

**Comment by pdanpdan** [comment]
You have it as `overlay` - it cannot be open by default

**Comment by Rolanddoda** [comment]
> You have it as `overlay` - it cannot be open by default

Nowhere do the docs say that `overlay` cannot be opened by default. So maybe something should be added in the docs if you are right?

@rstoenescu if you think it's not a bug that `overlay` cannot be opened on initially render, then it's a bug that on refresh the Drawer appears opened and then closes by itself. Am I wrong ?

**Comment by pdanpdan** [comment]
You made a mess with the props:
- you have it as `container`
- - overlay
- `behavior="mobile"`
In you case the problem is it is `container` - my bad, `overlay` works to show on load

**Comment by Rolanddoda** [comment]
@pdanpdan I don't know what is your problem but you certainly don't want me to open bugs. I am trying to help Quasar by investing my time in reporting the bug. And you seem to just add random comments.

There is no mess with the props. [Here is a "no mess with the props" version](https://codesandbox.io/s/fancy-hill-qnw2y?file=/src/App.vue) with only these props:

```
      v-model="drawerLeft"
      side="left"
      overlay
```

You went from "You have it as overlay - it cannot be open by default" to "my bad, overlay works to show on load" and now the problem is the `container` ?? 

### Did you try the container? Because again, it doesn't work

Can you please be helpful by actually taking a look at the issue ? Thank you

**Comment by rstoenescu** [comment]
This seems like a bug in Vue. A watcher in QDrawer is erroneously called.
Will investigate.

**Comment by rstoenescu** [comment]
@Rolanddoda 

1. Workaround until I'll sort this out: use "persistent" prop on the QDrawer. Ruled out Vue as a root cause. It might actually be a regression in vue-router because it all starts from a route watcher. Will keep this thread up to date as I progress.
2. Thanks for reporting and for your time! Please do not take Dan's comments in a negative fashion. We're all dealing with lots of stuff on our plate and just trying to make the best of it, but sometimes exhaustion can lead to things like this. All it matters is that in the end Quasar can serve developers even better.

**Comment by rstoenescu** [comment]
@Rolanddoda 

So it seems that Vue Router issues a route change when page is first loaded. This triggers a drawer hide() call (unless the QDrawer is set to be `persistent`).
Now, since App.vue is the root component, the route watcher gets to be triggered by this initial route change.

There is no technical solution to: a) start the watcher after Vue Router's first initial route change or even b) determine if the route change is the initial one or not.

The only solution is to just not make the QLayout part of the App.vue directly. Let App.vue render your QLayout through `<router-view />`.

**Comment by rstoenescu** [comment]
Pushed a perf improvement on route watching though. It'll go into Quasar v2.4.14.
A side-effect will be that if your app is started from the root route, it won't trigger the drawer hide() call described earlier (even if you put QDrawer directly under App.vue). But if starting your app with another route, the problem will still happen.

Bottom line: get your layout out of App.vue or use `persistent` on QDrawer.

**Comment by Rolanddoda** [comment]
Thanks for the detailed explanation @rstoenescu.
