### ISSUE TITLE
Updated content is available. Please refresh the page.

### ISSUE THREAD

**Issue by mrleblanc101** [quasarframework/quasar#12312]
### Description

<img width="2032" alt="Capture d’écran, le 2022-02-02 à 13 57 29" src="https://user-images.githubusercontent.com/17392251/152220581-c2c9108d-8be3-4b93-b774-dbf41a5b0ba8.png">

I don't understand why I get this everytime I come to check the documentation.
Shouldn't the data be up-to-date the first time I load it ?  I just came from a Google Search link.
I would understand if it did this while I was on the page, to notify me the content might have changed.

### Documentation Section URL

https://quasar.dev/

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
It means exactly what the banner says. That we made an update to the docs. Is this such a bad thing that we care for the docs being up to date with the latest releases? :)

**Comment by mrleblanc101** [comment]
I still don't understand why I get this almost every time I go to the doc... Shouldn't the doc be up to date when I load the page ? 🙃

**Comment by rstoenescu** [comment]
No. Because that's not how PWAs work. When you open the page it uses the PWA cache and checks if there's a newer version. If it detects a newer version it downloads it and then it shows the banner that it's been updated. Only a refresh of the page would then use the updated version. We could do this page refresh automatically but it would mean that the docs refresh WHILE you are already browsing it. In other words, "it gets in the way" of what you are currently doing aka bad experience. So the user needs to decide when he wants the refresh.

**Comment by mrleblanc101** [comment]
I thought this was related to PWA. Vue also does something like this I believe. (Or VuePress ?)

I guess I don't see the attractiveness of a PWA if you land on an outdated page and get nagged by yet another banner. 

But I understand some people might like that the doc is available offline. I just wish PWA handled this differently.

Thanks for the reply

**Comment by rstoenescu** [comment]
The whole point is to get that page up and running instantly. Then check for updates in the background. If it would check and also update when you start the page that would be (for the most part) equivalent to not running a PWA at all :)
