### ISSUE TITLE
QKnob: toggling "disable" prop leads into dragging still working

### ISSUE THREAD

**Issue by iliubinskii** [quasarframework/quasar#12372]
### What happened?

Disabled Knob is editable by hand-dragging

### What did you expect to happen?

Should not be editable

### Reproduction URL

https://codepen.io/ilyalyu/pen/YzEpvZv

### How to reproduce?

1. Go to codepen https://codepen.io/ilyalyu/pen/YzEpvZv
2. Click "Disable" toggle
3. Try to edit Knob by dragging

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.5.4

**Comment by gregadro** [comment]
@rstoenescu I also worked on this yesterday and tried with the same `hDir` solution, but after toggling back to the enabled state, the dragging didn't work as it should (couldn't drag to more than 5 or less than 3 in the provided example). Then I tried your code from [8be5585](https://github.com/quasarframework/quasar/commit/8be5585dbcb810a82f881f7e57851ec9f56eff40) and the behavior is the same. 

I "solved" the issue by calling ToucPan directive without the value (`pan` function), arg, and modifiers, and it worked ok when toggling back to the enabled state. I guess this is not the correct solution but maybe it will help you identify the real problem.

You can check my commit [4cecd44](https://github.com/gregadro/quasar/commit/4cecd44d8bae8e5adf4b0a8efe2e352962827c6c); knob.vue is heavily modified for easier problem identification.

**Comment by rstoenescu** [comment]
Hi,

The fix I pushed is the correct one. Let me explain. There is a fundamental problem with directives lifecycle in Vue 3. Directives are attached to VNodes and their lifecycle matches the VNode's. When using render functions, once a directive is attached to a VNode it cannot be removed by simply not using withDirectives() on the same node on next render tick.

render() -> withDirectives(node, ...) ---> attaches directive
next render() -> node ---> does NOT mean it removes the directive; it's still there, attached to node

This is why I invented the hDir() which forces the creation of a new VNode when we need to attach or remove our directive. So that the VNode's lifecycle makes the directive's lifecycle kick in. And problem solved, with high efficiency, since we won't have the overhead of the directive when we don't need it.

Now, indeed there's still a problem, but a completely different one. So thanks for the follow-up! Since I now recreate the root VNode, the old `$el` variable is no longer pointing to the correct DOM node, so all computations with it are bogus, which is why you experience the second issue.

Fixed that too.

**Comment by gregadro** [comment]
Thank you for a great explanation! My commit is the one I was referring to as the wrong one since I knew it is not ok to have an empty and not-needed dir. But I was clueless about where is the problem coming from after enabling back the knob. :bow:

**Comment by rstoenescu** [comment]
Thanks for testing and finding the other issue!
