### ISSUE TITLE
polyfills not applied for typescript project

### ISSUE THREAD

**Issue by panmenghan** [quasarframework/quasar#12452]
### What happened?

see as title

### What did you expect to happen?

see in the **How to reproduce?** section

### Reproduction URL

...

### How to reproduce?

1. run `quasar create quasar-ts`  to create a **typescript** project

2. edit `src/App.vue`, and add this line `const text = ''.trimEnd()`  somewhere in `<script lang="ts">` to trigger the corejs polyfill

3. edit `babel.config.js` to enable babel debugging:
```js
module.exports = api => {
  return {
    presets: [
      [
        '@quasar/babel-preset-app',
        api.caller(caller => caller && caller.target === 'node')
          ? { targets: { node: 'current' } }
          : { debug: true } // add this 
      ]
    ]
  }
}
```

4. run `quasar build`, the output should have this line. (**javascript** project has this line, but not **typescript** project)
```
...

[... src\App.vue]
The corejs3 polyfill added the following polyfills:
  es.string.trim-end { "android":"91", "chrome":"89", "edge":"95", "firefox":"87", "ios":"12", "opera":"79", "safari":"13" }
...
```

my fix: edit `quasar.conf.js`, and add this:
```js
build: {
  extendWebpack(cfg) {
    const jsRule = cfg.module.rules[2].use[0] // js babel-loader rule
    cfg.module.rules[3].use.unshift(jsRule) // insert to ts
  },
}
```

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app), TypeScript Support

**Comment by yusufkandemir** [comment]
It's not TS vs JS, it's about `package.json > browserslist`.

If you create a new project or update the browserslist DB, `last 10 Chrome versions` would target down to Chrome 99, but let's say, you come back to the project in a year, and it'll still think the last 10 Chrome versions are down to Chrome 99. However, if you then update the browserslist DB, it'll update itself to fetch the latest available Chrome versions. So, your TS project is a new one and browser targets don't require a polyfill, but your JS project requires one, not because it's a JS project, but because of the browserslist.

If you still think there is a problem regarding TS vs JS, then please provide two reproduction repositories so we can take a deeper look.
