### ISSUE TITLE
vue-cli-plugin-quasar not working with Vue-cli v. 5.0.1

### ISSUE THREAD

**Issue by capgert** [quasarframework/quasar#12514]
### What happened?

I created a new project using Vue-CLI v. 5.0.1 and then installed Quasar with: vue add quasar.
When I run the application I get the warning: Failed to resolve component for each Quasar component found in the page.
Everything was working fine up to Vue-CLI v. 5.0.0-rc.2, this problem surfaced starting from v. 5.0.0-rc.3 and persists with v. 5.0.1
Any idea what causes the problem?
Thanks

### What did you expect to happen?

Quasar components working properly as when using Vue-CLI v. 5.0.0-rc.2 + vue-cli-plugin-quasar 4.0.4

### Reproduction URL

no URL

### How to reproduce?

1. Create a new vue project with: vue create project-name
2. Add quasar with: vue add quasar
3. Run then project with: npm run serve (or through vue UI)

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox

**Comment by yusufkandemir** [comment]
Hi, Vue CLI's first stable release [v5.0.1](https://github.com/vuejs/vue-cli/releases/tag/v5.0.1) is released yesterday. So, we don't support it yet. Please open a feature request on https://github.com/quasarframework/vue-cli-plugin-quasar. You can also experience this with other community Vue CLI plugins as well, because of the breaking changes. So, you might also consider waiting for the community to catch up.

Also, you might consider using Quasar CLI or Vite instead:
https://vuejs.org/guide/scaling-up/tooling.html#project-scaffolding
> [Vue CLI](https://cli.vuejs.org/) is the official webpack-based toolchain for Vue. It is now in maintenance mode and we recommend starting new projects with Vite unless you rely on specific webpack-only features. Vite will provide superior developer experience in most cases.
> 
> For information on migrating from Vue CLI to Vite:
> [Vue CLI -> Vite Migration Guide from VueSchool.io](https://vueschool.io/articles/vuejs-tutorials/how-to-migrate-from-vue-cli-to-vite/)
[Tools / Plugins that help with auto migration](https://github.com/vitejs/awesome-vite#vue-cli)

**Comment by OneFourFree** [comment]
Vue CLI has made 'cache-loader' optional.

So you need to install cache-loader as a dev dependency.
`yarn add -D cache-loader`

**Comment by capgert** [comment]
Hi Yusuf,
thank you very much for your help. I checked the issue with cache-loader
but it doesn't seem to be the culprit.
cache-loader has been deprecated as of Webpack 5 (the version used by
vue-cli 5), and as such trying to install it gives a dependency error.
Looking at the changelog for vue-cli rc.3 actually seems that the only
breaking change added (from rc.2) is making cache-loader optional as you
say.
I'll do some more investigation when I have time, if i get to some result
I'll let you know.

Thanks again
francesco

Il giorno dom 20 feb 2022 alle ore 22:54 OneFourFree <
***@***.***> ha scritto:

**Comment by qxygene** [comment]
> cache-loader

We couldnt install cache-loader to Vue CLI's [v5.0.1] > Conflicting peer dependency: webpack@4.46.0, so it is not working with it, any updates?
