### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#12806]
### What happened?

Unable to cache `pwa-camera-modal.entry.js` 

TypeError: Failed to fetch dynamically imported module: 

`yarn add @ionic/pwa-elements` 

`boot/capacitor.ts`
```
import { defineCustomElements } from '@ionic/pwa-elements/loader';

export default async () => {
  await defineCustomElements(window);
};

```
`https://127.0.0.1:8008/node_modules/.q-cache/vite/spa/pwa-camera-modal.entry.js`

### What did you expect to happen?

able to use capacitor camera on the web

### Reproduction URL

no link 

### How to reproduce?

install 

1: `yarn add @ionic/pwa-elements` 

2: Add capacitor.ts to quasar.config.js boot

3: quasar d

4: test the capacitor camera on web you it wont work 

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SPA Mode

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Hi,

Please try again with q/app beta.4
And if it is still reproducible, post a reproduction repo here and I'll reopen.

**Comment by diadal** [comment]
still not able to make this work  node_modules delete fresh install still the error keep coming

<img width="708" alt="Screen Shot 2022-03-17 at 4 08 22 AM" src="https://user-images.githubusercontent.com/19895516/158796563-da070622-b8e0-44b9-b5cf-3d26f5c066dd.png">



```
import { defineCustomElements } from '@ionic/pwa-elements/loader';

export default async () => {
  await defineCustomElements(window);
};

```

**Comment by rstoenescu** [comment]
Please post a bare-minimum reproduction repo.

**Comment by diadal** [comment]
https://github.com/diadal/tester.git

**Comment by rstoenescu** [comment]
Thanks for supplying the repo.

Your problem is more related to Vite itself or the way that you are supposed to use the ionic stuff, but can't tell without extensive research. This is a very unusual way to use Capacitor stuff without Capacitor mode itself (not that you need it; I get what you're trying to achieve). Unfortunately, can't afford to invest this large amount of time on an unproven Quasar CLI issue -- I'm fairly confident (99%) that this is not Quasar at fault here.

**Comment by diadal** [comment]
but this work fine with webpack i guess like you said the issue may be with vite

also, it will be nice if quasar will have its own module for file input and camera option 

but have used a different approach

**Comment by paladyne-io** [comment]
Hi,

It's been a while since this issue was raised (and closed) but I have experienced the same issue. It seems that the file, "pwa-camera-modal.entry.js" is not in the location it is expected.  http://localhost:9000/node_modules/.q-cache/vite/spa/deps/pwa-camera-modal.entry.js. 

The camera example on this page, https://quasar.dev/quasar-cli-vite/developing-capacitor-apps/capacitor-api does not work.  I understand it is not a priority but it would be great if you could take a look at the issue.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/99455791/171636660-6ee280e5-5715-4d10-9007-c009e0d94bfc.png">

**Comment by Jeziel-Guiev** [comment]
El problema se soluciona utilizando webpack, a mi igual me salto el error y al parecer es de vite el error para no seguir con el problema me tuve que pasar a webpack

**Comment by paladyne-io** [comment]
I translated your comment. Yes, it works with Quasar with Webpack but not Quasar with Vite.  I tried again today with a new app with  the same (bad) result. This page mentions the issue and a possible workaround: https://github.com/ionic-team/pwa-elements/issues/109. I added the cdn links on this page https://capacitorjs.com/docs/web/pwa-elements to the index.html file in the Quasar project folder and it seems to work (but it took quite a long time to initilalise the first time). I think it will be possible to load the ionicpwaelements.js file locally  but I havent tried it. It would be good to not have to go to this trouble. Here are the links.

  <script type="module"
    src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.js"></script>
  <script nomodule
    src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.js"></script>

**Comment by Jeziel-Guiev** [comment]
That yes, with CDN it works well and I was testing details in that way, is that when I need to do it offline the CND does not give the first time but as a temporary solution it is not bad at all.

**Comment by obadakhalili** [comment]
> I translated your comment. Yes, it works with Quasar with Webpack but not Quasar with Vite. I tried again today with a new app with the same (bad) result. This page mentions the issue and a possible workaround: [ionic-team/pwa-elements#109](https://github.com/ionic-team/pwa-elements/issues/109). I added the cdn links on this page https://capacitorjs.com/docs/web/pwa-elements to the index.html file in the Quasar project folder and it seems to work (but it took quite a long time to initilalise the first time). I think it will be possible to load the ionicpwaelements.js file locally but I havent tried it. It would be good to not have to go to this trouble. Here are the links.
> 
> <script type="module" src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.js"></script> <script nomodule src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.js"></script>

Thanks for the suggestion!

**Comment by bruno-py** [comment]
Yes, It is possible to load the files from node_modules folder:

`<script
      type="module"
      src="node_modules\@ionic\pwa-elements\dist\ionicpwaelements\ionicpwaelements.esm.js"
    ></script>
    <script
      nomodule
      src="node_modules\@ionic\pwa-elements\dist\ionicpwaelements\ionicpwaelements.js"
    ></script>`

**Comment by CreativeWarlock** [comment]
The very same error is occurring when using "ckeditor" in a Vue / Vite project. Very annyoing. 70% of the page request this error pops up, 30% of the time the editor loads and the content is being displayed.

**Comment by LuanNascimentoRocha** [comment]
> Yes, It is possible to load the files from node_modules folder:
> 
> `<script type="module" src="node_modules\@ionic\pwa-elements\dist\ionicpwaelements\ionicpwaelements.esm.js" ></script> <script nomodule src="node_modules\@ionic\pwa-elements\dist\ionicpwaelements\ionicpwaelements.js" ></script>`

This is a possible solution, but it doesn't work if you are using Capacitor and want to build a web application and an android app. I was doing some tests, and using this kind of ''import'' only works when we run `quasar dev` or `quasar dev -m pwa`. When I tried to run `quasar dev -m capacitor -T android`, the app got an infinite white screen and would not load, so the solution I found to work around this problem was to use the following ''import'': 

`<script type="module" src="https://unpkg.com/@ionic/pwa-elements@2/dist/ionicpwaelements/ionicpwaelements.esm.js"></script>
    <script nomodule src="https://unpkg.com/@ionic/pwa-elements@2/dist/ionicpwaelements/ionicpwaelements.js"></script>`

I found this script in the pwa-elements documentation:
https://capacitorjs.com/docs/v2/web/pwa-elements#including-through-script-tag
