### ISSUE TITLE
The link to Layout Builder is broken

### ISSUE THREAD

**Issue by h2jose** [quasarframework/quasar#12923]
### What happened?

![Screen Shot 2022-03-24 at 11 07 12 AM](https://user-images.githubusercontent.com/1481933/159947232-8bb29738-86bc-471a-8aae-6b75e197fc7a.png)

### What did you expect to happen?

Open the layout builder

### Reproduction URL

https://quasar.dev/layout/layout-builder

### How to reproduce?

1. clic en "Layout Builder" button (blue and red)

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
Hi 👋 that link is not working because it's wrong. The menu item redirects to the correct page. If it's not working, then you might somehow get stuck in a half-cached version where the link is wrong, but the actual route is updated. You can try in another browser or in a private tab to confirm that it's working.

![image](https://user-images.githubusercontent.com/6266078/159983828-64030fb0-0387-49d7-a63b-957fe6d110fa.png)
![image](https://user-images.githubusercontent.com/6266078/159983888-d2dcc3e8-5b79-4c9d-b22f-d8ade5445b8f.png)
