### ISSUE TITLE
@quasar/vite-plugin@1.0.8 vite:css Undefined variable $primary

### ISSUE THREAD

**Issue by softbeehive** [quasarframework/quasar#13027]
### Conditions
I've just upgraded to latest `@quasar/vite-plugin@1.0.8`.
SCSS variables in `index.scss` that worked in 1.0.7 are not defined now.

### Error
```
[vite:css] Undefined variable.
  ╷
2 │   color: $primary;
  │          ^^^^^^^^
  ╵
  src/assets/styles/main.scss 2:10  @import
  src/assets/styles/index.scss 1:9  root stylesheet
```

**vite.config.ts**
```ts
import path from 'path'
import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'
import { quasar, transformAssetUrls } from '@quasar/vite-plugin'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: { transformAssetUrls },
    }),
    quasar({
      // sassVariables: 'quasar/src/css/variables.sass',
    }),
  ],
})

```

**index.scss**
```scss
@import 'main.scss';
```

**main.scss**
```scss
.router-link {
  color: $primary;
  text-decoration: none;

  &:hover {
    text-decoration: underline;
  }
}

```

### What did you expect to happen?

SASS/SCSS variables loaded automatically. I downgraded to 1.0.7 and tested it, sass variables are injected automatically

### Reproduction URL

none

### How to reproduce?

1. Upgrade @quasar/vite-plugin from 1.0.7 to 1.0.8
2. Use SASS variable in any scss file imported to root index.scss

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Style & Identity (quasar)

**Comment by rstoenescu** [comment]
For performance reasons, we check if the initial scss/sass file contains any variables. And then and only then we inject the variables, otherwise we'd need to inject the variables for all the files whether they use it or not, which degrades performance. And unfortunately, we can only inspect the initial scss/sass file -- and not follow the chain of what other files are imported and if those use the variables or not (the perf penalty would become really huge).

So it might not seem nice, but you can add a line into your index.scss:`// $` and all will work as you'd expect.
This is also how both q/app-webpack and our vue-cli plugin have always worked.

However, should enough devs require us to always include the variables regardless of if needed or not (and have the perf penalty which becomes non negligible as a project grows), we'll do so. So everyone reading this please comment about it.

**Comment by Liwoj** [comment]
Hi there!
I'm not sure I fully understand the issue or the response but I'm also affected...just in different way.
I'm not getting any compilation error. Instead my app is rendering as if there were no Quasar variable overrides (and I'm still able to use Quasar variables in Vue SFC `<style>` blocks)

I'm using (as far as I understand) standard Vite setup described in the [docs](https://quasar.dev/start/vite-plugin) (upgraded from Vue CLI + Quasar plugin just yesterday and it worked fine). After upgrade to `@quasar/vite-plugin@1.0.8`  whole app renders as if no variables were defined in `src/styles/variables.scss`

`vite.config.ts` (shortened)
```js
import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'
import { quasar, transformAssetUrls } from '@quasar/vite-plugin'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: { transformAssetUrls },
    }),
    quasar({
        autoImportComponentCase: 'kebab',
        sassVariables: 'src/styles/variables.scss',
    }),
  ],
})
```

`src/styles/variables.scss`

```css
$primary   : #00804B;
$secondary : #323232;
$accent    : #f36f20;
$dark      : #1D1D1D;
$positive  : #21BA45;
$negative  : #C10015;
$info      : #31CCEC;
$warning   : #F2C037;

$table-hover-background         : rgba(0, 0, 0, .1);
$table-selected-background      : rgba(0, 0, 0, .2);
$table-dark-hover-background    : rgba(255, 255, 255, .1);
$table-dark-selected-background : rgba(255, 255, 255, .17);
```

`configure-quasar.ts`

```js
import iconSet from 'quasar/icon-set/mdi-v6'
import { LoadingBar, Notify } from 'quasar'

import { availableLocales, defaultLocale } from '@/i18n'
import { useUserSettings } from '@/composables/useUserSettings'

import '@quasar/extras/roboto-font/roboto-font.css'
import '@quasar/extras/mdi-v6/mdi-v6.css'
// Import Quasar css
import 'quasar/src/css/index.sass'

const userSettings = useUserSettings()

// To be used on app.use(Quasar, { ... })
export default {
  components: { /* not needed if importStrategy is not 'manual' */ },
  directives: { },
  plugins: {
    LoadingBar,
    Notify,
  },
  lang: availableLocales[defaultLocale].localeData.quasar,
  iconSet,
  config: {
    dark: unref(userSettings.isDarkThemeActive),
    notify: { position: 'top' },
    loadingBar: {
      size: '4px',
    },
  },
}
```

I guess problem is that `'quasar/src/css/index.sass'` also does not contain any variable reference ('$...') because only way to fix it is:
1. Create a new SASS file `@/styles/app.scss` with content below
2. Replace `import 'quasar/src/css/index.sass'` in `configure-quasar.ts` by `import '@/styles/app.scss'`

```css
@import '@/styles/variables.scss';
@import 'quasar/src/css/index.sass';
```

**Comment by rstoenescu** [comment]
Hmm, rather than seeing the pain above, decided to always include the variables regardless if they are needed or not.
Will publish q/vite-plugin v1.0.9 in a few minutes.
