### ISSUE TITLE
Quasar v1.18.9 QDialog focus bug

### ISSUE THREAD

**Issue by dev31337** [quasarframework/quasar#13088]
### What happened?

Hi,

The change you made in v1.18.9 for QDialog messes up the focus for my app.

When a QDialog is shown the first QInput is no longer focused anymore but the close button (X) of the QDialog is focused instead.

Let me know if you need more information from me.

Regards.

### What did you expect to happen?

Leave the focus as it was before v1.18.9.

### Reproduction URL

https://codepen.io/Zikey/pen/WNdMdjb?editors=101

### How to reproduce?

-

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by dev31337** [comment]
Sorry I tried to reproduce it in Codepen and I'm unable to do it.

Here is the link to the code:

https://codepen.io/Zikey/pen/WNdMdjb?editors=101

In my app the close button is focused (instead of the qinput) when the dialog opens, while it does not in v1.18.8.

The solution would be to make the close button non-focusable (tabindex="-1") but in that case the dialog could not be closed with the keyboard (accessibility).

Can you please give me some pointers about this change in v1.18.9:

fix(QDialog): (backport from Qv2) it should directly focus on the autofocusable only first time; then on focusing out it should look for any focusable element

Is there a commit linked to it so I can check the code changed to try to find the issue ?

**Comment by dev31337** [comment]
I found the commit, currently working on it, please leave this issue opened until I finished analyzing it.

(https://github.com/quasarframework/quasar/commit/3766aab473e212911de177121acacfe6ad748aed)

**Comment by dev31337** [comment]
I found the issue but I need some help to understand why it happens.

The issue happens because of this change:

[ui/src/components/dialog/QDialog.js](https://github.com/quasarframework/quasar/commit/3766aab473e212911de177121acacfe6ad748aed#diff-2fe072bf8a98d216be2be8e5b6de0016c65a93fa233cab03a32d674b46f2775b)

-      this.focus()
+      this.focus('[tabindex]:not([tabindex="-1"])')

This change makes the close button be focused in my QDialog, which seems to be logical since it finds the first element with a tabindex not being equal to -1.

The reason why it does not happen in my Codepen example eludes me. Because the code should make it happen.

I think the reason lies in the code before the this.focus() call which is only triggered if the following "if" is true:

if (
          this.showing === true &&
          this.__portal !== void 0 &&
          childHasFocus(this.__portal.$el, e.target) !== true
        )

For some reason this code is triggered in my app but not in the Codepen example I provided.

But believe me that the change in the "this.focus()" statement, if executed as it should, should select the close button and not the qinput of my example.

Any help much appreciated, I'm ready to make more test if required, let me know how I could help.

**Comment by dev31337** [comment]
Sorry for this long thread I will summarize it for the sake of clarification.

The change in v1.18.9 about the selection of the focused element in a QDialog has a side effect when the QDialog has a close button.

The side effect is that the close button becomes focused instead of the first element with "autofocus" in the QDialog.

**Comment by dev31337** [comment]
I was able to overcome the issue while respecting the idea behind the initial commit/modification by doing the following change that I would like to submit:

[ui/src/components/dialog/QDialog.js](https://github.com/quasarframework/quasar/commit/3766aab473e212911de177121acacfe6ad748aed#diff-2fe072bf8a98d216be2be8e5b6de0016c65a93fa233cab03a32d674b46f2775b)

line 162:
 node = node.querySelector(selector || '[autofocus], [data-autofocus]') || node;

Changed to:
 node = node.querySelector('[autofocus], [data-autofocus]' || selector) || node;

**Comment by rstoenescu** [comment]
Hi,

The main point was to try the to focus on the first autofocusable element when opening the dialog, then when TABBing through to allow reaching every element.

Your changes not only won't allow this, but they contain problems. `'[autofocus], [data-autofocus]' || selector` will always evaluate to the first string, so the "or" operation is worthless. But more than this, when the dialog is spawned, nothing changed. Your problem is somewhere else, but I can't reproduce (not in your Codepen, not in a CLI app)...

Please provide a bare minimum working reproduction with your exact use-case (a CLI project?)

**Comment by dev31337** [comment]
You do realize that your modification [this.focus('[tabindex]:not([tabindex="-1"])')] implies that the focus is given to the first item with a tabindex not equal to -1 and thus implicitly ignores/overrides the item with autofocus attribute ?

It's your code and I can not argue with it but I strongly believe that this is a mistake. (not respecting the HTML autofocus attribute) 

For us we will simply freeze with v1.18.7, wait for more people to install your latest code who will have our issue and report it to you in the future.

**Comment by rstoenescu** [comment]
@dev31337 

I feel compelled to explain the algorithm given your comments above, because I think that you are missing one key point. You may see focus(tabindex) but you need to understand in which case this is run. 

When the dialog gets shown, the default focus() is called without any params, **so it does what it has always done**, which is use the autofocus selector. Then, when user is TABBing through the elements on the Dialog and/or when focus jumps outside of the dialog, __onFocusChange() is called which in turn calls focus with the tabindex selector. Which is a correct behavior for accessibility purposes. So initially it focuses as it always has, and later on when focus jumps outside of the dialog it should focus on the first focusable element -- this allows the user to TAB through all the dialog elements, otherwise all elements before the autofocus one will never get a chance to be focusable.

So, please supply a reproducible case, something to work with. Because as explained above, the code runs as it always has when dialog is shown, and later on it indeed differs (fixing an accessibility issue). But I guess that you are complaining about when dialog is shown. And this is the thing that doesn't makes sense, at least for me.

I don't think that I am unreasonable asking for more details as long as I've done my due diligence, took a look on your Codepen and couldn't reproduce (you yourself too) then tried on a CLI project and again couldn't reproduce then revisited the code. So let's work together and see what the actual problem is.

**Comment by rstoenescu** [comment]
You can zip a project folder (without node_modules in it) or fork https://codesandbox.io/s/github/quasarframework/quasar-codesandbox/tree/legacy-v1

**Comment by dev31337** [comment]
Thank you for your very detailed explanation, I understand now the point of your modification, its important purpose and when it is supposed to happen.

I can assure you that for a reason I can not find this code is executed when my QDialog is shown and the result is that the close button gets the focus instead of the QInput with an "autofocus" attribute.

I wish I could be able to reproduce it in CodePen but unfortunately I can't. It may be related to the way my QDialog opens (from a QItem selection within a QMenu, the QMenu closing may interfere somehow with the QDialog opening).

What I'm also sure is that by simply/only restoring the call to simply "focus()" as it was before, the issue does not happen anymore.

I also completely understand that without an example where the bug happens it is quite impossible for you to acknowledge it and fix it.

To answer your other suggestion (uploading a zip), I'm not using nodejs (nor any modules, nor any boilerplate), my app is a full UMD app with just plain HTML/CSS/JS files.

I guess I've reached the limit on what I can offer, unless I could somehow create a break point on your new focus() call within a web browser and show you the stack trace when it is called, would that help ?

I could also show it to your live in a Zoom session (I can message you in the Quasar Discord channel).

I will also try to reproduce the QMenu launching the QDialog in Codepen just in case.

If nothing works, then the only thing I can ask you is to keep my issue in your mind somewhere because I'm confident that someone else will run into it at some point and it would help if you know that you already seen it reported before.

It's really a small issue for me and I can totally live with it and I don't want to impose more on your excellent job on Quasar which is such an amazing product.

**Comment by dev31337** [comment]
Yes!  I was able to reproduce it here is the CodePen:

https://codepen.io/Zikey/pen/WNdMdjb?editors=101

If you click on the first button "DIALOG" you will see that it does not produce the bug.

But if you click on the second button "MENU" then on the menu item "DIALOG" then you will see it happen. (the close button will be focused/selected)

So the issue happens when the QDialog is instanced by a click on a QItem in a QMenu.

**Comment by rstoenescu** [comment]
Great! Thank you!
Reopening for assesment.

**Comment by rstoenescu** [comment]
QMenu has an accessibility feature where the focus is restored to the element that had it before the menu was shown. This is triggered as the menu closes and the dialog opens. QMenu refocuses on the QBtn, which is outside of the dialog, then the dialog's __onFocusChange() is called, so your focus ends up being on the first focusable element.

Will try something out, but until then, you can disable QMenu's refocusing:

```html
<q-menu no-refocus>
```

**Comment by rstoenescu** [comment]
Fixed the new issue in Qv2 (link above). Will backport to Qv1 later this evening.
Tomorrow is release day.

**Comment by rstoenescu** [comment]
Please upgrade to v1.18.10 (releasing it tomorrow).
And big thanks for providing the Codepen!

**Comment by dev31337** [comment]
You changes fixed the issue, thank you so much for your quick fix :)
