### ISSUE TITLE
QChip with 'outline' prop ignores 'text-color' prop

### ISSUE THREAD

**Issue by suyundukov** [quasarframework/quasar#13484]
### What happened?

`QChip` component ignores `text-color` prop if `outline` prop is passed and label is coloured in colour passed in `color` prop.

### What did you expect to happen?

`QChip` doesn't ignores `text-color` prop and label is coloured in colour passed in `text-color`.

### Reproduction URL

https://codepen.io/suyundukov/pen/PoQjOGK

### How to reproduce?

1. Go to the provided reproduction link
2. ...
3. See the error

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge, iOS, Android

### Additional context

The issue is reproducible in both version of Quasar (v1 and v2).

**Comment by MilosPaunovic** [comment]
As I can figure out from this line:

https://github.com/quasarframework/quasar/blob/eeed49bc2ebe377326ddc2f0aaa5ecceedd031d7/ui/src/components/chip/QChip.js#L87

If there is an `outline` prop, text is taking the color of `color` prop first, and, if that's not provided, `text-color`. That's causing the issue you've reported.

You should wait for someone from the core team to confirm if that's like it by design.

**Comment by rstoenescu** [comment]
Designed as described above.
