### ISSUE TITLE
Datetime component model is a Date object instead of a Unix timestamp number if the users presses "set" without actively choosing date and/or time

### ISSUE THREAD

**Issue by florentpeyrard** [quasarframework/quasar#1353]
### Software version

Quasar: 0.14.7
OS: Win7
Node: 6.10.3
NPM: 3.10.10
Browsers: Chrome 63.0.3239.84 64bits
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Model value is a Date object.

### What were you expecting?
Should be a number (Unix timestamp).

### What steps did you take, to get the error?
1 : the model is initialized with 0 (number).
2: the user opens the Datetime component
3: the displayed value is "today at 00:00"
4: the user just presses "set" because the displayed value is already what he wants.
5: the model type is now a Date object, which is faulty : this should be a number (Unix timestamp)

Note: everything goes fine if the user actively chooses date and/or time then presses "set".

**Comment by wedog** [comment]
hi ,i looked at the source code . This is not bug. The model must be a timestamp not a single number. Because the js constructed function "new Date(0)" get 0. It's not a time. The selection area shows 00:00 by default  is not the 0 you passed in. I suggest you calculate the timestamp like this 
var today = new Date();
today.setHours(0);
today.setMinutes(0);
today.setSeconds(0);
today.setMilliseconds(0);

**Comment by wedog** [comment]
sorry ,new Date(0) get current time.

**Comment by wedog** [comment]
hi ,i looked at the source code . This is not bug. The model must be a timestamp not a single number. Because the js constructed function "new Date(0)" get 'Thu Jan 01 1970 08:00:00 GMT+0800'. The selection area shows 00:00 by default is not the 0 you passed in. I suggest you calculate the timestamp like this
var today = new Date();
today.setHours(0);
today.setMinutes(0);
today.setSeconds(0);
today.setMilliseconds(0);

**Comment by wedog** [comment]
Hello, I read the source code this is not a bug. The js time constructor can pass in a number.But the definition makes it clear: **Integer value representing the number of milliseconds since January 1, 1970, 00:00:00 UTC, with leap seconds ignored (Unix Epoch; but consider that most Unix timestamp functions count in seconds).** If you pass in to 0 ( many judgments are false ) , the frame takes the current time by default and sets to model . I suggest you get a time stamp like this：
`var today = new Date();
today.setHours(0);
today.setMinutes(0);
today.setSeconds(0);
today.setMilliseconds(0);`

**Comment by wedog** [comment]
May pass 0 is the boundary value, some people need to select 1970-1-1 00:00:00

**Comment by wedog** [comment]
May pass 0 is the boundary value, some people need to select 1970-1-1 00:00:00.
The code needs to deal with the value of 0.

**Comment by wedog** [comment]
[https://github.com/quasarframework/quasar/pull/1376](url)

**Comment by rstoenescu** [comment]
Merged PR. Thank you for reporting and offering a PR!
