### ISSUE TITLE
Installing @quasar/app-webpack@3.5.4 fails while resolving dependencies

### ISSUE THREAD

**Issue by thexeos** [quasarframework/quasar#13784]
### What happened?

```
npm ERR! While resolving: project@1.0.0
npm ERR! Found: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@"^2.6.14 || ^3.2.0" from pinia@2.0.14
npm ERR!   node_modules/pinia
npm ERR!     peerOptional pinia@"^2.0.0" from @quasar/app-webpack@3.5.4
npm ERR!     node_modules/@quasar/app-webpack
npm ERR!       dev @quasar/app-webpack@"3.5.4" from the root project
npm ERR!   peer vue@">= 2.5 < 3" from @vue/composition-api@1.6.3
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.14
npm ERR!     node_modules/pinia
npm ERR!       peerOptional pinia@"^2.0.0" from @quasar/app-webpack@3.5.4
npm ERR!       node_modules/@quasar/app-webpack
npm ERR!         dev @quasar/app-webpack@"3.5.4" from the root project
```

### What did you expect to happen?

I have `vue@3.2.30` installed in the project (implicitly - it is not set in package.json). Installed version of `@quasar/app-webpack` is `3.5.1`.

This error happens when running `quasar upgrade -i` as well as `npm install @quasar/app-webpack@3.5.4` directly.

Deleting `node_modules` and/or `package-lock.json` has no effect.

All other packages are latest versions or @next versions to support Webpack 5.

There is no `vue@2.6.14` anywhere in `package-lock.json` - it is not being requested by any other package either.

### Reproduction URL

https://codepen.io/alvarotrigo/pen/b

### How to reproduce?

None

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by yusufkandemir** [comment]
See https://github.com/quasarframework/quasar/issues/13786#issuecomment-1166456057.

> I have `vue@3.2.30` installed in the project (implicitly - it is not set in package.json). Installed version of `@quasar/app-webpack` is `3.5.1`.

You should have it directly as a dependency in your project, not "implicitly".

**Comment by rfox12** [comment]
I've been using Quasar for quite some time... and we've never had to include Vue as a direct dependency.  This change will have a wide impact.  And for the record, you avoid this dependency problem by including Vue in **devDependencies**

**Comment by yusufkandemir** [comment]
@rfox12 that was the case since [@quasar/app-v3.3.0](https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-v3.3.0) which got released 5 months ago. We had to externalize these dependencies to let the dev take full control of the Vue version, and adjust the compatibility of the packages they are using. Also, TS was not offering auto-import suggestions for transitive dependencies(#9235). Unless the package manager doesn't install those dependencies under the hood, then decides to stop doing that later[^](https://github.com/quasarframework/quasar/issues/13786#issuecomment-1166487357), running `quasar dev` automatically detects those dependencies are missing, and installs them. The release notes also mentions this behavior, so it's a known and documented fact. Project templates have these dependencies added by default, so new projects are not affected in any way.
