### ISSUE TITLE
quasar dev -m ssr The screen will be blank before loading.

### ISSUE THREAD

**Issue by vrockn** [quasarframework/quasar#14180]
### What happened?

![image](https://user-images.githubusercontent.com/15974713/184332480-1c0991a6-4b41-425c-8042-5bc3ae6e50ce.png)
![Uploading image.png…]()

### What did you expect to happen?

Hope to complete it directly

### Reproduction URL

quasar dev -m ssr

### How to reproduce?

quasar dev -m ssr

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SSR Mode

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
quasar dev -m ssr
```

### Relevant log output

```Shell
no error
```

### Additional context

no error

**Comment by rstoenescu** [comment]
For dev (only) with q/app-vite the critical CSS path cannot be computed due to the nature of how Vite works. We would have to compile the whole project (for any code change) to have this info available, but this defeats all the advantage that Vite has and would make for a horrendous dev experience. This is why CSS is loaded after client takes over. However, the production code will load as expected.
