### ISSUE TITLE
[meteor] Q-layout issue with padding and height

### ISSUE THREAD

**Issue by ralphchristianeclipse** [quasarframework/quasar#1431]
So my problem is there is a padding bug on the layout container as you can see on the images below i don't know what's happening i've reinstalled quasar and it works fine but at some point it will do it again checked my code never seen that padding 10000

![image](https://user-images.githubusercontent.com/25447231/34979359-0e0d9fac-fadc-11e7-9570-4e53f124da8d.png)
![image](https://user-images.githubusercontent.com/25447231/34979374-1727b9ba-fadc-11e7-92e7-edf79d1f663c.png)

Index.vue
```js
<template lang="pug">
  q-layout(view="hHh Lpr fFf" ref="layout" reveal)
    q-toolbar(slot="header")
      img.avatar(:src="LOGO")
      q-toolbar-title UPlant
    router-view(style="margin-bottom: 80px")
    q-tabs(slot="footer" align="center")
      q-route-tab(slot="title" v-for="(route,i) of routes", :key="i", :to="route.to", :icon="route.icon", :label="route.label")
</template>

<script>
export default {
  name: "Index",
  data() {
    return {
      LOGO: "/statics/logo.png",
      routes: [
        {
          icon: "spa",
          label: "Plants",
          to: {
            name: "plants"
          }
        },
        {
          icon: "local_florist",
          label: "Nurseries",
          to: {
            name: "nurseries"
          }
        },
        {
          icon: "face",
          label: "Users",
          to: {
            name: "users"
          }
        },
        {
          icon: "local_shipping",
          label: "Partners",
          to: {
            name: "partners"
          }
        },
        {
          icon: "local_offer",
          label: "Pickups",
          to: {
            name: "pickups"
          }
        }
      ]
    };
  }
};
</script>
```
App.vue
```js
<template lang="pug">
 #q-app
  router-view
</template>

<script>
  import { Auth } from "gql/Auth.gql";
  export default {
    name: "App",
    apollo: {
      auth: {
        query: Auth,
        fetchPolicy: "network-only"
      }
    }
  };
</script>

```

**Comment by realcarbonneau** [comment]
I looked through the code and this most probably would have to come through the following stylus files and variables.  
core.variables.styl: $space-base, $space-x-base, $space-y-base, $spaces
size.styl: $space, $spaces, $value

Maybe it was a temporary corruption, however, if it happens again, you can try to trace these.

**Comment by mwarren2** [comment]
The ui at the moment appears to be completely broken due to this padding bug, which adds massive amounts of padding.
- I can't get q-layout to respond in any reliable way.

I see that 0.15 has a q-layout rewrite. I suspect we will need to wait for that.

**Comment by rstoenescu** [comment]
I cannot reproduce this. Can someone make a github repo with the minimum amount of code to reproduce this, pls?

**Comment by mwarren2** [comment]
The meteor starter kit shows the bug, can you simply install according to the README and take a look?

**Comment by mwarren2** [comment]
There's an invisible div in the header:
`<div class="absolute-top-left transition-0" style="width: 100000px; height: 100000px;"></div>`

**Comment by rstoenescu** [comment]
@mwarren2 Investigated why this only happens on Meteor.

Seems like the the CSS is injected/evaluated later than the mount point of vue components (including Quasar ones). Since there is a resize observer (QResizeObserver) that relies on the CSS in order to work correctly, it then breaks the layout (has "absolute-full" and other Quasar CSS class) by reporting wrong layout sizes.
The workaround would be to replace the CSS classes in QResizeObserver with an equivalent inline style within Quasar code.

Hand-written workaround, based on the transpiled version of QResizeObserver from meteor starter kit:
```js
var QResizeObservable = { render: function render() {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;
    return _c('div', { staticStyle: { "z-index": "-1", "position": "absolute", "top": "0", "left": "0", "right": "0", "bottom": "0", "overflow": "hidden", "visibility": "hidden" } },
    [_c('div', { ref: "expand", staticStyle: {"position": "absolute", "top": "0", "left": "0", "right": "0", "bottom": "0", "overflow": "hidden", "visibility": "hidden"}, on: { "scroll": _vm.onResize } },
    [_c('div', { ref: "expandChild", staticStyle: { "position": "absolute", "top": "0", "left": "0", "transition": "0s", "width": "100000px", "height": "100000px" } })]), _vm._v(" "),
    _c('div', { ref: "shrink", staticStyle: {"position": "absolute", "top": "0", "left": "0", "right": "0", "bottom": "0", "overflow": "hidden", "visibility": "hidden"}, on: { "scroll": _vm.onResize } },
    [_c('div', { staticStyle: { "position": "absolute", "top": "0", "left": "0", "transition": "0s", "width": "200%", "height": "200%" } })])]);
  }, staticRenderFns: [],
  name: 'q-resize-observable',
  .......
```

**Main point**
---
**Please investigate why the CSS is injected after Vue mounts components. If you can't make it work correctly, then I'll release this workaround for Quasar.**

Let me know how it goes.

**Comment by rstoenescu** [comment]
Also, this is guaranteed not to occur with v0.15 code out of the box because it works differently.

**Comment by mwarren2** [comment]
@rstoenescu Thank you for your work on this.

This is presumably happening because I do a dynamic import of the css, based on whether it's IOS or Android. 

```
    if(Meteor.isCordova){

        if(cordova.platformId == 'android'){
            //dynamic import
            import('/node_modules/quasar-framework/dist/quasar.mat.css');
        }
        else if(cordova.platformId == 'ios'){
            import('/node_modules/quasar-framework/dist/quasar.ios.css');
        }

    }else{
        //default dynamic import
        import('/node_modules/quasar-framework/dist/quasar.mat.css');

    }

```

It seems like a lot of work for you to correct this, considering that I only got v0.14.7 working with Meteor a week ago, so there can't be that many people using it. 

For the moment I can also try going back to the 'require' syntax I was using before, instead of the dynamic imports.

So I'll try to solve this based on the information you've given me, and wait for v0.15. 
If all else fails, I can add a message anyway to the Starter Kit about the problem, because I presume that v15.0 can't be too far away.

---------

On another note, Meteor is still working on removing the need for a commonjs version, hopefully soon I can avoid transpiling Quasar from es6.

**Comment by rstoenescu** [comment]
@mwarren2 Published v0.14.8 with the workaround. Try that.

Also, I suggest you make those symlinks in the starter kit with relative path, instead of absolute. For example, I had to re-do them since they were pointing to path on your machine.

Let me know how it goes on investigating the injection order of script/css too.
Thank you for all your efforts on Meteor!

**Comment by mwarren2** [comment]
@rstoenescu 

1. If I substitute the dynamic `imports` with `require` it all works with **0.14.7**.
2. If I install `0.14.8` I can use the dynamic `imports`, which is a good result.
3. Thanks for the pointer about the absolute paths for the links. I've corrected them and I'll be working on those in the future as well to try and remove them.

Thanks again for your wonderful work.

**Comment by rstoenescu** [comment]
@mwarren2 I am the one who needs to thank you for your continuous Meteor integration work!
