### ISSUE TITLE
Error QForm

### ISSUE THREAD

**Issue by juanrdlo** [quasarframework/quasar#14492]
### What happened?

QForm this error

https://github.com/quasarframework/quasar/commit/3c67abf627ce4199eee9c7e4cb8a2d55c9992d5c#r84998211

### What did you expect to happen?

When running the form, it gives an error for the .length

### Reproduction URL

https://github.com/quasarframework/quasar/commit/3c67abf627ce4199eee9c7e4cb8a2d55c9992d5c#r84998211

### How to reproduce?

Create form
Click btn submit

Error .length

### Flavour

Vue CLI Plugin (vue-cli-plugin-quasar)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment]
Please make a reproduction codepen

**Comment by zhouwf108** [comment]
@pdanpdan  `quasar@1.20.2`


![image](https://user-images.githubusercontent.com/15206537/192217509-6960bd17-ee9d-4abd-b097-525466a15165.png)

**Comment by pdanpdan** [comment]
Yep - in that place it is a bug :)

**Comment by DouglasCalora** [comment]
Up, same issue! ⬆️

**Comment by lancamonica** [comment]
Up, same issue! ⬆️

**Comment by felipejuzo02** [comment]
Up, same issue! ⬆️

**Comment by pansx** [comment]
Up, same issue! ⬆️

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.21.0 (releasing today or tomorrow)

**Comment by digitalit** [comment]
Anyone knows when v1.21.0 is coming?

Have a nice day

**Comment by rstoenescu** [comment]
It's coming. It's coming. Just very close to finalizing v1.20 and v2.8.5. It's in the final stages of testing. Lots of goodies and hard work went into these. If nothing extraordinary comes up, expect the releases tomorrow. Sorry for the delay. In the mean time you can use the previous version.

**Comment by digitalit** [comment]
@rstoenescu take your time. 
All my projects has an Quasar site for www that is for the customers of my customer and a admin site where my customers make all work that will show in www and as a precaution i always only update admin at fist in case of any bugs (this one being the fist ive encounter).

This way it's no big deal when this happens as the official site www still works running 1.19.15 so my customers will just wait for the 1.21.0 version. Yes i know i could revert to 1.19.15 in admin site but maybe im stupid cause even though i delete the node_modules folder and lock file and change in package.json i get 1.20.2.

Have a nice day and please take you time.

**Comment by MilosPaunovic** [comment]
I'm guessing the issue here is that in your `package.json` file you have a caret before Quasar version (something similar to ` "quasar": "^1.20.2"`). That caret states that the latest minor and patch versions available will be installed.

To (temporarily) avoid issues you're having with `QForm`, pin version of Quasar in your `package.json` file like this `"quasar": "1.20.1"`. after this, run `npm i` again and it will install that particular version.

**Comment by digitalit** [comment]
@MilosPaunovic thank you so much,

This was a rookie mistake regarding the caret.

Works like a charm, thanks again and have a nice day.

**Comment by digitalit** [comment]
Hi guys,

I can confirm that 1.21.0 works and solves the issue.

I'm impressed by the quick fix and especially since i know this is "the old version". 

Of course i have an ongoing work rebuilding all my projects with the fantastic and really improved version 2.

Thank you so much and have a nice day.
