### ISSUE TITLE
No change event fired for q-select (v0.15-beta.7)

### ISSUE THREAD

**Issue by wux5** [quasarframework/quasar#1454]
### Software version

Quasar:
OS: Mac
Node: 8.9
NPM: 5.x
Browsers: Chrome, Firefox

### What did you get as the error?
The q-select component does not fire change event on selection change.

### What steps did you take, to get the error?
<q-select @change="onChange">..... </q-select>
The onChange never got fired.

**Comment by rstoenescu** [comment]
Hi,

v0.15 changes the events related to the model in order to match v-model and future v-model.lazy. This applies to almost all form components (QInput, QSelect, ... and so on).

So, example of v-model and also catching when model changes:
* Option 1: `<q-select v-model="model" @input="modelChanged" .... />`
* Option 2: `<q-select v-model="model" ... />` + vue watcher on model

Example of lazy v-model. Will use props and events until v-model.lazy will be merged into Vue (soon):
`<q-select :value="model" @change="val => model = val" ... />` Hook into `@change` event or add a watcher on model to detect when the model changes.
