### ISSUE TITLE
Q- Showcase of Demo Apple not working

### ISSUE THREAD

**Issue by robertkraig** [quasarframework/quasar#1494]
http://quasar-framework.org/quasar-play/apple/index.html#/showcase 
http://quasar-framework.org/quasar-play/android/index.html#/showcase 

Both show the same thing.

Right now, the demo for apple is not showing. I cannot show this as a demonstration to my client/employer. I need to be able to demonstrate both apple + android for comparisons.

Both look like Material UI

**Comment by leopiccionia** [comment]
Actually, they are different (notice the navbar text placement and shadows, for instance).

Quasar has some platform-specific styling (e.g. buttons, tabs, dialogs, datepickers, spinners, chat bubbles, etc.), but some components are more platform-agnostic. Quasar is not currently as pixel-perfect as alternatives like [Framework7](https://framework7.io/), maybe because it aims to be more than a mobile-only framework.

**Comment by realcarbonneau** [comment]
Can you provide more precisions and examples of what does not have the correct visual appearence? Have you tried it on an actual Mac?  Here are some screenshots of the time component which are completely different for the two versions.

![2018-01-26 14_48_54-quasar play app](https://user-images.githubusercontent.com/29619229/35458263-ad2c2610-02a9-11e8-87a0-1f8b2d994c75.png)

![2018-01-26 14_47_45-quasar play app](https://user-images.githubusercontent.com/29619229/35458264-ad432428-02a9-11e8-8565-ce281bb60335.png)

**Comment by rstoenescu** [comment]
Please help out tweak Quasar Play if you feel it's necessary. Can't handle writing Quasar features, offering support, writing Quasar Play, testing, writing documentation etc only by myself in a timely manner. Thank you and hoping everybody understands.
