### ISSUE TITLE
parallax not updating when src binded value change

### ISSUE THREAD

**Issue by marcelofoca** [quasarframework/quasar#1495]
Parallax image is not been corrected displayed when an src bound value changes after page has been loaded

**Comment by rstoenescu** [comment]
Hi,

Here is an example of it working. https://jsfiddle.net/rstoenescu/ydpLs193/
You may want to mingle with the "height" prop. If the default height is taller than your image, then you'll get the impression that the Parallax doesn't works. Which is semi-true, since the image has no room to "play" inside of the Parallax.

Please reopen with a reproducing case if you still feel there is something wrong. Thanks.

**Comment by codingfriend1** [comment]
I found the solution to this issue is to add a :key="" property to the parallax component:

:key="image_src"

**Comment by rstoenescu** [comment]
How can you reproduce it??? @codingfriend1

**Comment by codingfriend1** [comment]
I had setup a header banner component that utilized the q-parallax that switched background images depending on the route you were on by listing a bunch of possible banners that used v-if to show the right one based on the current route. The issue was it seems Vue didn't recognize that each instance was a different element and wouldn't update the component unless I added :key="image_src" to q-parallax to help the browser identify it was a separate element.

```html
<template>
  <div>
    <div class="row justify-between relative-position">
      <!-- 
        - It is vital for this element to have a `key` attribute or images and videos won't change during page navigation
        - We must set the speed attribute to 0 with video or the video will drop down vertically in position on page resize
      -->
      <q-parallax
        :key="bg + video"
        :src="bg ? bg: null" 
        :height="700"
        :speed="video ? 0: 1"
      >
        <!-- If we have video, display it instead -->
        <template v-slot:media v-if="video">
          <video width="1280" height="720" autoplay loop muted>
            <source type="video/mp4" :src="video">
          </video>
        </template>

        <template v-slot:content="scope">

          <div class="dark-overlay">
            <div 
              class="row banner-content items-center" 
              :class="{ 
                'justify-start text-left': justify === 'left', 
                'justify-center text-center': justify === 'center', 
                'justify-end text-right': justify === 'right' 
              }"
            >
              <div class="five-percent-horizontal-padding">
                <slot></slot>
              </div>
            </div>
          </div>
        </template>
      </q-parallax>
    </div>
  </div>
</template>
```

This component gets repeated multiple times with only the slot and bg image changing and each instance is hidden with v-ifs until the correct route matches.
