### ISSUE TITLE
Unable to use i18 inside quasar.config.js file

### ISSUE THREAD

**Issue by AhmedHamdy-B** [quasarframework/quasar#15138]
### What happened?

I was trying to add i18 to the global loading message but couldn't import the vuei18 inside of the quasar.config file.

### What did you expect to happen?

use i18 after importing it inside quasar.config file.

### Reproduction URL

https://codesandbox.io/s/admiring-bardeen-c7yhh3?file=/quasar.conf.js:376-383

### How to reproduce?

1-go to https://codesandbox.io/s/admiring-bardeen-c7yhh3?file=/quasar.conf.js:376-383
2-click 
![image](https://user-images.githubusercontent.com/56585994/208276346-a138622e-c805-4e73-9db7-85203053fcbe.png)
to show the loader
3- loader wont show the translated message as expected in the line:
 message: useI18n.t("sidebar.questionsCategory"),
 which is inside quasar.config file:
![image](https://user-images.githubusercontent.com/56585994/208276529-041aca19-769b-4259-9ada-725d83dda6df.png)
which was imported in these lines:
![image](https://user-images.githubusercontent.com/56585994/208276884-c497c3bf-5ba7-473e-9e08-7ac800ebda8e.png)

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Plugins (quasar)

**Comment by yusufkandemir** [comment]
This is not a bug, it's how things work. `quasar.config.js` runs in the Node context, separate from your app. Luckily, `quasar.config.js > framework > config > loading` is not the only way to set up the defaults. So, you can use `Loading.setDefaults()` in a [boot file](https://quasar.dev/quasar-cli-vite/boot-files), which runs in the context of your app, instead.

https://quasar.dev/quasar-plugins/loading#setting-up-defaults
> Should you wish to set up some defaults, rather than specifying them each time, you can do so by using quasar.config.js > framework > config > loading: {…} or by calling **Loading.setDefaults({...})** or $q.loading.setDefaults({...}).

Also, you are using `useI18n` incorrectly, you need to invoke it first, e.g. `useI18n()` instead of just `useI18n`.

**Comment by AhmedHamdy-B** [comment]
![image](https://user-images.githubusercontent.com/56585994/208420555-6d35b178-35c5-42db-90e1-d467291acc94.png)
I tried to add it to a boot file as you suggested but it shows that $q.loading is undefigned, how am I supposed to import it in a boot file. Thanks ^^

**Comment by yusufkandemir** [comment]
There is a reason I've specifically highlighted `Loading.setDefaults()` and not `$q.loading.setDefaults()`.
```js
import { Loading } from 'quasar';

Loading.setDefaults({
  message: 'test'
});
```

But, then, you will probably try to use `useI18n()` here, which is not going to work. Vue's provide/inject only works inside component render scopes. It'll not work in other places such as boot files, Pinia store files, plain js files, etc. So, I'd recommend studying the topic a bit, before anything else.

Also, it would be better if you do this in the exported function instead of the top-level.

```js
import { boot } from 'quasar/wrappers'
import { Loading } from 'quasar'
import { i18n } from 'boot/i18n'

export default boot(({ /* app, store, ... */ }) => {
  Loading.setDefaults({
    message: i18n.t('...')
  })
})
```

Should you need further help/information, please do more research and ask it in the discussions section or in our Discord server, the issues section is reserved for bug reports.

**Comment by AhmedHamdy-B** [comment]
Works perfectly fine now, Thanks a lot bro <3 <3 <3
