### ISSUE TITLE
QDrawer gets stuck in mobile mode & :breakpoint prop not working

### ISSUE THREAD

**Issue by cmcleese** [quasarframework/quasar#15166]
### What happened?

QDrawer easily gets stuck in mobile mode when resizing window.
QDrawer doesn't seem to be affected by different values for prop: `breakpoint`

### What did you expect to happen?

The breakpoint prop should be used like used to work.

When window resize occurs the drawer should respect the breakpoint and properly switch between desktop and mobile modes accordingly and not get stuck.

### Reproduction URL

https://codesandbox.io/s/quasarv2-qdrawer-stuck-mobile-mode-7qucts?file=/src/layouts/MainLayout.vue

### Issue 1: Breakpoint for QDrawer has no effect
1. Notice how changing breakpoint value in `MainLayout.vue` has no effect.
**Note**:  Observe in the top right header the window width.

### Issue 2: Drawer gets stuck in Mobile mode
1. Ensure starting in desktop layout for drawer (adjust your window size)
2. Resize window until drawer closes
3. Click drawer menu button to open the drawer (drawer will be in mobile mode)
4. With drawer still open, resize browser back pa
6. Attempt to re-open drawer from header menu button again
7. Notice how drawer is stuck in mobile mode
**Note**: what seems to work is if you close the drawer (still in mobile mode and in desktop layout) then resize a little to trigger the appearance of the desktop drawer.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19044) - win32/x64
NodeJs - 16.18.1

Global packages
  NPM - 8.19.2
  yarn - 1.22.19
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.10.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.8 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.28 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.29.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-testing - 2.0.6 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-unit-vitest - 0.1.0 -- A Quasar App Extension for running tests with Vitest
  @quasar/quasar-app-extension-testing-e2e-cypress - 5.0.0-beta.10 -- A Quasar App Extension for Cypress e2e
```

**Comment by rstoenescu** [comment]
The **designed** behavior is that once you open a QDrawer below the breakpoint, it will stay opened in this "mobile" mode until you close it. It doesn't mean that the breakpoint is not taken into account when it's closed and/or the user changes the window dimensions.

However:
1. When in Cordova or Capacitor modes, Quasar also takes into account that when you open the drawer and the user hits the native "back" button (ex: Android), it closes the drawer and halts navigation rather than keeping the drawer opened and also navigating to the previous route. That is definitely not something anyone wants, but due to the architecture of Cordova/Capacitor it is really hard to manage the history state if we allow the automatic switch between "mobile" and "on the layout" behavior for the drawer (remember that even on mobile platforms, the user can switch the screen orientation and the breakpoint can get activated).
2. Apart from the things mentioned above, there is also the issue of maintaining a single source of truth for the QDrawer open state and not forcing Quasar to override the developer's configuration. When we switch from one state to another, we want to minimize (to the extreme) tampering with this state and let only the developer handle it (he/she is the king on this one). Otherwise it will lead to apparently unpredictable behavior. To make things worse, there are a billion combinations of how QLayout + QDrawer can be configured (through the QLayout `view` prop and QDrawer's `overlay`, `mini`, `mini-to-overlay` etc props) and each has its own particularities and no golden path to encompass all possible combinations in a predictable and easy to grasp way should we change this default behavior (referring to "once you open QDrawer in mobile mode it stays this way until user closes it").

Having said the above, we will try to research and see if there's still a safe way to do it, but I wouldn't bet on it for Quasar v2. Rather, for Quasar v3, since there are already so many new features on the pipeline already that we want to ship for v2.
