### ISSUE TITLE
Grid not working correctly with drawer visible

### ISSUE THREAD

**Issue by mariaczi** [quasarframework/quasar#152]
Hi,

basically, when drawer is visible, grid is working incorrectly, as e.g. width-1of2 is giving 50% of whole width not real container (so window witdth - drawer width) which is giving really bad results.

**Comment by rstoenescu** [comment]
Can you post your layout template and a screenshot, please? I am sure it works correctly. Thanks!

**Comment by rstoenescu** [comment]
Please reopen with requests above. Thanks!

**Comment by mariaczi** [comment]
Hi,

It is also giving issues with height.
It inherits from div.layout:
```
height: 100vs;
bottom: 0;
```
which makes issues with the component inside `<router-view>`.
It basically gives any component inside the `layout-view` 100% height which should be not happening... 
It is also causing that there is no scrolling (layout has `100vh` size).

This is my parent component to host all other components (or quite often component which is only set of other components).
```
<template>
    <quasar-layout>
        <div slot="header" class="toolbar">
            <button class="hide-on-drawer-visible" @click="$refs.leftDrawer.open()">
                <i>menu</i>
            </button>
            <quasar-toolbar-title :padding="1">
                MyApp
            </quasar-toolbar-title>
            <button>
                <i>settings</i>
            </button>
            <button @click="logout">
                <i>power_settings_new</i>
            </button>

        </div>
        <quasar-drawer ref="leftDrawer">
            <div class="list no-border platform-delimiter">
                <quasar-drawer-link icon="mail" to="/" exact>
                    Link
                </quasar-drawer-link>
            </div>
        </quasar-drawer>
        <router-view class="layout-view"></router-view>
    </quasar-layout>
</template>
```

and this is component:
```
<div class="row">
    <div class="card lt-bg-auto gt-md-width-1of4">
```

I have tried without first div but it was the same issue...

My App.vue
```
<div id="quasar-app" class="fullscreen flex items-center justify-center">
            <router-view>

            </router-view>
        </div>
```

**Comment by rstoenescu** [comment]
Quasar is designed so that your direct children of a layout router views to contain an empty `<div>` as in https://github.com/quasarframework/app-template-v2/blob/master/template/templates/view.vue:
``` html
<template>
<div>
  ...your router view template...
</div>
</template>
```

There are several reasons why this is so:
1. Crossbrowser CSS compatibility
2. Layout should fully extend on your viewport both on its height and width AND still allow scrolling for your view or layout. Any other implementation would either make your footer not visible at all times if your view template has height > 100vh OR it will position your footer right after view template (and not at bottom of screen) when view template has height < 100vh - header height.

So, use that extra empty `<div>` (which replaces `<router-view>` when Vue compiles) and everything will work correctly. When CLI generates a project folder you have that `/templates` folder there. You can add your own component templates or use the ones supplied by default and then make use of `quasar new` command (read here: http://quasar-framework.org/guide/quasar-cli.html#Generating-Components)

**Comment by mariaczi** [comment]
Thank you for explanation. I will check when back home in the evening.
