### ISSUE TITLE
No type check on quasar dev

### ISSUE THREAD

**Issue by FlorianAgilap** [quasarframework/quasar#15448]
### What happened?

The `quasar dev` command doesn't seem to run any type check on files that use Typescript.

### What did you expect to happen?

The `quasar dev` command should fail to build if type errors are detected.

### Reproduction URL

https://stackblitz.com/edit/node-f2ksyr?file=src/components/EssentialLink.vue

### How to reproduce?

In the stackblitz I provided, in the `EssentialLink` component, I've added `as number` after `required: true` (L22), this should give a TS 2352 error (I don't know how to make it appear in stackblitz, but it does show up in my vscode or in the official Typescript playground) but it doesn't prevent `quasar dev` from completing. 

Code in Typescript playground (see the error tab on the right) : https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGELgQ5bwC+c6UBcA5AG4CuqNA3AFBuoAeksKGAQwYAbeGkw58hYjAAUCNnDhYBIVAC5aAUQDOO1CWADhAGWwBrGgBpFcMFTA7NCpUpjAYwjYluu4MAE8wbwBlGChsAHMbPyUoVABHBmB45E1wpjgBHWUGEAAjVCgY11IbXzgAYwEwdyJnCrcg0PCokr9xIVFNGmsKso4-YQsG2P9mzTCIrGjG-nQumB6AYj6-AYrgSvqfMcDgydaZ9tdOkSXaNdKSgdIAShYgA

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

### Quasar info output

```Shell
Operating System        Linux(5.15.93-1-MANJARO) - linux/x64
NodeJs                  16.17.0

Global packages    
  NPM                   8.15.0
  yarn                  1.22.19
  @quasar/cli           2.0.0
  @quasar/icongenie     Not installed
  cordova               Not installed
```

**Comment by pdanpdan** [comment]
https://github.com/vitejs/vite/issues/749

**Comment by ydrolet** [comment]
I was surprised too that there wasn't type checking out-of-the-box. What I understand is that Vite transpiles TypeScript but [doesn't type check, for performance reasons](https://vitejs.dev/guide/features.html#typescript). It's assumed that the developer will rely on his IDE for type checking.

If you want to be very rigorous with typing and you are not bothered with performance penalty caused by type checking, you can use a Vite plugin currently in development : [vite-plugin-checker](https://www.npmjs.com/package/vite-plugin-checker). It will give type checking with `quasar dev` and `quasar build`. Build will fail if there are type errors.

Here is a quick guide how to use it :

1. Install the plugin and `vue-tsc`

   ```bash
   yarn add -D vite-plugin-checker vue-tsc
   ```

2. Add/configure the plugin in `quasar.config.js`
   ```js
   vitePlugins: [
     // ...
     ['vite-plugin-checker', { vueTsc: true }],
   ]
   ```
3. To avoid a bunch of type errors related to `node_modules` folder, enable [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) in `tsconfig.json`
   ```
   {
    // ...
    "compilerOptions": {
      // ...
      "skipLibCheck": true
     }
   }
   ```

That's it! You have type checking with `quasar dev` and `quasar build`. Read [plugin doc](https://vite-plugin-checker.netlify.app) for more details and other features, like include linting alongside type checking.
