### ISSUE TITLE
Layout Drawer mini not reactive

### ISSUE THREAD

**Issue by Torone** [quasarframework/quasar#15671]
### What happened?

I'm building an app that should support mobile to desktop view and I'm using the Layout drawer to display navigation on tablet and desktop, while on mobile I will hide the Drawer showing a Toolbar, this part is not in this example because it is not needed.

Basically, on large / desktop view I will show the drawer with Icon and Text, on tablet view (mini) I will show only icons and finally, on mobile view, the Drawer is hidden.

I tried several combinations using `$q.screen.xx.xx` moving it on the HTML or down as a computed but the result is always the same.

If you start playing with the window, from large to small several times you will see that the `mini` property start to go crazy and not respond anymore.

Another easier way to emulate it is to put the window in mobile view, reload the page and then start to play with it to make it large and small again. The `mini` after a few seconds will not be reactive anymore.

I attach a Fiddle that proves what I'm trying to explain, I just added minimal code, avoiding all the tests I did (using watchers, etc...).

I hope you can give a solution, maybe I'm doing something wrong... Or maybe I just found a bug. Thanks!

### What did you expect to happen?

I expect the `mini` property on the Drawer to be reactive on the Screen plugin.

### Reproduction URL

https://jsfiddle.net/toroncino/xu0e2kz1/3/

### How to reproduce?

1. load the page in any screen size
2. start to play with the window to emulate desktop/mobile view
3. you will see the `mini` not to be responding anymore when exit mobile view

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), Plugins (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by rstoenescu** [comment]
Hi.

There are a few problems with your example:

1. You are supplying a read-only computed object to your v-model. This will obviously generate a Vue error (`Write operation failed: computed value is readonly`).

```
const drawer = computed(() => $q.screen.gt.xs)
<q-drawer v-model="drawer" />
```

2. You are doing the same thing inside the methods attached to `show` and `hide` events. You cannot assign a value to a computed prop.

```
const showMini = () => {
  console.log("showMini", $q.screen.sm);
  mini.value = true;
};
<q-drawer @show="showMini" />
```

3. I'm unsure if you are aware, so pointing it out here: When you open the devtools and switch between desktop & mobile view, you are required to refresh the browser window. The Quasar's Platform plugin is not designed to be reactive to a platform change because: a) this cannot happen in production, b) so it would be a waste of resources to have a reactive system in place for this.

---

What I think that you actually want is to use a Vue `ref()` instead for your `drawer` and `mini`, supply the initial value, then use watchers on $q.screen.gt.xs / $q.screen.sm (or whatever you're interested in from $q.screen) to change the value of the refs (your `drawer` or `mini`).
