### ISSUE TITLE
What is data/table.json is imported and how should i use this? 

### ISSUE THREAD

**Issue by jayudhandha** [quasarframework/quasar#1581]
Hi,

I am new in quasar so please pardon me if i did some basic mistake. 
I am trying to use [DataTable component](http://quasar-framework.org/components/datatable.html) of quasar in my Vue Project (Which i made from quasar cli using quasar init default <project-name>, npm install, quasar dev)

After clicking on 'View Source' inside datatable component, I am redirected to https://github.com/quasarframework/quasar-play/blob/master/src/components/showcase/grouping/data-table.vue

I have used this template in App.vue file. But I got the error data/table.json bundle not found. And obviously, it is not in my quasar project. 

So my question is how should I create this data/*.json. Is there any npm package I should install or this data folder is created manually.

I am unable to find any good documentation of how to import in quasar component in my project.

Any help will be highly appreciated.

**Comment by rstoenescu** [comment]
Hi,

You don't need any data/table.json. That's simply there (being imported from `https://github.com/quasarframework/quasar-play/tree/master/src/data` through a Webpack `data` alias) because in order to demo something to you you need some random data...

So, supply the data-table component with your own data...
One more thing. Please use the forum or Gitter chat for questions as described in the ticket template. This repo is reserved for issues only. Thanks.

**Comment by jayudhandha** [comment]
Thanks!!
