### ISSUE TITLE
Row "disappear" in QTable after popup editing while sorting on column

### ISSUE THREAD

**Issue by aberbenni** [quasarframework/quasar#15836]
### What happened?

The table row "disappear" after changing the contents of the cell in the sorted column. If I also want to change another cell in the same row, I have to 'chase' the row.
The row ends up on the last page due to the active sorting. 
This behaviour is particularly problematic in tables with many rows.

### What did you expect to happen?

I expect the changed row to stay where it is and only move if the sorting is changed.

### Reproduction URL

https://quasar.dev/vue-components/table#popup-editing
https://codepen.io/aberbenni/pen/vYVabRX

### How to reproduce?

1 Go to provided link
2 Click on the first column header ("Dessert (100g serving)") ordering a-z (up arrow shown)
3 Click on "Cupcake"
4 Insert "Zagnut"
5 Hit Enter
6 Go to last page of table by clicking on right pagination arrow of table
7 In page two (6-10 of 10) click on calories cell of "Zagnut" row and change "305" to "220"

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Safari

**Comment by aberbenni** [comment]
Hello, the bug is visible on the QTable documentation page at the link

https://quasar.dev/vue-components/table#popup-editing

Just use the online example on the quasar.dev site.

**Comment by aberbenni** [comment]
I added a 'codepen' address by copying the code from the QTable documentation item 15: 'Popup editing'.

https://codepen.io/aberbenni/pen/vYVabRX

**Comment by ronfak** [comment]
> I added a 'codepen' address by copying the code from the QTable documentation item 15: 'Popup editing'.
> 
> https://codepen.io/aberbenni/pen/vYVabRX

Hi @aberbenni,
I tried your Codepen and tried to reproduce your problem following your explanations. I can't reproduce it. Everything works as expected on my side (using the Edge browser).

Be aware, however, that step 5 is wrong: "5 Hit Enter or click outside table". Pressing Enter saves the new value, while clicking outside cancels it.

**Comment by aberbenni** [comment]
Here is a screen recorded reproduction of step 2 to 7. The edited row is moved to last position immediatly after saving "Zagnut". If you need to edit more than one value you need to "follow" te row. 

https://github.com/quasarframework/quasar/assets/1632412/f210560c-49a9-493c-8e44-813e48260aa2

I think sorting should not be reactive when editing rows.

**Comment by pdanpdan** [comment]
Do not sort and edit using same values :)
Or navigate to the new position after edit
Sorting is live, not one time on click

**Comment by aberbenni** [comment]
In the example shown in the documentation: https://quasar.dev/vue-components/table#popup-editing sorting and editing are performed on the same values. I myself took the code from documentation example for the issue #15836. I think a warning should be placed in the documentation.

Question:
Why does the sorting have to be live? After all, the most useful thing is sorting when you click on the column.

Proposal:
Why not make this configurable by leaving the choice to the developer between live sort and one time on click sort via a table prop?

**Comment by aberbenni** [comment]
Hi @pdanpdan 

In the example shown in the documentation: https://quasar.dev/vue-components/table#popup-editing sorting and editing are performed on the same values. I myself took the code from documentation example for the issue https://github.com/quasarframework/quasar/issues/15836. I think a warning should be placed in the documentation.

Question:
Why does the sorting have to be live? After all, the most useful thing is sorting when you click on the column.

Proposal:
Why not make this configurable by leaving the choice to the developer between live sort and one time on click sort via a table prop?

**Comment by pdanpdan** [comment]
If you do not want sorting then remove it and provide the rows pre-sorted

**Comment by aberbenni** [comment]
@pdanpdan I want sorting only by clicking on column header. 

The use case is this:

In a table with many rows, the user sorts or filters to find what interests him, then edits and saves, then continues. In a similar way as one might do with a spreadsheet.

**Comment by pdanpdan** [comment]
In this case you should use external sorting and filtering, și that the order and rows in list do not change

**Comment by aberbenni** [comment]
Is there documentation on how to perform external sorting and filtering?

I tried custom sorting with the "sort-method" prop but it does not work, it is live too.

**Comment by ronfak** [comment]
You can keep the live sorting, but using a row editing mode instead of a cell editing mode. This way you edit all the columns in a row at the same time.
________________________________
De : Alessandro Berbenni ***@***.***>
Envoyé : Thursday, May 18, 2023 8:08:35 AM
À : quasarframework/quasar ***@***.***>
Cc : ronfak ***@***.***>; Comment ***@***.***>
Objet : Re: [quasarframework/quasar] Row "disappear" in QTable after popup editing while sorting on column (Issue #15836)


Is there documentation on how to perform external sorting and filtering?

I tried custom sorting with the "sort-method" prop but it does not work, it is live.

**Comment by aberbenni** [comment]
Hi @ronfak

True, but the problem still occurs because as soon as the entire row is saved, if the value in the sort column has changed, it "disappears". From the end user's point of view, this behaviour is unusual.

**Comment by pdanpdan** [comment]
https://quasar.dev/vue-components/table#server-side-pagination-filter-and-sorting

**Comment by aberbenni** [comment]
I had also thought of handling it server-side, but is there a way to use Vue client-side by implementing non-live sorting?

**Comment by ronfak** [comment]
So you need to disable the sorting. This is not what you want.
Instead, sort the data on the server side or into a "calculated" value seen and give that value to the table or just when you fetch the data…
________________________________
De : Alessandro Berbenni ***@***.***>
Envoyé : Thursday, May 18, 2023 8:14:39 AM
À : quasarframework/quasar ***@***.***>
Cc : ronfak ***@***.***>; Mention ***@***.***>
Objet : Re: [quasarframework/quasar] Row "disappear" in QTable after popup editing while sorting on column (Issue #15836)


Hi @ronfak<https://github.com/ronfak>

True, but the problem still occurs because as soon as the entire row is saved, if the value in the sort column has changed, it "disappears". From the end user's point of view, this behaviour is unusual.

**Comment by pdanpdan** [comment]
It is just s name - do not do remote call but change the rules in client

**Comment by aberbenni** [comment]
Thanks for the help @pdanpdan @ronfak I will work on your suggestions. I owe you a ☕.
