### ISSUE TITLE
build path wont work with capacitor

### ISSUE THREAD

**Issue by modemb** [quasarframework/quasar#15878]
### What happened?

distDir: 'public/'+dirname, // Build Path
quasar dev -m capacitor -T android
Not working for capacitor, the build is on src-capacitor/www instead of public/'+dirname

### What did you expect to happen?

to build on public/dirname

### Reproduction URL

https://github.com/modemb/larasar

### How to reproduce?

run quasar dev -m capacitor -T android

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Capacitor Mode

### Platforms/Browsers

Android

**Comment by rstoenescu** [comment]
Hi,

1. Setting the distDir to any path being used for actually building the app (src*, public etc) is a bad idea due to the circular nature of this setup. Your target folder is being used to build itself. Please avoid this.
2. The following is a recommendation: if configuring distDir, use the `ctx` parameter from the default exported function in quasar.config.js so that the distDir is configured differently for each build mode. Example: `distDir: `some-folder/${ ctx.modeName }`. Otherwise, you won't be able to build multiple modes without the distributables being overwritten.
3. I assume that the public folder has some meaning outside of Quasar itself, which is why you are targeting it for distDir. I suggest that you leave the project folder to work as intended and configure Quasar's build system (through quasar.config.js settings) to output to a different public folder (in some other place, where you can use it by your external systems as well). In other words, the Quasar project folder should be left to work as intended, and your desired public folder (that's being used by Laravel or whatever else you have) to be constructed separately.

**Comment by modemb** [comment]
Hey, Thank you for this explanation
outside the public folder the base URL wont communicate with the server on my experience, maybe because of the project setup (looks like .env do not works without public folder ),  capacitor mode dont work because it never follow the config, it doesn't  appear even on the dist folder as quasar intend, it always on the src-capacitor based on my experience, 
as result "hostname": "suguffie.com"  on capacitor config dont communicate with the server but "hostname": "suguffie.com/" with / go to public/pwa  that take the app from capacitor mode to pwa

pwa and spa work well on the public folder for me but because capacitor wont go there I tried also to move it there manually, still wont work
