### ISSUE TITLE
Table selection checkbox is not visible in header slot;

### ISSUE THREAD

**Issue by woghks778803** [quasarframework/quasar#15935]
### What happened?

```html
<q-table
  v-model:pagination="pagination"
  v-model:selected="selected"
  :title="title"
  :rows="rows"
  :columns="columns"
  :filter="filter"
  :selected-rows-label="getSelectedString"
  row-key="name"
  selection="multiple"
>            
  <template #header="props">
    <TableHeader :item="props" />
  </template>
 </q-table>
```

`TableHeader` component:
```html
<template>
  <q-tr :props="props.item">
    {{ props.item }}
    <q-th v-for="col in props.item.cols" :key="col.name" :props="props.item" class="bg-grey-7 text-white">
      {{ col.label }}
    </q-th>
  </q-tr>
</template>

<script setup>
const props = defineProps({
  item: { type: Object }
})
</script>
```

![화면 캡처 2023-06-02 144137](https://github.com/quasarframework/quasar/assets/38343913/057ab6de-896d-4a29-a4d4-40942c617fdb)

### What did you expect to happen?

![스크린샷 2023-06-02 144427](https://github.com/quasarframework/quasar/assets/38343913/567288f5-a34f-4de2-a013-8de78bf1c849)

### Reproduction URL

None

### How to reproduce?

None

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), SPA Mode

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
None
```

### Relevant log output

```Shell
None
```

### Additional context

None

**Comment by woghks778803** [comment]
```
 <q-table  v-model:pagination="pagination" 
                :title="title" :rows="rows" :columns="columns" :filter="filter"
                :selected-rows-label="getSelectedString"
                row-key="name" selection="multiple" v-model:selected="selected"
                >                    
                <template #header="props">
                    <TableHeader :item="props" />
                </template>
           </q-table>
 -------------------------------------------
<template>
    <q-tr :props="props.item">
        <q-th v-for="col in props.item.cols" :key="col.name" :props="props.item" class="bg-grey-7 text-white">
            {{ col.label }}
        </q-th>
    </q-tr>
</template>

<script setup>
const props = defineProps({
    item: { type: Object }
})
</script>
```

**Comment by yusufkandemir** [comment]
You must handle the selection yourself when using the `header` slot. Add another `q-th` or `th` before the `q-th v-for` section in your code, and put a `q-checkbox`/`q-toggle`, give it `v-model="props.item.selected"`. But, since you are accepting `item` as a prop, mutating it indirectly will be bad, so, consider adding `update:item` event and manage the updates properly. If you feel like you don't have enough Vue knowledge to understand this, I recommend checking out Vue docs. If you still need help after that, make a Codepen so someone can update it and send the solution to you.
