### ISSUE TITLE
Can't reach file without extension

### ISSUE THREAD

**Issue by anteqkois** [quasarframework/quasar#16165]
### What happened?

I want to host file under the route: domain.com/.well-known/apple-developer-merchantid-domain-association to handle Stripe Apple Pay verification. I can do it at local, but at server it;s doesn't work and show me 404

### What did you expect to happen?

Resolve route

### Reproduction URL

i can't provide repo etc. it's private (company)

### How to reproduce?

Add .well-known dir and apple-developer-merchantid-domain-association file.
You can follow this Stripe tutorial: https://stripe.com/docs/stripe-js/elements/payment-request-button#verifying-your-domain-with-apple-pay

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

SPA Mode

**Comment by anteqkois** [comment]
Probable it can also be issue contented to wrong server configuration, so I will let know as soon as other dev checked it at server

**Comment by rstoenescu** [comment]
Hi,

This is not related to Quasar itself. At best, it's related to how you've set up your production webserver. I can't know your project specific stuff, but do you really need to supply this through the app itself? I bet you can configure the webserver to respond to that specific route. If you have some dynamic content, then it makes sense. Otherwise, it matters what publicPath & vue router mode (hash or history) you are using in your app. If publicPath is '/' and the content for that route is not dynamic, then you can use the public folder directly.

Regarding the reproduction URL, you mentioned: `i can't provide repo etc. it's private (company)` -> We don't require/need a reproduction with the whole proprietary project. Just a **barebones** reproduction of the problem, highlighting the Quasar CLI or UI problem. If you follow this procedure you might actually discover if the problem is actually within your code and not Quasar's. But bottom line, we handle lots of tickets every day and a clear and barebones reproduction of a problem actually helps us investigate and fix a potential problem in Quasar much more quickly.

**Comment by anteqkois** [comment]
@rstoenescu
I tried to supply this through the app because I earlier supplied other files in this way, and I don't have access to webserver config etc.. So I must wait until other devs do it. Thanks for your response and I will get in consideration your advice! 🙌
