### ISSUE TITLE
Can anyone explain what the prop of height-hint means?

### ISSUE THREAD

**Issue by HwuuF7** [quasarframework/quasar#16273]
### Description

DOCS: When using SSR, you can optionally hint of the height (in pixels) of the QHeader

When I set a new value to this prop, how do I know if I trigger success? I don't see any changes on my website??? 
Please anyone to explain it for me, thanks!!!

### Documentation Section URL

https://quasar.dev/layout/header-and-footer

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), SSR Mode

**Comment by rstoenescu** [comment]
I'll just give the high level explanation here, because an in depth one would mean I need to fully explain QLayout (which would be a book in itself).

The server-side part does not know the width/height of the window in which the page will be displayed and it also doesn't know what height your header has. But it has to render the layout nevertheless. Now, when on client-side, there will already be something rendered on the page before the client can jump in and hydrate. On the client-side we have access to all the information I mentioned not being available on server-side (window width/height and we can compute header height). If the sizes don't match (and -very important- based on your QLayout `view` configuration) at hydration then you might have your page "jump up or down" to account for the header height difference.

To avoid this, you can use this `height-hint` prop to help out the server-side already render the content with the correct height.

**Comment by rstoenescu** [comment]
Please use the Discussions tab here on Github for questions.

**Comment by HwuuF7** [comment]
> On the client-side we have access to all the information I mentioned not being available on server-side (window width/height and we can compute header height). If the sizes don't match (and -very important- based on your QLayout `view` configuration) at hydration then you might have your page "jump up or down" to account for the header height difference.

Thanks! But if I set a static height on header, what‘s the difference between them?
Next time I will use Discussions Tabs. Sorry!

**Comment by rstoenescu** [comment]
It matters to the QLayout engine because of the sheer number of `view` combination which affect the positioning of the other layout elements. By having `height-hint` all of the layout elements will just "fit" on server-side too.

**Comment by HwuuF7** [comment]
> It matters to the QLayout engine because of the sheer number of `view` combination which affect the positioning of the other layout elements. By having `height-hint` all of the layout elements will just "fit" on server-side too.

Oh~This really spend a little time to realize deeply~Thanks again!
