### ISSUE TITLE
QUploader - Undocumented event @change

### ISSUE THREAD

**Issue by cimpok** [quasarframework/quasar#16280]
### Description

I am using QUploader in a component.  My component has its own emit defined that I unluckily called 'change' with the intent to notify it's parent of data changes. The parent is supposed to save data, and unmount the child with the QUploader.

It took some time to realize that my component emitted false 'change' evens that leaked from the QUploader and propagated sneakily to my component level each time when a file was dropped in the uploader.  (it resulted a premature unmounting the component containing the QUploader, thereby stalling the file upload, giving me the false assumption my back-end server api endpoint has some bug (I had to sleep on it to find the sneaky error)

@change emits an object with 'isTusted' and '_vts' fields when a file is dropped or opened in the QUploader.

The moral of the story: do not name your object, events, variables, using often used common words in programming, treat such words as reserved.

### Documentation Section URL

https://quasar.dev/vue-components/uploader

### Flavour

None

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Hi,

We do not voluntarily emit any "change" event (or any event that is not specified in our API card), otherwise our internal build system would have notified us about it. However, we have an inner "input" element and Vue 3 does not stop the propagation of that native event on it (or for that matter, Quasar too). We could start adding listeners for all possible native events just to stop their propagation, but that would only mean A LOT of runtime overhead just to work around how Vue 3 is supposed to work. Your scenario is indeed unfortunate but there's nothing "proper" that we can do to avoid it.
