### ISSUE TITLE
Support for Bun

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#16335]
### Discussed in https://github.com/quasarframework/quasar/discussions/16320

<div type='discussions-op-text'>

<sup>Originally posted by **ssuess** September  9, 2023</sup>
Now that bun is at version 1.0 (https://bun.sh/blog/bun-v1.0) I was curious how difficult it would be to migrate a quasar app. Has anyone tried? Is this possible?</div>

**Comment by jclaveau** [comment]
Someone tried since past december: https://stackoverflow.com/questions/73088029/how-to-use-quasar-framework-and-or-vue3-with-bun-js but not since 0.5

As `worker_threads` is implemented now, it may work https://bun.sh/blog/bun-v0.7.2

Btw, thank you very much for considering it, it seems to be a true game changer!

**Comment by rstoenescu** [comment]
Will be available in q/app-vite v1.6 & q/app-webpack v3.11 (backported from the next major version of the CLIs -- unreleased yet)
