### ISSUE TITLE
referencing with this.$q.notify does not work

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#1648]
See http://forum.quasar-framework.org/topic/1852/0-15-notify-with-html/11

**Comment by rstoenescu** [comment]
Add "Notify" to `/quasar.conf.js` > framework > plugins.

**Comment by rstoenescu** [comment]
Posting some explanations I gave on the forum here too:

1. Installation. Required. http://quasar-framework.org/components/notify.html#Installation
2. Usage: http://quasar-framework.org/components/notify.html#Basic-Usage

Now, I see following complaints:
1. **Not supporting HTML markup**. Yes, because Quasar needs to make your app be protected from [Javascript injection](http://www.testingsecurity.com/how-to-test/injection-vulnerabilities/Javascript-Injection).
2. **You probably want HTML markup because you need multiple lines**. First, according to Material Guidelines, the notification needs to be short. As short as possible. It's not a full-blown alert message. Having a notification popping up and covering half of the screen defeats its purpose (and it's also bad UI). Use a Dialog for these cases. Notifications are a "soft" way to inform user something has happened. Add a button to it for "More Info" if you have to. Or use the `details` prop, but be short with it.
3. **"I added Notify to quasar.conf.js, but I still need to import it from Quasar"**. This applies to the usage outside of Vue files. And you need to import it where you use it in this case. How else would you reference the Notify object??? You may ask yourself: but why do I also need to add it to quasar.conf then? You need to understand that Notify is a Quasar Plugin, so it needs to do some initialisation before it can be used. This is why you need it in quasar.conf.js.
4. **this.$q.notify does not work in a Vue file. I still need to import it from Quasar??"**. Where are you using `this.$q.notify`? Inside the Vue component definition, or outside of the `export default {...}`. Notice the usage of `this`!! It has meaning inside of the Vue component definition or in your vue template, not outside of it. If you need it **before** `export default {...}` then yes, you need the "outside of a Vue file" usage, because your scope is not the Vue component scope...
