### ISSUE TITLE
"Static Assets - /public" section is contradictory on use of absolute or relative paths

### ISSUE THREAD

**Issue by agarden** [quasarframework/quasar#16674]
### Description

This section states that references to statics should use absolute paths: "your statics are correctly referenced if and only if they do not use a relative path." But the example shows a relative path reference (`<img src="logo.png">`) and comments that it is good and an absolute path (`<img src="/logo.png">`) and says it is bad. The text contradicts the examples.

### Documentation Section URL

https://quasar.dev/quasar-cli-webpack/handling-assets/#static-assets-public

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment]
For Quasar CLI with Webpack, the documentation is accurate. Under the covers, the CLI dynamically adds a `<base>` tag which is why the native `<img>` can work in all cases (regardless of your configured publicPath or vue router mode) if your src does not already start with a forward slash (which overrides the default behavior).

However, this does not apply for Quasar CLI with Vite (https://quasar.dev/quasar-cli-vite/handling-assets/#static-assets-public).

Are you sure that you are not using Quasar CLI with Vite and looking at Quasar CLI with Webpack doc pages?

**Comment by agarden** [comment]
Shouldn't the text then read, "if and only if they do not use an absolute path"?
