### ISSUE TITLE
Unnecessaries node_modules in Electron?

### ISSUE THREAD

**Issue by bergmorten** [quasarframework/quasar#16685]
### What happened?

I use `quasar build -m electron` on windows with electron-builder configured in `quasar.conf.js`. I'm also using webpack, but think the issue is the same for Vite. Webpack does bundles the code and makes a vendor.js with all necessary code, however electron-builder thinks is needs to include all dependencies from `package.json`, which makes the electron package larger than it has to.

### What did you expect to happen?

I would expect the script to remove dependencies from package.json or use a build specific package.json in `src-electron` (same as for capacitor / src-capacitor)

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

* Make a project with some dependencies 
* Build for Electron
* See that the package includes both vendor.js and node_modules.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Electron Mode

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22631) - win32/x64
NodeJs - 20.10.0

Global packages
  NPM - 10.2.3
  yarn - 1.22.21
  @quasar/cli - 2.3.0
  @quasar/icongenie - 3.1.1
  cordova - Not installed

Important local packages
  quasar - 2.14.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.12.0 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.16.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.9 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - Not installed
  vuex - Not installed
  electron - 27.1.2 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - 24.9.1 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box      
  @babel/core - 7.23.5 -- Babel compiler core.
  webpack - 5.89.0 -- Packs ECMAScript/CommonJs/AMD modules for the browser. Allows you to split your codebase into multiple bundles, which can be loaded on demand. Supports loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 7.0.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 5.3.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - 5.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - 5.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 5.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - NTK-PW03W1AZ
  Wi-Fi - 192.168.86.30
```

**Comment by rstoenescu** [comment]
Hi,

We need those deps in there to make a reliable build system.

Here's why bundling the deps in main/preload files is not a good idea: because the electron-main/preload files can (and are) importing stuff from node_modules. If we drop the externalizing of deps, this will lead to bigger compiled main/preload files AND (highly possible) **duplicated deps** in both files (which is the real problem). From our testing, even if this somehow gets solved, there will still be issues with dynamic imports of deps (we got all sorts of trouble with them) should anyone run the production executable outside of the project folder (where all deps have already been installed).

However, Quasar CLI is flexible. Should you want, you can tamper with the configuration and use electron > extendPackageJson to change your "dependencies" to those used by main/preload scripts only (meaning drop the UI ones, which indeed should not be there -- but we can't automate this because there's no generic way to tell if a dep is used by the UI only). You can even go further and tweak the webpack configs for both the main & preload scripts to suit your exact needs (you could drop the externalization of all deps and change "dependencies" to point only to the main/preload used ones):

![image](https://github.com/quasarframework/quasar/assets/4665641/d95e7309-f54f-4596-be5d-c59855a1392b)

**Comment by rstoenescu** [comment]
Will add an "optimization" section to the docs on the subject.

**Comment by bergmorten** [comment]
Thanks, I did not see the `extendPackageJson` option :-)

With 
```
 extendPackageJson(pkg) {
    pkg.dependencies = {};
},
```

I saved 80mb and many minutes during build :-)

**Comment by rstoenescu** [comment]
Just make sure that your app still works! Like I mentioned earlier, copy the executable outside of your project's folder and run it.
In any case, we try to make the Quasar CLI as flexible as possible so it's a good idea to first check the quasar.conf options when you need something very specific to your use-case.
