### ISSUE TITLE
Update Roadmap

### ISSUE THREAD

**Issue by DaleMckeown** [quasarframework/quasar#16747]
### Description

Now that we're into 2024, would it be possible to get an updated roadmap?

The current roadmap still shows outstanding items for all quarters. I've no idea how accurate this is, items may have been done or they may not have been done.

It would be great to know what the direction is for Quasar going forward. There are some important changes to dependencies such as Vite, meanwhile Material Design 3 has now been released by Google. Will Quasar be implementing MD3?

Lots of questions. Would be good to know where we are heading.

### Documentation Section URL

https://github.com/quasarframework/quasar/blob/dev/ROADMAP.md 

### Flavour

None

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by kklem0** [comment]
Is there a thread or issue for discussing the activeness of this project? Compare to others framework is a lot more complete but also a lot less activity, which makes me wonder if it should still use this framework in projects that we plan to launch in 2025.

**Comment by DouglasCalora** [comment]
I have the same worries @kklem0, it seems like with time, the repo get less and less updates.

**Comment by WCN-llc** [comment]
I have put off using Quasar for now.
The reason is that I have not been able to configure and apply the official GraphQL.
The official GraphQL is still in beta version.
It hasn't been updated for a long time and was updated a couple months ago. But now, as I realized, it doesn't match Quasar's internal configuration.
I would like GraphQL to be included in the initial settings of the project template, just like Axios, Pinia

MD3 - yes, I would like that. But, as I understand, Google itself doesn't have it completely finished yet, well, except for the Flutter version.

**Comment by IlCallo** [comment]
> The official GraphQL is still in beta version

It is in beta because the Vue Apollo package, on which we rely, is still in beta
We're just waiting for the upstream package to go stable, but you can definitely use it in production (my company is doing so withou problems)
I'll ping that package maintainer once more on the matter
If you had problems installing it, I'd suggest you to read latest versions release notes and possibly ask on our Discord server

> it doesn't match Quasar's internal configuration

???

> Will Quasar be implementing MD3?

We don't have plans to work on this soon, we're focusing on next q-app vite and webpack major versions right now

> Now that we're into 2024, would it be possible to get an updated roadmap?

We're working on it, all points in the current roadmap are still WIP and that's why we haven't updated it lately
We are wrapping up next q-app-vite and q-app-webpack major versions release notes, to be able to release them as beta asap
The development itself is mostly done, the focus now is offering a smooth migration path
Check out this issue for more info: https://github.com/quasarframework/quasar/issues/14077

**Comment by WCN-llc** [comment]
> > The official GraphQL is still in beta version
> 
> It is in beta because the Vue Apollo package, on which we rely, is still in beta We're just waiting for the upstream package to go stable, but you can definitely use it in production (my company is doing so withou problems) I'll ping that package maintainer once more on the matter If you had problems installing it, I'd suggest you to read latest versions release notes and possibly ask on our Discord server
> 
> > it doesn't match Quasar's internal configuration
> 
> ???
> 

Hi!
I'll try to remember the details...
If I remember and understand correctly, Quasar runs on Vite-2, but the new GraphQL requires Vite-5.

And then you can go to the official page (Github) : quasarframework / app-extension-apollo / Issues - that's where the "story" with links and discussion starts.
There is a temporary solution for GraphQL and i18n there

So can this temporary solution be written in the official documentation?
Because I used exactly the official GraphQL documentation (Github)

**Comment by yusufkandemir** [comment]
@WCN-llc I am not sure if there is such a thing as "new GraphQL requires Vite 5", the original issue in the `graphql` package is https://github.com/graphql/graphql-js/issues/3978 and it's left without any answer. And, the only thing that seems to be working is using Vite `define` differently. I created https://github.com/quasarframework/app-extension-apollo/pull/155 to apply that workaround in Apollo AE so that things start working OOTB until `graphql` package releases address the problem.

Also, since the problem is in `graphql` package, I don't think you can avoid it by "putting off Quasar".

**Comment by rstoenescu** [comment]
Updated the roadmap. Will make further updates in the coming weeks.
