### ISSUE TITLE
Expansion Item Props Not Recognizing Scoped SCSS Classes

### ISSUE THREAD

**Issue by okm321** [quasarframework/quasar#16854]
### What happened?

I'm facing an issue with `QExpansionItem` component where a class specified through the `header-class` or `exact-active-class` props is not being recognized if it's defined within a scoped style block in the file. Here's a quick example to illustrate the issue
```:vue
<template>
  <QExpansionItem class="my-custom-class">
    ....
  </QExpansionItem>
</template>

<style lang="scss" scoped>
.my-custom-class {
  color: red;
}
</style>
```

In this case, the my-custom-class is not applied to the QExpansionItem. However, removing the scoped attribute from the <style> tag makes it work as expected.

### What did you expect to happen?

I expected the class to be recognized even when using scoped SCSS.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-vbdqap?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

When I use scoped css, 'my-custom-header-class' and 'my-custom-exact-class' are not recognized.
```:vue
<template>
  <div class="q-pa-md">
    <q-expansion-item
      to="/"
      header-class="my-custom-header-class"
      exact-active-class="my-custom-exact-class"
    >
      <div>test</div>
    </q-expansion-item>
  </div>
</template>

<script></script>

<style scoped>
.my-custom-header-class {
  background-color: black;
}
.my-custom-exact-class {
  background-color: green;
}
</style>
```

When I remove scoped, I can use QExpansion's header-class and exact-active-class

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by yusufkandemir** [comment]
To clarify, `class` works, but `header-class` and `exact-active-class` doesn't. And, it's due to how Vue's scoped CSS works. Basically, Vue creates a dynamic id and assigns `data-v-...` to the root element of the component, which is q-expansion-item's root div in this example. Then, the class definitions inside `<style scoped>` get transformed, e.g. from `my-custom-header-class[data-v-...]`. But, `my-custom-header-class` is supposed to be given to a deeper level element, which ends up not getting matched. So, you have to instruct Vue to be able to match it. You can learn more about it in [Vue Docs](https://vuejs.org/api/sfc-css-features.html). So, this is not a bug, this is how Vue works. Here is how to achieve what you want:
```html
<template>
  <div class="q-pa-md">
    <q-expansion-item
      to="/"
      header-class="my-custom-header-class"
      exact-active-class="my-custom-exact-class"
    >
      <div>test</div>
    </q-expansion-item>
  </div>
</template>

<style scoped>
:deep(.my-custom-header-class) {
  background-color: black;
}

:deep(.my-custom-exact-class) {
  background-color: green;
}
</style>
```
