### ISSUE TITLE
`q-btn`: `textColor` prop sets color of component in `outline` design

### ISSUE THREAD

**Issue by nymphaea-v1** [quasarframework/quasar#16866]
### What happened?

If you have button with `outline` prop set, `textColor` will override `color` prop entirely, setting color for things like border, ripple or hover effects

### What did you expect to happen?

Only color of text (and dropdown icon for `q-btn-dropdown`) is overriden by `textColor` prop

### Reproduction URL

https://codepen.io/nymphaea-v1/pen/poYKmGP

### How to reproduce?

Use `q-btn` or `q-btn-dropdown` with `outline`, `color` and `textColor` set

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Additional context

I found a similar issue https://github.com/quasarframework/quasar/issues/6252 which provides a workaround, but I still think this is a bug that should be fixed as `textColor` behavior is completely wrong. 

And this is how I'm dealing with it with Quasar & Tailwind:
```vue
<template>
  <q-btn ref="control" class="c-btn">
  </q-btn>
</template>

<script setup>
import { onMounted, watch, ref } from 'vue'

const props = defineProps({
  textColor: { type: String, default: '' },
  outline: { type: Boolean, default: false }
})

const control = ref()

const changeTextColor = (newColor, oldColor) => {
  const content = control.value?.$el.querySelector('.q-btn__content')
  if (!content) return

  if (newColor) content.classList.add(`text-${newColor}`)
  if (oldColor) content.classList.remove(`text-${oldColor}`)
}

onMounted(() => changeTextColor(props.textColor))
watch(() => props.textColor, changeTextColor)
</script>
```

**Comment by rstoenescu** [comment]
Hi,

The `outline` with both `color` and `textColor` makes no sense. By design, there will be used only one color for the button (that was the Material Design specs back when we wrote this). For outline, we use either textColor or color prop (in this order).

You probably want one color for the border and one for the text, but this can only be achieved through writing a custom CSS class for those buttons.

We are sorry, but we cannot change the current behavior, even if we wanted, as this would be a breaking change and can only be part of a major release.
