### ISSUE TITLE
Problems with using Q-table Component

### ISSUE THREAD

**Issue by chenxq-297** [quasarframework/quasar#17149]
### What happened?

The Q-table is sorted by any field, and the watch command cannot detect changes in rows data.

### What did you expect to happen?

Regardless of page turning or sorting, the watch cannot monitor changes in the data source. What could be the reason behind this?
I want to achieve fixed multiple columns (left or right) through configuration.[example](https://codesandbox.io/p/sandbox/fixed-columns-and-header-ant-design-vue-4-2-1-9fnqjj?file=%2Fsrc%2Fdemo.vue%3A2%2C52-2%2C58) .Any good suggestions?

### Reproduction URL

https://codepen.io/297ya/pen/BaEEjGW?editors=1111

### How to reproduce?

1.Click to sort or next page buttom
2.Check the console and find no response

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by yusufkandemir** [comment]
> Regardless of page turning or sorting, the watch cannot monitor changes in the data source. What could be the reason behind this?

`rows` is not mutated, it's a one-way binding. QTable handles the sorting/pagination/etc. internally by using a subset of your data as needed. So, it's expected behavior.

If you want to access the sorted data, you can use `filteredSortedRows` or `computedRows` depending on your aim.
![image](https://github.com/quasarframework/quasar/assets/6266078/3ab4d977-3b5c-4402-bfba-89966710136e)
```ts
// example
// <q-table ref="tableRef" ... />

import { Ref } from 'vue';
import { QTable } from 'quasar';

const tableRef = ref() as Ref<QTable>;

function something() {
  console.log(tableRef.value.filteredSortedRows)
}
```

> I want to achieve fixed multiple columns (left or right)

You can create a discussion for this to get help. But, you can work your way up by using this examples as the base: https://quasar.dev/vue-components/table#example--sticky-first-column
