### ISSUE TITLE
QFile inputClass prop does not work

### ISSUE THREAD

**Issue by cirolosapio** [quasarframework/quasar#17166]
### What happened?

using QFile component with input-class prop does not work

### What did you expect to happen?

see input class on inner input

### Reproduction URL

https://stackblitz.com/edit/quasarframework-jnyyuz?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. open reproduciton

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

**Comment by rstoenescu** [comment]
Hi,

The `input-class` and `input-style` are applied to the inner `<input>` which is only shown when at least one file has been selected by the user:

<img width="363" alt="image" src="https://github.com/quasarframework/quasar/assets/4665641/f5ff05d1-329e-4efb-bf4a-ba5d13ea064d">

Since you've opened up this ticket, I think that you actually want to use the `bg-color` prop instead.

<img width="608" alt="image" src="https://github.com/quasarframework/quasar/assets/4665641/1a8da4f1-86a2-4885-bbbb-e5e7d9d03ca2">
