### ISSUE TITLE
CSS layout-padding with default margin set to auto

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#172]
Hi,

This class makes perfect sense as quite often we don't want to use the whole width of the screen as it would look silly, but it has to be in the centre to make real sense.

Of course, I can add it as developer, but it should be in this class as default because 1280px div aligned to left looks just bad :)

**Comment by rstoenescu** [comment]
You're not the first requesting this. Care for a PR? It's an easy fix.

**Comment by rstoenescu** [comment]
PR merged in. Will be available in v0.9

**Comment by arddor** [comment]
This change fixed it for bigger screen sizes (> 1280px), but on for example a tablet this issue still remains. However I would rather suggested removing the `max-width` on bigger screens. Is there a specific reason for the `max-width`?

**Comment by rstoenescu** [comment]
@arddor "layout-padding" class is not required. It's just a helper for most of the use cases. Of course, you can craft your own if it does not met your specific demand (can't meet 100% cases). But basically how exactly would you see the CSS class working for a tablet (please specify width interval)?

**Comment by arddor** [comment]
@rstoenescu Yes I completely agree that it is a helper for most use cases. However what I would expect from the name "layout-padding" is that it actually does add some padding to both sides, which is a often seen pattern for page content. I think the way it is now is rather specific and not a general use case. If the default was that `max-width` would be removed from all sizes it would work as I expect it (padding on left and right side). Now you get different paddings because of `max-width` and it keeps to the left side.

As you said it is trivial to fix it or use my own css, however I felt that it is counter intuitiv and it could be discussed. If you want to keep the `max-width` I would suggest that you add `margin: auto` to all sizes so that it behaves the same for `md` `bg` and `lg`.

**Comment by rstoenescu** [comment]
@arddor Care for a PR?
