### ISSUE TITLE
Make SSR `create` function async

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#17235]
In order to use Fastify with SSR, you would need to use a compatibility layer such as `@fastify/middie` or `@fastify/express`. That is because Quasar uses and expects connect/express-like middleware. However, the registration process for those plugins is async, which is problematic as `create` is expected to be synchronous.
https://github.com/fastify/middie#usage

For the dev web server, we should be able to just put an `await` here:
https://github.com/quasarframework/quasar/blob/36146ba1dddecf47ba7b066d7fd492b84a18a23b/app-vite/lib/modes/ssr/ssr-devserver.js#L317

For the production web server, we should be able to move the create call and app interaction logic into `isReady` which is async.
https://github.com/quasarframework/quasar/blob/36146ba1dddecf47ba7b066d7fd492b84a18a23b/app-vite/templates/entry/ssr-prod-webserver.mjs#L147-L160

**Comment by FadhiliNjagi** [comment]
I second this.

In the docs, it says that you can use anything you want for your backend server, yet in practice there are obstacles to doing this:

1. The `create` function in `src-ssr/server.ts` is sync only with a warning that is should not be async. So replacing Express with `@fastify/express` or `@fastify/middie` Fastify plugins does not work (they are registered asynchronously).
2. Express-specific middleware are injected in the dev server in between `create` and `listen` which breaks Fastify apps. If more control was given over this, for example application devs having to call these middlewares ourselves, then we could register `@fastify/middie` plugin in `listen` function then "use" all those middlewares.
3. In middleware files generated by the cli (`quasar new ssrmiddleware myMw`), the type of app is hardcoded as Express. So to use Fastify or anything other than express is a pain since you have to lie to the TS compiler by casting to unknown then to Fastify App. Possible solution: make the type of app as `ReturnType<typeof create>`.
4. The `serveStaticContent` function in `src-ssr/server.ts` is expected to be an Express middleware. Using another backend framework only to be locked in to serving static files using express kind of beats the whole point.

Quasar SSR seems too opinionated towards Express at the moment. It's just too much hustle to try and fight it in order to use Fastify. I might try Nuxt with Fastify on future SSR projects.

**Comment by rstoenescu** [comment]
The "create" function can be async in q/app-vite 2.0.0-beta.16 (unreleased yet).
But I'm not done yet. Will push more changes to ease the SSR usage.

**Comment by rstoenescu** [comment]
Improvements will be available in q/app-vite 2.0.0-beta.16

**Comment by FadhiliNjagi** [comment]
I have managed to get Quasar SSR working with Fastify. However, in the render function in `src-ssr/middlewares/render.ts` the `render` function takes in ssrContext of the type `RenderVueParams`. The base type `RenderParams` interface has Express Request and Response hardcoded. This is giving me Vue-tsc warnings, but it is still working.

**Comment by FadhiliNjagi** [comment]
I vote to reopen this issue, for the above stated reasons

**Comment by yusufkandemir** [comment]
@FadhiliNjagi I noted your suggestion back when you posted it. Thanks for raising awareness. Now, I implemented it with many other improvements in #18052
