### ISSUE TITLE
QTime: time has been removed when changing AM to PM and vice versa after adding limiting-options

### ISSUE THREAD

**Issue by seemaPatelTest** [quasarframework/quasar#17282]
### What happened?

Please see https://quasar.dev/vue-components/time#limiting-options
When changing AM to PM, selected time disappear
![image](https://github.com/quasarframework/quasar/assets/165925110/2b97eb5f-e9e2-4a65-823c-75ae3eeb555a)

### What did you expect to happen?

When change AM to PM and vice versa selected time should present in the picker.

### Reproduction URL

https://quasar.dev/vue-components/time#limiting-options

### How to reproduce?

1. Go to reproduction link
2. In first time picker click on PM in the header

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by yusufkandemir** [comment]
You didn't provide a valid reproduction link. It's an empty Codepen link. It works fine in Quasar docs: https://quasar.dev/vue-components/time#basic

**Comment by seemaPatelTest** [comment]
Hello @yusufkandemir
I updated the reproduction link and added official documentation link. You can find described issue in `Limiting Options` sections.

**Comment by yusufkandemir** [comment]
Hello, this is expected behavior.

In the first example, it only allows the hours 9, 10, 11, 13, and 15. `10:45` comes as selected, which is allowed. But, when you switch to PM, it becomes `22:45`, which is not allowed, so the model becomes empty.

In the third example, it only allows hours that satisfy `hr % 2 === 0 || hr % 3 === 0`. `10:56` comes as selected, which is allowed. When you switch to PM, it becomes `22:56`, which is also allowed, so the model doesn't become empty.
