### ISSUE TITLE
Add examples on how to properly write components propagating changes to parents for bi-directional communication

### ISSUE THREAD

**Issue by ivanjaros** [quasarframework/quasar#17417]
### Description

There is unofficial recommendation on how to make child component notify parent about prop mutation, effectively making bi-directional communication via use of modelValue. This is used in things like form input where you provide a prop that you actually want to mutate.

I would like for the Quasar team to provide actual documentation page on how this is supposed to be done **the right way**. By that i mean how created(), mounted(), updated() and other native hooks should be used and how and in what way should changes be propagated via events up to the parent or down to the nested components via watchers or other events.

Personally, I have couple of working components that do the job but I am never 100% sure I am doing it correctly. And so an official guide would be quite welcome.

### Flavour

None

### Areas

Components (quasar)

**Comment by FadhiliNjagi** [comment]
This is a Vue "issue" (more like how-to question) not a Quasar one. You can make props bi-bidirectionally reactive by using `v-model`. Refer here: [https://vuejs.org/guide/components/v-model](https://vuejs.org/guide/components/v-model)

`Child.vue`
```Vue
<template>
  <q-input v-model="name"></q-input>
</template>

<script setup>
const name = defineModel()
</script>
```
`Parent.vue`
```Vue
<Child v-model="someVar"></Child>
```

`name` becomes a prop and a model at the same time so the variable can be updated both ways. When accessing a model from inside script, you need to use `.value` because it's actually a `ref`. Under the hood, it uses a combination of props, refs and emits, but saves you the trouble.

You can even have named models so you can specify multiple models:
`Child.vue`
```Vue
<template>
  <q-input v-model="firstName"></q-input>
 <q-input v-model="lastName"></q-input>
</template>

<script setup>
const firstName = defineModel('firstName')
const lastName = defineModel('lastName')
</script>
```
`Parent.vue`
```Vue
<Child v-model:first-name="someVar1"></Child>
<Child v-model:last-name="someVar2"></Child>
```
`defineModel` can take the usual prop options as the second argument. e.g. `defineModel('lastName', { required: true, default: 'something' })

**Final word**: Quasar is a wrapper around Vue, so you might want to consult the Vue docs a bit more often.

**Comment by yusufkandemir** [comment]
Hello, this is about Vue and luckily already documented nicely. Please consult Vue docs. I would especially recommend reading these pages:

- https://vuejs.org/guide/components/props.html
- https://vuejs.org/guide/components/v-model.html
- https://vuejs.org/guide/components/events.html
- https://vuejs.org/guide/components/provide-inject.html
