### ISSUE TITLE
New Quasar Project with Vite and i18n

### ISSUE THREAD

**Issue by tinohager** [quasarframework/quasar#17534]
### What happened?

When I create a new Quasar project, `@intlify/vite-plugin-vue-i18n` is installed. This project was discontinued in 2021 and should no longer be used for new projects. In your documentation “https://quasar.dev/quasar-cli-vite/upgrade-guide#other-considerations” it is suggested to use `@intlify/unplugin-vue-i18n`. Is there a reason why this is not used in the default template?

### What did you expect to happen?

Use `@intlify/unplugin-vue-i18n` in the default project template

### Reproduction URL

-

### How to reproduce?

`npm create quasar`
Choose `App with Quasar CLI, let's go!`
Choose `Quasar v2 (Vue 3 | latest and greatest)`
Choose `Typescript`
Choose `Quasar App CLI with Vite`
...
Toogle `Vue-i18n`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Project Creation (create-quasar)

**Comment by yusufkandemir** [comment]
The documentation mentions that for app-vite v2 beta which uses Vite 5. app-vite v1, which is the one you are using, uses Vite v2. That's why it's different. We would need to confirm unplugin-vue-i18n works perfectly in all aspects with Vite 2 before being able to update the template. If you and some people can confirm it works fine, then we can consider updating the template for app-vite v1. app-vite v2 template already uses this.

**Comment by tinohager** [comment]
Is there a release date for app-vite v2? The roadmap has not been updated for some time.

**Comment by rstoenescu** [comment]
Hi, we are trying hard to release it this month, but there's ecosystem changes that keep happening and we want it to be up to date with everything, rather than having to introduce breaking changes in our CLIs later.

But nothing stopping you from upgrading right away. It's pretty stable, but some minor breaking changes might still occur (but nothing major).
