### ISSUE TITLE
Inflexible tsconfig setup for new quasar

### ISSUE THREAD

**Issue by Smrtnyk** [quasarframework/quasar#17682]
### What happened?

I am extending the quasar tsconfig as per upgrade guide
```json
{
    "extends": "./.quasar/tsconfig.json",
    "compilerOptions": {
        "sourceMap": true,
        "forceConsistentCasingInFileNames": true,
        "useDefineForClassFields": true,
        "types": ["vitest", "vitest-browser-vue", "@vitest/browser/providers/playwright"],
        "strict": true,
        "noImplicitAny": true,
        /* Enable error reporting for expressions and declarations with an implied `any` type.. */
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictBindCallApply": true,
        "strictPropertyInitialization": true,
        "noImplicitThis": true,
        "useUnknownInCatchVariables": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "exactOptionalPropertyTypes": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        // "noUncheckedIndexedAccess": true,
        "noImplicitOverride": true,
        "paths": {
            "src/*": [
                "./src/*"
            ]
        }
    },
    "references": [
        {
            "path": "../backend"
        },
        {
            "path": "../floor-creator"
        },
        {
            "path": "../types"
        }
    ]
}

```
and I am specifying my own paths entry.
This overrides the path of the quasars tsconfig meaning that import in `import { defineConfig } from "#q-app/wrappers";`
quasar.ts file is throwing type error and fails on typechecker.
This feels inflexible, because I need to specify my own paths, but if I specify it then the recommended import from #q-app wrappers throws type error.
For now I went back to deprecated import
`import { configure } from "quasar/wrappers";`
Just wanted to report this in case there is some interest to improve this.
For now I can live with this.

### What did you expect to happen?

Maybe there is already a proper solution that I am just missing here

### Reproduction URL

https://stackblitz.com/edit/quasarframework-stackblitz-templates-3nbvo1?file=quasar.config.ts

### How to reproduce?

I have described the issue in the intro
You should update your app-vite stackblitz template to have the newest state and not the rc-2

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment]
Hi,

You could use quasar.config file to extend the generated tsconfig. As a rule of thumb, we always provide ways to extend everything, sometimes even multiples for convenience.

![IMG_9807](https://github.com/user-attachments/assets/695dfcf9-5be8-4e51-b3b7-0076d0f56dc7)

**Comment by Smrtnyk** [comment]
I am running a typecheck with my own script using vue-tsc
 as seen here https://github.com/Smrtnyk/Firetable/blob/master/packages/frontend/package.json#L14
 I like having it like this, so my IDE (webstorm) and build setup are all on the same page
 I prefer to have lint and typecheck outside of quasar build, because I run lint across all packages in my monorepo at once, so I also have typechecker like that
 
 I am fine if you want to close this issue, I found a workaround for myself
 just wanted to point this out when I did the upgrade to new quasar.
 To be honest, I don't understand this new path alias pointing to dynamically generated chunk in node_modules, but I am also not that familiar with quasar internals.
 Importing from quasar/wrappers still works just fine so I am sticking with that for now.

**Comment by rstoenescu** [comment]
Doing it through quasar.config is the way to go. The `quasar/wrappers` way is now legacy. We haven't removed that to soften the transition only. At least you could use `@quasar/app-vite/wrappers` (because remember that `#q-app` is just an alias to `@quasar/app-vite` -- or to `@quasar/app-webpack`, based on what CLI you are using).
However, let me explain the bigger picture on why the paths are necessary. TS does not support aliasing and we opened a ticket for the TS team to evaluate. The answer was that they don't plan on adding this. So the only thing left for us was to use a path specifically for `#q-app`. We wanted something simple, and also to make it easier for anyone to switch from q/app-webpack to q/app-vite (or the other way around).
We really recommend using quasar.config > build > extendTsConfig. Your IDE will also work (some might require a restart after changes to tsconfig, but regardless, they will still work).
