### ISSUE TITLE
QTable sortable not working at Quasar Framework v0.15

### ISSUE THREAD

**Issue by CristalT** [quasarframework/quasar#1794]
### Software version

Quasar: 0.15.7
OS: Linux
Node: 8.10.0
NPM: 5.7.1
Browsers: Firefox, Chrome
iOS: -
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/marceloforclaz/85ookbmr/

### What did you get as the error?
Sortable columns not sorting

### What were you expecting?
Sort table data by column name clicking in column's header

**Comment by rstoenescu** [comment]
Hi,

Two things missing:
1. A "name" prop for each column in columns definitions -- need a way to tell each column from each other
2. Use a row-key prop for performance

https://jsfiddle.net/85ookbmr/5/

**Comment by CristalT** [comment]
Thank you very much! :+1: 
And sorry by my distraction, I did things like olders quasar versions :S

**Comment by rstoenescu** [comment]
No problem. Thanks for supplying a jsfiddle so I could sort this out fast.

**Comment by hmeine** [comment]
I had the same problem, but a different cause. Because this old issue is the only obvious Google hit I got, I thought I would leave another possible solution here, even if it may appear strange and/or off-topic:

In order to disable pagination (which I did not realize to be too closely related to sorting), I was using

    <q-table :pagination="{ rowsPerPage: 0 }" ...>

while I needed to do 

    <q-table :pagination.sync="pagination" ...>

with `pagination` being defined in `data()`.

Rationale: `pagination` is a property that is also used for the sorting setup (may have an entry `sortBy`), and Vue components may not write to their own properties, but just emit change events. So it is vital that one has a _writeable_ data element for such dynamic configurations, and that one uses `.sync` to set up a two-way synchronization.
