### ISSUE TITLE
CSS: Toolbar option inverted is white and not transparent (says documentation)

### ISSUE THREAD

**Issue by wvansl** [quasarframework/quasar#1799]
### Software version

Quasar: 0.15.8
OS: Win10
Node:
NPM:
Browsers: Chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
When you set "inverted" to a toolbar, the toolbar background turns white.
In the documentation it says it should turn transparent.

### What were you expecting?
Docs says it should be transparent

### What steps did you take, to get the error?
Documentation:
http://quasar-framework.org/components/toolbar.html
Example:
http://quasar-framework.org/quasar-play/android/index.html#/showcase/navigation/toolbar
Do inspect on inverted you see the background color is set to "#fff" instead of transparent.

Maybe it should be white, but then the docs are wrong. In that case it would be nice to have a "transparent" option directly in quasar toolbar.

**Comment by rstoenescu** [comment]
Hi,

Thanks for opening this ticket. Yes, the docs are a bit outdated on the color -- will take care of fixing this issue on docs.

However, you can make good use of the color/inverted/text-color props to achieve the same effect with a combination of `color="transparent" text-color="<some_Quasar_color>"`. This sets the main color to "transparent" (in this case the background, since it doesn't have "inverted" to invert colors), and then you're requesting that text-color be whatever color you want.

Example: `<q-toolbar color="transparent" text-color="green">`
Hope this makes sense.
