### ISSUE TITLE
QKnob no longer emits an @change event

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar#1803]
QKnob now only emits an `@input` event so there's no way to call a method on @change (for lazy loading)

**Comment by rstoenescu** [comment]
For lazy loading, check the lazy loading section of the QKnob docs.
```html
<q-knob :value="model" @change="val => { model = val }" />
```
This is just syntactic sugar for v-model.lazy, but `lazy` modifier **for components** is not yet merged into Vue - https://github.com/vuejs/vue/pull/6940

Now the big picture: if you use v-model (notice no "lazy", which is syntactic sugar for `:value="model" @input="val => { model = val }"`) the model updates immediately. When user releases mouse (or lifts finger), then QKnob checks model again and if it changed, emits `@change` event. But due to 'v-model' (no "lazy") already previously updated model, no change is detected so it doesn't emits the event.

So, if you want lazy update, use the v-model.lazy equivalent (until v-model.lazy is merged into Vue) and you get the `@change` event. Otherwise, use simple v-model and listen for `@input`.

**Comment by rossity** [comment]
@rstoenescu I see, thank you very much for the clarification! I think in order for the component to have the desired action then, I would need it to have its `@dragend` event back. Is there any reason it was taken out?

**Comment by rstoenescu** [comment]
What I'm saying is that you can use `<q-knob :value="model" @change="val => { model = val }" />` -- so you get the `@change` event which is similar to `@dragend` (which wasn't documented).

**Comment by rossity** [comment]
I see what you mean, but let me clarify (I may still not be doing it correctly)

Using your example, since the component doesn't have a v model associated with it, the number on the Q knob only updates after you stop dragging.

I'd like the "value" to update as the user is dragging the Knob, so they know what number they're stopping on, but I need to post to an API once they've stopped dragging.

If I listen for @change, the model doesn't update and the user doesn't know what number they're on until after they let go. If I listen for @input, it would send an API post request every time they drag the knob another step. I think listening for @dragend is a compromise between the two and would allow me to use a v-model on Q-Knob and essentially still allow lazy loading.

**Comment by rossity** [comment]
On mobile so I can't edit, but I'm going to use the code in your comment when I get back to desktop as that may solve my issue!
