### ISSUE TITLE
Image dynamic path (:src / v-bind:src)

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar#182]
How to make images that are referenced dynamically, also be considered by the webpack?

Today only the fixed paths and the contents of the "static" directory are considered.

Thank you.

**Comment by rstoenescu** [comment]
This is more of a question for Webpack than for Quasar. You can read about handling static assets here: http://quasar-framework.org/guide/app-handling-static-assets.html

Simply reference your image with a relative path (from *.vue file containing that "src"). Alternatively, you can use `~assets/...` (to directly reference a file from `/src/assets` folder (this is due to the fact that the default project template created by Quasar CLI offers the `assets` Webpack alias).

Example referencing an asset:
``` html
<img src="~assets/some-image.png">
```

Example referencing a static asset:
``` html
<img :src=" 'statics/some-image.png' ">
<!-- this is just a trick using dynamic Vue property so Webpack won't pick this image and reference it dynamically -->
```

**Comment by xereda** [comment]
Thanks for the feedback. I'm using statics.
