### ISSUE TITLE
[Change Proposal] Merge QDialog and QModal into a single component

### ISSUE THREAD

**Issue by zuck** [quasarframework/quasar#1824]
With Quasar 0.15.x release, the **QDialog** already received a big refactoring in order to allow devs to use it as a normal component too.

In my opinion there are still some design issues and missing use case coverage:

- I really often need the **use QDialog as a function** approach, but with a little bit more complex form/prompt inside it. This use case is quite useful because you can return a Promise from the function and use it in your calling piece of code to handle user choice or form submission in a very clear way:

```
// In my calling component:

this.$q.dialog({
  // NOT possible with 0.15.x
  prompt: [
    { type: 'text', model: 'firstname' },
    { type: 'text', model: 'lastname' },
    { type: 'datetime', model: 'birthdate' }
  ]
}).then(data => {
  this.$q.notify(
    `Hello ${data.firstname} ${data.lastname}, you were born on ${data.birthdate}`
  )
}).catch(e => {
  this.$q.notify('Bye bye, then...')
})
```
- Instead, on 0.15.x, it is suggested to use QDialog **as a component** in order to customize its content and implement this kind of custom prompt/form. The idea makes sense, but it has some pitfalls in my opinion:

1. You loose the **use as function** code style, which has the very big advantage of being very clear on purpose.
2. If you want to still use Promises, you have to create and handle your own **open** method which create a Promise, registering its resolve and reject functions inside your component's data object in order to control the original Promise's resolution or rejection from your component's code, which looks like an ugly hack.
3. To use QDialog **as a component** you're actually using QModal subcomponents to define its template!

So, my proposal is to merge these two components into only one, with some more flags in order to control its behavior and appearance.

For the **use as a function** approach, I'm not sure about a viable solution yet. A possible way could be to add another **option** to QDialog/QModal factory method (`this.$q.dialog()`) which allow devs to pass a component to be used as dialog's body:

```
this.$q.dialog({
  // It overrides 'prompt' option:
  bodyComponent: () => import('./MyCustomFormComponent')
})
```

**Comment by rstoenescu** [comment]
Hi,

Let's take them one by one:

1. Yes, it is convenient to have a function to use instead of defining a template. But the first problem with pre v0.15 dialog was that it got very bloated and it looked like it is never going to end as more and more use cases appeared. So it really makes sense to lose all this complexity and allow full customisation by using a template. Furthermore, the biggest problem of them all was that due to how Webpack tree-shaking works (it's actually UglifyJS that did that): importing anything in the Dialog (QInput, QRange, QSelect, etc etc) means these components go into the bundle regardless if they are ever used OR IF DIALOG is imported from Quasar. There are numerous opened tickets on Webpack tree-shaking explaining this behavior. The end result is: all form components are bundled, regardless if you yourself are importing them or not. So a big "no-go" on this.

2. You can still use promises... QDialog has show() and hide() methods which return a Promise, just like QModal.

3. QDialog is just a special QModal and nothing more. While it sounds like a good idea to merge them, it's not. This would mean QModal gets bloated with unnecessary code checks. The end result: performance will suffer, especially on low end mobiles. Conceptually speaking, QModal is a basic building block component, just like QPopover for example. QDialog is not. QDialog is a wrapper on QModal to enable for quick Material Design alerts/confirms etc.

4. Your example with specifying a body component sounds like a good idea at first. But then, how is the scope of MyCustomFormComponent linked to QDialog's one so that the Promise resolves with the form components' data? Furthermore, since you are still defining and importing a component (along with its template), how is this any different than creating a component which has QDialog in it?

---

V0.15 is more inline with how a Vue developer should think about its app and it allows for full customisation, as opposed to pre-v0.15 where everything had to be pre-cooked inside Quasar. Should some special needs arise in an app, developers can create a wrapper over QDialog (which exposes show/hide Promise returning methods) and in the end they can even use that to create their own "dialog as a function" custom use case.
