### ISSUE TITLE
"Adding your own colors" to q-input does not work

### ISSUE THREAD

**Issue by joerg-walter-de** [quasarframework/quasar#1901]
http://quasar-framework.org/components/color-palette.html

quasar 0.15.12

`.text-brand {
  color: #a2aa33;
}
.bg-brand {
  background: #a2aa33;
}`

and

`<q-input color="brand" ... />`

does not affect a q-input field in the expected way:

![image](https://user-images.githubusercontent.com/33499391/38466190-a2c599f4-3b25-11e8-8e3d-55b668ad8d2c.png)

![image](https://user-images.githubusercontent.com/33499391/38466200-c01830b6-3b25-11e8-916f-44b4dbcabd71.png)

![image](https://user-images.githubusercontent.com/33499391/38466206-d7deacf2-3b25-11e8-8eae-efe190b1f5df.png)

the text is not blue (what I actually want) but the field line is blue.

How do I modify the color of the text in the input field?

**Comment by rstoenescu** [comment]
Hi, The `color` prop refers to the bottom bar, not the color of text. For that write your own CSS rule.

**Comment by rstoenescu** [comment]
Nothing needs changing because:
1. `color` prop for all components refers to the decorative color; in the case of QInput it's the bottom bar color
2. What does a component property has to do with the way a custom Quasar color is defined? The way it's being defined has nothing to do in common with the purpose of the color property.

Please ask on Discord or forum. Otherwise use Chrome/Firefox dev tools to see what selector you need to target.

**Comment by aprixon01112017** [comment]
> Use text- or bg- prefixes as class names to change the color of text or the color of the background.

from 
[http://quasar-framework.org/components/color-palette.html](url)

So the prefixes text- and bg- are built into quasar. The color defined with text-brand is used for the line, not the line-brand color. Quasar forces me to name something what it is not, it forces me to name the line color the text color.

**Comment by joerg-walter-de** [comment]
As far as I understand :

You have defined that the property color for a q-input influences its properties in some way.
You have defined that definitions .text-<customname> and .bg-<customname> are used in some way when property color="<customname>"
And it happens that the color defined in .text-<customname> is used for the line.

Let's assume I want to color the lines of my q-input fields blue. So I write:

`<q-input v-model="credentials.userId" color="brand" placeholder="Your ...`

What do I have to write in my style file to make that work?

Am I free to write something with the identifier line?

Because it certainly would be reasonable to name the color definition after the gui element I want to color.

If the answer to my last question is no than I am forced to name something in my code what it is not - I have to use the identifier text for a definition that is not used on text but on lines.

**Comment by pknuth** [comment]
Also text-color prop should come together with placeholder-color.

**Comment by Manubi** [comment]
I have the same problem. No ideas how to fix this?

**Comment by felexkemboi** [comment]
I got a way out of this, I don't know if it is exactly what you guys are suggesting
`:input-style="{ color: 'white' }"`

**Comment by Divensky** [comment]
An alternative way to change the color of the input text in `q-input` is: remove` "scoped"` from your `<style>` and then apply the CSS classes as always.

The way it seems to work is: under the hood of a `q-input` component is a native HTML `input` element. It is wrapped into an HTML `label` element, as you can see in the Dev Tools. When you apply any styles to a `q-input` component, they apply to the root HTML element, which is `label` in this case. They do not apply to its inner `input` element. This mechanism is explained here: https://vue-loader.vuejs.org/guide/scoped-css.html. As covered on this page, you have to remove "scoped" or add `::v-deep` to get the styles to apply to a non-root element. 

So far as I saw, Quasar prop `:input-class` does permit you to apply the class to the HTML `input` tag but the class has no effect until "`scoped`" is removed. 

The problem I was trying to solve when I came across this thread might be of interest to someone. I had to remove spinner buttons from `<q-input type="number">`. This requires a modification of the `input` element and the above solution by @felexkemboi did not work in this case because it did not allow pseudo-elements. I ended up with this code: 

```
<template>
  <q-input type="number" :input-class="input-class" />
</template>

<style lang="scss">
// important: no "scoped" here
.input-class {
   // color, background-color, etc. work on the Input tag if used here. 
  -moz-appearance: textfield;
  appearance: textfield;

  &::-webkit-inner-spin-button,
  &::-webkit-outer-spin-button {
    -webkit-appearance: none;
  }
}
</style>
```

**Comment by rutkaykarabulak** [comment]
> I got a way out of this, I don't know if it is exactly what you guys are suggesting `:input-style="{ color: 'white' }"`

It works for input text, but not for hint's color...
