### ISSUE TITLE
[Request] fixed columns on dataTable

### ISSUE THREAD

**Issue by abertolotto** [quasarframework/quasar#1914]
Hi, it will be nice to have on dataTable the possibility to fix one or more columns on the left or on the right. This can be useful with long rows content

![schermo3-2](https://user-images.githubusercontent.com/35486214/38584023-4d041ad0-3d15-11e8-86bc-d4ad8c3076c6.gif)

**Comment by rstoenescu** [comment]
Hi,

This was a feature of v0.14 DataTable. Unfortunately, people wanted DataTable to be able to fully customisable, and the new architecture of the component does not allow this feature anymore due to technical issues. However, with a carefully crafted CSS, this is possible, but in app space, not Quasar code. Sorry for any inconvenience.
