### ISSUE TITLE
Unable to read stop event of ajax-bar if my http call fails (Not everytime)

### ISSUE THREAD

**Issue by jayudhandha** [quasarframework/quasar#1976]
I am facing this issue after I upgrade my quasar from **v0.15.6 to v0.15.10**

If my HTTP call is failed, then sometimes I am unable to read the stop event.

It blocking my application and I have to manually reload the application.

Previously it was working fine, And on my dev server it is working fine with v0.15.6

Does anyone face this issue?

Please note that for success response of HTTP call, Everything is working fine!

Thanks,
Jayesh

**Comment by nothingismagick** [comment]
Hi Jayesh, it is impossible to help you because you did not give us enough information to really know what is going on. That is why we expect those who report issues to give us ALL of the following information.

### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### JsFiddle (for Quasar v0.15+ only)


### What did you get as the error?

### What were you expecting?

### What steps did you take, to get the error?
