### ISSUE TITLE
Feature Request: Make the entire leaf 'clickable' when QTree has tickable entries

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#1998]
Clicking anywhere on the label in QTree is a common behaviour, and serves to expand / contract the tree if the node has children. However, on leaf nodes when `tickable` is set true, clicking the node could also set / unset the checkbox.

I would argue this should be the default behaviour, but I guess it could be made optional via a prop to be backwards compatible.

I'm happy to look at making a PR for this.

**Comment by rstoenescu** [comment]
Hi,

This would generate a lot of confusion when used along the selectable, tickable features. I think this request is similar to https://github.com/quasarframework/quasar/issues/1866
Not to mention the QTree code would become a spaghetti very hard to comprehend/maintain while also performance would drop due to the extra code logic (which would become noticeable on low end mobile devices for example).

Maybe I am missing something obvious, some "light" code logic. If you think you can PR this while not breaking the other features, not making QTree features themselves hard to comprehend, and make it performant, please go ahead with a PR. We'll comment it and then merge it.

**Comment by dsl101** [comment]
Is this the right place to discuss ideas for this? I see you closed it...

Anyway, my thought is that `selectable` and `tickable` are (almost) mutually exclusive, in that one uses a checkbox and the other could use a radio box (i.e. when only a single leaf can be 'selected'). Then the whole leaf can always be clickable, and it sets either the checkbox or the radio button depending on the mode.

I'm not sure what the use case for selectable is though—perhaps radio button wouldn't be right?
