### ISSUE TITLE
Bug Loading class got undefined if customClass not pass

### ISSUE THREAD

**Issue by fuadmuhtaz** [quasarframework/quasar#2000]
### Software version

Quasar: v.0.14.10
OS: Arch Linux
Node:
NPM:
Browsers: Chromium v.65
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Loading component not covered sidebar and navbar because customClass got undefined
### What were you expecting?
Loading component need covered all element
### What steps did you take, to get the error?
I just click show and loading not covered navbar and sidebar
[http://v0-14.quasar-framework.org/quasar-play/android/index.html#/showcase/progress/loading](http://v0-14.quasar-framework.org/quasar-play/android/index.html#/showcase/progress/loading)
### Suggest
// customClass = false

if (customClass && typeof customClass === 'string') {
    props.customClass = ` ${customClass.trim()}` //undefined
  }

return h('div', {staticClass: staticClass + props.customClass}, child) 
will return 'q-loading animate-fade fullscreen column flex-center z-maxundefined'

I think we need one if to check customClass

**Comment by fuadmuhtaz** [comment]
![Images bug](https://lh3.googleusercontent.com/-30MsTwEBWBem49Q9xNl_Kb9tdK0n2o71z73orquAhTF127308uDnJerLcOmiq9zknLgFRGvHig-BvUGLUi0=w1301-h678-rw)

**Comment by rstoenescu** [comment]
Hi,

Thank you for also supplying a PR for the v0.14 baseline. I must apologise I didn't have time for it due to the current work-load. My honest question is: can you upgrade to newer Quasar instead? Releasing another v0.14 version would eat a LOT of my time at the moment. If it is critical, please feel free to reopen and I will take care of it. But please, only if it's critical for you business.

**Comment by fuadmuhtaz** [comment]
I will migrate my project to newer version in future, for this time I just add if for that problem.
