### ISSUE TITLE
support feather icons

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#2022]
Would be nice to have feather icons supported: https://github.com/feathericons/feather

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, we only support icon libraries that also supply a web font, and Feather Icons does not from what I've seen. Although, a [github ticket](https://github.com/feathericons/feather/issues/135) is opened, it is uncertain when the official web font will arrive. I am reluctant to go on and use unofficial web fonts due to the mess it can create regarding versioning and updates.
