### ISSUE TITLE
[Request] Data Table Inline Editing

### ISSUE THREAD

**Issue by krugerpl** [quasarframework/quasar#2023]
I work with Data Table Component a lot. I would like to have these features:
- inline editing 
https://vuetifyjs.com/en/components/data-tables#example-editdialog
- custom filters for desired columns
 https://react-table.js.org/#/story/custom-filtering

**Comment by olegvakulenko** [comment]
inline editing: +1

**Comment by Lou-Der** [comment]
Specific column inline editing can already be achieved using the Q-TD slot component.   It even works with vuelidate if coded properly.

While having it already in data table component would be convenient,   I'd hate to see it bulk up the control for basic table layouts.

I use something like:

```
<q-td slot="body-cell-fieldName" slot-scope="props" :props="props">
       <q-field :error="$v.form.$each[props.row.__index].fieldName.$error"
                    :error-label="errorMsg($v.form.$each[props.row.__index].fieldName)">
                    <q-input type="text" v-model="props.row.fieldName" maxLength=9
                      @blur="$v.pi.$each[props.row.__index].fieldName.$touch()" 
                      @change.native="changedField(props)" />
      </q-field>
</q-td>
```

**Comment by kerbo** [comment]
Editable cells should be activated dynamically. Yes, you can create an editable table by inserting many q-input components but this is inefficient. The table should display an editable cell when the user clicks (or double clicks) on the cell or tabs into the cell. 

Of course, since table columns can have different data types, you'd need to activate the correct editable component for the data type. Select components should also be supported.

**Comment by hurrycaner** [comment]
@krugerpl Have you tried using a a popover with a input inside?
The column filter is a nice proposal, much better than actual filtering... today you can do something using body slot...

**Comment by BenoitRanque** [comment]
Very easy to achieve this using slots. IMHO should stay as is, else linking it up with things like validation will become a pain

**Comment by rstoenescu** [comment]
It will get in. Thanks for your patience.

**Comment by rstoenescu** [comment]
Added QInlineEdit new component. Will be available in Quasar v0.17.10.

<img width="226" alt="inline-edit-1" src="https://user-images.githubusercontent.com/4665641/44308233-2d0ef680-a3ba-11e8-9ce5-70fe0171a4ad.png">
<img width="239" alt="inline-edit-2" src="https://user-images.githubusercontent.com/4665641/44308234-2d0ef680-a3ba-11e8-8930-1f66a5b353ab.png">

The custom filters can be done using QTable scoped slots.

**Comment by kerbo** [comment]
The spec does allow for "inline menus" which is basically what I'm asking for. I think the popover editor design spec is there because it better supports mobile devices. With larger screens/mouse, I think the approach is terrible for data entry. And data entry is the primary use case for editable tables. I guess I have to complain to Google...

**Comment by sustained** [comment]
First, let me thank you for taking the time to implement the feature.

I too was hoping for a true inline solution, personally but ideally wouldn't it be best if both methods were supported?

Especially if the Material design spec does in fact allow actual inline editing as well, as @kerbo says it does.

I'm going to take a stab at implementing true inline editing myself because I personally really need it and don't particularly care if I'd be breaking away from the Material design spec (but I understand if you want Quasar to the spec religiously).

I'm not sure if I'll even be able to figure it out myself (pretty new to Vue and Quasar) but I'll try anyway. If a PR wouldn't be accepted, I'll still post here if I get a solid implementation working in case anyone finds this and wants to use it.

**Comment by kerbo** [comment]
Option 1 - my opinion is only show the editor on the active cell. For example, if you are editing a currency cell, its nice to see the content (which is formatted with the currency symbol) to change to a number for editing. After leaving the cell, the edited value formats with the currency symbol. Same with dates. You can show a mask for input.

Option 2 is a good choice for use cases where the table represents a table of records and you want to do a CRUD operation on a row.

Option 2b doesn't make any sense to me.

Option 3 is good. For a common use case where you have a parent record with child records (e.g., Invoice/Invoice Line Items), the table would represent the child records for the parent. A save on the form would save everything (parent and all child records) n one transaction. 

I find for the use case where you are displaying a list of records and an edit is complex (child records or rule validations), in line editing of records is impractical. Instead you would click on an edit icon (or double click the row) to open the record and display a form for editing.

**Comment by rstoenescu** [comment]
@sustained @kerbo 

* As you can see there are many options of editing. There's no golden solution as each developer has  custom needs. It's one of the reasons of why QTable allows for scoped slots, so use them.
* An inline editing custom component is easy to create. So easy that it just doesn't make sense to add it to the framework. Just use two divs (one with content as text, the other with an input) and a v-if + v-else combination on them; a state variable that gets changed based on mouseover/mouseout or click (for entering editing mode) + capture ENTER/ESC keys on the input (for returning to non-edit mode).

**Comment by radiantone** [comment]
Hi,
  When will real inline editing be available? The popup modal is intrusive to the UI margins.

**Comment by pazarbasifatih** [comment]
@rstoenescu 
Hi,
Sorry but inline editing doesn't seem as easy as putting a v-if before the cell.
Am I doing something wrong here? Clicking on cell activates editing for whole colomn.
![chrome-capture](https://user-images.githubusercontent.com/42507858/112634452-a95bf700-8e4b-11eb-9d73-e7e3fbfa4001.gif)
https://codepen.io/pazarbasifatih/pen/MWJKNyN?editors=1010
There is something you've done that targets the exact individual cell that has been clicked on and we're after that precise behavior, only inline.

**Comment by ronfak** [comment]
@ghost Here's a revised working version of your attempt:
https://codepen.io/fakron/pen/QWZMoRX
The editor is activated with a double-click. This is a quick solution that shouldn't be used in production since I've dynamically added a property to the loaded data. In a real-life scenario, you wouldn't do this, but it should be sufficient to keep you or other going.

![Enregistrement-2023-04-30-232503](https://user-images.githubusercontent.com/10092905/235377024-5bca8302-8950-470e-b4cb-b85170563da9.gif)

Depending on your needs, you could also simply set the "contenteditable" attribute of the div without the need for an input. That way, the input will not be injected into the cell.
