### ISSUE TITLE
card / adding color property modifies background AND text color

### ISSUE THREAD

**Issue by joerg-walter-de** [quasarframework/quasar#2025]
`<q-card >
        <q-card-title class="bg-deep-purple-2">
          <q-icon color="black" slot="right" name="euro_symbol" size="32px"/>
          Kosten
        </q-card-title>
        <q-card-separator />
        <q-card-main >
          Preis auf Anfrage
        </q-card-main>
      </q-card>`

produces:

![image](https://user-images.githubusercontent.com/33499391/39875665-81f765d0-5471-11e8-970b-ec4a78dc5d1a.png)

`<q-card color="purple-1">
        <q-card-title class="bg-deep-purple-2">
          <q-icon color="black" slot="right" name="euro_symbol" size="32px"/>
          Kosten
        </q-card-title>
        <q-card-separator />
        <q-card-main >
          Preis auf Anfrage
        </q-card-main>
      </q-card>`

produces

![image](https://user-images.githubusercontent.com/33499391/39875697-9ff4dca2-5471-11e8-92a5-528f1bc7eff4.png)

changing the background color to purple should not change the text color at all.

**Comment by rstoenescu** [comment]
Hi,

```js
<q-card color="purple-1" text-color="black">....
```

Usually most colors are darker, so the default case, unless `text-color` prop is specified, is to turn text to "white". The color/text-color props are important (and very easy to master) as they apply consistently to many Quasar components.

**Comment by joerg-walter-de** [comment]
So actually with color=".." I am not setting a color but a color scheme.

http://quasar-framework.org/components/color-palette.html#Adding-Your-Own-Colors

`.text-brand {
  color: #a2aa33;
}
.bg-brand {
  background: #a2aa33;
}`

> Now we can use this color for Quasar components:

That is not a color, but a color scheme, a combination of colors.

The color management is a mess.

It is very important to choose precise nomenclature because it creates expections in the users of the api.

**Comment by rstoenescu** [comment]
Strong word there. I think the color management is pretty clear and consistent:

1. The most important point: Leaving aside Quasar for a moment, you are setting a property on a component. What are docs saying for that property? "color" can mean a lot of different things for a component. Imagine a complex component. Does "color" refer to the color of the title, the color of the subtitle, the background, the color of the border? I fail to see how this can create a precise expectation from a developer without reading component docs. Now back to Quasar, it has a consistent way of dealing with color/text-color props, explained below.

2. The rule of thumb of is the combination of color/text-color + inverted for most components. "color" is mainly for background, while text-color is always obviously for the color of text should you don't like the default one. "inverted" refers to inverting the color, so setting as text color instead of background. You may ask "Why?". The answer is simple. It adds the ability to do things like: `<q-toolbar color="teal" :inverted="$q.theme === 'ios'">` which easily matches Material and iOS design expectations, instead of writing one (or two) long ternary operators for background and text color.
Once you fully grasp the concept it makes everything easy. You just have to see the bigger picture and take into account the most used cases, which is setting a darker color on which black as text-color is not an option. Not setting a default "white" would force you to use text-color a lot.

3. That combination represents a Quasar color used on components as color/text-color prop value. The components need to be prepared for both cases (background or text color). Again, look at the bigger picture and take into account point no. 2. I won't even get into details on the inner workings of components' CSS delicately handled so that the footprint is as low as possible (many times relying on "currentColor" as CSS property value).

Does that makes sense to you?
