### ISSUE TITLE
Empty space instead of icon’s name when icon not loaded yet

### ISSUE THREAD

**Issue by monoc44** [quasarframework/quasar#2036]
Hi there,

When an icon hasn’t been loaded by the browser yet (q-icon name=“lock"), the icon's name appears instead (example: ‘lock’ displayed for a lock icon). Some customers reported to us that it looks like a glitch to them and ask if we could just put an empty space while waiting for the icon to appear.

I haven’t seen any attributes that allow to prevent the icon’s name from appearing. Any suggestion?

And if not possible, would it be easy to provide such an option?

Many thanks
-Frederic

**Comment by ibrainventures** [comment]
I got the same effects and it would be much better to have not this flickering on the load-state.

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, this is due to how Material icons web font is designed. It's a ligature font, as opposed to the other icon fonts that you can use. Material icons generate `<i>icon_name</i>` whereas the other icon fonts generate: `<i class="icon_name"></i>`. Until material icons are loaded, the "icon_name" is displayed, because there's no CSS yet to deal with these "i" tags. Now notice the "class" attribute for the other font icons; it doesn't adds content inside the "i" tag, so it doesn't affects the content.

Should you wish to avoid this, it would be better to switch to one of the other icon fonts. Maybe "mdi" so you can still use material style, but please note that mdi font files are bigger than material-icons' font files.

Sorry, but closing this as it's out of Quasar's reach anyways.

**Comment by monoc44** [comment]
@rstoenescu Thanks Razvan for your clear explanation, makes sense. You are right, I can see what you describe when inspecting the DOM elements.

One option could be maybe to hide the content through CSS, something like this:
```
i .material-icons {
  display none
}
```

Will take a look at other icons providers. Thanks again!

**Comment by rstoenescu** [comment]
There was also this ticket which eventually got closed: https://github.com/google/material-design-icons/issues/150

You could also experiment with:
* https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/load
* https://stackoverflow.com/questions/12312323/how-to-know-if-a-font-font-face-has-already-been-loaded
