### ISSUE TITLE
LayoutDrawer mini mode: still animating when hidden

### ISSUE THREAD

**Issue by onurkose** [quasarframework/quasar#2059]
I've been testing new [Mini Mode](https://quasar-framework.org/components/layout-drawer.html#Mini-mode) of LayoutDrawer especially how to toggle between mini mode, overlay mode etc.

If overlay prop is set true by default, there's some bugs when the drawer is set to mini mode. But if I switch overlay to false by default and toggle between true/false after page build, it works as it should.

Here is the overlay set false by default;
https://jsfiddle.net/m2rv6am8/2/

And this is the buggy version;
https://jsfiddle.net/4jzhue84/28/

Please try to test jsfiddles on big screens or resize the build window to larger size to workaround screen size breakpoints to mini mode works fine.

I believe Mini Mode is still in this early stage and needs some more work to be done. This issue probably be solved by modifications on `showing` prop of `QLayoutDrawer.js` at line 55.

**Comment by rstoenescu** [comment]
Hi,

1. Thanks for reporting this.
2. You did not explicitly say what the bug is, so fixed what I observed. Hopefully it's the same issue. When drawer is hidden and you switch the mini-mode or overlay mode, drawer is temporarily shown on screen and gets hidden with animation.

Fix available in 0.16.0 in a few days. Don't worry, v0.16 has no breaking changes.

**Comment by onurkose** [comment]
I'll check and report when it'll ready. Thanks.
