### ISSUE TITLE
font-awesome icon class name needs "fa" and "fa-iconname"

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#2072]
There have been reports about class="fa-iconname" no longer working. I am not sure why it ever worked...

**Comment by rstoenescu** [comment]
Because we switched to Fontawesome 5, which has breaking changes. From docs:

### Cheatsheet

| Name | Prefix | Examples | Notes |
| --- | --- | --- | --- |
| material-icons | *None* | thumb_up | Notice the underline character instead of dash or space |
| ionicons | ion-, ion-md-, ion-ios-, ion-logo- | ion-heart, ion-logo-npm, ion-md-airplane | Use QIcon instead of `<ion-icon>` component; Logo icons require 'ion-logo-' prefix |
| fontawesome | fa[s,r,l,b] fa- | "fas fa-ambulance" | QIcon "name" property is same as "class" attribute value in Fontawesome docs examples (where they show `<i>` tags) |
| mdi | mdi- | mdi-alert-circle-outline | Notice the use of dash characters |
