### ISSUE TITLE
[Request] Notify- Suggest allow to display html tag 

### ISSUE THREAD

**Issue by jamesYapKM** [quasarframework/quasar#2077]
I suggest allow to display html tag in Notify, currently the component is not allow to show html tag.

**Comment by rstoenescu** [comment]
Hi,

1. This would allow for XSS attacks, which from a framework perspective is a critical security flaw.
2. Notification messages should be short and concise. If you need to display more information you can add (as an example) a "Show More" button which could pop up a custom QDialog.

**Comment by ajcastro** [comment]
Hi @rstoenescu . I understand your perspective.
But there are also valid use-cases for adding html in Notify, like the ff:

1. Adding `<b></b>` or `<strong></strong>` for emphasis
2. Adding an anchor link `<a></a>`

I guess adding a button like "Show More" is quite overkill for those use-cases.
What if we can have a boolean option that can enable this feature so that it will not be a security flaw, 
and the developer should make sure to sanitize the data they bind.
`{ html: true } // default: false`
