### ISSUE TITLE
No parser error

### ISSUE THREAD

**Issue by Haixing-Hu** [quasarframework/quasar#2082]
### Problem

Execute the following command the create a new project:

```
$quasar init test
$cd test
$quasar dev

```

Get the following error:
```
error  in ./src/App.vue?vue&type=template&id=7ba5bd90
Module build failed:   Error: No parser and no file path given, couldn't infer a parser.
```

Is this a bug?

### Software version

Operating System        	Linux(4.15.0-20-generic) - linux/x64
NodeJs                  	8.10.0

Global packages         	
  NPM                   	3.5.2
  yarn                  	1.7.0
  quasar-cli            	0.16.1
  vue-cli               	2.9.3
  cordova               	You have been opted out of telemetry. To change this, run: cordova telemetry on.
8.0.0

Important local packages	
  quasar-cli            	0.16.1	(Quasar Framework CLI)
  quasar-framework      	0.16.0	(Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras         	2.0.1	(Quasar Framework fonts, icons and i18n.)
  vue                   	2.5.16	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router            	3.0.1	(Official router for Vue.js 2)
  vuex                  	3.0.1	(state management for Vue.js)
  electron              	Not installed
  electron-packager     	Not installed
  electron-builder      	Not installed
  @babel/core           	7.0.0-beta.46	(Babel compiler core.)
  webpack               	4.8.3	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server    	3.1.4	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin	3.2.0	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)

Networking              	
  Host                  	deep-learning
  enp0s31f6             	192.168.199.2
  vmnet1                	192.168.212.1
  vmnet8                	172.16.99.1

**Comment by rstoenescu** [comment]
Hi,

One thing to note: this is not a problem caused by Quasar.

Seems like a package called `prettier` has caused a regression in their latest release, which is affecting package `@vue/component-compiler-utils`.

Possible fixes until `prettier` maintainers release a new version:

1. If you are using NPM, then first try to delete node_modules AND package-lock.json, then npm install again. If this doesn't works, then:
```bash
npm install --save-dev prettier@1.12.0
npm run dev
```
2. If you're using Yarn add this to your package.json to force @vue/component-compiler-utils to use the right version:

"resolutions": {
  "@vue/component-compiler-utils/prettier": "1.12.1"
}
Then do a fresh install.

---
References:
* https://stackoverflow.com/questions/50555953/vue-webpack-template-missing-parser

**Comment by Haixing-Hu** [comment]
@rstoenescu   Thank you very much. You saved me a lot of time!
