### ISSUE TITLE
[Bug] QInput letters are cut off bottom: line-height fix needed

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2084]
On Safari and Chrome on 0 zoom in writing 'g's inside a q-input make them cut off on the bottom.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/3253920/40340018-ebb18128-5db7-11e8-89e5-4c7e2748969d.png">

The root of the problem seems to be that the `height` of q-input is set, but the `line-height` isn't.
Setting the line height fixes the problem.

I have created a pen with a fix button so you can compare it and see the fix:
https://codepen.io/mesqueeb/pen/XqGMMd

**Comment by nothingismagick** [comment]
Hey, thanks for opening the issue. I am not sure if this really fixes the problem. I just compared chrome and safari on mac, and depending on your screen scaling this becomes an issue - no matter if the fix is applied or not. So it seems you have just discovered an underlying rendering issue.

@rstoenescu - any idea how to resolve this?

![g-cropper](https://user-images.githubusercontent.com/35242872/40610082-36184522-6271-11e8-9a03-3242a44e0467.gif)

**Comment by mesqueeb** [comment]
On the iPhone all problems can be fixed by not setting the `line-height` but the `input height` by:
```css
.q-input-target {
  height: inherit !important;
}
```
### PRE FIX
  
![img_0052](https://user-images.githubusercontent.com/3253920/42816728-b8938d10-8a06-11e8-8a4c-b1a909d0d4b0.jpg)

### AFTER FIX

![img_0053](https://user-images.githubusercontent.com/3253920/42816735-c370a7e0-8a06-11e8-8ed9-efb226565765.jpg)

**Comment by rstoenescu** [comment]
Fix available in next 0.17 beta (which is through CLI v0.17.0-beta.20)
