### ISSUE TITLE
Pinch zoom event not available and q-context-menu identifies it as long press

### ISSUE THREAD

**Issue by darkscript** [quasarframework/quasar#2109]
### Software version

Quasar: 0.16.0
OS: 
Node: 8.9.0
NPM: 5.6.0
Browsers: Mozilla and Chrome (touch devices)
iOS:
Android: 7.1.1
Any other software related to your bug: No

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/darkscript/drpsehfx/11/

### What did you get as the error?
When you pinch (two finger event) to zoom, the context menu appears

### What were you expecting?
The context menu should not appear on top of map div unless a long press event is done

### What steps did you take, to get the error?
Try to do a pinch zoom on the map and the context menu appears
### More Description
When two fingers event is done on a component with q-context-menu as a child, the event is intepreted as long press (touch hold). I attached a video below which is more elaborate on a map component
https://www.youtube.com/watch?v=dWhwh5-JDSo&feature=youtu.be

**Comment by nothingismagick** [comment]
@darkscript - I have seen the video and can confirm that something *seems* wrong, but because you provide us with no information other than "it doesn't work", I will not speculate to the cause. 

Therefore, please update your issue according to the "new issue" template.

In this case it is absolutely essential to know everything about: 
- your environment
- the build target
- quasar components you are using
- other plugins that might be interfering
- link to a codepen that displays the behaviour

My advice: set breakpoints in your IDE or step through the execution stack in your browser developer tools. That should help to know more about what is capturing the long-click, which may reveal either a problem in your code or a regression in one of the components.

**Comment by darkscript** [comment]
@nothingismagick I did update the issue

**Comment by darkscript** [comment]
@nothingismagick come here and do a fix 😊

**Comment by darkscript** [comment]
@pdanpdan thanks for the fix

**Comment by rstoenescu** [comment]
Do not close until I merge it.
