### ISSUE TITLE
slots not working in material Qicon

### ISSUE THREAD

**Issue by ajayashuba** [quasarframework/quasar#2130]
please check this feature for me any content inside q-icon tag doesn't show up in output. The problem persists only with material icon
<script async src="//jsfiddle.net/akjsfiddle/k5tsu7ef/51/embed/"></script>

**Comment by rstoenescu** [comment]
Hi,

You need to understand how each icon library works. Material is the only one differing from the other ones, because the font itself is using ligatures. What this means is that the generated markup needs to be `<i class="...">icon_name</i>`, as opposed to `<i class="..."></i>` for all the other icon libraries. So having this limitation, Quasar can only offer you a way to inject a popup (QPopover, QTooltip) as content of the icon (for Material Icons only), besides the string being used for the ligature font, because these components are placed outside of the icon tag in the DOM structure. **Normally**, you should need to inject any content in it. An icon is an icon and shouldn't contain any content.

Should you have not ignored the issue template completely, I would have better explained this by forking your jsfiddle.

**Comment by rstoenescu** [comment]
Updating your initial description is not nice behavior. It makes following this thread really hard. That's why we have the ability to comment here.

You're totally disregarding my explanation. Please read it again. Google for ligature fonts to understand.

Thank you.
