### ISSUE TITLE
Autocomplete no best option highlighted by default.

### ISSUE THREAD

**Issue by lei-cao** [quasarframework/quasar#2149]
Hi, 

I think the new Autocomplete won't automatically highlight the first (best) option as the old version anymore. It can be seen here https://quasar-framework.org/components/autocomplete.html
So I can't just type Enter to finish the search which the user always does. I have to use arrow to choose first now. Is this something to add back? Thanks a lot.

![image](https://user-images.githubusercontent.com/136104/41227600-088ee538-6da8-11e8-95f3-e5d3b36129e9.png)

Cheers,
Lei

**Comment by jean-moldovan** [comment]
Current workaround `this.$refs.autocomplete.keyboardIndex = 0`. Maybe something that can be configured through props in future version?

**Comment by pdanpdan** [comment]
I think we'll leave this as it is now.
Reason:
- autocomplete does not restrict input to be one from the list
- we have improved kdb navigation that would select current option when navigate with UP/DOWN

- we have a list `['aaa', 'bbb']`
- we type `a`, in order to type `abc` => we would get `aaa` with no way to type `abc`
