### ISSUE TITLE
[REQUEST] Scrollable QTables

### ISSUE THREAD

**Issue by kerbo** [quasarframework/quasar#2247]
There should be an option to make QTables scrollable. Headers would remained fixed.

**Comment by pdanpdan** [comment]
The new QTable does not provide this option. If you need it you can pick it from v0.14.

**Comment by kerbo** [comment]
So you are suggesting I can copy the 0.14 code for QTable, rename the component and use it in my 0.16 based project? Is it as simple as copying the component file?

Aside from that, this capability still needs to be in QTable going forward. I'm surprised this feature was removed.

**Comment by rstoenescu** [comment]
@kerbo Hi,

Give it a go with `table-style` prop, like this in your Vue templates: `table-style="height: 400px"`
However, you won't get the fixed header. Unfortunately, having those sticky header/columns relies on too many things which the developer would need to do if they used scoped slots, so it’s not an option at the moment, sorry. We chose full table customization instead of this feature -- and we can't have both.

**Comment by kerbo** [comment]
How about a separate table component that doesn't have scoped slots. The table would work more like a basic HTML table. I have more use cases for this type of table than one that is highly customizable. In fact, while I haven't used the 0.14 table, maybe that component can be renamed and pulled into the current project as an alternative.
