### ISSUE TITLE
[0.17 beta]TypeError: nr.commit is not a function

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [quasarframework/quasar#2263]
### Software version

Quasar:0.17.0-beta.12
OS: Windows 10
Node:10.2.1
NPM:6.1.0
Browsers:Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
TypeError: nr.commit is not a function
### What were you expecting?
Expect no error
### What steps did you take, to get the error?
I have a seperate guard file for each route guard, I'm importing the store in my route guards files like 

```
import store from '../store/index'
```

Because I make commits from these guards like:

```
store.commit('loadingRoute', false);
```

I think the `nr` in  `nr.commit is not a function` error refer to the `store` that I'm importing.
Now if I run `quasar dev` everything working fine but when I build to SSR with the command `quasar build -m ssr -t mat` and run `npm run start` in the `\dist\ssr-mat` and navigate to a route that uses these guards I get this error, even though I've updated the `SRC/STORE/INDEX.JS` and `SRC/ROUTER/INDEX.JS` by following the instructions [here](https://forum.quasar-framework.org/topic/2481/quasar-quasar-cli-v0-17-aka-ssr-developer-preview)

When I console log the store I got a function, what should I do know please?

**Comment by rstoenescu** [comment]
Hi,

1. On SSR, the store needs to be created with a function due to the singleton issue. So you are exporting a function returning the new Store instance instead of the Store instance itself. Quote from Vue SSR docs:

> When writing client-only code, we are used to the fact that our code will be evaluated in a fresh context every time. However, a Node.js server is a long-running process. When our code is required into the process, it will be evaluated once and stays in memory. This means if you create a singleton object, it will be shared between every incoming request.
>
> [...], we are creating a new root Vue instance for each request. This is similar to how each user will be using a fresh instance of the app in their own browser. If we use a shared instance across multiple requests, it will easily lead to cross-request state pollution.

2. So, don't import the Store file as you would for non-SSR. Instead, use an app plugin which receives the `store` parameter, OR use `this.$store` inside Vue components. The Router needs same change as Store -- instantiation through a function, and the function takes `store` as parameter, in case you need it.

All this because the Store and Router are specific to each client and we need to avoid the singleton issue.
