### ISSUE TITLE
[0.17 beta 12 UMD] Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#2265]
I try to test 0.17 beta build.
I just replace 0.16 files to 0.17, but got error after page load:

```
quasar.mat.umd.js:23548 Uncaught TypeError: Cannot read property 'appendChild' of null
    at Object.install (quasar.mat.umd.js:23548)
    at quasar.mat.umd.js:1259
    at Array.forEach (<anonymous>)
    at Object.install (quasar.mat.umd.js:1256)
    at Function.$n.use (vue.min.js:6)
    at quasar.mat.umd.js:24208
    at quasar.mat.umd.js:10
    at quasar.mat.umd.js:11
```

This error located in block `var loadingBar = { ... }`
But when I try to reproduce error in Codepen, I have no error.
I download files from:

`https://cdnjs.com/libraries/quasar-framework/0.17.0-beta.12`

What I forgot when upgrading to 0.17?

**Comment by olegvakulenko** [comment]
It seems I found problem. In 0.16 I add scripts in head section. Is it now I must add all scripts in body section?

**Comment by rstoenescu** [comment]
Hi,

It's actually a bad practice to put script tags in the head because scripts are blocking the execution (and download) of everything (any type of resource) that comes after them. So yes, please do put the script tags for Vue and Quasar at the very end of your body tag.

Also, big thanks for testing the beta version! Note that beta.13 is coming tomorrow.

-Razvan
