### ISSUE TITLE
QSlider marker exceeds 100%

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#2268]
### Software version

Quasar: 0.16.4
OS: Ubuntu 16.04
Node: 9.4
NPM: 6.1.0
Browsers: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

### What did you get as the error?
When the `duration` is not exactly 15 seconds, the dev tools console will show a range error: `Range error: step must be a divisor of max - min 0 14.81 1 0`. This is ok, we can live with this. However, the slider markers looks like this in Chrome Elements:
```
<div class="q-slider-handle-container">
  <div class="q-slider-track"></div>
  <div class="q-slider-mark" style="left: 0%;"></div>
  <div class="q-slider-mark" style="left: 6.75584%;"></div>
  <div class="q-slider-mark" style="left: 13.5117%;"></div>
  <div class="q-slider-mark" style="left: 20.2675%;"></div>
  <div class="q-slider-mark" style="left: 27.0234%;"></div>
  <div class="q-slider-mark" style="left: 33.7792%;"></div>
  <div class="q-slider-mark" style="left: 40.5351%;"></div>
  <div class="q-slider-mark" style="left: 47.2909%;"></div>
  <div class="q-slider-mark" style="left: 54.0468%;"></div>
  <div class="q-slider-mark" style="left: 60.8026%;"></div>
  <div class="q-slider-mark" style="left: 67.5584%;"></div>
  <div class="q-slider-mark" style="left: 74.3143%;"></div>
  <div class="q-slider-mark" style="left: 81.0701%;"></div>
  <div class="q-slider-mark" style="left: 87.826%;"></div>
  <div class="q-slider-mark" style="left: 94.5818%;"></div>
  <div class="q-slider-mark" style="left: 101.338%;"></div>
  <div class="q-slider-track active-track" style="width: 100%;"></div>
  <div class="q-slider-handle" style="border-radius: 0px; left: 100%;">
    <div class="q-chip row no-wrap inline items-center q-slider-label no-pointer-events q-chip-pointing-down q-chip-square q-chip-pointing q-chip-dense bg-alerts text-white label-always">
      <div class="q-chip-main">14.8</div>
    </div>
    <div class="q-slider-ring"></div>
  </div>
</div>
```
As you can see, the last marker exceeds 100% and "bleeds over" into the next component.

### What were you expecting?
The last marker should not exceed 100%. Even though the last segment would be smaller than the other marker segments, this is fine.

### What steps did you take, to get the error?
```
          <q-slider
            v-model="currentTime"
            :min="0"
            :max="duration"
            label-always
            markers
            square
            :label-value="String(Math.round(currentTime * 10) / 10)"
          />
```
We are using the QSlider to show clips of video. The clips are usually around 15 seconds, but some are less than, for example 14.89 seconds.

As a work-around, I am adding this:
`style="max-width: calc(100% - 10px);"`

It kind of looks better, but not perfect as it never reaches the last marker at 100%.

I am also finding the label to be white text on very light grey, which is difficult to see:
```
<div class="q-chip row no-wrap inline items-center
  q-slider-label no-pointer-events q-chip-pointing-down
  q-chip-square q-chip-pointing q-chip-dense
  bg-alerts text-white">
  <div class="q-chip-main">1.0</div>
</div>
```
You can change the color of the slider, but not the label. :( You can see the `white-text` in the generated code above and the default background for .q-chip is: `background: #eee;`

**Comment by rstoenescu** [comment]
Hi,

No, this is not ok when you get the error. It means that the QSlider params are configured wrong and the component can't divide into equal length units.

In your example, we got a 14.89 interval, starting from 0, with a default step of 1. So QSlider shows the following markers: 0, 1, 2, 3, 4, 5, ..., 14... then 14 < 14.89 so it needs to show another marker: 14 + default step of 1 = 15, which will be > 100%.

Either:

1. Specify a step which you know it's going to divide any interval into equal length units. Beware that JS has some funky errors when dealing with floating points (https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript)

OR

2. Translate the model back and forth into something that can easily be managed and divided. Like 0-100 or 0-1000 etc, depending on the granularity that you want. Then use the label-value to actually display a timestamp instead of the 0-100 value.

  Example below. There are many ways to go, depending on your needs. This is just one.

  ```html
  <template>
    <q-sider
      v-model="currentPercentage"
      :min="0"
      :max="100"
      :label-value="currentTime"
    />
  </template>

  <script>
  export default {
    data () {
     return { currentPercentage: 0 }
    },
    computed: {
      currentTime () {
        // here we convert the percentage in a timestamp
        // for the QSlider label
        return convertFromPercentageToStamp(this.currentPercentage)
      }
    }
  }
  ```
