### ISSUE TITLE
[Bug] CSS of Floating buttons broken - v0.17.0

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#2321]
[https://quasar-framework.org/quasar-play/android/index.html#/showcase/layout-demo/floating-action-button](https://quasar-framework.org/quasar-play/android/index.html#/showcase/layout-demo/floating-action-button)
![photo_2018-07-25_14-27-47](https://user-images.githubusercontent.com/9668277/43217329-b2594dce-9017-11e8-9cc4-a3c5cedcfbf4.jpg)

### Software version
Quasar: 0.17.0
OS: -
Node: -
NPM: -
Browsers: -
iOS: -
Android: -
Any other software related to your bug:

**Comment by rstoenescu** [comment]
Another sleepless night..

This is a bug in the CLI due to weird webpack behavior regarding CSS files. The order in which CSS files were included was wrong. Fixed and will be available in Quasar CLI v0.17.1.

Leaving this open until I release this CLI version.

Reference for those interested: https://github.com/quasarframework/quasar-cli/commit/89d24937fcfe704591e0411e48fbc21e10b66035

**Comment by rstoenescu** [comment]
Released CLI v0.17.1
