### ISSUE TITLE
q-table conditional cell format 

### ISSUE THREAD

**Issue by JWDobken** [quasarframework/quasar#2326]
I would like to format values in a QTable according to their value and according to the documentation of QDataTable this should work:
```
<template>
    <q-table title="Table Title" :data="tableData" :columns="columns" row-key="name" />
</template>

<script>
export default {
    data: () => ({
        columns: [
            {
                name: 'desc',
                required: true,
                label: 'Dessert (100g serving)',
                align: 'left',
                field: 'name',
                sortable: true
            },
            {
                name: 'cals',
                required: true,
                label: 'Calories',
                align: 'left',
                field: 'calories',
                sortable: true,
                classes (value) {
                    return value > 300 ? 'bg-red' : 'bg-black'
                }
            }
        ],
        tableData: [
            {
                name: 'Frozen Yogurt',
                calories: 159,
            },
            {
                name: 'Ice cream sandwich',
                calories: 237,
            },
            {
                name: 'Eclair',
                calories: 262,
            },
            {
                name: 'Cupcake',
                calories: 305,
            },
            {
                name: 'Gingerbread',
                calories: 356,
            },
        ]
    })
}
</script>
```

Is there a way to make this work with QTable (which apparently replaces QDataTable)

Please take a look at the [JSFiddle](https://jsfiddle.net/jwdobken/peor79ak/16/)

**Comment by JWDobken** [comment]
I tried to make my first PR ever, but I unfortunately do not have the permissions. I found the request in `q-data-table` [here](https://github.com/quasarframework/quasar/issues/242).


I would implement it accordingly in `src/components/table/table-body.js`:

line 40:

    ...
    : h('td', { staticClass: col.__tdClass, class: this.getCellClasses(col, row) }, this.getCellValue(col, row))
    ...

Just before the `getCellValue` function (line 106):

```
getCellClasses (col, row) {
  if (typeof col.classes === 'string') {
    return col.classes
  } else if (typeof col.classes === 'function') {
    return col.classes(this.getCellValue(col, row))
  }
},
```

**Comment by rstoenescu** [comment]
Hi,

Use the scoped slots. It's what the power of QTable lies in. See examples in the docs.

**Comment by solovieff** [comment]
Using scoped slots means defining the columns in two places. Also, what about the performance?

**Comment by solovieff** [comment]
@rstoenescu do you plan to include this in v1 future releases? Writing slots is not always the best and always clearest way of doing this...

**Comment by ronfak** [comment]
Having only a slot approach to customize a cell is definitely a bad strategy.
It's fine in a lot of simple cases, but as soon as we try to do something a little more complex that's just going to fall and we see the whole limit in the Table component.

For example, in a grid that we want to customize (in the same way), let's say a boolean value, we need to create the slot template for as many columns as we need. This can easily get very big.
If the columns are created dynamically when we load the data, it simply becomes impossible to do so because we can not predict the column's name to create slot.

Allowing the classes property in the column definition to get a function, (like format does) would be perfect. Or allow the use of an external component as a renderer. Or simply a way to disable the html sanitization on the format function would have been enough to inject font icons or other .

For now, it's just good to display text in a standard way.
