### ISSUE TITLE
Unable to set default property of QRouteTab in nested QTabs.

### ISSUE THREAD

**Issue by sustained** [quasarframework/quasar#2395]
### Software version

Quasar: 0.17.6
Quasar CLI: 0.17.7
Quasar Extras: 2.0.4
Vue: 2.5.17
Vue Router: 3.0.1
VueX: 3.0.1
Vue CLI: 2.9.6
OS: Fedora 27
Node: 8.10.0
NPM: 5.6.0
Browsers: Chrome 66
iOS: N/A
Android: N/A
Any other software related to your bug: N/A

### CodeSandbox

- [Demo](https://y0z2mz4x99.codesandbox.io/#/issue-2395)
- [Code](https://codesandbox.io/s/y0z2mz4x99?module=src/pages/issue-2395/index.vue) (line `7`)

### What did you get as the error?

When using VueRouter's support for children of child routes and a secondary page-level `QTabs` (containing one or more `QRouteTab`s), the `default` property has no effect.

### What were you expecting?

The "Foo" sub-tab to be active by default, since `default` is set.

### What steps did you take, to get the error?

See the CodeSandbox.

### Image demonstration

![image](https://user-images.githubusercontent.com/5995080/43814108-94b9015c-9ac0-11e8-93f5-9c5779f7d352.png)

The "Foo" tab should be active (`default` property is present).

**Comment by rstoenescu** [comment]
Hi,

**QRouteTab does not (and should not) work with `default` prop**. What this property would do to QRouteTabs is that it would change current route on first render. This is definitely something you do not want because it would create a non-deterministic mess, very hard to debug. With further misusage your app might even get into an infinite route redirect loop. Components should not change current route on first render. You as a developer should be in control of the current route. QRouteTab's purpose is to only highlight the current route and change it on user feedback (click/tap). Does this makes sense to you?

**Comment by sustained** [comment]
Hmm, I'm not sure I understand fully but don't worry; I'll just read it a few more times after more coffee. :coffee:

What _is_ the best way to deal with this then, I wonder?

Now that I think about it, I suppose that making the "Testing" tab link to `testing/foo` is probably the simplest and cleanest solution?

That at least half-fixes the problem - the only remaining issue being if someone navigates to `.../testing` some other way.
