### ISSUE TITLE
About the time line component in small screen

### ISSUE THREAD

**Issue by Zhangshunyao** [quasarframework/quasar#2411]
The timeline is really amazing component！
Is there anyway to make it keep put the entry of timeline one left one right in the mobile device？
I know the design of it is to make more information showed, but sometimes, I think more user action will get user more fun

**Comment by smolinari** [comment]
What do you mean by one left one right? The time line itself?

Scott

**Comment by Zhangshunyao** [comment]
the line entry, in the small size of screen, all will be list in the right side automatically, in the bigger screen, the entry can be set to right or left of the line.

**Comment by smolinari** [comment]
That is what I thought you meant. 

As I understand the [QTimeline component](https://github.com/quasarframework/quasar/tree/dev/src/components/timeline), the CSS controlling the design is controlled by the screen size. Once the screen size goes below a certain breakpoint width, the timeline is formatted to "stick" to the right side version. To change that would take some major redesigning.

To be honest too, it doesn't look good very good with the text on the left and the time line on the right, because the text is right justified. Alternating the sides would look even worse IMHO. I played around with the component to demonstrate what I mean. 

![image](https://user-images.githubusercontent.com/3314957/43975522-45480418-9cde-11e8-8e57-dca9362aaf9b.png)

To me, I think this is one of those things, where we are going to have to be happy with the design decisions made by the developers. 😄 

Scott

**Comment by Zhangshunyao** [comment]
Thank you Scott, it's really so nice of you :)
What I mean is that when use the Timeline in **mobile device**, it can be displayed as in the screenshot attached. 
Even when user use a mobile phone, I don't want the window full of information, just leave some space with nothing, and user can scroll down to get more information.
<img width="677" alt="001" src="https://user-images.githubusercontent.com/33653539/43985448-182025d6-9d3a-11e8-8cc2-938cf41ef13d.png">

**Comment by rstoenescu** [comment]
If you mean that you don't want the QTimeline to be responsive, just update to latest Quasar (currently v0.17.8). It's no longer responsive by default.

**Comment by rstoenescu** [comment]
If on the other hand you want the QTimeline items to be only on one side of the line only, then use the `side` prop (and if on Quasar v0.17.8 then also add the `responsive` prop). Then for second & third breakpoints all your items will be aligned on that specific side of the line.

Did I understand correctly?

**Comment by Zhangshunyao** [comment]
Many thanks！
Thank you so much！
@smolinari @rstoenescu

**Comment by smolinari** [comment]
@Zhangshunyao - Thank you for the thank you. But, nothing has been done yet. From my (not so extensive) knowledge of Quasar and front-end development with Vue in general, I highly doubt the changes I made above can be done in client-dev land. 😄 It is a design decision within the QTimeline component. I might be wrong with that though.... 😊 

Scott

**Comment by Zhangshunyao** [comment]
@smolinari I have tested it and it just as you said. But I believe that the way you point out is the right and  the only way to get what I wanted. (change the setting of the default breakpoints)
Quasar is so powerful and really appreciated this great framework and great guys of you.

The request from mine that '_when use mobile device but timeline prop side also worked_' maybe not very reasonable, so I will follow the design of quasar now

:)
