### ISSUE TITLE
DataTable - exporting to CSV, excel, ... feature

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#244]

**Comment by colinmollenhour** [comment]
IMO this is better to leave up to server-side, perhaps just adding a UI button to trigger the request.

Also note in my experience for one data table UI I often need to export multiple different grids. E.g. one might be parent rows only and another might be one-row-per-child with some parent columns duplicated, etc..

**Comment by mesqueeb** [comment]
+1 for export

**Comment by purell** [comment]
@colinmollenhour I'm totally agree with you. 

If we look at the Datatable.js, a lot of transfer time is consumed because of the csv, pdf, ... export plugins. So it's better to leave up the server do the conversion and call the route on a top-bar button of the QTable.

**Comment by rstoenescu** [comment]
This will be left to an external Quasar plugin. There's going to be such a plugin system for v1.0 (after v0.15) that will allow the community to make their own Quasar plugins. Stay tuned.

**Comment by purell** [comment]
Most of existing plugin I tried like [tableexport](https://tableexport.v4.travismclarke.com/#tableexport) use the whole table to produce the xls(x) file. I tried them with the quasar QTable v0.15 but it does not work as expected. The QTable only draw the `computedRows` property that is holding the rows **only** for the current page instead of all rows.  

Looking at the `jquery.datatable`, even if we are looking the page 1/50, the exported files contains the rows of all pages.

I think we will have to create a quasar plugin from scratch without help of third party library. 

PS : Do we want the exported file to keep the same row order and row filter as we see ?
