### ISSUE TITLE
[Feature request] add large-list-solution

### ISSUE THREAD

**Issue by shawerestart** [quasarframework/quasar#2443]
memory and performance issue on super long list

when a make a cordova app or h5 app use quasar-framework
I often encounter a problem when i developing a web mobile chat app.
a super long list view will make performance down and crash in the end because of mobile phone memory problem.(i must make it like whatsapp or wechat)
will maintainer make a plan for super long list optimization? 
thanks!

**Comment by rstoenescu** [comment]
Hello,

I am unsure of what you are requesting. If in your app-space you use millions of DOM elements (exaggerating a little) how would this be an issue to raise for the framework that you are using? That's app-space stuff, not framework stuff, and of course any DOM element adds to the memory resources needed. So you, as a developer of your app, have the responsibility of thinking how to avoid stuffing millions of DOM elements in your page. Neither Whatsapp nor Wechat don't just throw all content into the page and expect it to render fast. That's why there are techniques like Infinite Scroll, Pull to Refresh or Virtual Lists.

A Virtual List component is scheduled for Quasar in v1.0 or v1.0+ (I opened a ticket here on Github describing it), but until then, you can check out https://github.com/Akryum/vue-virtual-scroller or https://github.com/tangbc/vue-virtual-scroll-list

Hope this helps,
Razvan
