### ISSUE TITLE
Group transitions

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#251]
Hi,
would be really useful to have transitions which can handle list of elements, not to create transition for every element.
E.g. having some list which is refreshed/element is added/removed we would just need to put all `<div class='item'>` inside `<q-transition-group>`

What you think?

**Comment by rstoenescu** [comment]
Basically you can work this out with Vue's `<transition-group>`.

`<q-transition>` is going to get removed at some point in the near future. Only made it because its default animation is only achievable with Velocity and not through CSS-only. So I wouldn't put too much dev time into this just to remove it later on.
