### ISSUE TITLE
q-toggle & checkbox emit both events "blur" & "focus" in the same time

### ISSUE THREAD

**Issue by Abdelaziz18003** [quasarframework/quasar#2548]
### Software version

Quasar: 0.17.12
Quasar-cli: 0.17.15
OS: Linux(4.15.0-34-generic) - linux/x64
Node: 10.7.0
NPM: 6.0.2
Browsers: Firefox 62

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/waugrryy/6564/

### What did you get as the error?
both events "focus" & "blur" are triggered in the same time when checkbox gains or loses focus.

### What were you expecting?
I am expecting:
- @blur | Triggered, when Checkbox loses focus.
- @focus | Triggered, when Toggle gains focus.

### What steps did you take, to get the error?
1. assign two different methods to @focus & @blur events
2. Check the checkbox or the toggle.
3. both methods are executed in the same time.

**Comment by pdanpdan** [comment]
It looks like the events are correct:
- when using keyboard navigation you get focus and blur when you get the control in focus and when you blur it
- when using mouse/touch to click you get them focus+blur because that's what's happening - you can test it by trying to press ENTER after you click the control - nothing happens - then press TAB/SHIFT+TAB and you'll see the focus event
