### ISSUE TITLE
Quasar v0.17.15 Web Storage API bug

### ISSUE THREAD

**Issue by metalsadman** [quasarframework/quasar#2581]
After upgrading to Quasar v0.17.15 & CLI v0.17.18, **$q.localStorage** is not pointing to **LocalStorage** but on **SessionStorage** instead, **$q.sessionStorage** is not working as well gives "Cannot read property 'set' of undefined" if I use its functions.

**Comment by nothingismagick** [comment]
Can you please give us full details about this issue including `quasar info` and what you are specifically building?

**Comment by rstoenescu** [comment]
What you are describing is not possible.
Describe your environment (`quasar info`) and also do a jsfiddle -- because the devil is in the details.

From your initial description, my feeling is that it's a user error on your part but I cannot correct any mistakes if I don't have a reproducible environment.

**Comment by metalsadman** [comment]
Sorry for the missing details.
Quasar: v0.17.15
OS: Windows 7
Build: SPA/Cordova
Android: 5.1
Browser: Chrome/Chromium

Here's the codepen:
[https://codepen.io/metalsadman/pen/zJMERY](url)

This is not how exactly I implemented it but it's close as an example.
