### ISSUE TITLE
QInput and lower-case --> cursor jumps to end when holding SHIFT key

### ISSUE THREAD

**Issue by tandrew** [quasarframework/quasar#2647]
Found an interesting bug which I could not find already reported.

It seems when using a QInput field and the "lower-case" attribute then when you mark a piece of text in the input field, then hold the SHIFT key and try to enter a value, the cursor jumps to the end of the field.

Check out the GIF and fiddle.

Other than that: AWESOME framework. Love it!

![oct-01-2018 18-07-48](https://user-images.githubusercontent.com/8017453/46300821-f75a5180-c5a4-11e8-8608-08758eb79f15.gif)

### Software version

Operating System                Darwin(18.0.0) - darwin/x64
NodeJs                          8.11.1

Global packages
  NPM                           6.4.1
  yarn                          Not installed
  quasar-cli                    0.17.19
  vue-cli                       3.0.0
  cordova                       Not installed

Important local packages
  quasar-cli                    0.17.19 (Quasar Framework CLI)
  quasar-framework              0.17.16 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.6   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.19.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.8   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.5.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

Browsers: Safari 12.0 (14606.1.36.1.9) / Chrome 69.0.3497.100

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/tandrew/mvqy7pur/

### What did you get as the error?
The cursor jumps to the end on entry when the field is set to lower-case only and you hold the SHIFT key on entry of letters.

### What were you expecting?
Was expecting that it would just accept the lower keys and not jump.

### What steps did you take, to get the error?
Happens when lower-case attribute is used in QInput.

**Comment by Narmer23** [comment]
No need to press SHIFT, this behaviour happens whenever you type something in between the value in the input box, [because setting the value moves the cursor to the end of the text](https://www.the-art-of-web.com/html/input-field-uppercase/). A possible solution, which can be seen in the linked page, is to store the position of the cursor before applying the upper-case or lower-case and resetting it immediately after.

**Comment by rstoenescu** [comment]
Hi,

We're currently under heavy load with v1, which I recommend to upgrade to as soon as possible.
If your business requires this fix in 0.17, let me know. But just to paint the bigger picture: fixing this for 0.17 requires a whole great deal of effort, so please make sure that you really really need this otherwise it is very detrimental to Quasar to halt working on v1.

Thanks.
