### ISSUE TITLE
date.formatDate function returns -1 day on format 'DD-MM-YYYY'

### ISSUE THREAD

**Issue by arieltoledo** [quasarframework/quasar#2658]
The date is saved well in the database but when I try to format it to show it the date.dateFormat () function subtracts one day. Lets say today its 2018-10-04
` data () {
    return {
      visit: {
        date: date.formatDate(Date.now(), 'YYYY-MM-DD'), description: '', weight: ''
      },
}`
 then
`this.visit.date = date.dateFormat(this.visit.date, 'DD-MM-YYY')` will return 03-10-2018

Im on gmt-3 and this its working good.

**Comment by rstoenescu** [comment]
Hi,

This is related to JS Date() Object and some issues with it. In your case it takes into account local timezone when it gets parsed.

**What you should do is**: use `/` as separator instead of `-`.

Good example: 2018/10/05
Bad example: 2018-10-05

Reference for further reading: https://jj09.net/javascript-date-a-bad-part/
