### ISSUE TITLE
QList doesn't work properly with transition-group

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2724]
Hello!

Quite often you may want to animate items in the list (adding/removal new item) by wrapping them inside `transition-group`.

If you put `transition-group` inside QList some props does not seem to be working: `separator`, `dense`, `sparse`.

Example:
https://jsfiddle.net/pr3jdsux/

NOTE: I didn't add logic related to list animation to the fiddle because I think it's not relevant.
Basically QList with `transition-group` should be rendered smae as it does without.

Thanks!

**Comment by rstoenescu** [comment]
Hi,

This is because `transition-group` is an element itself, so breaking QList expectations on the content, while separator, dense, sparse etc are being applied with CSS selectors. Rather than using "dense" and "sparse" on the QList, use these on the QItem directly. In v1.0 there will also be a QSeparator component (usable anywhere, not connected to QList and QItem specifically).
