### ISSUE TITLE
Maximized modal not closing anymore

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#2728]
Hello,

I have just upgraded from 0.16 to the latest 0.17.17 and noticed that maximized modals do not close anymore with the Escape key, nor do they close with a click outside of the modal when the modal is maximized with a top/right/left/bottom position. `no-backdrop-dismiss` and `no-esc-dismiss` have no effect.

Tested in Chrome version 71.0.3578.30 (Build officiel) beta (64 bits) on Windows 7. I went back to 0.17.15 and it works again.

I was able to reproduce in a new project, as simple as

```
<template>
  <q-page class="flex flex-center">
    <img @click="open=true" alt="Quasar logo" src="~assets/quasar-logo-full.svg">
	<q-modal
		maximized
		:no-backdrop-dismiss="false"
		:no-esc-dismiss="false"
		position="top"
		v-model="open"
	>hey</q-modal>
  </q-page>
</template>

<script>
export default {
  name: 'PageIndex',
  data () {
	return {
		open: false
	}
  }
}
</script>
```

Thanks for the great work on the framework anyway.

**Comment by rstoenescu** [comment]
Hi,

"position=top" has precendence over "maximized". But the real thing is that it doesn't makes sense to use position and maximized.. because the Modal can either be maximized or positioned on one of the four directions. Are you doing this because of the animation? If so, you should create a Vue transition for it and use the Modal prop.

However, on v1 there's going to be a LOT of predefined transitions that you can use out of the box.
Gonna close this BUT feel free to reopen if I am missing something!

-Razvan
