### ISSUE TITLE
NW.js support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [quasarframework/quasar#2745]
**Benefits of NW.js over Electron:**
* Supports twice as many OS's including back to OSX 10.6 and XP (via NW.js 0.14.7 LTS)
* Actually cares about proper Linux support
* Allows for protected source code (Huge deal as almost all for profit software is closed source)
* Backed by Intel
* Updated within 24 hours of a Chromium or Node release, where as Electron routinely ships with already outdated versions of both, sometimes by half a year. This is very bad from a security standpoint.
* Still a resource hog, but uses less RAM and disk space than Electron
* Smaller distribution sizes (it's possible to get a Windows installer down to ~25MB)
* Been around 5 years longer/used by thousands of projects
* Requires almost no boilerplating because it assumes you want to create a desktop app, and not a node script with an optional UI.
* Super easy to get started with and a no-nonsense API
* `nw-vue-devtools` package always uses the latest Vue DevTools code (where as the Electron version is only updated periodically)

The main benefit of Electron over NW.js is ecosystem. However, users of Quasar for the most part are shielded from needing to worry about this. NW.js wins out from a technical perspective in almost every other category (smaller, faster, more efficient, better OS support, faster updates, more features, etc.). When given a choice and the same amount of effort is required of them, it seems like a pretty easy choice. I don't see people picking Electron over NW.js for any reason other than name recognition, ignorance of the differences, or maybe some very specific edge case. Most users would have a better outcome with NW.js from it's smaller footprint, better security, wider platform support, and access to latest dev features.

**Comment by julijane** [comment]
I agree with almost every point mentioned, the fast updates probably being the most important. I would love to see NW.js in quasar, as I would love to use quasar but can't right now because I decided to use NW.js for the reasons mentioned above.

I'm not fully satisfied with NW.js though, some things are rather cumbersome like the file dialogs which are piggybacked on the normal file input element and require some ugly code to use (and don't offer a easy way to determine if the user has canceled the dialog).

But in general NW.js is great and I would love to see support in Quasar. NW.js is simple to use and build for. I recommend against using the available solutions like nw-builder or nw-builder-phoenix because frankly they all suck. But building a NW.js app is easy. It is basically putting a generated package.json, a (optional) background.js and the web app itself into a zip archive and then either ship it along with the nw.js binary+libs or append it to the nw.js binary. For my own purposes I have implemented my own packer and builder and it should be easy to do something like this for quasar.

I'm not familiar (yet) with the quasar internals, so I don't know how to add a new build target, but if someone with the knowledge can help, I'm more than willing to contribute code or whatever.

**Comment by TheJaredWilcurt** [comment]
@julijane 

**Quick tip:** Toss your app files into a `package.nw` folder with the `package.json` at the root of it, then place the `package.nw` folder next to the `nw` executable. Launching the executable will automatically run your app. If you do the zip or append methods for packaging the application it causes longer start up times because it has to unzip to a temp folder and run the app from there.

**Comment by fansanelli** [comment]
Dear @TheJaredWilcurt  @julijane 
Quasar team is currently working on an integrated testing solution and I have a webdriverio based project that is able to keep the same test-base for all the modes that quasar framework supports namely: browser, Cordova and electron. I hope/think that in future will be mandatory to have the webdriver support sorted before to merge a new mode, like nw would be. If you truly wants to work on this can you please investigate also about this? You can ping me if you need help on this part.

**Comment by julijane** [comment]
@fansanelli I'm not sure what to make out of your comment but please be advised that the sdk variant of nwjs comes with chromedriver support.

**Comment by fansanelli** [comment]
@julijane this would probably make things easier.. about my comment, I just wanted to point out that quasar is weak on testing now, but we want to add jest, webdriver and other testing capabilities. Before to merge a new mode in near future may become a requirement to also make the testing working on it. I am happy to see interest adding new modes and I hope to see a pr sooner than later to add nw

**Comment by rstoenescu** [comment]
Adding this to the todo list. Based on the funding that we have this will see the light of day or not... Unfortunately, this is how things stand at the moment. Sorry for any inconvenience.

**Comment by TheJaredWilcurt** [comment]
## Workaround:

1. `git clone https://github.com/nwutils/nw-vue-cli-example`
1. `cd nw-vue-cli-example`
1. `npm install && npm start`
   * This will run the basic desktop app
   * Close it and kill the webserver
1. `npm install -g @vue/cli && vue add quasar`
1. Good luck

You'll also need to do stuff like this if you want to have your NW.js code live in the same codebase as your web version:
```js
if (window.nw) {
  let fs = window.nw.require('fs');
  let data = fs.readFileSync('file.txt', 'utf-8';
  console.log(data);
}
```
