### ISSUE TITLE
Calculate q-popover from right

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#2768]
Hi,

I'm wondering if you could add the ability to calculate the q-popover's position from the right rather than left?

As an example: 
I have a popover as such.
![image](https://user-images.githubusercontent.com/13761766/48818458-8c0c4f00-ed9f-11e8-83ef-6c3f0e466bc3.png)

When I click on one of the items, the popover expands, however because it's CSS position is calculated from the left, this happens:

![image](https://user-images.githubusercontent.com/13761766/48818502-b4944900-ed9f-11e8-8f2e-c8bf9428fe01.png)

I have tried overriding the CSS so that:
`left:0; right: 50px;`

However it's a hack solution and I'd prefer if the right position was actually calculated from the divs's actual position from the right.

Cheers

**Comment by rstoenescu** [comment]
Hi,

This sounds like a UX issue on your app rather than a Quasar issue. Can't just change alignment to use "right" instead of "left" because that potentially breaks other people's apps.

What I suggest is using a horizontal scrollbar on your Popover, or find some way so it doesn't need more horizontal space than a mobile screen width. Lastly, it would help us both if you reopen this ticket with a jsfiddle as required by the github issue template.
