### ISSUE TITLE
Modal layout breaks when wrapping with <form> tag

### ISSUE THREAD

**Issue by toymachiner62** [quasarframework/quasar#2784]
As discussed in this thread https://forum.quasar-framework.org/topic/2930/what-s-the-proper-way-to-use-a-q-modal-layout-with-a-div-slot-footer-along-with-a-form-tag/11 the `q-modal-layout` breaks when using a `<form>` tag along with a `<div slot="footer">` tag

**Comment by rstoenescu** [comment]
Way to do it: https://jsfiddle.net/rstoenescu/sza3qncg/4/

Few comments:

1. Quoting you: "So is quasar promoting not doing things correctly and breaking accessibility?" and "my suggestion/recommendation to address things like this in the quasar framework" --> No, Quasar was actually the first Vue framework working on accessibility. We take great pride in the components being accessible.

2. This confusion of yours comes from the fact that you are misunderstanding the concept of a slot. You're using slot="footer" yet you wrap it with a DOM element (`<form>`). Slots are strictly connected to the component upon which you are using them, and it's equivalent to saying: "hey, component X, this slot needs this content" then the component fills its own template (not your template!) with the indicated slot content. So, wrapping a slot with an element makes no sense... because it's a slot, it's not content that you can wrap or place in a specific DOM tree of your choosing for the component --- the component decides where to put it.

3. Finally, some thing that you should be aware of regarding your comment "Vue doesn’t promote this behavior and neither should quasar": You are operating with Vue components, not native form elements. `<form>` is designed for native form elements. In any case, this is not to be taken as "Quasar components don't work with `<form>`", because QInput, QButton (which actually even has a "type" prop: submit, reset, ...), ... do work. But just be aware these are components, not native form elements.

-Razvan
