### ISSUE TITLE
A wrapper for form components that can decorate all form elements inside

### ISSUE THREAD

**Issue by mkhanal** [quasarframework/quasar#2787]
## Feature request

It would be nice to have the capability to manage multiple form elements from a single wrapper/decorator element.

Example:
A form that is editable by users with the edit rights but not for someone with view only rights.

```
<q-fieldset :allElements={'readonly':viewOnlyRights, ...more decorations}>
  <q-input1...>
  <q-input2...>
  <q-input3...>
</q-fieldset>
```

or 
```
<q-fieldset :readonly="viewOnlyRights">
  <q-input1...>
  <q-input2...>
  <q-input3...>
</q-fieldset>
```

The first one is flexible and also helps remove conflicts between properties that can be applied to the form or the individual wrappers, whereas the second one is less verbose.

### Existing alternative
A close alternative is to use a "fieldset" html tag to wrap the elements. However, the attributes of a fieldset are very limited. While disabled works on a fieldset, attributes like readonly don't.

### Helps

1. Treat/Manage the whole form as a single entity
1. Apply role rights management at a higher level
1. Simple central state managed form states

**Comment by Zebirdman** [comment]
this would be massively useful, +1

**Comment by nothingismagick** [comment]
I also sometimes find myself using a wrapping form element to do things like turn off autocorrect and autosuggest. I don't think q-form will land before we go to RC (unfortunately I dropped the ball on this one, sorry everybody), but it is something the core team really wants Quasar to have and we will be bringing it in sooner rather than later. Stay tuned to this thread for updates.

**Comment by rstoenescu** [comment]
Due to performance constraints this will not get implemented. Sorry for any inconvenience.
