### ISSUE TITLE
QChip with QTooltip

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#2816]
QTooltip display only when hovering on content, not all QChip shape.

https://jsfiddle.net/c5649zsq/

**Comment by smolinari** [comment]
Hey Oleg. 

There are a few instances where components don't play right with QTooltip, simply because they weren't designed for, or thought of having, Tooltips. 😃 QChips is one of them. 

You can get around this though. Check out this new Chip-Tooltip component. 

https://jsfiddle.net/smolinari/4eaf7o2u/

Scott

**Comment by metalsadman** [comment]
give the div wrapper one of the **inline** style display, coz tooltip will display in the center of the page rather than the component.

**Comment by smolinari** [comment]
Interesting. In Chrome it works as it should. display: inline brings the button up to the same line. I'm terrible at css. I've used inline: table and it seems to work.

Scott

**Comment by rstoenescu** [comment]
This will get fixed. Thanks for reporting.

**Comment by rstoenescu** [comment]
Fix available in 0.17.19
