### ISSUE TITLE
Can the route jump of QBtn component with “to” attribute be changed?

### ISSUE THREAD

**Issue by 941477276** [quasarframework/quasar#2870]
Quasar: 0.17.18
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
At present, the route jump mode of QBtn of quasar is controlled by js:
```
const go = () => {
  this.$router[this.replace ? 'replace' : 'push'](this.to)
}
```
Sometimes I want to click on QBtn and open the page in a new window. At this point, I will add a target="_blank" attribute to the QBtn component.for example:
`<q-btn to='/login' color="primary" label="to login" target="_blank">`
But this is not valid in QBtn because quasar has cancelled the default click event for the "a" tag
### What were you expecting?
Do not block the default event when clicking the QBtn button with the "to" attribute

**Comment by panstromek** [comment]
You can achieve this by using:
`<q-btn type="a" href="/login"  target="_blank" label="to login"/>`

The problem is that Vue router just emulates navigation in current tab by "masking" default browser behavior. You try to handle broswer action with it. `to="/login"` is command for Vue which only lives in current window/tab, while `target="_blank"` is command for browser.

If you want to open new window/tab, there is no longer need to handle this by Vue router, everything starts from scratch in there.

Hope this helps ;)

**Comment by rstoenescu** [comment]
Opening in new window:
`<q-btn tag="a" href="...url..." target="_blank" ...rest.of.props.. />`

**Comment by panstromek** [comment]
@rstoenescu It's `type="a"`, not `tag="a"` ;)
