### ISSUE TITLE
[BUG] Only in iOS Device, the footer float on scroll and block view

### ISSUE THREAD

**Issue by mamcx** [quasarframework/quasar#2882]
This is a problem that we only observe so far on a actual iOS device (like: https://imgur.com/a/Qth2Ald) but not emulator or other targets.

Is even worse the larger is the device (ie: In a iPhone SE is less bad, in iPhone 8 Plus make the UI non-usable)

### Software version

Quasar: v0.17.18
Browsers:
iOS: iOS 12+

### JsFiddle
https://jsfiddle.net/mamcx/7tg3c8nj/4/

### What were you expecting?

The footer to stay at the bottom without move.

### What steps did you take, to get the error?

To reproduce, use an actual iOS device. Emulator not work.

Scroll **after try to write something in the search box**. Scroll to the bottom and bounce back using the fingers. The toolbar in the footer will start floating and blocking the screen.

**Comment by rstoenescu** [comment]
Hi,

This is due to the awfully buggy iOS webview. Please try to install https://github.com/apache/cordova-plugin-wkwebview-engine to replace the default webview.

When keyboard shows up on screen, "position: fixed" will heavily misbehave. There's nothing that we can do. It has been reported a thousand times to Apple, yet they still refuse to fix this. So use the engine above.

Thanks.
