### ISSUE TITLE
Unable to TAB through QBtns on Safari desktop

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#2906]
Hello!

When on latest desktop Safari (v12.0.2) tabbing through QBtn elements does not seem to be working.

See: https://jsfiddle.net/209r8zjo/
1) Press Tab
2) Input is focused, button is not

Works fine on Chrome.

Thanks!

**Comment by rstoenescu** [comment]
I'm using Version 12.0.2 (14606.3.4).. I get tab focus alright...

**Comment by jean-moldovan** [comment]
Safari Version 12.0.2 (14606.3.4) macOS Mojave 10.14.2

**Comment by jean-moldovan** [comment]
Chrome & Firefox are both fine

**Comment by rstoenescu** [comment]
Exactly same OS here too.. can get tab focus right. This is something really simple, getting managed by browser through the "tabindex" attribute...  if it fails then it means it's a P0 critical issue of the browser. It's out of Quasar's reach...

Please reopen with a more specific case. Otherwise can't reproduce and we're not going anywhere with this issue :)
