### ISSUE TITLE
building a community

### ISSUE THREAD

**Issue by dkebler** [quasarframework/quasar#292]
All my favorite open source projects have at least one of these going.   
There is no way currently to get input, share code, get mutual support etc.  Github issues is not the place.

Suggestions any or all.
1. Start a Gitter
2.  Run a docker instance of discourse in an aws linux instance (or other docker host).  
     https://github.com/discourse/discourse_docker
     my favorite static site builder Hugo has an active one https://discuss.gohugo.io/
3.  Make a tag "quasar" at stackoverflow and follow it.

If I had a project of this scope I'd do at least 2 and 3.

This is a great project.  The docs are good.   I am already supporting another developer at patreon and I'd help you out but only if there is active community support and a good place to do that.  For example I would like to take quasar and put it together with a feathersjs socket app and would like some mutual support to pull that off.

---
fyi, I have a ubuntu instance running at AWS that could easily host discourse for you but for new AWS accounts you get a year of free micro instance which should be plenty enough to run discourse.

**Comment by Async0x42** [comment]
For point #1 at least, there is a gitter room @ https://gitter.im/quasarframework/Lobby

I know there's a forum link on the main homepage, perhaps it should be changed to 'community' and then have various places for collaboration? stackoverflow / forums / gitter links

**Comment by smolinari** [comment]
Hi David,

You are definitely right in that such a project like Quasar lives and dies with its supporters/ community. 

Though, somehow you missed the forum. 😜  

http://forum.quasar-framework.org/

The link to the forum is front and center and on top of the[ project's homepage](http://quasar-framework.org/). It is also mentioned clearly in the [README.MD for Quasar](https://github.com/quasarframework/quasar). Just pointing that out to show it shouldn't be easily missed. I can only think you are really new to the community. It is nice to see Quasar can get someone so excited to make such a suggestion without even looking a bit deeper. 😄 

For 3. Since there is a dedicated forum, the SO tag would be ok, but spreading the community out isn't necessarily a good thing right now. To me, it ends up watering down a community and it causes extra work. I'd say the SO tag is something to attack, when Quasar has established itself and there are more contributing team members to cover the multiple bases (i.e. Github, Gitter, the Forum, writing documentation, programming new stuff, fixing bugs....you get the point). 

Currently, gaining traction among developers is the name of the game for Quasar. I believe, the best thing that could happen to gain traction best is to add an SSO for Github user to sign in to the forum to make the registration process much quicker. This has been asked for before, but is low on Razvan's todo list currently, as he (and hopefully @CookieJon?) are working hard towards 1.0.

The next thing is just spreading the word. If you are a user and somewhat a fan of Quasar, tweet or post on FB about new stuff (like the current 0.12 release!). Write blog articles explaining what you've learned or what you like about Quasar. Go to other communities related to Quasar's technologis (not its competition!) and mention it. Oh, and of course, contribute to the community and Quasar too. 

For instance, I write articles for [Sitepoint.com](https://www.sitepoint.com/). Once Quasar goes 1.0, I'll be writing up an article about creating an application with Quasar, but before that, I'll be writing up an example app and also build it out to be a tutorial. I need to do the example app, because I am learning and I also need the experience to be able to explain the work properly. 😄 I believe that contributing to a community, even if it is a suggestion, requires some work in learning or research of the subject and/ or a lot of experience. When that is given, the contribution has a lot more value. 👍   

Scott

**Comment by dkebler** [comment]
ah duh...totally missed all the links....now I see them top of guide toolbar, and a link in the gitub readme.
Maybe in the very opening "Getting Started" mention right there a forum and gitter exist and the links are above

**Comment by dkebler** [comment]
per @smolinari  you should encourage this fellow do you a video like he did for vuejs2.   He's good.  I got an excellent quick start on vue from him which then led me to quasar.   
https://www.youtube.com/watch?v=z6hQqgvGI4Y&t=1224s

**Comment by rstoenescu** [comment]
@smolinari Scott, you heard what the people want. We must concede to this idea. Quasar tutorials/courses from you :D
