### ISSUE TITLE
q-input text-align center not work even add width with css

### ISSUE THREAD

**Issue by sonygod** [quasarframework/quasar#2963]
q-input text-align center not work even add width with css

```
<template>
  <div>
    <q-input type="number"   class="myInput" max="10000" min="0"/>
  </div>
</template>

<style lang="stylus">

  .myInput
    width 500px
    text-align center


</style>
```

what's wrong with my code ?

**Comment by BboyAkers** [comment]
have you tried putting it in a container and then a row? Also text-align: center will only center the text inside the input. If you want to center the element reference this. https://quasar-framework.org/components/layout.html . If  i'm not mistaken quasar is using flexboxes for the grid so look into flexboxes instead of margin, or text-align to center elements.
`
<template>
  <div class="layout-padding">
    <div class="row">
            <q-input type="number"   class="myInput" max="10000" min="0"/>
    </div>
  </div>
</template>

<style lang="stylus">

  .myInput
    width 500px
    text-align center


</style>`

**Comment by sonygod** [comment]
@BboyAkers ,have you test your code ? not work .

**Comment by BboyAkers** [comment]
@sonygod I wasn't able to. I typed out my answer on my phone. Sorry about that

**Comment by JayeshLab** [comment]
As q-input wrapped the input component, so you need to add the text-align: center to .q-input-target which is the class of the input.
```
.myInput .q-input-target
{
    text-align: center;
}
```

**Comment by nothingismagick** [comment]
agreed. this is not a problem with quasar but with devland CSS
@rstoenescu - please close
