### ISSUE TITLE
QDatetime date picker arrows not working (browser compatibility)

### ISSUE THREAD

**Issue by usu** [quasarframework/quasar#3076]
### Software version
Quasar: 0.17.19
Browsers: Samsung Internet 8.2.01.2

### JsFiddle
https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/datetime/datetime-input

### What did you get as the error?
For date picker, forward and backward arrows are not working in Samsung Internet browser on Android. Clicking on arrows has no effect, picker stays in the same month.
Reproducible with official demo on https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/datetime/datetime-input

Will try later to check, whether an error is thrown on the console.

**Comment by rstoenescu** [comment]
Hi,

We're currently under heavy load with v1, which I recommend to upgrade to as soon as possible.
If your business requires this investigation + fix in 0.17, let me know. But just to paint the bigger picture: investigating + fixing this for 0.17 requires a whole great deal of effort, so please make sure that you really really need this otherwise it is very detrimental to Quasar to halt working on v1.

Thanks.
