### ISSUE TITLE
Suggestion - Data Source Component

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#3237]
It would be really great if Quasar team would create a "DataSource" component as a middle man between Data coming from outside and Quasar components that uses data like Table, Input, editor, Label and etc. (basically any component that can read/write data).

This way if we use a REST data service via Axios, our datasource will be fed by Axios. Or if we use data from Firestore, the datasource will be fed by Firestore. And none of the components need to connect directly to Firestore, we just connect to the datasource and get/set data by supplying collection name, Document ID and property.

This way, if we need to do local testing, we can switch from Firebase to local data.
Thanks!
..Ben

**Comment by panstromek** [comment]
...this would probably be good candidate for an `app-extension` 😉

**Comment by BenHayat** [comment]
> 
> 
> ...this would probably be good candidate for an `app-extension` 😉

Does Quasar V1 provide that capability to create extensions?

**Comment by panstromek** [comment]
Yes, there are already two `@quasar/testing` and `quasar-ide-helper`, one is in the making - with an article coming soon ;)

**Comment by BenHayat** [comment]
Excellent.
I'm also suggesting Quasar to friends that are new to Vue and Quasar. We need at least one CodeLab or tutorial that takes a person through steps to build app.

For example, this Codelab teaches you a lot and you get up and go. We need something like this to get people started with Quasar.

https://codelabs.developers.google.com/codelabs/firebase-web/index.html?index=..%2F..index#0

**Comment by Jeremywhiteley** [comment]
Yes!  A Datasource component and a Codelap Tutorial would be very helpful in getting new users up and running!

**Comment by qyloxe** [comment]
I'm not sure that something like this, should have a form of a component. Maybe rather a library or extension. The use case is of course presentation, but in Vue/Quasar we have vuex so anything "data related" should have some kind of integration with vuex. Vuex have its own quirks. The main one is nested structs and nested setters and nested observables. There is on VERY interesting solution, which uses a normalization of nested data structs:

https://vuex-orm.github.io/vuex-orm/guide/prologue/what-is-vuex-orm.html

It is quite useful, because you have in one library the data layer, data models, validation, queries, possible synchronization and integration with vuex and UI part. This integration part is interesting, because one could work with offline data using indexedDB and this vuex-orm.

I'm not saying that something like this should be a default and only one data access method for Quasar UI components - of course not - but if anyone would propose to have one, and only one "saint" solution to data access, something like this vuex-orm would be quite OK. I'm totally against "DataLayer components" as in ancient ideas of Delphi or Visual Basic/early .NET.

**Comment by nothingismagick** [comment]
Please close this issue. It should be an app-extension because that is why we have it. There are way too many edge-cases for a data-source component to cover. And it doesn't have to be vuex, it could also be apollo-link-state or even localstorage based.
