### ISSUE TITLE
[v1]QBtnDropdown - The scroll bar is not on the right-most side

### ISSUE THREAD

**Issue by QQ34205037** [quasarframework/quasar#3284]
### Versions and Environment
**Browsers:** Chrome 72.0.3626.96
**OS:** Mac OS 10.14.3

### Reproduction Link
https://v1.quasar-framework.org/start （The dropdown menu on the right side of the toolbar,the "Support" menu has this problem, the "v1.0.0-beta.1" menu and the "Quick Link" menu have no problems.）
or
https://codepen.io/qq34205037/pen/BMqpBW?editors=1010
#### step 2.Do not close the dropdown menu and resize the window
![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/quasar/q-btn-dropdown-3.png)

**Comment by mountash** [comment]
The problem is that CSS styles are not integer numbers
![bug](https://user-images.githubusercontent.com/6277925/55933257-5de7b880-5c35-11e9-9086-5e95e36f01dc.gif)
after changing that to integer all looks good
![ok](https://user-images.githubusercontent.com/6277925/55933293-8a033980-5c35-11e9-82dc-7b2bb24e190f.gif)

PR #3854 created

**Comment by rstoenescu** [comment]
Fix will be available in beta.17.
@mountash Thanks for contributing!
