### ISSUE TITLE
[v1]Styling issues on input fields

### ISSUE THREAD

**Issue by schniper** [quasarframework/quasar#3357]
There are 2 issues in the image below, on an app using the latest beta (3):
1. autocompleted values, which appear automatically on the latest Chrome on Mac OS, seem to trick the floating labels into sticking in the original position.
Focusing one of the fields fixes the labels for both fields, so some event seems not to be firing on the first load
2. having multiline field hints, even with bottom-slots enabled, spills the layout over the next components, as the hint uses absolute positioning.

![image](https://user-images.githubusercontent.com/533628/53227687-a9df9d80-3687-11e9-929c-3d2d0005eec9.png)

### Software version

Quasar:
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by schniper** [comment]
Update: the 1st issue, the focus of the autofilled fields, does not seem to replicate anymore, after shuffling the layout around, a bit. Don't know if it's a real issue.
The 2nd issue is there to stay, though.

**Comment by rstoenescu** [comment]
Hi,
1. Please mention the beta version that you are using.
2. For instance, the first issue was fixed in beta.4 (which you probably upgraded to).
3. The second is part of the design (following Material Guidelines) and you can a) manually increase bottom padding of QInput or b) add top margin/padding to the element that follows or c) externalize the hint out of the QInput. Cannot have dynamic height on the QInput otherwise the animations between hint and error would not work.

**Comment by schniper** [comment]
Got it! Thanks
