### ISSUE TITLE
Datetime with min/max - can't set date after reaching one limit and hitting previous/next month

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#340]

**Comment by Snippo** [comment]
I found an issue which I think is related to this one:
Using
`<q-datetime v-model="model" type="date" min="2017-10-31T00:00:00.000+01:00" />
`
, going to the next month will go straight to December instead of November, and going back to November will result in all dates disabled. This seems to happen everytime when min is set to the last day of the month. However, settings min to "2017-10-31" seems to work...

**Comment by Snippo** [comment]
This actually seems to work fine in 0.15.0, just not in 0.14.2...
