### ISSUE TITLE
[v1] QTable - scrollbar over last row

### ISSUE THREAD

**Issue by labs20** [quasarframework/quasar#3414]
The scrollbar is overlapping part of the last row.

![captura de tela 2019-02-27 as 14 17 21](https://user-images.githubusercontent.com/4047789/53509567-cf5f1380-3a9a-11e9-9314-b49a0446c515.png)

The way I expected it to be (I put a padding-bottom of 16px at q-table__middle)

![captura de tela 2019-02-27 as 14 22 25](https://user-images.githubusercontent.com/4047789/53509769-44cae400-3a9b-11e9-8bb4-363a3b72d91b.png)

**Comment by rstoenescu** [comment]
The way I see it, you're on MacOS and this is a feature of MacOS (scrollbar on top of content). So if you really need that bottom CSS just write it in your app. Won't do this on Quasar core because it feels like something very specific.

Correct me if I am wrong with MacOS and feel free to reopen. Thanks.
