### ISSUE TITLE
q-infinite-scroll not working with q-modal

### ISSUE THREAD

**Issue by franfrwork** [quasarframework/quasar#3476]
I'm having a problem with the q-infinite-scroll component (quasar 0.17.19).
When I use it in a modal, the loadmore method does not start.
Here is an example :
https://jsfiddle.net/ke52vm7g/4/
I have test with v1 beta and it's work :
https://codepen.io/anon/pen/WmGexj?&editable=true&editors=101

**Comment by rstoenescu** [comment]
Hi,

We're currently under heavy load with v1, which I recommend to upgrade to as soon as possible.
If your business requires this investigation + fix in 0.17, let me know. But just to paint the bigger picture: investigating and fixing this for 0.17 requires a whole great deal of effort, so please make sure that you really really need this otherwise it is very detrimental to Quasar to halt working on v1.

Thanks.
