### ISSUE TITLE
Put default values in documentation

### ISSUE THREAD

**Issue by emahuni** [quasarframework/quasar#3506]
I think it'd easier to know default values of properties in the documentation area so as to inform the reader what behaviour to expect on a component etc.

**Comment by rstoenescu** [comment]
They already are...

<img width="395" alt="default-value" src="https://user-images.githubusercontent.com/4665641/54005962-149ed780-4164-11e9-82bd-7765c538933c.png">

**Comment by mgd722** [comment]
@rstoenescu Many parameters still do not have default values listed though. I am new to Quasar after many years in other frameworks, and for example it is not clear what `vertical` defaults to in the example you linked above. There are many examples like this were I am left guessing what the default value is, not just booleans.

Here's how it looks now:

![image](https://github.com/quasarframework/quasar/assets/12187845/847b506f-efd7-4335-8ae5-3343377c57f8)

**Comment by rstoenescu** [comment]
@mgd722 

This information for Boolean props is not needed/useful and would just clobber the API cards. "Wait, what?" Well, yes, because a Boolean prop in Vue has `false` as its value by default. And we stick by it. It makes even more sense for lots of such Boolean props to be used as:

```html
<q-card-actions vertical>
```
...rather than:
```html
<!-- extra useless typing to change the prop, assuming it would be "true" by default -->
<q-card-actions :vertical="false">
```
...to change the "default". Less typing and clearer API overall.
