### ISSUE TITLE
Autocomplete/select suggestions xss vulnerability

### ISSUE THREAD

**Issue by iMakedonsky** [quasarframework/quasar#3539]
Example with a google option there. Forked from v1.0.0-beta9 fiddle.
https://codepen.io/anon/pen/xBLBbg?&editable=true&editors=101

**Comment by nothingismagick** [comment]
Thanks for raising this issue. Investigating.

**Comment by iMakedonsky** [comment]
Btw, same issue in 0.19. Labels are directly rendered as html in both autocomplete component popup AND q-item label & sublabel props.
If you render them as q-tile's they're fine though.

**Comment by rstoenescu** [comment]
Hi,

This is a valid concern, but it shouldn't be dealt from Quasar side. Initially, I didn't allow HTML to be rendered (in order to avoid possible xss attacks), but there were so many developers requesting the ability to render HTML for the labels that I literally had no choice and enable this feature.

The reasoning is that it's the developer's responsibility to ensure that the content is not susceptible to XSS attacks as with all HTML that comes from user input and gets rendered on the page. In 99% of the cases, the label content does not come a user input, so it's safe. But in the cases where the label content IS user input based, it's the developer of the app who needs to make sure it filters out any xss attacks.

**Comment by rstoenescu** [comment]
References:

https://github.com/quasarframework/quasar/issues/2011
https://github.com/quasarframework/quasar/issues/2455

**Comment by nothingismagick** [comment]
Thanks @rstoenescu for the reminder and the clarification - and thanks @iMakedonsky for raising this issue. Indeed, we are "caught-in-the-middle-again". 

Whenever I review projects, I consistently see cases where devs are not sanitising user-input. Now, if we can't merely wave off MITM / evil maid / browser-extension injections / pure P2P distributed serverless / db-less instances, what do we do?

First of all, I must advise you to be vigilant with ALL types of user input. This includes text, but also includes images. I mean, we can add browser-side "pseudo mime-type" checking - but professionals can easily sidestep this and upload files that are not truly what they seem. GIFAR, for example is one such vector - but out of bounds PNGs are as well (among many, many others). The point is that **YOU** need to make sure that every bit and byte that ends up on a server is really safe. 

NEVERTHELESS - I do see your point here, and in the context of hardening the application, I would like to propose a new prop to that turns off this rendering. It will be optional though, because we must preserve backwards compliance at all costs.

**Comment by nothingismagick** [comment]
When I make the PR, I will ask you to review it for me @iMakedonsky - ok?

**Comment by nothingismagick** [comment]
Ok - great. Then since you are new to vulnerability reporting, I would like to just take this opportunity to remind you that best practice is not to directly report on a public repo (I learned this the hard way too, and now seek more discrete channels). No reason to give the haters ammunition. ;)

**Comment by iMakedonsky** [comment]
Will do!
