### ISSUE TITLE
Feature request: allow for 2-colour app bar on Cordova

### ISSUE THREAD

**Issue by RohanTalip** [quasarframework/quasar#3637]
Mobile apps using material design typically have 2 sections and 2 colours in the app bar:
https://material.io/design/components/app-bars-top.html
https://material.io/design/material-theming/implementing-your-theme.html#color

i.e. A primary colour and a (usually darker) variant of that primary colour.

The top section / colour is used as a background for the system notification icons, and the bottom section / colour is used for the app toolbar.

I don't currently see an easy way to implement this in Quasar's header/toolbar for apps running on Cordova.

Is this something that would be simple to implement?  Or have I missed something that already exists?

**Comment by rstoenescu** [comment]
When building mobile apps, this is handled entirely by Cordova. You can configure the statusbar through [Cordova statusbar plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-statusbar/)

When building in any other mode, you can use [QBar](https://v1.quasar-framework.org/vue-components/bar) (assuming you are using v1 because you haven't mentioned any Quasar version). Take a look at QHeader with QToolbar example specifically.

**Comment by RohanTalip** [comment]
Thanks!
