### ISSUE TITLE
Menu drawer isn't defined enough (desktop)

### ISSUE THREAD

**Issue by Async0x42** [quasarframework/quasar#364]
I find that the default drawer could be improved a little with some bordering or a shade, or something. It's often bothered me in the past, but it's really noticeable when compared to the same layout in other libraries.

I think it's the large amount of white-space on large desktop screens that makes it less attractive, since because mobile has the dimmer to make it stand out.

Quasar:
![image](https://cloud.githubusercontent.com/assets/3268854/22494639/130af0f6-e807-11e6-94b3-95fbcb14c64b.png)

Vuetify:
![image](https://cloud.githubusercontent.com/assets/3268854/22494641/17f76658-e807-11e6-83e7-e759ea8322e4.png)

**Comment by rstoenescu** [comment]
You can add it by CSS in your app, but will see about it in Quasar directly. Thanks!

**Comment by smolinari** [comment]
Sounds like it may be "contributor friendly" too? 😄 

Scott

**Comment by rstoenescu** [comment]
@smolinari Yep.

**Comment by rstoenescu** [comment]
Pushed commit. Available in edge and next version after v0.13.

Added screenshot with Material theme. Using box-shadow. On iOS it's used a border instead of box-shadow to get in line with toolbars.

![screenshot from 2017-02-01 19 20 48](https://cloud.githubusercontent.com/assets/4665641/22518798/9a4e4ebe-e8b6-11e6-9da2-1c7866660df9.png)

Thanks for submitting this issue. Comments?

**Comment by smolinari** [comment]
Looks pretty sharp to me. 😄 

Scott

**Comment by Async0x42** [comment]
Big improvement, great!
