### ISSUE TITLE
Feature Request: Allow classes in QTable to be dynamically derived

### ISSUE THREAD

**Issue by infintesimal** [quasarframework/quasar#3686]
Hi,
I would like to be able to dynamically derived additional classes for table columns as follows
```
<template>
  <div class="q-pa-md">
      <q-table
        title="Results"
        :data="fontData"
        :columns="fontColumns"
        row-key="fontData.name"
        binary-state-sort
        dense
      ></q-table>
    </div>
</template>

<script>
export default {
  name: 'FontVoteTally',
  data () {
    return {
      fontColumns: [
        {
          name: 'name',
          required: true,
          label: 'Font Name',
          align: 'left',
          field: row => row.name,
          format: val => `${val}`,
          sortable: true,
          style: 'width: 200px; font-size: 2em;',
          classes: ['text-weight-bold', row => row.specialClassName1]
        },

```
Currently, this is not possible (at least) because of the direct translation of col.classes here
[table-body.js](https://github.com/quasarframework/quasar/blob/dev/quasar/src/components/table/table-body.js#L43)
[table-header.js](https://github.com/quasarframework/quasar/blob/dev/quasar/src/components/table/table-header.js#L58)

I am submitting a pull request that addresses this shortly.

**Comment by infintesimal** [comment]
Convincing reasons:
1) The code works
2) There are plenty of developers who have code where desired css classes can be inferred from dynamically return data. E.g. the data my return a class name, an array of class names or something derivable, such as
```font-name: Foo``` and the developer maintains a contract with stykesheets such that the class that specfies ```font-face: Foo``` always has a name like ```.font-foo```. Thereafter, a quasar developer can easily add a function on QTable that would be like ```getClasses(row) { return row.className }``` or ```getClasses(row) { return ArrayOfClasses }```

**Comment by rstoenescu** [comment]
Hi,

First of all, thank you for providing a PR! Much appreciate it.

Unfortunately, it's not really optimal. There's all sorts of slots that you can use in order to customize the QTable in case there is a scenario that can't be covered by the default set of options. Of course, I can add this PR, but the concern is that it adds overhead for 99% of the use cases. We need to keep this component to render as fast as possible hence for custom scenarios there are the slots.

Looking forward to other PRs from you though.
