### ISSUE TITLE
Installing quasar has broken hot-reload on my Vue CLI app

### ISSUE THREAD

**Issue by ymhr** [quasarframework/quasar#3726]
### Software version

Quasar:
@quasar/app (v1+ only): 1.0.0-beta.13
OS: macOS
Node:  10.15.1
NPM: 6.9.0
Browsers: Chrome

### What did you get as the error?
There are no error messages

### What were you expecting?
The app should hot-reload when I make a change

### What steps did you take, to get the error?
I installed quasar via the Vue CLI plugin. Since then, hot reloading has not worked for me. Webpack is correctly recompiling, which can be seen in my console output, but the changes never make it my browser.

**Comment by rstoenescu** [comment]
There's nothing in vue-cli-plugin-quasar that can cause that.

However, from my experience with webpack, HMR sometimes breaks when used along with symlinks in node_modules (due to some paths issues in webpack). Regardless if this is your case too or not, I recommend you delete node_modules and package-lock.json/yarn.lock and yarn/npm install your project again. I do recommend that you use Quasar CLI instead, but my point regarding this issue is that the problem cannot be happening due to the Quasar Vue CLI plugin.
