### ISSUE TITLE
q-input type="password" was giving weird behaviours

### ISSUE THREAD

**Issue by Nice2Work** [quasarframework/quasar#3751]
### Software version

Quasar:
@quasar/app (v1+ only):
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by Nice2Work** [comment]
So I have a page that is rendering a bunch of q-input that is reacting than in a weird way. I go to my login page, log in with my email address and password, come to the notes page, with some notes having password protection in it. Now suddenly I see my email address in the top in the search (q-input and even regular input). I changed it to another var, did not help. So I remembered it was working before fine, so I went back to the spot where I had regular input fields. Then slowly moved forward changing the regular into  q-input, all was fine, but when I changed the type to password it started to act weird. And all q-input fields were propagated with my email address. I tried giving it an ID, a REF, putting into a <form with remember off> etc, nothing helped.
So I was putting it back to type 'text' and used css to make it act like a password input ( text-security:disc; -webkit-text-security:disc;)
So this was my fix.  
Quasar : v1.0.0.-beta.11 
@quasar/app: v1.0.0.-beta.12
OS: windows
Node : v10.15.0
NPM : 6.4.1
Browser: Chrome

**Comment by rstoenescu** [comment]
Hi,

There's absolutely nothing special in the way Quasar renders QInputs with type=password. It's a regular QInput with `type` attribute set to `password`. Nothing more, nothing less.

Are you wrapping this in a `<form>` element? And then the browser autocomplete comes into place? Since you mentioned regular input "suffers" from the same thing. Use attributes to disable [autocomplete](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion).

Please reopen with a Codepen or seek help from the wonderful community on our Discord server. It's either the autocomplete (99% chance) which can be disabled or something with your app's code.

-Razvan

**Comment by carueda** [comment]
Basically what I'm just starting to note in my app as soon I added a change-password dialog (which just has two fields, password and password2); During the autocompletion behavior, Chrome not only brings in possible passwords but also fills in some completely unrelated search field in the background page; really weird!  Probably not a Quasar issue. Will try to investigate further.

**Comment by carueda** [comment]
Missed to put my two `<q-input>`s within a `<form>`!  The weird behavior is gone.

**Comment by Nice2Work** [comment]
Yes this was what I also did, It just worked. And this behavior was only in a chrome browser.
<form autocomplete="off" v-on:submit.prevent="PreventDefault">
   <q-input..../>
</form>
 methods: {
    PreventDefault(event) {
      event.preventDefault();
    },
.....

**Comment by nothingismagick** [comment]
also check out the q-form component:
https://v1.quasar-framework.org/vue-components/form

**Comment by carueda** [comment]
Thanks, I surely will (once my migration item climbs to the top of my list ;)
