### ISSUE TITLE
[v1] QSelect - selected slot not working

### ISSUE THREAD

**Issue by adiliqbl** [quasarframework/quasar#3752]
### Software Version
Quasar 1.0.0-beta.13"

### What were you expecting?
I have followed the documentation for custom selected item. I have tried both `v-slot:selected-item="scope"` and  `v-slot:selected` but doesn't work. Where as `v-slot:option` & `v-slot:no-option` work as expected.

**Options slot**
![Screenshot from 2019-03-30 22 46 43](https://user-images.githubusercontent.com/9465773/55279795-77882680-533e-11e9-9166-31dd2f2f03f4.png)

**Selected slot** (should be similar to options slot)
![Screenshot from 2019-03-30 22 46 14](https://user-images.githubusercontent.com/9465773/55279801-8a9af680-533e-11e9-9138-cee492139ac1.png)

**Comment by rstoenescu** [comment]
Hi, Please provide a Codepen so we can help you as requested in the ticket template. Thanks.

**Comment by adiliqbl** [comment]
Hi. Thanks for quick reply, really appreciate it. 
I am not able to reproduce on Codepen, its working fine there. But I am not able to make it working in local project. Here's the template for selected scope. 
``` pug
template(v-slot:selected-item="scope")
        q-item.d-flex.justify-content-between
            .valign
                img.mr-20.thumbnail.small(:src="scope.opt.image")
                .item
                    .item-title {{scope.opt.name}}
                    .item-subtitle(style="margin-top: -4px;") {{scope.opt.email}}
```

**Comment by rstoenescu** [comment]
It's working in docs, it's working on new project, it works in Codepen.

Possible issues:
* You're using an older `@quasar/app` which has a similar old Vue (upgrade to latest `@quasar/app`)
* You've manually installed Vue, which is highly NOT recommended
* You're doing something wrong in your app, but cannot tell what exactly since I don't have access to it.

Most likely, it's the first. If it's not, please join our Discord server and request for help. Either way, there's no issue with Quasar.

-Razvan
