### ISSUE TITLE
[V1] Set Quasar iconSet to ion ios/md

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3754]
Currently setting Quasar iconSet to `ionicons-v4` will use this file to map the icons:

https://github.com/quasarframework/quasar/blob/dev/quasar/icon-set/ionicons-v4.js

It's kind of a mix between `md` and `ios` icons. I'd like to choose Quasar to use all `ios` or all `md` icons.

**Comment by rstoenescu** [comment]
It may look like it's a mistake, but it's this so that the design of components to look correct, not appear "broken". For example, the type: positive, which with md has correct size, but with ios it's too small (!!). Should the size be consistent, then I'd make a change. But it's not. Both md and ios checkmarks look identical, except for their size. So it makes sense to have the icon set as it is now. And this was just an example. There are similar problems with the rest of the icons.
