### ISSUE TITLE
[V1] maximized + bottom dialog bug

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3809]
Beta 0.15 fixed some issues I had, but there's one issue left.
- `position="bottom" maximized` still doesn't maximize the dialog, and will only be as high as the content.
(if the content is as high - or higher - as the dialog, everything works fine)

See my pen:
https://codepen.io/mesqueeb/pen/JVommQ

Currently I believe it uses `.fixed-bottom`  as opposed to `.fixed-full` and I think before beta 0.13 with both `bottom` and `maximize` it would use `.fixed-full > .fixed-bottom`.

**Comment by rstoenescu** [comment]
This is by design. I keep explaining this over and over.
What is the purpose of position=bottom used along with maximized? You either want a maximized (full-screen) QDialog or a QDialog that is bound to one of the four sides of the screen (top, right, bottom, left). Rencently, I added support for maximized to be used along position prop, and what this does is that it makes the QDialog full height or full width. But as long as you are using a position, the QDialog will occupy only as much space as the content (unless custom CSS is injected).

What I think you are looking for is actually the animation, but then again, that's what `transition-show` and `transition-hide` props do.. Using these props allows for a wide range of not only sliding but fading, jumping, rotate, flip etc etc.

Now that we are in agreement that position + maximized should not act the same as when just using maximized (so to add value to the QDialog possibilities), let's talk about why fixed-full was transformed into fixed-bottom/top/right/left. This is because the transitions (such as slide-up or slide-down etc etc) are applied to the full extent of the space that QDialog occupies on screen. So if you have a 30px height QDialog positioned to bottom but it has fixed-full applied to it, then the animation will transition the whole portion of screen full height content --- essentially making it so that the QDialog content (those 30px) almost instantly disappears off screen (since they'll be the first px to slide out) while the animation goes on and ends when the full height screen size is slided off screen, which is not what we want. What we want is that the animation to be applied only to the content, only to those 30px. Will add a video recording if my explanation above is not easily comprehensible.

**Comment by mesqueeb** [comment]
I now understand completely. Thank you for your elaboration! 🌞
