### ISSUE TITLE
Add support for browser as cordova platform to utilize cordova in development mode

### ISSUE THREAD

**Issue by ramonmostert** [quasarframework/quasar#381]
As discussed here: http://forum.quasar-framework.org/topic/155/trying-to-use-codova-wraper/7

It would be very convenient to detect the cordova js library when running 'quasar dev'.  So you don't need to run the project on a device or emulator to access the cordova object.

**Comment by boustanihani** [comment]
As mentioned here (https://github.com/quasarframework/quasar-play/issues/14) it would also be great to have cordova functionality inside the "Quasar Play" app. Currently one can follow these steps for running and debugging cordova code =>

- Compile the "PhoneGap Developer App" using dev mode and install it on the target Phone. Check: (https://github.com/phonegap/phonegap-app-developer)
- Use the "Cordova App Wrapper" to generate a cordova project
- Run `quasar build`
- Install `phonegap` and from inside the cordova wrapper directory run `phonegap serve`
- Finally open "PhoneGap Developer App" and point it to your machine

Because the "PhoneGap Developer App" was compiled in dev mode one is also able to debug using Chrome-Dev-Tools. But each time I do any changes to my code I need to rerun `quasar build` & `phonegap serve`.

**Comment by rstoenescu** [comment]
Try v0.15. It should work.

But it's obsolete anyway, since in v0.15 you can now develop with HMR and Cordova plugins directly in the emulator or on phone.
