### ISSUE TITLE
Best backebd for quasar

### ISSUE THREAD

**Issue by j209** [quasarframework/quasar#3820]
Hi
What is the best backend for quasar?
[Django](https://github.com/django/django),
[Flask](https://github.com/pallets/flask)
[Meteor](https://github.com/meteor/meteor)
[Ruby on Rails](https://github.com/rails/rails)
[Nest.js](https://github.com/nestjs/nest)
[Asp.net core](https://github.com/aspnet/AspNetCore)
...?

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. 

To answer your question, there is no "best back end" for Quasar. If you plan to use SSR, then Node would be a good choice, since you'll need it to serve Quasar's SSR build. Other than that, it's up to you. My preference would be anything that supports GraphQL. If you don't know about GraphQL, you should learn about it. It's a step up from REST and supports single file component hierarchical systems like Vue's.  

Scott
