### ISSUE TITLE
[v1-bug] Global Event Bus not working in QDialog

### ISSUE THREAD

**Issue by ageeye-cn** [quasarframework/quasar#3900]
### Software version

Quasar:
@quasar/app (v1+ only): 0.16 beta

### What did you get as the error?

The root component  in QDialog  is different from other components

**Comment by rstoenescu** [comment]
"The root component in QDialog is different from other components" --> Yes, this is by design, since QDialog and QMenu use Quasar Portals (so content can be rendered at end of `<body>` in order to 1. avoid css pollution, 2. avoid z-index issues, 3. avoid possible parent overflow css, 4. work correctly on iOS).

What you can do is create your own global bus through a .js file:

```js
import Vue from 'vue'
const bus = new Vue()
export default bus
```
Then import this file wherever you need to access this bus.

**Comment by nothingismagick** [comment]
I am going to add this to the documentation. It has been cropping up in
several user reports on Discord.

>

**Comment by ageeye-cn** [comment]
Thanks
