### ISSUE TITLE
[v1-bug] Page scrolls when QDialog is in foreground

### ISSUE THREAD

**Issue by abrahamnm** [quasarframework/quasar#3908]
### Software version
Quasar:
@quasar/app (v1+ only): beta 17

Any other software related to your bug:
Cordova - Android

### JsFiddle
https://codepen.io/anon/pen/YMYJzG

### What did you get as the error?
On Cordova application, when QDialog is in foreground:
Scroll gesture over the QDialog content causes scrolling on background page.
Scroll gesture on QDialog's backdrop doesn't affect scroll position on background page.

On SPA scrollbars still work when QDialog is opened.

### What were you expecting?
Scroll position whould not change when QDialog is opened.

**Comment by nothingismagick** [comment]
Thanks for filing this issue @abrahamnm

**Comment by usu** [comment]
Encountered/reproduced the same issue on iOS 12.1.4 in Safari

**Comment by rstoenescu** [comment]
Hi,

* Android - cannot reproduce no matter how much I tried; there is code in place to make page "unscrollable"
* iOS - due to bugs in iOS webview and iOS safari this cannot be fixed; the approach for Android doesn't apply to iOS too due to bugs in iOS.
* Desktop - showing scrollbar is by design, otherwise there will be a flicker of hiding/showing the scrollbar when QDialog appears/disappears (reference: https://github.com/quasarframework/quasar/issues/1771); however there is code in place to hinder mouse-wheel scroll for background, but it cannot be applied to mobile environments due to performance constraints
