### ISSUE TITLE
Quasar deletes items in cordova config.xml

### ISSUE THREAD

**Issue by fega** [quasarframework/quasar#3975]
### Software version

Quasar: 0.17
OS: Mac Os latest
Node: Node 10@latest
NPM: Latest
### What did you get as the error?

Sometimes after I run quasar build  or quasar dev -m cordova, quasar deletes some of  my config.xml tags

![image](https://user-images.githubusercontent.com/6069807/56772881-6dace400-6781-11e9-817d-aafaf09b2f3e.png)

### What were you expecting?

it shouldn't override my config.xml

PS: I'm super happy with Quasar! great work!

**Comment by rstoenescu** [comment]
Hi,

So here's how it's working (high overview), and it only touches it for `quasar dev`: you hit the quasar dev command; Quasar builds the UI; reads config.xml and sets content src to point to the app URL of quasar devserver; runs cordova cli to start up the cordova app; after cordova starts up the emulator, Quasar then reset the content src to its original `index.html`.

Pushed a commit to improve this a bit, meaning config.xml wasn't reset if cli failed in a specific scenario (which I think that you've hit). And also, while cordova cli boots up the emulator, if you change config.xml these changes were lost because the config.xml reset was done from the in-memory contents of config.xml --> now, I've forced Quasar cli to re-read config.xml every time it needs to change it (set content src, reset content src, etc). 

The `allow-navigation` part is handled automatically and you should not need to change. Actually, don't change it by hand at all as it can easily break your cordova built app.

**Comment by rstoenescu** [comment]
Fix described above will be available in quasar/app beta.21
