### ISSUE TITLE
[v1][Feature Request] Auth module

### ISSUE THREAD

**Issue by geoffreylzf** [quasarframework/quasar#3986]
I was having problem when transfer my web app from nuxt to quasar. I found out that there is no default auth module in quasar.

suggestion in quasar.config.js
```auth: {
    strategies: {
      local: {
        endpoints: {
          login: {
            url: '/api/auth/login',
            method: 'post',
            propertyName: 'token'
          },
          user: { url: '/api/auth/user', method: 'get', propertyName: 'user' },
          logout: false
        }
      }
    }
  },

  router: {
    middleware: ['auth']
  },
```

and suggestion in each page that does not require auth

```
export default {
  auth: false
}
```

This suggestion is based from [Nuxt Auth](https://auth.nuxtjs.org/getting-started/setup)

**Comment by mesqueeb** [comment]
If you are talking about a suggestion about a built in auth module for Quasar, I would be against this.

### I would advice against this

There are so many millions of ways to do authentication, you just show one way via an http request using a token.

Besides that there are also sessions or many JavaScript SDK's that take care of auth for you like Google Auth API or Firebase Auth and many others.

Besides methods to actually do your auth, you also have to take into account that separate builds might need adjustments again.
Eg. In most of my Quasar projects I have both Cordova and SPA builds that use different auth SDKs entirely, and I'm sure if I add SRR support I'll again need to adjust the auth system to that build method.


### How to improve this issue

There are a couple of things you can do.
1. if there's something specific not working with your auth system and after research you've found that it's because of something in Quasar, try to open a specific issue for this
2. if you are trying to port a project to Quasar but have trouble porting a certain "auth module" you had working in Nuxt, your best bet would be to [open a thread on the forums](https://forum.quasar-framework.org).
3. if you really do believe a "general auth module" for quasar might benefit 99.9% of all devs who use some form of authentication, then please clarify your intentions a bit more. Give some examples of cases how projects from all build methods (srr, cordova, spa, pwa, electron, ...) and certain popular auth systems (eg. jwt) could benefit.
4. if you don't have a suggestion to your knowledge that would work for all build methods, but still have a suggestion for your use case specifically (a token auth system via http requests), then a [quasar app extension](https://v1.quasar-framework.org/app-extensions/introduction) might be better suited for this.
  - if you can build it on your own, that'd be great! Go to the discord community and promote it!
  - if you cannot build it on your own, your best bet would be to talk about it on the discord community and try to find some people who'd want to help you out to make this app extension.

Good luck! 😉
