### ISSUE TITLE
V1 - QSelect - filtering with hide-selected not working in beta19

### ISSUE THREAD

**Issue by kakajan** [quasarframework/quasar#3987]
Hi,
I just updated to beta19 and my all QSelect with filtering and hide-selected option does not show the value.
please help me to overcome this situation.
Thank you

**Comment by Lukino2000** [comment]
Same here.

just for instance you can view
[V18](https://codepen.io/Lukino2000/pen/Pgmdzd) vs [V19](https://codepen.io/Lukino2000/pen/jRmKda)
just search something and select it

**Comment by rstoenescu** [comment]
I am surprised that is being reported. The way `hide-selected` worked before seemed to not be understood by 95% of devs. Furthermore, this property also depended on single or multiple selection mode, as it worked differently for each.

So starting with beta.19, it simply removes the "selected" part and does not tampers anymore with the input. It will not fill the input with the currently single selected value. We avoid lots of misunderstanding on this feature and avoid lots of github tickets opened (first that comes to my mind, but there are a lot more: "You need to manually delete current selection from the input in order to be able to see all selectable menu options"). If I revert this behavior to what it used to be then tickets will keep on opening to request the opposite.

Main point is to not use `hide-selected` anymore if you don't want QSelect to hide the part where it shows what's currently selected.

**Comment by kakajan** [comment]
Thank you dear Razvan for your explanation. It helped me to understand correctly the hide-select.
But main reason i liked to use it was the feature to clear the text with backspace and search the new one again, that simple filter does not have this feature and you should search new one beside the old selected one showed for user.
any way thank you for your great job
I am a big fan of yours

**Comment by rstoenescu** [comment]
I am inclined towards your thoughts too (which is the reason why I wrote that feature the way it was in the first place), but I want to listen to the majority of devs, and they were not happy with how it worked :(

**Comment by Phunky** [comment]
When upgrading to v1 QAutocomplete was replaced with QSelect but it's no longer possible to get the previous behaviour of;

- Input entered by the user into the component.
- Trigger Ajax request to populate a menu of results to choose from.
- User select desired value.
- The selected value by the user becomes the value of the Input.

If this isn't something you're going to support going forward then I suggest it gets stated in the upgrade guide rather than directing people to an incompatible component.

**Comment by nothingismagick** [comment]
This is totally possible.

https://v1.quasar-framework.org/vue-components/select#The-%40new-value-event

**Comment by dontwork** [comment]
@nothingismagick It does not seem to be possible to populated the *input* with the selected items label like it was in 0.17. All of the new-value-event show the selection to the left of the input. Could be missing something though.

The functionality we are trying to emulate can be seen in the top example on the right, here: https://quasar-framework.org/components/autocomplete.html

**Comment by 123mitnik** [comment]
the user flow is totally broken if you try to emulate what @Phunky described.. gonna need to find workaround for this with third party components

**Comment by rstoenescu** [comment]
@dontwork @123mitnik @Phunky @kakajan @Lukino2000 Starting with beta.23 (to be released in 1-2 days), there will be a new Boolean prop: `fill-input`. Example of your needs (replacing QAutocomplete from 0.17 on a 100% level):

```
<q-select
        use-input <<<<<<<<<<<
        hide-selected <<<<<<<<<<<
        fill-input <<<<<<<<<<<<<<<
        input-debounce="0"
        :options="options"
        @filter="filterFn"
        ......
      >
```

Make sure to check the [Filtering and autocomplete](https://v1.quasar-framework.org/vue-components/select#Filtering-and-autocomplete) section again, AFTER beta.23 is released.

Thanks for your patience.
