### ISSUE TITLE
Autocomplete on Chips Textbox

### ISSUE THREAD

**Issue by delueg** [quasarframework/quasar#400]
Hey,
i wanted to ask if it would be possible to have autocomplete functionallity on the Chips Textbox Component.

**Comment by rstoenescu** [comment]
Will be available soon.

**Comment by furui** [comment]
I solved it by creating [an extended version of the Chips vue file](https://gist.github.com/furui/7fe3ed224f223c564bc1bb57185ee37f) and loading it in to a custom component tag. I admit this might not be the best way to do things since I'm inexperienced with vue, Quasar, and ES2015, but I hope it helps! It lets you v-bind a search function and also v-on events when chips are added or removed.

**Comment by amaranthius** [comment]
@furui Awesome! Will do the trick until an official version is out

**Comment by fnicollier** [comment]
Hi,
Are there any updates on this feature having an official implementation? Thanks!
