### ISSUE TITLE
QMarkupTable isn't working in Codepen

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#4042]
And I have no idea why. 😮 

https://codepen.io/smolinari/pen/qGWMVb

Scott

**Comment by rstoenescu** [comment]
This is due to how browsers work with UMD. So: browser loads the page, parses the HTML, sees non-native  element `<q-markup-table>` that wraps a `<thead>`/`<tbody>` -> *boom* invalid DOM hierarchy (browsers require this exact hierarchy: table > thead/tbody otherwise they "fix it" to specs compliant). Then Vue & Quasar kicks in, and it parses the template which was previously "fixed" by the browser, so not the same thing that we wrote.

This cannot be accommodated for UMD because of what I just said. And due to this, for UMD versions I recommend replacing `<q-markup-table>` tag with its Vue rendered equivalent tag. No way around it.

**Comment by smolinari** [comment]
Ah. Ok. Didn't know the browser would try to "fix" HTML. 

Would there be a way to remove the codepen buttons in the examples in the docs for QMarkupTable? I you think it's possible, I can take a look at it. 

Or, if that isn't possible, I guess just a warning at the top that the codepens won't work?

Scott
