### ISSUE TITLE
Request to support NW.js as well as Electron

### ISSUE THREAD

**Issue by adam-zpos** [quasarframework/quasar#405]
The Electron wrapper is nice, thank you. We wanted to use the NW.js platform https://nwjs.io/ as an alternative because, among other things, it supports Windows XP (Although for how much longer; I don't know).

I believe it shouldn't be a large deal to support it (I'm not expecting a wrapper). From my investigations into your source code, the functions which control the Platform variable seem to assess the platform for Cordova when no other platform could be chosen and when the URL does not contain "http" (https://github.com/quasarframework/quasar/blob/dev/src/features/platform.js#L151). As Quasar interprets it as Cordova, a few quirks are presented, including trying to import a cordova.js which is not found.

If this isn't possible, then that is fine and we would start to learn how to use Electron, and how to migrate.

**Comment by rstoenescu** [comment]
Hi,

Cordova supports Windows. Well, not Windows XP, but its marketshare is minimum nowadays and Microsoft has ended support for it 3 years ago.

Unfortunately the overhead of maintaining NW.js compatibility (along with its wrapper) too is simply out of reach currently due to lack of resources (both human and financial). If it's not too much trouble, go with Electron.

Cheers,
Razvan

**Comment by smolinari** [comment]
Support for Windows XP was dropped by Microsoft almost 3 years ago. 😮 

Scott

**Comment by adam-zpos** [comment]
Yes, you're right there, but I meant support with respect to NW.js supporting it. Windows XP was a preference as our apps are based around EPOS, and many point of sale still rely on XP (Even 2000!).

We'll use Electron for now and work it out, thanks for the consideration.
