### ISSUE TITLE
Add prop for QTable that will behave like in odranoelBR/vue-quasar-admin-example 

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#4077]
I suggest we can add a prop that will be set to QTable so that it can behave like in odranoelBR/vue-quasar-admin-example so that users can view all data for each rows without scrolling to the side when in mobile.

https://quasar-admin.firebaseapp.com/?ref=madewithvuejs.com#/server-side-data-table

**Comment by rstoenescu** [comment]
Hi,

This was a feature of Quasar in some 0.x releases ago. It's no longer possible to have this behavior automatically, unfortunately, due to the bulk of new features in newer Quasar versions in regards to QTable. Sorry for any inconvenience. Will keep this in mind when I got a bit of time to see if this can be revived.

**Comment by ajcastro** [comment]
Ok no problem. Thanks for the response. I will be waiting if it will be available in next versions. Thanks!

**Comment by rstoenescu** [comment]
Will add example in docs on next deployment ;)
Also, be sure to upgrade to beta.24 when it's released -- made some CSS tweaks that will help with this.

**Comment by ajcastro** [comment]
Thanks a lot for this! <3 :)
