### ISSUE TITLE
QTabPanels inside QCard (dark) = white background

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar#4098]
When use QCard in dark mode with QTabPanels, card content render on white background:

https://codepen.io/anon/pen/WBxago?&editable=true&editors=101

As I can understand, this rule unnecessary:

```
.q-tab-panels {
  background: #fff;
}
```

**Comment by rstoenescu** [comment]
QTabPanels need a default background color because of a lot of reasons. It's also been made easy to customize. Just add `bg-*` class to it (hint: you could even try `bg-transparent`, but like I said there's a reason for a color to be specified, so you'd better go with the same bg color that you apply to the card itself).
