### ISSUE TITLE
[v0.17] Dynamic before/after with q-select

### ISSUE THREAD

**Issue by leighwilliams** [quasarframework/quasar#4115]
### Software version

Quasar: 0.17.20
OS: macOS Mojave
Node: 10
NPM: 6.4.1

### CodePen

https://codepen.io/leighwilliams/pen/dEpOOj?editors=1010

### What did you get as the error?

q-select does not appear to allow dynamic before/after icons. This does work with q-input.

### What were you expecting?

The same behavior as q-input. As demonstrated in the CodePen.

### What steps did you take, to get the error?

See: https://codepen.io/leighwilliams/pen/dEpOOj?editors=1010.

Click the "Toggle Edit" button to see the behavior.

**Comment by leighwilliams** [comment]
I've added a workaround to the pen: https://codepen.io/leighwilliams/pen/dEpOOj?editors=1010 using `key` on the `q-select`.

**Comment by rstoenescu** [comment]
Hi,

We're currently under heavy load with v1, which I recommend to upgrade to as soon as possible.
If your business requires this fix in 0.17, let me know. But just to paint the bigger picture: fixing this for 0.17 requires a whole great deal of effort, so please make sure that you really really need this otherwise it is very detrimental to Quasar to halt working on v1.

Thanks.

**Comment by leighwilliams** [comment]
Hello,

That's understandable. We have a workaround, so we're ok.

Good luck with v1!

Thanks.
