### ISSUE TITLE
Proposal for a small doc refactor

### ISSUE THREAD

**Issue by eladyaniv01** [quasarframework/quasar#4144]
Hello, i have noticed that every component that is using computed methods,  or  needs to fetch some data from the store, 
is really hard for developers to grasp  how to implement( few examples are QSelect, QTable, QmarkupTable, QCalendar)  and i am sure there are more.  
so,  what can we do to make it clear as in  ( the dev needs to grab his own data, and then serialize it into the component data model)  
i propose to include a couple (comeplete - as in ,  from the backend,  to the component, including axios mock, and some data maipulation )examples 
that demonstrate use cases where the dev needs to grab his own data, and then serialize it into the component data model .  i can help providing such example because i have already dont it with the components i am using

**Comment by rstoenescu** [comment]
Hi,

Thanks for the proposal. I'm open to any improvements and looking forward for a try with a PR.

I should note that each component can be connected to a backend API (Quasar is backend agnostic) because each component has data getting in (its props) and data getting out (rendered HTML). How and from where you supply the props can be done in an infinite number of possibilities. Covering them all is impossible and showing just one possibility can wrongly suggest "this is the only way". Also, we're not trying to teach devs Vue itself because the Vue documentation covers this very well on their documentation website.

Thanks,
Razvan
