### ISSUE TITLE
Feature Request - Platform Aware Components

### ISSUE THREAD

**Issue by eladyaniv01** [quasarframework/quasar#4145]
### So,  
what if each componend ran a platform check on itself when its being rendered, 
and then BEHAVE according to that platform without any outside dev help ? 
i think this is possible to implement, at least for most components , 

 without too many special/edge cases

**Comment by rstoenescu** [comment]
Hi,

Each component is already aware of the platform it is running on and makes decisions. It is one of the key points of Quasar against all other frameworks.

But really, I cannot tell if you have at least a specific case in mind where things can be improved even more. I'm open to detailed/focused suggestions (and please send them by email - Github is reserved for bugs only), otherwise the description is too abstract.

Thank you and looking forward to hearing suggestions,
Razvan
