### ISSUE TITLE
[v1 bug] QColor error in QInput

### ISSUE THREAD

**Issue by ageeye-cn** [quasarframework/quasar#4223]
Cannot use no-header and no-footer parameters

![TIM截图20190527225325](https://user-images.githubusercontent.com/1737208/58427547-8424c300-80d2-11e9-9d27-401509232f2d.jpg)

https://codepen.io/anon/pen/PvaQrB?&editable=true&editors=111

**Comment by rstoenescu** [comment]
Hi,

QColor's content (below header and above footer) resizes dynamically. In this case, it needs a min-width applied to it. And when using QPopupProxy or QDialog with it (and QColor having no-header and no-footer), then QColor cannot compute a width and height. So apply a css with "min-width" prop on it.

Changed Quasar so that now QColor has a min-width of 150px by default.

Thanks for reporting!

**Comment by ageeye-cn** [comment]
Thanks!
