### ISSUE TITLE
Re-opening ... [V1] QTabs positioning error on QToolbar (#4209)

### ISSUE THREAD

**Issue by digiproductmarketer** [quasarframework/quasar#4236]
Hi Razvan,

Sorry I had to re-open this ticket because I'd already tried SHRINK ... and I just went and tried it again to confirm ... that doesn't help.

I also tried shrink on the QToolbarTitle ... but that causes an infinite recalculating loop ...

BUT .. then I tried your codepen ... and it worked ...

So, I couldn't understand it ... until I realised that I was running your codepen on my laptop that is using Windows 10 ... and I was running my own codepen on my laptop that runs Windows 7.

So, I tried running your codepen on my Windows 7 laptop ... and your codepen also fails under Windows 7.

Tried both your codepen and my codepen on OS/X High Sierra and both Safari and Chrome and they both work there.

Not sure if you want to persue this further as I am not really bothered about getting it running on Windows 7 for myself ... just so happens I have a development machine that has to remain on Windows 7 and was testing there.

So, it's actually an issue related to Windows 7 ... just wanted you to be aware of this ...

**Comment by KnowZero** [comment]
I am having a weird issue with QTabs on chrome (not on firefox) in Windows 10 and Linux Mint. Where the tabs would recalculate themselves infinitely. (looks like they are jumping back and forth when the last tab is partly covered). FireFox is perfectly fine though.

The issue seems to be dependent on the resolution (or more accurately the container), I'm testing on 1080p

https://codepen.io/anon/pen/wLvJoR?editors=1010

Is this the same issue you are having?

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
