### ISSUE TITLE
[v1 docs bug] Not all content index by search engine.

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [quasarframework/quasar#4379]
I tried to search `reveal-offset` with algolia search on top of the docs site.
And found only it 
![image](https://user-images.githubusercontent.com/10674646/59495474-031e4780-8e98-11e9-9f7c-2b942173ef72.png)
In upgradde guide section.

But its here
![image](https://user-images.githubusercontent.com/10674646/59495551-2ea13200-8e98-11e9-8840-88b7e182d73a.png)

**Comment by rstoenescu** [comment]
Hi,

We've outsourced the search to Algolia for the Quasar docs, since it is now a Quasar SSR app (so search engine friendly). Main point is that Algolia is not indexing quite everything, which is why we've written a search feature into the API card..

On behalf of Algolia, we're sorry for any inconvenience.
