### ISSUE TITLE
[Big Feature] Replace Cordova with Capacitor

### ISSUE THREAD

**Issue by eladcandroid** [quasarframework/quasar#4388]
With an eye of developers, Capacitor has many advantages over Cordova...
Please look here:
https://capacitor.ionicframework.com/docs/cordova

It also supports Cordova plugins so it's easy to be migrated

**Comment by rstoenescu** [comment]
Thanks for writing this ticket. We will seriously look into this.

**Comment by nothingismagick** [comment]
Yeah, I have also heard from it being used with quasar - so I know its possible. Would be good to add as a target.

**Comment by speyou** [comment]
I am making the move right now in my Quasar app, so far so good but if you get into trouble I might be useful, don't hesitate to @me or contact me.

**Comment by eladcandroid** [comment]
Here's a good reference:
https://github.com/nklayman/vue-cli-plugin-capacitor

**Comment by emahuni** [comment]
man this is awesome, the things that capacitor can do that codova can't are just amazing. I just read it.

**Comment by nothingismagick** [comment]
We're working on this right now.

**Comment by wooliet** [comment]
@nothingismagick Does that mean used as default for final v1?

**Comment by nothingismagick** [comment]
No, it will be an option in addition to Cordova. We will not deprecate
Cordova just because something else is better. There are too many people
using quasar to build Cordova apps. Check the PR.

**Comment by hugetiny** [comment]
Ionic team replace Cordova with Capacitor in Ionic4 already.I think Quasar could use Capacitor as the default PWA/Ios/Android/(Electron) builder

**Comment by nothingismagick** [comment]
Until Cordova reaches end of life, is deprecated and no longer developed - I see absolutely no reason to force people to change. There are entire businesses using the Quasar Framework that at this very moment use Cordova in production, and "replacing Cordova with Capacitor" is just simply infeasible and such a breaking change that we would alienate people.

Quasar is all about having options @hugetiny - and I know for a fact that some Cordova plugins that are currently in use DON'T work with Capacitor. This is why its inclusion is a "forward-change", where we retain the current API and build targets and enhance them with new things.

Cordova is not the "default" builder for anything (really, why make things more complicated???) and while I definitely know where you are going with this, I could just as easily (and probably better) argue that we replace everything with webview wrapped in rust - but I won't do that because that is just too opinionated.

Let's first get 1.0 done, see what Vue 3 brings to the table and then decide where to go from there. 

I am voting to close this issue, as the primary claim of "replacing cordova" is not going to happen, but we will be adding capacitor. Hope that my answer has given you some insight. Thanks for reading!!!

**Comment by eladcandroid** [comment]
@nothingismagick But Capacitor has support for almost all of Cordova plugins... 
See here:
https://capacitor.ionicframework.com/docs/cordova/using-cordova-plugins

Also, this is a great reason to decide between choosing Ionic over Quasar for the long running...

You just give the choice to use it in CLI.. No forcing on anyone. It's hard for me to see what could break down as a result ...

**Comment by smolinari** [comment]
@eladcandroid - Just to make sure you are aware, the ability to use Capacitor instead of Cordova is being added to Quasar, but as an option to Cordova, not as a replacement.

Scott

**Comment by eladcandroid** [comment]
@smolinari Thanks 👍

**Comment by nothingismagick** [comment]
Almost all is NOT all. So it is NOT a replacement. It will be added, but
Cordova will also continue to be available.

If this is so important to you, then I wound urge you to check out Noah's
PR and get involved in making it a reality.

**Comment by emahuni** [comment]
> Until Cordova reaches end of life, is deprecated and no longer developed - I see absolutely no reason to force people to change. There are entire businesses using the Quasar Framework that at this very moment use Cordova in production, and "replacing Cordova with Capacitor" is just simply infeasible and such a breaking change that we would alienate people.
> 
> Quasar is all about having options @hugetiny - and I know for a fact that some Cordova plugins that are currently in use DON'T work with Capacitor. This is why its inclusion is a "forward-change", where we retain the current API and build targets and enhance them with new things.
> 
> Cordova is not the "default" builder for anything (really, why make things more complicated???) and while I definitely know where you are going with this, I could just as easily (and probably better) argue that we replace everything with webview wrapped in rust - but I won't do that because that is just too opinionated.
> 
> Let's first get 1.0 done, see what Vue 3 brings to the table and then decide where to go from there.
> 
> I am voting to close this issue, as the primary claim of "replacing cordova" is not going to happen, but we will be adding capacitor. Hope that my answer has given you some insight. Thanks for reading!!!

This is what i meant by breaking change and he is right.

**Comment by emahuni** [comment]
I vote you close the issue as well you have made it clear what's going on and I for one am happy with the this.

**Comment by nklayman** [comment]
Capacitor support is almost ready! See https://github.com/quasarframework/quasar/pull/4475 for progress and instructions on how to test in your own project. Both dev and build are supported, all that's left is documentation and plugin support.

**Comment by nothingismagick** [comment]
FYI @eladcandroid, @nklayman wrote the vue plugin you mentioned above. Anyway, closing this issue as we will not be replacing cordova, but will be introducing capacitor. Thanks for the input
