### ISSUE TITLE
Typescript out-of-box support during quasar create

### ISSUE THREAD

**Issue by zrfrank** [quasarframework/quasar#4399]
**Is your feature request related to a problem? Please describe.**
Typescript is kinda widely used now, although it can be added and configured afterwards, it will be great if quasar could integrate it.

**Describe the solution you'd like**
Adding an option to using typescript and typescript related linter, when using `quasar create`.

**Comment by nothingismagick** [comment]
we have an app extension for installing typescript into your project.

$ quasar ext add @quasar/typescript

>

**Comment by lucasfernog** [comment]
Maybe we can add "Typescript support" to the list of features the dev can choose, such as ESLint, vuex, axios (already there).

However, one problem with it is that it would work only for 1.0.0+, and the create command is defined on @quasar/cli instead of @quasar/app, and the CLI must be backwards compatible.

**Comment by lucasfernog** [comment]
Actually its resolved on the starter kit so I'll try that when I have some time

**Comment by zrfrank** [comment]
I wish this proposal is not too bold, that would Quasar consider the possibility of rewrite/refactor using Typescript. There are a few reasons:
- Vue will use typescript
- Many famous packages are rewritten using typescript
- Majority of Quasar users are writing mid->large size projects, so that proper typing support can reduce enormous amount of documentation and developing pain.

**Comment by rfox12** [comment]
Quasar failed to be adopted by one of my client companies because of lackluster Typescript performance.  The instructions that currently exist for Typescript setup (https://quasar.dev/quasar-cli/cli-documentation/supporting-ts#Installation-of-TypeScript-Support) result in a VSCode environment that doesn't do proper command-line completion of class types.  I know this is probably due to babel vs typescript...  Ironically using @quasar/typescript (which I now understand isn't promoted for the newest version of Quasar) got me closer to a fully functional Typescript environment (where class fields/methods completed fine).

What I love about Quasar is how it uses best practices and makes everything work.  Right now setting up Vue / Typescript / Class-based components / Linting is super complex.  I don't know the right path but there is real pain for companies that want to adopt Typescript.

This guy is doing some interesting stuff:
https://github.com/akoidan/vue-webpack-typescript

And this stack overflow answer caught my eye:
https://stackoverflow.com/a/60187886/5153063

**Comment by IlCallo** [comment]
Hi @rfox12, Quasar now supports TypeScript out-of-the-box when creating a new project, which let you choose your preferred component style (Composition API, Class API, Options API).

Older codebases could use the [TS App Extension](https://github.com/quasarframework/app-extension-typescript) to partially ease the migration process.
Quasar + TS + Jest support is currently in beta and can be added via `quasar ext add @quasar/testing-unit-jest@beta`.

We don't know which error you bumped in, but we encourage you to open a new issue if they persist, providing a repro to let us check what is not working.

Also note that migration instructions doesn't cover how to add the needed packages to use Class API (or any other opt-in API), but feel free to jump in and send a PR to integrate this aspect :)

Original feature request has been satisfied, so I'm going to close this issue

**Comment by rfox12** [comment]
Thanks @IlCallo , I've created a fresh project, and I think the Composition API really helps make Typescript viable in Vue (and hence Quasar!).   I really appreciate the code example Quasar creates for me--super cool!, but @rstoenescu I've noticed a bug in `CompositionComponent.vue`.

The reason for the bug is documented [in the official docs](https://composition-api.vuejs.org/api.html#setup) (scroll to the phrase: "However, do NOT destructure the props object, as it will lose reactivity".  If you change the todos array most things will get updated in `CompositionComponent.vue` but you'll notice that **todoCount** is not reactive.  

To fix `CompositionComponent.vue`, add `toRefs` to the import and then change:
```
function useDisplayTodo (todos: Todo[]) {
  const todoCount = computed(() => todos.length)
  return { todoCount }
}
```
to:
```
function useDisplayTodo(todos: Ref<Todo[]>) {
  const todoCount = computed(() => todos.value.length);
  return { todoCount };
}
```
and change:
```
  setup ({ todos }) {
    return { ...useClickCount(), ...useDisplayTodo(todos) }
  }
```
to:
```
  setup(props) {
    return { ...useClickCount(), ...useDisplayTodo(toRefs(props).todos) };
  },
```
and that should do it!  If there is a cleaner way to do it please let me know.  I really appreciate Quasar.  Thanks for all the hard work.

As a side note here is my Composition API version of `Index.vue` (which can also help if you want to rest reactivity on the todos array:
```
<template>
  <q-page class="row items-center justify-evenly">
    <example-component title="Example component" active :todos="state.todos" :meta="state.meta"></example-component>
    Hi and the total is {{ state.todoCountMine }}
    <q-btn label="add" icon="add" @click="addTodo" />
  </q-page>
</template>

<script lang="ts">
import { reactive, computed } from '@vue/composition-api';
import ExampleComponent from 'components/CompositionComponent.vue';
import { Todo, Meta } from 'components/models';

interface PageState {
  todos: Todo[];
  meta: Meta;
  todoCountMine: number;
}

export default {
  name: 'PageIndex',
  components: { ExampleComponent },
  setup() {
    const state = reactive({
      todos: [
        {
          id: 1,
          content: 'ct1',
        },
        {
          id: 2,
          content: 'ct2',
        },
        {
          id: 3,
          content: 'ct3',
        },
        {
          id: 4,
          content: 'ct4',
        },
        {
          id: 5,
          content: 'ct5',
        },
      ] as Array<Todo>,
      meta: {
        totalCount: 1200,
      } as Meta,
      todoCountMine: computed(() => state.todos.length),
    }) as PageState;

    const addTodo = () => {
      state.todos.push({
        id: state.todoCountMine + 1,
        content: `ct${state.todoCountMine + 1}`,
      } as Todo);
    };

    return {
      state,
      addTodo,
    };
  },
};
</script>
```
The `PageState` interface helps you avoid Typescript errors.

**Comment by IlCallo** [comment]
I'll check your suggestion, yet I wanted to keep the example really minimal to showcase the basics of composition API.

In the meantime, thank you for your feedback!
