### ISSUE TITLE
Can I use third party font icons like Iconfont？

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#4402]
The doc says:
Material Icons, Font Awesome, Ionicons, MDI, Eva Icons and Themify Icons are supported.

Can I use other third-party fonts icon like Iconfont？
And what's the difference between supported and other third-party font icons

**Comment by rstoenescu** [comment]
Hi,

Are you referring to Quasar Icon Set or to importing any third party font icons? Because you can import any font icon that you want... and if Quasar does not have an icon set for that custom icon font, you can [PR it](https://github.com/quasarframework/quasar/tree/dev/ui/icon-set) or write that icon set in your app and tell Quasar to use it.
