### ISSUE TITLE
QRange `change` event not being emitted

### ISSUE THREAD

**Issue by BritishHumor** [quasarframework/quasar#4428]
**Describe the bug**
The quasar documentation for v1 states that QRange has a @change event which is emitted when the user releases the thumb of the range slider, this does not actually happen.

**Codepen/jsFiddle (required)**
https://codepen.io/anon/pen/PrWNQZ?editors=1011#anon-login

**Expected behavior**
Emitted value on lazy model value change (after user slides then releases thumb)

**Comment by pdanpdan** [comment]
You cannot have both `@input` (as in `v-model`) and `@change` that updates the same model because the `@input` is emitted first and it updates the model - and change will check and emit only if it is a change.
If you want you can update another model on `@input` and the model on `@change`, like here:

https://codepen.io/anon/pen/dBNpoz?editors=1010

**Comment by BritishHumor** [comment]
So there is no way to have a v-model that constantly updates as I drag, and also use a @change event to update a different model? I have to use value with @input and @change? It seems a bit tedious.

All I'm wanting to do is use the value set in v-model to update a display value, and then upon releasing the thumb update a different value.

**Comment by rstoenescu** [comment]
Bug report is valid. Will fix it.

**Comment by rstoenescu** [comment]
Fix will be available in final 1.0.0
