### ISSUE TITLE
dialog maximized on ios  

### ISSUE THREAD

**Issue by jehadja** [quasarframework/quasar#4496]
Hi, and thanks for this great and awesome framework .

i just think the maximised dialog not working correctly on new IOS ! 

it just opinion i am not imposing any thing 
as the current view test on iphone XR 
![image](https://user-images.githubusercontent.com/17106547/60346932-ea984c00-99c4-11e9-96e0-8bea5433c382.png)
which i think its not ideal specially that it have been replace modal ! 

my suggestion is to make the default style
```
.q-dialog__inner.flex.no-pointer-events.q-dialog__inner--maximized.q-dialog__inner--standard.fixed-full.flex-center
   padding: 0!important;

body.q-ios-padding
 .q-dialog__inner > div.tut-bar
  max-height: 100%!important;

.platform-ios
  .tut-bar
     .q-bar--standard
      height: calc(34px + env(safe-area-inset-top))
     .q-btn
       padding-top: env(safe-area-inset-top) !important;

```
 tut-bar is can be replace with the maximized class for the bar  

![image](https://user-images.githubusercontent.com/17106547/60347131-537fc400-99c5-11e9-86a3-df9f2d25c251.png)

thanks again !

**Comment by rstoenescu** [comment]
Hi,

Quasar needs to take into account all possible use cases (remember a QDialog does not always contains a header/footer) and so the current way that it works is correct because it's bulletproof. 

If you need a custom way to deal with QDialog, you can always create a CSS class and apply it to the QDialog content (like you did). But such a solution cannot be applied from within the framework as it would break other use cases.
