### ISSUE TITLE
ssr + cookie

### ISSUE THREAD

**Issue by dungeon2567** [quasarframework/quasar#4503]
i am using express session on the server side for storing user information but axios on server side (ssr) is not sending the cookie for auth and im using axios with preFetch

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions or for making certain your issue is a bug. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by smolinari** [comment]
Did you see this? https://github.com/expressjs/session/issues/464#issuecomment-306044124

Scott
