### ISSUE TITLE
QDate : The date passed to `options` should respect the `mask`

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#4560]
When we provide a mask to QDate, it would make sense that the date passed to the `options` callback respected that mask. Currently it's forced to YYYY/MM/DD (QDate.js line 215).

Explanation: if I provide a mask, it means that it's the format used in my app. Right now in my `options` callback I have to reformat the YYYY/MM/DD date to compare with my YYYY-MM-DD HH:mm:ss dates, I find this unexpected and impractical. Thank you

**Comment by metalsadman** [comment]
@louisameline any reproduction pen/fiddle? as i understood it only forces that `YYYY/MM/DD` format if you're using Persian Calendar as stated here https://quasar.dev/vue-components/date#Model-mask.

**Comment by louisameline** [comment]
Please check QDate.js line 215. Quasar passes a YYYY/MM/DD date.

**Comment by TobyMosque** [comment]
u would use a computed property.:
```js
computed: {
  formatedDate: {
    get () { return this.formatDate(this.date) },
    set (value) { return this.date = this.parseDate(value) }
  }
}
```

**Comment by pdanpdan** [comment]
The are lots of problems with this approach:
- because it's QDate the expected thing it's to have only the date for options/events, but the mask could be a full one with time
- the mask could be localized based on what the user wants, but the options/events could come from a DB in a normalized form
- the checks are performed lots of times (on each render for each visible day) and the conversion is not so cheap
