### ISSUE TITLE
[v1] QSelect: bug when using both `use-input` and `multiple`

### ISSUE THREAD

**Issue by matheusoluz** [quasarframework/quasar#4600]
**Describe the bug**
QSelect filter is not being cleaned after selecting a value.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/matheusoluz/pen/ZdVvQL?editors=1010

**To Reproduce**

1. Enter select field
2. Type a value
3. Select a value
4. See that the value entered will not be deleted

**Expected behavior**
Clean input filter

**Platform (please complete the following information):**
OS: Windows
Node: v10.15.3
NPM: 6.9.0
Browsers: Chrome
Quasar: 1.0.3
@quasar/app: 1.0.2
@quasar/extras: 1.1.4

**Comment by pdanpdan** [comment]
This is the expected behavior. It allows you to select/deselect other values.

**Comment by rstoenescu** [comment]
Hi,

This is not a bug, but a feature. When the QSelect is set to handle multiple values, your filter needs to stay in place, because most of the times the list has lots of options, and you might want to select something, then next element in the options list, and so on. Example: you have an option list containing tags (vue, vuejs, vuejs2, vue components), and you start typing "vue" --- you're able to easily select all of the options I just mentioned, otherwise you'd have to type same thing to filter the list over and over again. Furthermore, this behavior also allows you to quickly deselect an option if it was chosen by mistake.
