### ISSUE TITLE
q-collapsible with lazy content

### ISSUE THREAD

**Issue by druppy** [quasarframework/quasar#461]
The content of the `q-collapsible` need to be present when rendering.

If we added a `content_load` function property, we could use this like we use `handler` function in the `q-infinit` component. 

Or, even better ... we could let the content of the `q-collapsible` use `v-if` instead of `v-show`, as this also will allow for a late rendering of the content. This solution seems most simple, but this could challenge the rendering of the component, I guess.

**Comment by stephentuso** [comment]
Just to be clear, is the issue that you are loading the content asynchronously, and you only want to load it once the collapsible is opened? If so, the right thing to do might be to make `q-collapsible` emit open/close events, then you could listen to the open event and load your content. `v-if` probably shouldn't be used, because it completely recreates the content every time it is toggled, which could be an expensive operation and isn't ideal for something that will likely be toggled often.

**Comment by druppy** [comment]
The `open` and `close` emit would help load data, but I like to have some complex content (dynamically generated), and having to pay for a total DOM rebuild sounds like a fair price here.

Maybe a combination if `v-if` and `v-show`, where we only render the content first time and hides it for the rest of the time, and the two emit's could still be used to load data into a already rendered tab (like live data). Both cases are useful, really

**Comment by smolinari** [comment]
Could you please explain a bit more in detail what live data is or what the use case would be? It is for my own curiosity. 😄 

Scott

**Comment by druppy** [comment]
An example could be live weather data where each collapsible contain a country, and when you open one of these, it starts the collection of live information for this country, and update the content using this data.

My current need is more a one time rendering of the content, but lazy on demand to keep the initial rendering as cheap as possible.

Does that make sense ?

**Comment by smolinari** [comment]
Yes. Completely. Thanks for the explanation. An actual solution is above my head currently, but I am interested in how you do get it resolved. I'm learning. 😄 

Scott

**Comment by druppy** [comment]
I am happy to be able to help :-)
