### ISSUE TITLE
[v1][Feature] QIcon color customization when using custom svg

### ISSUE THREAD

**Issue by gpasini** [quasarframework/quasar#4681]
**Is your feature request related to a problem? Please describe.**
When we use the `QIcon` component with a custom `.svg` (ex: `<q-icon icon="img:statics/my/path/to/some.svg" />`, the `color` attribute is not used because the `.svg` is wrapped in a `<img>` tag

**Describe the solution you'd like**
Maybe add a new way to use custom icons like this : `<q-icon icon="svg:statics/my/path/to/some.svg" />` that would render a `<i>` tag so the `color` attribute can be used

**Describe alternatives you've considered**
Any other way to customize the icon color when using a custom `.svg`.

**Comment by Globulard** [comment]
Would totally like this to be implemented. Having no proper way to use custom icons (eg. not being able to use `active` classes with them) is a real problem for me.

**Comment by lukadriel7** [comment]
Hello, I have been looking for some ways to customize icons too. I stumbled upon [@mdi/js](https://www.npmjs.com/package/@mdi/js) and [@mdi/react](https://dev.materialdesignicons.com/getting-started/react) . It is easy to use and the implementation doesn't seem to be too hard. You can check the link and judge by yourselves.
Personnaly, if no one else wants to do it, I will try doing it and make a pull request. It might be a good training since I am a beginner in vue and quasar. So let me know what you think about it and if I should make a pull request for it.
Have a nice day

**Comment by rstoenescu** [comment]
Hi,

For a complete description of how can this be done, please head over to: https://quasar.dev/vue-components/icon#Images-instead-of-webfont

**Comment by rstoenescu** [comment]
Especially check the Dynamic svg example.

**Comment by rstoenescu** [comment]
RFC to watch: https://github.com/quasarframework/quasar/issues/6027
