### ISSUE TITLE
QButtons are misaligned when used in QDialog

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#4713]
**Describe the bug**
In Chrome, QButtons with icons have text displaced by 1px when used in QDialog

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dsl101/pen/jgbXWo

**To Reproduce**
1. Go to the codepen
2. See the text baseline in the 2 buttons is aligned
3. Click on either Open button
4. See the text baseline in the buttons in the QDialog is not aligned

**Expected behavior**
The baseline of the text in the buttons should be aligned, whether or not they have icons, when used in a QDialog

**Screenshots**
Scaled up screenshot: 
![image](https://user-images.githubusercontent.com/900542/61653435-3089bc80-acb2-11e9-986c-c44ca2d6a9f3.png)

**Platform (please complete the following information):**
OS: Window 10 Pro 64-bit
Node: 10.16.0
NPM: 6.9.1-next.0
Yarn: 1.16.0
Browsers: Chrome 75, Chrome 77.0.3854.3 (Official Build) dev (64-bit)

Note this appears to only be a Chrome issue—Firefox display looks OK.

**Comment by pdanpdan** [comment]
It looks more like a rendering glitch, probably related to the 3d rendering context triggered by QDialog. I changed the codepen a little to be easier to check: https://codepen.io/anon/pen/XvjmNz.

But on Windows Chrome Dev 77.0.3854.3 it does not appear. Sorry, I hope it'll get fixed in the browser.
