### ISSUE TITLE
Allow HTML in table

### ISSUE THREAD

**Issue by dennisdup** [quasarframework/quasar#4735]
**Is your feature request related to a problem? Please describe.**
Allow HTML in <td></td>. I would like to use icons in the table fields. Or include link tags. currently not possible to do so
**Describe the solution you'd like**
Would be better to make it possible on the format options for columns, to include mark up. Not just work with data.
**Describe alternatives you've considered**
Currently, I have to work with a different data table that is more flexible. Cannot seem to see a way around this since HTML tags are rendered as text.
**Additional context**

**Comment by nancoder** [comment]
You can use scoped slots to achieve this. Please take a look into https://quasar.dev/vue-components/table#QTable-API and search for the slot body-cell-[name]

**Comment by dennisdup** [comment]
Figured it out. Thanks.

**Comment by ronfak** [comment]
Having only a slot approach to customize a cell is definitely a bad strategy.
It's fine in a lot of simple cases, but as soon as we try to do something a little more complex that's just going to fall and we see the whole limit in the Table component.

For example, in a grid that we want to customize (in the same way), let's say a boolean value, we need to create the slot template for as many columns as we need. This can easily get very big.
If the columns are created dynamically when we load the data, it simply becomes impossible to do so because we can not predict the column's name to create slot.

Allowing the classes property in the column definition to get a function, (like format does) would be perfect. Or allow the use of an external component as a renderer. Or simply a way to disable the html sanitization on the format function would have been enough to inject font icons or other .

For now, it's just good to display text in a standard way.

**Comment by rstoenescu** [comment]
@ronfak u can use the specific column slot. u don't have to define all the columns....

**Comment by ronfak** [comment]
I'm sorry, I don't see how this could work.
The columns are not known at the time of design. When the data is loaded, I define the columns by pushing them to columns [].
The order of the columns and the type of columns are only known when I push them into the columns table (when loading data from the server).

So I may have few boolean types in which I want to display a "thumb up" icon (just an example). And I may also have other types of columns for which I want a specific design.

As far as I know, slots are defined at design time with body-cell-[name] where name must be unique per column, so how can I define it once for several columns with the same type?

I'm not a pro at Quasar or Vue, and so far, the only thing that has disappointed me with Quasar is this Table that just lacks a few elements to be very good and perfectly expandable.

**Comment by rstoenescu** [comment]
QTable has everything baked in. Use dynamic slot name if you only know the col name at runtime...

```
<template v-slot:[dynamicSlotName]>
```

**Comment by smolinari** [comment]
@ronfak - Expanding on what Razvan just said, in some way your data has to be formed to fit the table, not the table has to fit your data. By that I mean, your data needs some sort of metadata to form the table properly (i.e. the columns) to match your data. There is no way to fit your data, as it is, and have all the columns "just work". 

In other words, in some way you MUST define the columns array. It is either in some dynamic manner with the data you get from the server or from the server itself. Once you've done that, you know what your columns are (the naming) and can render the slot as you will. See here for a small example. 

https://codepen.io/smolinari/pen/XWmRwQB?editors=1010

Scott

**Comment by ronfak** [comment]
Of course, the columns are defined ! The data is read from the server, and then the columns are built from it. And it works very well. But my point is different.

To put it simply, let's see the Codepen you just sent.

You have there a template, with a v-slot (dynamic name or not, is not this the problem so far).

So the "name" column will use this slot and will then be rendered based on this template.

Now, what happens if other columns want to use the same template? And I don't know right away how many columns I'm going to have that want to use it.
(Use one template for several columns).

Now I am thinking I could use a v-for directly in the templates (actually, I didn't know that the v-for was compatible with template) and with the v-slot defined by this v-for... I'll try it later tonight.

**Comment by ronfak** [comment]
Thank you, using v-for on the slot template was the way to go to use make a multi-column template, I wouldn't have thought of it without your comments.

**Comment by smolinari** [comment]
You must build your column definition at some point. Once you've built it, then you know what is being built and can "slot in" any template you want. You could also use the `:is` attribute with the standard column slot and dynamically set the template that way.

https://codepen.io/smolinari/pen/WNQjVBN?editors=1010

Scott
