### ISSUE TITLE
Time picker's 24-hour format clock is incorrect

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#4755]
The right 24h clock should be:
![24h-clock](https://user-images.githubusercontent.com/4423905/62023354-1cd6dc80-b203-11e9-9bbe-b2933ba788d7.jpg)

**Comment by pdanpdan** [comment]
Citation please? According to Android the current one is the valid one.

**Comment by bigradish** [comment]
Hi,
The link you provide belongs to a personal site.
Do you think 0 directly going to 13 is correct?

**Comment by pdanpdan** [comment]
Please check the native Android time picker.

**Comment by louisameline** [comment]
The perception of time differs from country to country I guess.

Android's native clock starts at 1 and finishes at 0 (midnight).
Bigradish's clock starts at 0 and finishes at 23.

**PROS** Bigradish's clock actually makes more sense to me from a logical point of view, because the 0 that comes after 23 in Android's clock is actually the first hour of the next day in my opinion, and mathematically the figure 0 does come after 23 nor does it come before 13, so yeah it's strange.

**CON** On a 12hour clock, the number at the top is 12, so I understand that Android's developers wanted to keep it that way.

My preference, for what it's worth, goes to Bigradish's clock.

![image](https://user-images.githubusercontent.com/371814/62109745-392f5380-b2ad-11e9-9b7c-b422663b63dd.png)

**Comment by hawkeye64** [comment]
I have always felt the same way about this, that the 0 and 12 should be swapped. Just my 2 cents.

**Comment by olegvakulenko** [comment]
https://github.com/quasarframework/quasar/issues/2504

**Comment by bigradish** [comment]
Hi @pdanpdan,
The picture is from Vuetify. I feel its clock is better.

**Comment by hawkeye64** [comment]
Closing this one as https://github.com/quasarframework/quasar/issues/2504 is also closed and they are same thing.

**Comment by louisameline** [comment]
This would be an improvement though to offer the choice. Other people might open tickets again. Closing means it's a won't do? Just asking.

**Comment by hawkeye64** [comment]
My bad. I mistakenly though PDan had closed the other one. Yes, you are correct. This could be controlled by a prop.

**Comment by rstoenescu** [comment]
Updated and will be available in v1.1.1.
Seems like latest Android has the clock wheel changed.

![time](https://user-images.githubusercontent.com/4665641/64495395-1461cf00-d2a2-11e9-8c2b-2e057f3c13d7.png)
