### ISSUE TITLE
QInput with autofocus inside a vertical QStepper throws QStep overlap

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar#4811]
**Describe the bug**
When using QInput with autofocus inside a vertical QStepper the QStep overlap each other

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/anon/pen/NQwBwb?&editable=true&editors=101

-- EDIT

**Codepen/jsFiddle/Codesandbox (updated) - not working**
https://codepen.io/heartbeatLV/pen/mdbqWWz?&editable=true&editors=101#_=_

**Comment by rstoenescu** [comment]
Thanks for reporting!
Fix will be available in 1.0.6.

**Comment by heartbeatLV** [comment]
**Thanks for solving!**
However in the codepen happens anyway if the input is of type number :(
any reason?

**Codepen (updated)**
https://codepen.io/heartbeatLV/pen/mdbqWWz?&editable=true&editors=101#_=_

**Comment by rstoenescu** [comment]
After each release, the CDN must do its work, and this may take a bit (24 hrs, sometimes even more).

**Comment by heartbeatLV** [comment]
Still not working

**Comment by pdanpdan** [comment]
The last codepen seem to be working just fine for me (Chrome windows). Can you please give more details on the problem?

**Comment by heartbeatLV** [comment]
I'm using firefox on windows

**Comment by heartbeatLV** [comment]
hello, are there any news?

**Comment by pdanpdan** [comment]
Sorry, I missed your answer. Yup, firefox broke it big time. I'll try to find something.

**Comment by rstoenescu** [comment]
Final fix will be available in "quasar" v1.2.0.

**Comment by RoelRoel** [comment]
This bug is still occuring in quasar v1.16.0 in Chrome 96

I have a numeric input in a QStep with autofocus. If you open this step sometimes (not all the times) the steps overlap.
The strange thing is that when you move the div in the dom and move it back it looks normal so it seems a bug in Chrome or something.

I now use an (ugly) work-around to focus the field with setTimeOut in the mounted event of the component that contains the q-input.

![image](https://user-images.githubusercontent.com/531248/145583178-c3673256-f65d-4ca6-8ebd-4f2fefe83edb.png)
Note: This screenshot is just for illustation from an old version of Quasar (v0) but this issue still occurs in the latest v1.
