### ISSUE TITLE
Font Awesome 5 icons render larger than default (Material) icons

### ISSUE THREAD

**Issue by jesperhoy** [quasarframework/quasar#4858]
**Describe the bug**
Font Awesome 5 icons render larger than default (Material) icons.
I would like to only include one icon font in my project (in oder to reduce overall size) - but it doesn't look as nice when the icons are oversized like this.
When mixing Material and Font Awesome it looks even worse.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/jesperhoy/pen/KOGdpX

**To Reproduce**
Use Font Awesome 5 with Quasar.

**Expected behavior**
Same icon sizes as default (Material) icons.

**Screenshots**
![image](https://user-images.githubusercontent.com/12099212/62809126-5c9e9d80-bafa-11e9-9ae0-1c6484208c18.png)

**Platform (please complete the following information):**
Any (tested in Windows/Chrome)

**Additional context**
none.

And lastly - thanks for an awesome framework :-)

**Comment by rstoenescu** [comment]
Hi,

This is a source of frustration for me too. Unfortunately, each icon library has a different grid used for the webfont. From what I noticed, Fontawesome chose to fill this grid the way it is so that you'd be more incentivized to choose the "Pro" version.

Bottom line, there is nothing we can do from within Quasar for this :(
