### ISSUE TITLE
QInput with mask/fill-mask has odd behavior causing cursor jump and model mismatch

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar#4878]
**Describe the bug**
This is hard to describe. I'll attempt, byt I also made a codepen where this can be viewed.

First, take two QInput's similar, but one has `fill-mask` and `clearable` properties set, but both are using the same model.
A couple of issues to observer:
1) The one with `fill-mask` will have the cursor 'jump' around and isn't necessarily matching where it's being typed.
2) When typing in the `fill-mask` version, the second one that does not have `fill-mask`set, does not match. Even though they are using the same model. However, typing in the non-fill-mask version always works for the `fill-mask` version.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Hawkeye64/pen/MWgabmx?&editable=true&editors=101

https://codepen.io/Hawkeye64/pen/gVVNWL?editors=1010

**Comment by qwesda** [comment]
Here is a more reduced case for the models getting out of sync: https://codepen.io/qwesda/pen/pozjPbx

The issue is related to this `this.stopValueWatcher` being set to true here:
https://github.com/quasarframework/quasar/blob/f10606905d2d6b3fc93e0e88ffd2a2a1926955f2/ui/src/mixins/mask.js#L266
https://github.com/quasarframework/quasar/blob/f10606905d2d6b3fc93e0e88ffd2a2a1926955f2/ui/src/components/input/QInput.js#L122-L135

which causes the new value to be ignored here:
https://github.com/quasarframework/quasar/blob/f10606905d2d6b3fc93e0e88ffd2a2a1926955f2/ui/src/components/input/QInput.js#L31-L40

**Comment by hawkeye64** [comment]
This is no longer an issue with bleeding edge, because the cursor stays at the end of the input mask. Which I am fine with.
Is this the desired behavior now? If so, this issue can be closed.

**Comment by rstoenescu** [comment]
Fix will be available in v1.1.1
