### ISSUE TITLE
q-select and required break validation with no errors when using Vuelidate

### ISSUE THREAD

**Issue by edgarciametro** [quasarframework/quasar#488]
Doing something like below where the "required" is entered in the element fully breaks validation and gives no error about issue. I know this is not mentioned as an option in the docs, but many people are used to include it. 

Solution is to ONLY use required in the validations, never on element.

              <q-select
                type="list"
                class="full-width"
                label="Treats"
                v-model="newVisit.treat"
                :options="treatOptions"
                :class="{'has-error': $v.newVisit.treat.$error}"
                required 
              ></q-select>

Great work on this framework!

### Software version

Quasar: 0.5.2
OS: OSX latest
Node: 6.10
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment]
Hi,

Thank you for your kind words. Stay tuned for next release (v0.14) ;)

As long as there are good libraries out there like Vuelidate, Quasar will never handle validations with its own engine because it would only mean reinventing the wheel. So, in this case, please fully adhere to Vuelidate's way of validating forms, which means importing the `required` rule and assigning it to the model.

Cheers,
Razvan
