### ISSUE TITLE
Possibility to add extension from another extension

### ISSUE THREAD

**Issue by gbouteiller** [quasarframework/quasar#4922]
**Is your feature request related to a problem? Please describe.**
First of all, thank you for the amazing job made with Quasar.
I'm currently playing with app extensions as it is described as the way to create a clean starter.
I've already created extensions to cover my needs but instead of invoking them sequentially, I wonder if there is a way to create kind of a "meta" extension to install them automatically.
I've seen the `hasExtension` in the API but no `addExtension`.

**Describe the solution you'd like**
Possibility to add extensions from another extension in Quasar API

**Describe alternatives you've considered**
I ended up using [execa](https://github.com/sindresorhus/execa) with the `quasar ext add` command but it only works because I don't have any prompts yet

**Comment by nothingismagick** [comment]
This is indeed something we discussed - and although I can't remember the exact reasoning it was decided not to enable this on an API level. We should probably make a note of that in the docs.

Anyway, I have indeed created two official app extensions that work this way.
https://github.com/quasarframework/app-extension-testing
https://github.com/quasarframework/app-extension-wizard

For brevity's sake, I encourage you to look at wizard, esp. because it is using a newer version of execa. I haven't gone back and updated the testing meta-harness.

**Comment by nothingismagick** [comment]
And - by the way - exciting stuff with niama 👍

**Comment by gbouteiller** [comment]
@nothingismagick Thank you for your reactivity, I'll check the repositories you linked and update mines :). By the way, thank you for mentioning niama. I love what you guys did and keep doing with Quasar and I try to adapt my previous tools to embrace it and consolidate my own projects. Also, I haven't taken time to answer to your issue on niama's repository but I'll do as soon as I update everything. Thanks again

**Comment by nothingismagick** [comment]
@gbouteiller - I'd love to talk with you about considering coming onto one of the next Quasar Radio Shows. Please join the https://chat.quasar.dev and ping me if you're interested.

**Comment by gbouteiller** [comment]
@nothingismagick thank you for your offer that I'd have accepted with joy if my english wasn't that rusty :D .

**Comment by rstoenescu** [comment]
Accurate example can be found in https://github.com/quasarframework/app-extension-wizard, like mentioned earlier. So closing.
