### ISSUE TITLE
Error in callback for watcher "value": "TypeError: Cannot read property 'desktop' of undefined" found in <QMenu>

### ISSUE THREAD

**Issue by nikoz84** [quasarframework/quasar#4930]
I have this problem when import a new QSelect component, 

`
app.js:67460 [Vue warn]: Error in callback for watcher "value": "TypeError: Cannot read property 'desktop' of undefined" found in 
---> <QMenu>
       <QSelect>
         <SearchForm> at resources/assets/js/forms/SearchForm.vue
           <Table> at resources/assets/js/components/Table.vue
             <Listar> at resources/assets/js/components/ListAdmin.vue
               <Admin> at resources/assets/js/pages/Admin.vue
                 <QPageContainer>
                   <QLayout>
                     <Default> at resources/assets/js/layout/Default.vue
                       <Main> at resources/assets/js/layout/Main.vue
                         <Root>
`

I use quasar without quasar CLI in standalone way, my app file look that way

![Captura de tela de 2019-08-20 08-37-28](https://user-images.githubusercontent.com/6708508/63344523-02d27a80-c327-11e9-9f68-80bb8f9ebdb6.png)

And when debug in the transpiled file app.js 

![Captura de tela de 2019-08-20 09-09-16](https://user-images.githubusercontent.com/6708508/63346281-ffd98900-c32a-11e9-8819-a43f45629030.png)

Thanks

**Comment by yusufkandemir** [comment]
@nikoz84 you need to provide more information. Also as you are using the UMD version, you don't need to use `Vue.use(Quasar, //...`, Quasar UMD already calls that for you. If you need to change the `iconSet`, you need to do `Quasar.iconSet.set(Quasar.iconSet.fontawesomeV5/* or something else */)`, MaterialIcons is already the default so you can remove the `Vue.use(Quasar, //...`, part completely. You can check [the docs for icon sets](https://quasar.dev/options/quasar-icon-sets#UMD-Way).

@smolinari I think you will take care of this issue. The problem is about the Platform plugin. One call for that plugin that produced an error is in [here](https://github.com/quasarframework/quasar/blob/35e78f7fb710d2cfb879a380b13d41976c57a6bb/ui/src/components/menu/ClickOutside.js#L86). The place where the Platform plugin is installed is [here](https://github.com/quasarframework/quasar/blob/4691db529a1b4055b2c198888f6c9eb6f1fdf484/ui/src/install.js#L26), definition of the called `install` method is [here](https://github.com/quasarframework/quasar/blob/913f0024c373c5d01f5ad7c2c1047e55bbbda44c/ui/src/plugins/Platform.js#L266).

**Comment by smolinari** [comment]
Thanks @yusufkandemir. 

@nikoz84 - Are you using Vue CLI and attempting to "plug-in" Quasar?

Scott

**Comment by smolinari** [comment]
Also, looking at a plugged-in Quasar, the code to get it plugged-in looks like this. 

```
Vue.use(Quasar, {
  config: {},
  components: {
    QLayout,
    QHeader,
    QDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QIcon,
    QList,
    QItem,
    QItemSection,
    QItemLabel
  },
  directives: {
  },
  plugins: {
  }
})

```
So, bottom line, you need to explain better how you've gotten Quasar set up. UMD or Vue CLI plug-in or some other fashion. The first two are the supported ways. Anything else is not supported. 

Scott

**Comment by rstoenescu** [comment]
@nikoz84 
Please clarify your setup. Are you using Quasar CLI / Vue CLI / UMD?

**Comment by rstoenescu** [comment]
Any barebones repo with your setup would be immensely helpful for us in order to help you.

**Comment by nikoz84** [comment]
i'm not use quasar cli / vue cli or UDM. I use Laravel Mix and i install  like a NPM packege. 
![package json](https://user-images.githubusercontent.com/6708508/64199260-4ae1b900-ce60-11e9-9731-d202eb5f2672.png)

Only this component fail when i import in a vue file.

![Captura de tela de 2019-09-03 15-44-20](https://user-images.githubusercontent.com/6708508/64200448-ed02a080-ce62-11e9-8cfd-777bfbbb4cfd.png)

**Comment by nikoz84** [comment]
![Captura de tela de 2019-09-03 15-59-44](https://user-images.githubusercontent.com/6708508/64201358-e37a3800-ce64-11e9-9632-25db5bff8f83.png)
![Captura de tela de 2019-09-03 15-59-59](https://user-images.githubusercontent.com/6708508/64201359-e412ce80-ce64-11e9-9bcb-b50fa850b261.png)
![Captura de tela de 2019-09-03 16-00-23](https://user-images.githubusercontent.com/6708508/64201360-e412ce80-ce64-11e9-84ca-2c06d4cefcae.png)

**Comment by rstoenescu** [comment]
Ok, I see now.

The part with `Vue.use(Quasar, ...)` is extremely important. That, along many other things, installs the "Platform" Quasar plugin. Without it, "this.$q.platform" (and many others) will NOT be available and will break your app.

So make sure that on the client-side, `Vue.use(Quasar, ...)` is run before your app is kicked off (`new Vue(app)`).

I also notice inconsistencies into your app:
* you have the old "quasar-extras" package (which is meant to work with <= v0.17) instead of "@quasar/extras"
* you're loading material-design-icons and roboto-fontface instead of relying on "@quasar/extras"

**Comment by nikoz84** [comment]
Thanks

**Comment by nikoz84** [comment]
If someone want the solution, i update de quasar extras, and in the app.js pass the Quasar object with the options. Thanks and sorry for my terrible english @rstoenescu @smolinari smolinari
```
import Vue from "vue";

import Quasar from "quasar";
import "quasar/dist/quasar.ie.polyfills.umd.min.js";
import lang from "quasar/lang/pt-br.js";
import materialIcons from "quasar/dist/icon-set/material-icons.umd.min.js";
import "@quasar/extras/roboto-font/roboto-font.css";
import "@quasar/extras/material-icons/material-icons.css";

Vue.use(Quasar, {
  lang,
  iconSet: materialIcons
});
```

![Captura de tela de 2019-09-03 19-26-57](https://user-images.githubusercontent.com/6708508/64213013-c43dd380-ce81-11e9-939e-5637468bd05d.png)
![Captura de tela de 2019-09-03 19-27-52](https://user-images.githubusercontent.com/6708508/64213014-c43dd380-ce81-11e9-97de-2dd0359a84dc.png)

**Comment by shandrolis** [comment]
I'm getting the same error as above, except it only occurs when I compile my own component-library (that builds on top of quasar), and then import that into a different project.

My project is also a Vue app that plugs in Quasar.

However, I do correctly (to my knowledge) do Vue.use (quasar, {<options>}) in my main.ts, and all my packages are up-to-date with the latest versions of quasar.
![image](https://user-images.githubusercontent.com/10201423/67269384-eda8d200-f4b6-11e9-9080-e5f6d8ae555f.png)

![image](https://user-images.githubusercontent.com/10201423/67269464-15983580-f4b7-11e9-8664-0bdffb419d23.png)



The issue seems to originate from utils/escape-key.js that tries to make use of the Platform plugin.

After editing the (minified) file directly in my browser (console>sources tab in chrome) with some console.logs, I get the following.

![image](https://user-images.githubusercontent.com/10201423/67270051-25fce000-f4b8-11e9-9f9c-280638016a65.png)
![image](https://user-images.githubusercontent.com/10201423/67270106-3f059100-f4b8-11e9-9dde-8bf03a122f55.png)


If I change the if-statement as seen in the screenshot in my node-modules directly in both my component library and my web-app into the following, I can use the dropdowns (components that use q-menu) just fine!
`    if (Platform.is === undefined || Platform.is.desktop === true) {`

Obviously this would likely bug out the mobile view, so that's not much of a permanent solution.
