### ISSUE TITLE
When q-input's "error-message" prop is set, the error message does not change when other errors occur.

### ISSUE THREAD

**Issue by bigradish** [quasarframework/quasar#4997]
It will be better that after q-input's "error-message" prop is set for an error, the user does some actions which incur a new error, the new error message should be shown.
Thanks.

**Comment by rstoenescu** [comment]
Hi,

Please supply a codepen like requested. This sounds like a misunderstanding, so want to eliminate this possibility first. Thanks.

**Comment by bigradish** [comment]
Hi @rstoenescu ,

See this codepen: https://codepen.io/bigradish/pen/ZEzJymp
Click the button, an error msg will be shown, then input chars more that 5, the new error will not be shown.
Thanks.

**Comment by rstoenescu** [comment]
Hi,

The problem is that you're using both internal validation and external validation. Only pick one of them.
External (`error` + `errorMsg`), internal (`rules`).

In your example, you're setting `error` to `true` through the notify(), so no matter the content of the input field, you are forcing the errorMsg to be shown.

**Comment by bigradish** [comment]
Hi @rstoenescu,
Why only of internal validation and external validation can be picked? I think this is a bad design.
I have the need to mix them. Would you change the design?
Thank you.

**Comment by rstoenescu** [comment]
Because you can't have two sources of truth.

You either handle it with the external validation (which is also a way with which you can use some validation packages), or you use the internal one.

You can't have both because how is the component suppose to detect when it's in an error state? When you set "error" to true or when one of the rules fails? In your case, you're setting "error" to true, but then you expect the real source of truth to be rules...

However, why are you not using rules to handle both your states?

```js
:rules="[ () => error || errorMsg, .... ]"
```

**Comment by bigradish** [comment]
Hi @rstoenescu ,

Thanks for your answers.
IMO, the validation of a component or a form should be considered as a whole.
When we determin if a component or a form is in an error state, we should check both the "rules" and the "error" props.
In my use case, I want to check if the name a user inputed is duplicate remotely. As setting a interval (in your word: "debounce") to do this is not ideal, I prefer doing the checking in the "blur" event of the component. If it is duplicate, the "error" and "errMsg" are set to prompt the user.
Please consider.
Thank you very much.

**Comment by modemb** [comment]
@bigradish  both of them can work, just did it

**Comment by flowt-au** [comment]
@bigradish Could you post a codepen showing how you did that please? I can't make it work and @rstoenescu explains why. If there is a workaround I would love to see how you accomplished that.
Thanks! :-)

**Comment by bigradish** [comment]
@flowt-au , I have no other ideas. I just check the duplication after form submission, which leads to a lower user experience. Another option is to use an external validation package to do the whole validation work.
@rstoenescu , It seems that this issue may be met by other users of Quasar. I still think it will be better to combine the two sources of truth (internal and external) into one. Hope you can consider this. Thank you.

**Comment by flowt-au** [comment]
@bigradish Ok. Ta. I f I come up with a generalised solution for this pattern that works I will post back here. I would prefer to have a way to do this without a 3rd party library, at least initially.

**Comment by flowt-au** [comment]
Ok. This seems to work pretty well:
[https://codepen.io/flowt-au/pen/PoWZBJj?editors=1010](https://codepen.io/flowt-au/pen/PoWZBJj?editors=1010)

The logic is:

1.  Validate locally first. If invalid, do not allow submit
2. If locally valid, submit to server
3. If the server returns an error attributed to the field in question: 
         - display the error message on that field.
         - disable the submit button since that value is invalid 
4. Otherwise, all good.
:-)
Murray

**Comment by bigradish** [comment]
@flowt-au Certainly, you can achieve this by changing the "error" and "error-message" (external validation) manually to let the internal validation work or not. But what I mean is Quasar should perform internal validating no matter if there is an external validation error.

**Comment by flowt-au** [comment]
Ok. Yes, I understand what you mean. No worries. This pattern works for my purposes.
Cheers,
Murray

**Comment by bigradish** [comment]
@flowt-au Thank you. I'd like to summarize your pattern, for that should work in most cases.

1. Watch the field you are validating. When it changes, reset the "error" and "error-message" props to let the internal validation work.
2. On the q-input's blur or other events, perform the external validating, and if there is an error, set the "error" and "error-message" props of q-input to show it.

Thank you for your sharing. :)

**Comment by flowt-au** [comment]
As someone fairly new to Vue and Quasar I am very happy to have contributed something useful back to this great framework and helpful community members. :-)

**Comment by Chipop** [comment]
`<q-input
          v-model="formState.password2"
          type="password"
          label="Confirm your password"
          bottom-slots
          :rules="[
            (val) =>
              val === formState.password1 ||
              'Password and password confirm do not match.',
          ]"
          :error-message="remoteValidation.password2"
          :error="remoteValidation.password2.length > 0"
          @change="() => (remoteValidation.password2 = '' )"
        />`

Just added `@change="() => (remoteValidation.password2 = '')"`, and this works well for me without the need for watching
