### ISSUE TITLE
[docs] "Tab to search" functionality for docs

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#5013]
This feature allows you search a page directly by just typing its URL and "TAB"  key. It works on Quasar forum for example (but also on YouTube, Facebook, StackOverflow etc.).

This would be very handy, because you can skip two steps when looking up a docs page.

What we need to do to achieve this:
 1. Sync search input with URL query (or route param, but query is probably easier with current setup)
 2. Add a search manifest xml file with url template (it's like 5 lines, very simple file)
 3. Make sure that loaded page shows the results in popup

Advanced:
 4. We could also fetch search results on the server and redirect user directly to the top result (with search popup still open, I guess). That's probably more complicated work, though.

reference: https://www.chromium.org/tab-to-search

**Comment by rstoenescu** [comment]
This is a great idea, but there's one thing holding us back. We do not provide the search ourselves (have outsourced this to Algolia).

So we can't fill the manifest xml with anything like below, because we don't have any registered URL for searching.

```xml
<Url type="text/html" method="get" template="http://my_site/{searchTerms}"/>
```

However, maybe we can create such a page and connect it to Algolia (lot of work for this).
