### ISSUE TITLE
@input event not working in QTabPanels

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#5032]
When the tab changes, there is no `input` event that gets emitted. Try it here:

https://codepen.io/Louis99/pen/OJLzXvO?&editable=true&editors=101

This event should exist as documented here:
https://quasar.dev/vue-components/tab-panels#QTabPanels-API

**Comment by pdanpdan** [comment]
It's not emitted because the model is already changed by you before.
The event is emitted if the tab is changing the model, not if the model changes the tab.

**Comment by louisameline** [comment]
What do you mean "if the tab is changing the model"?

How could the panels change their own model? The only possibility for this to happen is with `swipeable` I guess, and it doesn't trigger the event either.

FYI, my pen uses an example from the doc with QOptionGroup but I use QTabs in my own app and the result is the same.

**Comment by pdanpdan** [comment]
Exactly, by using `swipeable`, like here: https://codepen.io/pdanpdan/pen/xxKpEwE?&editable=true&editors=101

**Comment by louisameline** [comment]
I see. I thought it didn't work but that's because I had an error due to the fact that it's triggered before the rendering of the new tab.

Anyway I think it should be clearly stated in the doc that only a swipe will trigger this event.
Or maybe it should not be documented at all, because I see no use in using this event rather than `before-transition`.
Or it should be `@swipe` to make it obvious what it does.
Thank you

**Comment by pdanpdan** [comment]
This event is the one that changes the model.
In Vue `v-mode="x"` is shorthand for `:value="x" @input="v => { x = v }"`.

**Comment by louisameline** [comment]
Ok I understand that it's used internally and will stay that way. But still the documentation is partial and thus misleading:

> @input -> function(value): Emitted when component's model changes (current panel name); Is also used by v-model

**Comment by louisameline** [comment]
Should be at least

> Emitted when the component's model changes due to a swipe (current panel name); Is also used by v-model

Do you want a PR for this edit?

**Comment by rstoenescu** [comment]
@louisameline Hi,

This is related to a basic concept in Vue. The communication between components.

1. Components receive data from the outer scope through properties (so going from outside into the component) and the components can emit events to the outer scope (so going from inside to outside).
2. Say you have a template with QTabPanels, and the scope of themplate has a "tabName" variable. When you change tabName by yourself (direct assignment to another value), the information goes into the QTabPanels (and QTabPanels switches to the according tab panel). When you swipe on the component, the flow of information travels in reverse. It's QTabPanels that must update tabName --> so information going from inside to outside. (Same applies to any vue component that supports v-model, in the sense that it means that the component needs to also update the outer scope variable too after some action or logic; in the case of QTabPanels, it has the action of swiping that must communicate to the outer scope of this change)
3. In Vue, there's "v-model" who is a syntactic sugar for this type of communication. It is the perfect equivalent of `:value="tabName" @input="val => { tabName = val }"`. `:value="tabName"` sends information into the component, while `@input` event receives information from inside of the component towards the outside (this outside is your Vue component where you are using QTabPanels in the template).

This is basic Vue knowledge that everyone must be aware of, so I do not think the docs are misleading in any way. We, as Quasar, should not teach the basics of Vue in our own docs as it is not our purpose to duplicate the Vue documentation. However, when there are cases of misunderstood information, we do our best to fill Vue knowledge gaps, like in this ticket, because we value donators.

I hope this eliminated any confusion on how v-model works and what the meaning of "value" and "@input" have.

**Comment by louisameline** [comment]
Thank you for the explanations. I've been using Vue on a personal side-project only for a year or so, picked up on it at the same time as Quasar actually, so I'm not yet an expert indeed.
I must say I vaguely knew this already but I don't always connect the dots.
Vue's learning curve makes it possible to start creating apps very fast, without the need to master all the details at first hand, and that's part of what makes it great.

Now I guess you could put a watcher on the model of the component and trigger the `input` event whenever it changes if you wanted, although surely it would be an anti-pattern?
Anyway, the bottom line is that I didn't challenge the documentation when it said
> input is emitted when component's model changes

The sentence is semantically wrong, I think this much can't be argued. No, `input` is not always emitted when the component's model changes. It's more like:

> input is emitted when the component changes the model

Probably a better Vue user will have the implicit knowledge to correct this sentence. I respectfully disagree and still think it's misleading for people like me who don't think enough about it :)
Thank you anyway
