### ISSUE TITLE
Allow to generate component library with Quasar

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/quasar#5063]
**Describe the solution you'd like**
There are two situations that aren't supported currently that require an enhancement on `quasar-cli` in order to allow building a standard component library (not quasar's app extension mechanism). There are at least two use cases for this feature request:
1. Create a component library to be used on plain Vue projects
2. Create a [Web Component](https://www.webcomponents.org/) to be used on any Web project (react, plain html, etc)

I built the following scenario without full success:
 - Project A: A vue-cli + quasar (as plugin) and using `vue build --target lib`, and `npm publish`
 - Project B: A plain Vue-cli project that includes Project A as JS dependency

The only problem I currently have with that scenario are Quasar styles. I've tried to following without success:
1. Inject the Quasar stylesheet as UMD ( `<link href=...`). 
   The problem with this approach is that quasar redefines some top level tags (h1,h2,etc) that affect the Project B's stylesheet.
2. Include the Quasar stylesheet with:
 ```
<style lang="stylus" scoped>
@import('../../node_modules/quasar/src/css/index.styl')
```
The problem with that approach is that it doesn't fully work, and is also a bit messy to make that inclusion.
3. I also tried the following manipulating webpack on Project A:
```
vue.config.js

const path = require('path');

module.exports = {
  pluginOptions: {
    quasar: {
      treeShake: true,
    },
  },
  css: {extract: false},
  transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/],
  chainWebpack: config => {
    const types = ['vue-modules', 'vue', 'normal-modules', 'normal'];
    types.forEach(type => {
      addStyleResource(config.module.rule('stylus').oneOf(type));
    });
  },
};

function addStyleResource(rule) {
  var dir =  path.resolve(__dirname, 'node_modules/quasar/src/css/index.styl');
  console.log("including dir", dir);
  rule.use('style-resource')
    .loader('style-resources-loader')
    .options({
      patterns: [
        dir,
      ],
    })
}
```
This worked in the same way as Case #2, it doesn't include all the quasar needed styles, and really don't understand why.

So, are there any plans to support this? Thanks a lot, I think it would be a great improvement taking into account the WebComponent technology that will end (in my opinion) with the gap between Vue and React, and would allow components of each to be integrated. For more information about this last, please read following [article](https://medium.com/javascript-in-plain-english/create-micro-frontends-using-web-components-with-support-for-angular-and-react-2d6db18f557a)

**Comment by rstoenescu** [comment]
Hi,

Like I mentioned on [another ticket](https://github.com/quasarframework/quasar/issues/4956), Quasar CLI's purpose (and even Vue CLI's purpose) is not to build a component library, but to build a website/app.

To fully answer this thread I'd have to go through great lengths to discuss about Web Components, Vue components, building a component, but the conclusion would be the same.

You mentioned: "The problem with this approach is that quasar redefines some top level tags (h1,h2,etc) that affect the Project B's stylesheet." -- well, just put Quasar's stylesheet before Project B's stylesheet. Not sure about your exact setup though. What's Project B? Does it have a build setup of its own? Does Project B's stylesheet is injected by its own build setup? ... but anyway, don't think it'll help much because of the above.

Sorry for any inconveniences. But what we need now is to focus on the already large area that we've spread to.

**Comment by loicmarie** [comment]
Here is a basic use case : we have multiple Vue apps, and are creating a centralized component library imported by all the apps. These components have dependencies on multiple Quasar components. After adding Quasar as a plugin, when building it with `vue build --target lib` and importing it in other apps, it results in conflicts with different `vue.esm.js` bundles used, with a well-known `$attrs/$listeners is readonly` error.

As far as I understand, this problem is Quasar-side and the way it is designed. So yes, I understand the purpose of Quasar is to build web apps, but this way we cannot use it in a custom component lib, and so cannot use it with more than one vue app. Or am I missing something ?

**Comment by jhoffner** [comment]
@rstoenescu I know that Quasar has UMD mode, but what would it take to support a new mode that exports the entire Quasar app as a single web component? The purpose for this would be to embed the app inside of a legacy app. 

If it's exposed as a single web component, then the entire app would be in a shadow DOM and wouldn't have issues with competing themes, and this should resolve for most people I would think the issue of needing to resort to using iframes. 

This could really help boost adoption of the framework (which is incredible BTW), because you can build it using the full CLI, but then export it as a web component so that parts of the app could be used within a legacy app, while at the same time eventually porting parts of the old app over to Quasar.

Normally an app works off of routing, but if it was exposed as a single web component (App.vue) using https://github.com/vuejs/vue-web-component-wrapper, then other apps could embed like so:
```
<my-app-wrapper route="/reports/123" />
```

And App.vue could handle internally how to override the router to use the route passed in instead of what is in the actual URL (this part doesn't have to be Quasar's problem to solve).
