### ISSUE TITLE
Footer leave excessive space

### ISSUE THREAD

**Issue by bodamat** [quasarframework/quasar#5180]
**Describe the bug**
If I use "display:none" for footer than padding in tag q-page is remains. I can't fix this problem. 

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/bodamat/pen/XWrwgpa

**To Reproduce**
1. Go to style and add @media screen and (min-width: 768px) {
    .q-footer {
      display: none;
    }
  }
2. Restart page
3. Footer don't see on the page, but footer leave excessive space

**Expected behavior**
 Footer don't see on the page and excessive space from footer

**Screenshots**
https://imgur.com/a/FwfwbPb

**Platform (please complete the following information):**
OS: All
Node: 10.16.3
NPM: 6.9.0
Yarn: i don't use
Browsers: Chrome

**Additional context**
I think that Quasar add padding before add style, because when I change display:none to display:block and vice versa, it's work.
Can you help me?

**Comment by rstoenescu** [comment]
Hi,

The proper way to do it is through using `v-if`.

**Comment by bodamat** [comment]
Thanks, but I try it and it don't work. 
I want that footer show in mobile and q-drawer on desktop. How does it do?

**Comment by smolinari** [comment]
Hi,

See here: https://quasar.dev/options/platform-detection#Properties
And here for more fidelity: https://quasar.dev/options/screen-plugin#Usage

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. And if we come to the conclusion, your issue is a bug, we'll ask you to then add an issue here. 

Thanks for your understanding. 😄 

Scott

**Comment by bodamat** [comment]
Thanks! I found what I was looking for.
