### ISSUE TITLE
Add auto margin vertically

### ISSUE THREAD

**Issue by furyscript** [quasarframework/quasar#5208]
Is a good practice, like bootstrap do, adding a `my-auto` spacing helpers.
Is usefull have it in the quasar core and not add this usefull spacing, for working with flex, in external app file.

Thanks

**Comment by pdanpdan** [comment]
What is the use case for this?

**Comment by hawkeye64** [comment]
https://www.codeply.com/go/akn5BYxQwn/bootstrap-4-vertical-center-using-auto-margins

Would this be the same as `vertical-middle`?
`my-auto` and `mx-auto` applied to y-axis and x-axis respectfully

**Comment by pdanpdan** [comment]
There are already classes for alignment in flex - check the docs and this sample: https://codepen.io/pdanpdan/pen/XWWrJja

**Comment by furyscript** [comment]
Yes I know there is flex classes for center the child div or div itself, but I think can be a standard class. WIth `mx-auto` you can center a child div of a flex. So why you couldn't add the `my-auto`?

**Comment by mesqueeb** [comment]
I strongly believe as well .q-mt-auto and .q-my-auto should be added. My reasons explained here: #6073

**Comment by rstoenescu** [comment]
Auto margins do not work with top and bottom. If the value has been set to auto, the specs define that the used value for top and bottom will be zero. That applies to inline and block level elements.

http://www.w3.org/TR/CSS2/visudet.html#Computing_heights_and_margins

**Comment by mesqueeb** [comment]
@rstoenescu I just want to provide a codepen that shows that auto margin top _does_ work:
https://codepen.io/mesqueeb/pen/WNbJaxM

parent flexbox column with fixed height + `.q-mt-auto` on child will push it to the bottom...

**Comment by rstoenescu** [comment]
Why would you want to use flex, but not fully, combined with old css specs (margin auto)...?

**Comment by drank** [comment]
If I want to vertically align all items to the top (e.g. justify-content: flex-start) but only one item to the bottom then the approach would be to set the top margin of the bottom item to "auto".
In short - the container is flex with vertical positioning and content justified to the start and the last item should be able to use `.q-mt-auto`.
This is one of the standard ways of aligning items in flexbox - https://stackoverflow.com/questions/32551291/in-css-flexbox-why-are-there-no-justify-items-and-justify-self-properties/33856609

**Comment by pdanpdan** [comment]
@drank, @rstoenescu  If you are talking about column flex alignment then you are right.
If it weren't for people that would try to use them to center vertically I would say they should be added in core.
But as it is it's just a few rows of CSS and if you need them you can put them in your custom CSS, and it avoids a lot of confusion if they are not present.

**Comment by drank** [comment]
@pdanpdan 
If you consider flexbox, which is direction agnostic, then both horizontal and vertical "auto"s become equally important, so why not have both in the core for those cases?
Yes, we can add our own CSS but the whole point of the OP was not about how to achieve the same without those but **about introducing them to the core**.
In addition, I believe that the whole "do not add feature A because there are people who would use it wrong" approach is flawed. There are gazilions of CSS features that many people (including me) are using wrong and the only real solution is - "learn more CSS", not "remove them from the specs".
I could also write my whole app with plain JS and CSS but I don't want to, I want to use Quasar :)
Just IMHO.

**Comment by mesqueeb** [comment]
Yes, as I've said before:
- parent flexbox column with fixed height + `.q-mt-auto` on child will push it to the bottom, if only that css class exists.

@rstoenescu asked me before the reason I use flex and not something else, is because the interactive parent component uses flexbox and then dynamically changes the direction between column and row etc.

So, since I'd need flexbox anyway when the parent element is in the the `.row` state, I see no reason why I should avoid flexbox in the `.column` state...

I strongly believe we should in all cases, and to avoid any confusion, provide the users with `q-mt-auto` and `q-mb-auto`.

**Comment by rstoenescu** [comment]
Confusion is over. q-my-auto, q-mt-auto and q-mb-auto are coming to "quasar" v1.9.12. Just make sure that you know what you are doing.
