### ISSUE TITLE
blur image in q-img but not its caption

### ISSUE THREAD

**Issue by DiaaEddin** [quasarframework/quasar#5254]
## problem:
 I'm always frustrated when trying to blur q-img but not its caption.

## solution:
it is would be nice to have a way to blur the image without the caption using q-img component

**Comment by pdanpdan** [comment]
Can't you apply the blur filter on `.q-img__image`?

**Comment by DiaaEddin** [comment]
@pdanpdan not when using `<style scoped>` :/ .

**Comment by DiaaEddin** [comment]
actually I just found [this](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) after a little search
I can simply use `/deep/` before the selector to affect child components
```
<style scoped>
/deep/ .q-img__image{
    filter: blur(1px);
    -webkit-filter: blur(1px);
}
</style>

```
though it would be nice to mention this in the documentation with a few example on how to add effects to the image.

**Comment by rstoenescu** [comment]
Hi,

New prop will be available in "quasar" v1.4.0: `img-class`.

**Comment by DiaaEddin** [comment]
Hi,
Thanks, I really appreciate you responding to my request.
I have to say that this is the most awesome front-end framework I ever used and now I like it even more. 
Really, thank you guys for bringing **quasar** to reality.

**Comment by sday** [comment]
Odd, I had to use the /deep/ css to make it work. It seems to ignore img-class for me.

Dev mode.......... spa
Pkg quasar........ v1.9.15
Pkg @quasar/app... v1.7.1

**Comment by AlexLeonNovak** [comment]
Why is this issue closed? 
The problem is not solved.
When you add some class to the img-class prop it is an added-to img tag but not an added data attribute, so you cannot change any style
![2024-06-11_12-36](https://github.com/quasarframework/quasar/assets/12094668/a31ab7af-0111-441a-ae85-bbb2bbb05d91)
![2024-06-11_12-39](https://github.com/quasarframework/quasar/assets/12094668/78cc47ca-9091-480e-9aa6-52cf1fe311ff)
