### ISSUE TITLE
QSelect should keep user input on focusout

### ISSUE THREAD

**Issue by James-Z-Tang** [quasarframework/quasar#5276]
**Is your feature request related to a problem? Please describe.**
When I use QSelect with use-input enabled I can type in the Select input box however when I click other place on the page the typed chars is always cleared. This makes it impossible to enter new but only existing options.

**Describe the solution you'd like**
Please keep user's input when Selector focuses out.

**Comment by userdude** [comment]
Instead of using enter to save before leaving, upon leaving the `use=input` textbox would send any value in it's buffer to the select list automatically? 

I could see maybe a `@discarded="listener"` that would be called before discarding leftover values. This would be passed the leftover value with an add callback. Seems a little narrow, but maybe there are other use cases.

**Comment by pdanpdan** [comment]
When the text typed is updated a `@filter` event (with the first parameter the text) is emitted. You can store this and do whatever you want on `@blur`.

**Comment by James-Z-Tang** [comment]
I am using this as a text input with autocomplete capability. I think you can simply leave the user input text there and let developer decide how to deal with it.

**Comment by pdanpdan** [comment]
If you need a text field then use a QInput and use a popup to provide the autocomplete.
