### ISSUE TITLE
Button Toggle multiple

### ISSUE THREAD

**Issue by furyscript** [quasarframework/quasar#5303]
Allow `multiple` on button toggle, can be usefull for mix the option.

**Comment by smolinari** [comment]
@furyscript - It wouldn't be much of a toggle, if you have multiple selectable buttons, would it?

And, you can build your own selectable button group with QBtnGroup.

https://quasar.dev/vue-components/button-group

Scott

**Comment by furyscript** [comment]
yes can be an alternative, but how can I set the active state? By managing my own class and v-model?
With a multiple options the v-model can be like `[true, false, true]` (example) and it's easily to manage.

Tell me if I'm wrong :)

**Comment by smolinari** [comment]
Are you looking for something like this?

https://codepen.io/smolinari/pen/jOOqydm?editors=1010

Scott

**Comment by furyscript** [comment]
Oh yes, more easily than I expected :) so isn't very important feature to do :)

**Comment by smolinari** [comment]
Great. Then I'll go ahead and close this issue. 

Scott

**Comment by septatrix** [comment]
@smolinari has the Quasar Team though about some kind of "code sample" collection. I now had the scenario repeatedly that some components I wished existed in Quasar was missing only to find out after searching and reading though several issues that some snipped exists which implements a large part of what I want. The other one which I currently remember was a picklist/transfer component (#8302) though there have also been others.

Other people might not be as determined as me or be simply looking at the existing components when investigating which framework to choose for their next project and be sad that a component they require is not listed anywhere only because it is too easy to build with what is given.

**Comment by KoTanukiKyoso** [comment]
First of all, I apologize for not being good at English.

All components can be implemented if you want to. The fact that they are easy is not a reason not to implement them.
If they are easy, you should implement them.
