### ISSUE TITLE
[docs]Quasar components have their own icons,so where can i find all the q-icons?

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#5336]
Need a q-icons list in doc

**Comment by ibrainventures** [comment]
if you read the 
https://quasar.dev/vue-components/icon
there are some links to the icon resources

https://material.io/resources/icons/?style=baseline

Those are implemented in standard config. But you can also integrate other icon libs.

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

And, if we come to the conclusion, your issue is a bug, we'll ask you to then add an issue here. 

Thanks. 😄 

Scott
