### ISSUE TITLE
Add label in Linear Progress

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#5353]
I think it is a nice feature if we can display a label in linear progress.
I just edited the image in paint to demo example.

![image](https://user-images.githubusercontent.com/4918318/67155344-ab10b980-f33f-11e9-830e-13dcda9babd5.png)

**Comment by pdanpdan** [comment]
Just add what you want in the default slot of the QLinearProgreee, like here:
https://codepen.io/pdanpdan/pen/qBBqGWL?editors=1010

**Comment by rstoenescu** [comment]
@pdanpdan Please add this example in docs.

**Comment by rstoenescu** [comment]
Better example:
https://codepen.io/rstoenescu/pen/GRRrRgE?&editable=true&editors=101

From updated docs:

To add a label to the progress bar you can use the default slot. Take care to:
  - use a `size` big enough to allow showing the label
  - set a text color for the label so that it is visible both on the filled and unfilled areas, or use text-shadow CSS, or use a QBadge as in the example blow
