### ISSUE TITLE
QPopupProxy does not pass through all events

### ISSUE THREAD

**Issue by kolbma** [quasarframework/quasar#5409]
**Describe the bug**
A `$on('show', ()=>{ // is not called })`, only `$on('hide', () => {})`

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/codesandbox-app-j4939?fontsize=14&module=%2Fsrc%2Fpages%2FIndex.vue

**To Reproduce**
1. Go to **[codesandbox](https://codesandbox.io/s/codesandbox-app-j4939?fontsize=14&module=%2Fsrc%2Fpages%2FIndex.vue)**
2. Click on **left clock icon**
3. There is an alert on show
4. Click next to popup to close it
5. There is an alert for hide
6. Click on **right clock icon**
7. There is **no** alert on show
8. Click next to popup to close it
9. There is again an alert for hide

**Expected behavior**
All documented events should be handled also via `$on(...)`

**Platform (please complete the following information):**
OS: Linux
Node: v8.16.1
NPM: 6.4.1
Browsers: Chrome and Firefox

**Comment by rstoenescu** [comment]
Hi,

Unfortunately, the way Vue works to passthrough all events is by using `this.$listeners`. But this Object gets filled in only when v-on (`@some-event="handler"`) is present. Registering with a Vue reference + `ref.$on` does not fill in `this.$listeners`..

One way this can be worked around in Quasar code is by avoiding `this.$listeners` and manually registering all events. But 1) the footprint of the framework would go up significantly 2) the maintenance cost is way too high and 3) the component will be error prone since it won't be obvious that any change to QDialog or QMenu should be mirrored into QPopupProxy too. A total no-go. So sorry for any inconvenience.

**Comment by kolbma** [comment]
Can't follow your (@rstoenescu) argumentation, because it is done correct in **QPopupEdit**.  
There it works like a charm.

**Comment by rstoenescu** [comment]
Because QPopupEdit explicitly emits its own events, while QPopupProxy passes through all listeners with `this.$listeners`, which Vue does not fill if you don't explicitly attach events in your Vue template.

**Comment by kolbma** [comment]
Doesn't really matter how it is done to receive events in extended components.
With QPopupProxy you have to copy and overwrite the whole render function to handle the events. Which means you have to follow any base changes.
QPopupEdit and also QSelect is simply writing a listener function.
