### ISSUE TITLE
How to get statics files using axios?

### ISSUE THREAD

**Issue by eladcandroid** [quasarframework/quasar#5410]
I didn't find anything in docs...

For example:
```javascript
const { data } = axios.get("/statics/markdown-examples/example.md");
```

Thanks!

**Comment by rutvij2292** [comment]
This question belongs to Axios plugin not to Quasar Framework. IMO, Quasar framework is not forcing you to use axios. I don't think its a bug.

**Comment by rstoenescu** [comment]
Hi,

There are two scenarios:

1. If your file is part of your /src folder (like in your example, /src/statics) then you're looking at this with the wrong mindset. You can use the webpack raw-loader (you need to install it) to dynamically load the file:

```js
import(`!raw-loader!src/statics/markdown-examples/example.md`)
  .then(content => {
    // raw file content
    console.log(content.default)
  })
```

If you also want to get that md file compiled, you can directly use a webpack loader for markdown (add it a rule for md files that uses the loader in the Webpack config through quasar.conf.js > build > chainWebpack/extendWebpack()) -- which also has the benefit of doing this at build time rather than at runtime (and runtime assumes you need to load the md parser on the client bundle too).

2. However, if you need to load the md file from a remote location, then indeed you'll need to use axios or other services to fetch the file, in which case it's best to get in touch with the developers of that service.
