### ISSUE TITLE
QTable - specifying background color for column in col definition object hinders Quasar's hover & selected effects

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#5442]
Bug description in title.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.3.0

**Comment by dariodepaolis** [comment]
With this fix I'm not able to change the selected row text color, because now there's a background in the :after of the cell

Previously I can easily changed text color with a simple `tr.selected { color:#fff }`
Now I have to struggle with the background in the :after

I don't know now if there is a simple way to achieve this, also in sass variables there's just $table-hover-background and $table-selected-background but nothing related to text color

**Comment by rstoenescu** [comment]
@dariodepaolis Please write a codepen so we can show you if you're doing something wrong or not. You shouldn't need to change the :before or :after... if we're missing something, we'll look at the codepen and correct it. Thanks!

**Comment by dariodepaolis** [comment]
Ok sure:
https://codepen.io/dariodepaolis/pen/QWwbMQK

I don't know how to use quasar vars in codepen like `$table-selected-background` but I think that you'll understand the problem

In css uncomment the lines to make it works with custom colors.

Anyway nothing impossible to achieve.

**Comment by ddenev** [comment]
Dear @rstoenescu 

I also have to say that the fix above seems to "greedily" override quite a lot of possible customizations.

For example: if I put a QInput within a cell (on a 'selected' row) and set the `bg-color` prop of the `q-input` to 'white' then it is still not white as the background color of the selected row (specified in `td::after`) overrides any other bg color (or to be more precise - comes on top of any other backgrounds within the table).
