### ISSUE TITLE
quasar dev question

### ISSUE THREAD

**Issue by yueqjGithub** [quasarframework/quasar#5471]
I use 'quasar dev -m cordova -T android' to dev my pro,but the CMD tell me 'no such file or directory open 'D:\work\bd-app\src-cordova\config.xml''.
I sure used 'quasar mode add cordova'

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

And, if we come to the conclusion, your issue is a bug, we'll ask you to then add an issue here. 

Thanks. 😄 

Scott
