### ISSUE TITLE
[docs]How to override proxyTable options, Please add it in docs

### ISSUE THREAD

**Issue by hugetiny** [quasarframework/quasar#5478]
in Vue-CLI I can  override proxyTable options  in config/index.js
```
proxyTable: {

      '/api': {

        target: 'http://www.somedomain.com',

        changeOrigin: true,
...
```
but how can I override proxyTable options in Quasar?

**Comment by pdanpdan** [comment]
You type 'proxy api' in the search box in docs and magic happens: https://quasar.dev/quasar-cli/cli-documentation/api-proxying#Introduction

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

And, if we come to the conclusion, your issue is a bug, we'll ask you to then add an issue here. 

Thanks. 😄 

Scott
