### ISSUE TITLE
Do not force css rules with !important, it breaks simplicity of customisation.

### ISSUE THREAD

**Issue by luckylooke** [quasarframework/quasar#5566]
First of all, thank you for great framework.

**Is your feature request related to a problem? Please describe.**
I wanted to set custom color of button text, but the color is not from quasar palette so I could not use "text-color" attribute. So I need to make selector with higher specificity and also use !important statement to force my color. IMHO components should be customisable without such force. 

**Describe the solution you'd like**
There is `white-text` class used internally on button which has rule:
"color: white !important;"
can we get rid of this? just set color white without important statement?

**Describe alternatives you've considered**
I know I can modify those colors via scss variables, but I cannot add custom names so it can be possibly confusing and what about users using plain css? They do not have such option.

**Additional context**
https://codepen.io/luckylooke11/pen/eYYLjRe

**Comment by pdanpdan** [comment]
simply define
```stylus
.text-my-custom-color
  color #f33
```

and use it as
```html
<q-btn color="my-custom-color" ... />
```

**Comment by luckylooke** [comment]
Ok, it works! Thank you :)

**Comment by anatoli26** [comment]
@pdanpdan is there any reason why you use `!important`? NiceGUI framework uses Quasar under the hood and is having complex issues styling components with Tailwind because of these `!important` rules. The workaround you proposed to define a custom color won't work in NiceGUI case as all possible properties would have to be redefined. Please have a look at this issue: https://github.com/zauberzeug/nicegui/issues/1821. Maybe you could suggest a solution?
