### ISSUE TITLE
[quasar/babel-preset-app]  request to integrate nullish-coalesce and optional-chaining plugins (stage 3)

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5617]
It would be great to have those 2 babel plugins inside the default setup:

https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining

https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator

those coming operators are really sexy and makes those possible:

![grafik](https://user-images.githubusercontent.com/8803626/68999031-967dfd80-08ba-11ea-9acb-db8ad648a866.png)

Would be great. Many Thanx.

**Comment by panstromek** [comment]
I am not sure it's great idea to include proposal syntax into the default preset. I use these often, too but they are pretty easy to setup anyway, and I think it's better to add them only if you really know what you are doing.

Adding them as default can have many consequences when the proposal change and Quasar projects breaks consequently (knowing that babel has been source of bunch of problems already).

Also, lot of people coming to Quasar don't have strong JS background and giving them invalid JS syntax will cause them troubles when they try to use it somewhere else (or just in Vue templates, because those are not transpiled and throw confusing errors at you instead).

**Comment by ibrainventures** [comment]
@panstromek 
many thanks for your feedback.

As is saw that there are some proposal plugins inside the existing babel preset 
https://github.com/quasarframework/quasar/blob/dev/babel-preset-app/index.js

i thought this would be also possible for those two requested plugins.

As long as the syntax will not be used in official documented usage examples, i think it can be good feature for the quasar developer.

May you can help me and others (e.g. also official documented) for extending the babel config which will survice any normal quasar upgrade  or a  git clone with a normal npm / yarn install routine.

That would be (alternatively) be perfect.

**Comment by IlCallo** [comment]
Both features are now stage 4 and will be implemented in JS. Can we add them as default babel plugins now?

**Comment by panstromek** [comment]
Btw. I just tried to use both in one project and they both work. I didn't change any Babel config or anything. Just default `babel-preset-app`...

**Comment by panstromek** [comment]
Yea, it's there. Comes from `preset-env`
`yarn why` output:
```
info Reasons this module exists
   - "@quasar#app#@quasar#babel-preset-app#@babel#preset-env" depends on it
   - Hoisted from "@quasar#app#@quasar#babel-preset-app#@babel#preset-env#@babel#plugin-proposal-nullish-coalescing-operator"
... 
info Reasons this module exists
   - "@quasar#app#@quasar#babel-preset-app#@babel#preset-env" depends on it
   - Hoisted from "@quasar#app#@quasar#babel-preset-app#@babel#preset-env#@babel#plugin-proposal-optional-chaining"
```

**Comment by IlCallo** [comment]
Strange, I just tried it with latest Quasar version and it doesn't work...

**Comment by rstoenescu** [comment]
Hi All,

Babel gets its config from `/babel.config.js`. If you need any extra presets, you can extend through this file.

**Comment by Mosharush** [comment]
It's not working...
My `babel.config.js`
```
module.exports = {
  presets: ['@quasar/babel-preset-app'],
  plugins: ['@babel/plugin-proposal-optional-chaining']
};
```

Abd error above on build:
```
Module parse failed: Unexpected token (99:56)
File was processed with these loaders:
 * ../../../node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js
You may need an additional loader to handle the result of these loaders.
| 
|     const itemData = Object.fromEntries(
>       Object.entries(item).map(([k, v], i) => [k, value?.value])
|     );
|     console.log(item, itemData);
```

The strang here is when I delete babel.config.js he throws an error on that, seem it loaded

**Comment by RaviH** [comment]
It would be nice if there's documentation on how to update babel config.

**Comment by Vestibule** [comment]
Anyone found a solution ? Getting stuck on this, too.

**Comment by x-ji** [comment]
At first I thought it didn't work but actually it's because ES6 syntax doesn't work in Vue templates, see https://forum.vuejs.org/t/does-vue-cli-3-come-with-pre-configured-optional-chaining/42609/4. Once I moved it to the `script` part it worked.

Steps to add the support to your project are simple:
- `yarn add @babel/plugin-proposal-optional-chaining --dev`
- Change `babel.config.js`:

```
module.exports = {
  plugins: ['@babel/plugin-proposal-optional-chaining'],
  presets: ['@quasar/babel-preset-app']
};
```

There didn't seem to be a need to upgrade to `@quasar/app` v2.

**Comment by ghost** [comment]
Joining the issue. Can't get @babel/plugin-proposal-optional-chaining to work in Quasar 1.x. Same as what @Mosharush described.
