### ISSUE TITLE
Swappable CSS frameworks (i.e. TailwindCSS)

### ISSUE THREAD

**Issue by 2x2xplz** [quasarframework/quasar#5618]
**Is your feature request related to a problem? Please describe.**
Adoption of Quasar may be limited due to the requirement to learn its styling rules.

**Describe the solution you'd like**
Would be terrific if users could choose among existing CSS frameworks, specifically [TailwindCSS](https://tailwindcss.com/), possibly Tachyons or others. (Tailwind is pure CSS, no components that conflict with Quasar's). 

**Describe alternatives you've considered**
- quasar devs explain how to prevent default CSS from being included in final package
- from there, community could probably figure out what to add to quasar.conf to include alternate CSS frameworks, if so desired. 
- Users happy with Quasar's default CSS can totally ignore the above.

**Additional context**
New users who are already familiar with Tailwind or other CSS frameworks might be hesitant to try Quasar because it requires learning a new set of CSS classes and abandoning their existing knowledge. Additionally, people familiar with multiple CSS syntaxes might prefer to just use one in  both Quasar and non-Quasar projects, as it can sometimes be difficult to switch between. Example `q-my-md` vs `my-4` (Tailwind) for setting vertical margin.

Tailwind is a great project (so is Quasar), in the long term it may ease internal development by allowing Quasar devs to focus only on components and the framework and not so much on styling. Both use similar methodologies (utility-based) so it's not like introducing a completely new way of thinking.

This is not the first time this idea has been raised, see also #4274 (specifically, [here](https://github.com/quasarframework/quasar/issues/4274#issuecomment-523998293)) and #5204

**Comment by pdanpdan** [comment]
It's not possible to swap one CSS framework for another. As far as I know TailwindCSS is a utility framework, so basically what you write in it are some utility classes. Just import them.

**Comment by gbouteiller** [comment]
I'm a big fan of Quasar AND TailwindCSS, and what @2x2xplz explained is some kind of redundancy between Quasar styling and TailwindCSS.
For now, integrate both solutions together, even if doable is not ideal :
- Quasar expose some styling redundant with TailwindCSS (including stuff like colors and breakpoints).
- Quasar styling is somehow hard to tree-shake resulting in a big css file (I haven't find a way ton setup purgess easily with Quasar in that matter): not all styles are prefixed or prefixable so it's not trivial to create a white list pattern.
- Many Quasar components have props that are linked to Quasar styling internally so you can't easily replace their use with TailwindCSS.
- As Quasar use classes, it's hard to simply replace some component styling with utility classes cause you need to use !important or add more specific selectors.
Even if Quasar is awesome for a lot of things, I think that in terms of styling, TailwindCSS is more robust and it should be wise to at least consider it.
Apart from having to rewrite components which is already in discussion by the way, I think the question is : if TailwindCSS was to be integrated into Quasar, what problems would emerge?

**Comment by pdanpdan** [comment]
The first problem would be why tailwind :D I want ...wind...

**Comment by 2x2xplz** [comment]
> what tailwind provides and quasar doesn't?

- Tailwind has a cool `@apply` function to combine existing CSS shortcuts and create a new class definition. For example `.redheader {@apply font-extrabold text-3xl text-red-700 py-2}` creates a new class named redheader with large, extrabold, red text with horizontal padding. Much easier than having to use all 4 individual class names on every element. 
- I also think creating/redefining new custom classes (i.e. new padding definitions) is quite easy in Tailwind
- Pseudo-class coverage (hover, first-child, odd-child, etc) is probably more complete than Quasar's. 
- One more big thing, Tailwind's docs are very clear on how to integrate with PurgeCSS in order to reduce file size (by 90+% on one React site I built)

But it's not so much which is better, Tailwind vs Quasar (Quasar is superior in some areas, for example its color space provides many more options, it works very well with Stylus, etc). More important, is easing developer preference, especially for people who sometimes build solutions that aren't Quasar. I think anything that will eliminate excuses NOT to try Quasar, will eventually lead to greater adoption of the platform.

@gbouteiller makes a good point that internal components use Quasar's CSS, therefore "swapping out" is likely unreasonable. Perhaps the best solution would be a guide to a) importing TailwindCSS and b) enabling PurgeCSS (I am pretty sure Quasar already uses PostCSS so this should just be a plugin of that, otherwise there are many other install methods [here](https://tailwindcss.com/docs/installation). Someone highly knowledgable about Quasar's internals could suggest the best option).

**Comment by 2x2xplz** [comment]
As you state, to be maximally effective with Quasar, you need to learn its own CSS, plus Stylus. Again, this can be intimidating for someone who knows neither. Can I use Quasar's CSS styles in an `@extend`? The Stylus docs appear to require the standard CSS (i.e. `margin-top: 4px; margin-bottom: 4px` rather than `q-my-xs`)

Earlier you wrote:
> Just import them.

I think a guide on how/where to do that, would go a long way. I believe there are 3 major requirements after installing via npm:
- add tailwind to postcss config. Quasar projects have a `postcssrc.js` file which might be the equivalent. This might be where PurgeCSS can be configured.
- import 3 files (base, component, utilities) and prepare global styles (maybe `app.styl` ?)
- create a `tailwind.config.js` and make sure it's included in webpack builds 

I think we all understand this is a rather difficult and tricky implementation, so everyone's contributions are greatly appreciated and nobody expects this to be in the next release or anything. Thanks for your help and opinions!

**Comment by ibrainventures** [comment]
To personally understand this feature request i would ask the OP (and also those who are also +1 that request) what is the motivation behind:

**Design / Component Design:**

Tailwind is relativ fresh on the market and with Steve Schoger behind, the UI Design is / will be very sexy. But quasar is a "nearly 100% Material Design" dedicated fw. So there are pros and cons against this groundbase - and myself can understand a little the "boringness" about the - every second app / website looks the same "feeling" - .. but you can overrule and re-design every quasar component with css actually .. This need some work by yourself, but its actually possible.

So yes .. to integrate a "other fronentend Theme / UI Design Theme" can be a request, but actually as some others in this discussion wrote, this would be need a complete re-coding to separate q-components from the css-styles. (may a design-api, a markup-language or going to a complete css-var-handled-system can be the future for this ?).


**CSS Code Styling / Wrapper**

I like the ideas behind the syntax-styling ideas behind Tailwind, but i also like the quasar styling syntax. The learning curve on both fw is the same .. as myself is a person who has a left/right problem since born, my pinwand is filled with styling-tables for q- p - etc. (and also for the vue-instance-lifecycle hooks and vuex-pattern.. :-) ) .. 

Every fw has its own taste, but the utility-based concept is given behind both css-fw...
So imo .. to refractor the css-wrappers from quasar to tailwind make no sense. If you found some advanced / additional / better styling wrappers, i am sure that the quasar-team is open for all kind of additions...

**Comment by matthias-influry** [comment]
I was looking for how to integrate TailwindCSS into my Quasar project and came across this issue. 

I think swapping the frameworks is not really an option, but it would be interesting to have the option to import Tailwind without having conflicts with internal CSS classes.

My point right now is that with Tailwind CSS, I don't really need to write any CSS anymore. It is a lot more straightforward to just keep writing HTML classes in my components. 
Quasar has implemented utility classes, too, but far less. 

Just compare Quasar CSS-border related classes:
https://quasar.dev/style/other-helper-classes#Border-Related

With Tailwind CSS:
https://tailwindcss.com/docs/border-color
https://tailwindcss.com/docs/border-style
https://tailwindcss.com/docs/border-width
https://tailwindcss.com/docs/border-radius

And on top of that, you can combine all theses classes with responsive prefixes or pseudo-class variants by prefixing e.g.: `hover:`.
Right now I am building a lot of those helper classes within my quasar CSS by creating loops for each color and creating classes like `hover:text-primary` etc for each color. 
But I feel like reinventing the wheel.

In the end, I am fine with just using tailwind CSS as the external CSS utility framework that it is, the only thing that needs to be made sure is that there are no conflicting class names.

**Comment by matthiasmeier** [comment]
While I understand your request, I would _not_ recommend to replace Quasar CSS with `insert framework name here` (and do not think that it would be possible). Quasar provides its own frontend framework. So when you decide to use it, you will also have to deal with how it’s to be used. (As said – I’m currently working on the first project we’re creating with Quasar; so I usually have 2 or 3 tabs with Quasar docs open while working on it.)

Having a 15+ years background in frontend development (with a strong focus on CSS and design), I’m still not a big fan of adding CSS classes to the markup for styling purposes instead of writing "proper" CSS and using semantic class names. But – I do absolutely see the advantages this has and understand that this makes it a lot easier – and especially faster – to have a nice and consistent frontend.

In an agency I used to work a couple of years ago, we had one large project for a client where we had to integrate 80+ external services; all using their own code (styles, scripts, …). Our job was to provide a solid modular frontend framework which then could be used by the external companies to adopt the main elements and design for their tools. So one of the issues we faced was that we had to ensure that our styles and scripts would not conflict with the styles and scripts of the 80+ external services.

What we ended up doing, was to prefix _all our CSS classes_. While this is a pretty simple approach, it was very effective and prevented conflicting styles e.g. if we and any external service would have used a class name like e.g. `.card` or the like. 

Quasar already uses the same approach for its own components – e.g. `.q-list` or `.q-item`, etc.) Also, Quasar already has this for most of its CSS classes e.g. for the padding (`.q-pa-sm`) or margin (`.q-mt-lg`). But this prefix seems _not_ to be applied to all CSS classnames (which – while it makes the according class names simpler also is a little inconsistent). For example the [Typography CSS classes](https://quasar.dev/style/typography) do not use that prefix as well as the [Other CSS Helper Classes](https://quasar.dev/style/other-helper-classes) or the `bg-` classes.

And as @matthias-influry mentioned above:

> the only thing that needs to be made sure is that there are no conflicting class names.

I think that introducing a prefix option (the default should probably be `q`, also to prevent possible breaking changes in existing projects) could make the used class names more consistent and also help making it easier to use (import / add / …) any external frameworks on top of Quasar.

**Example 1**

- Prefix: `q` (default)
- Class names currently used by Quasar: `.q-list` / `.q-item` / `.q-pa-sm` / `.q-mt-lg` / `.text-h1` / `.text-center` / `.bg-secondary`
- Class names after the proposed change:  `.q-list` / `.q-item` / `.q-pa-sm` / `.q-mt-lg` / `.q-text-h1` / `.q-text-center` / `.q-bg-secondary`

**Example 2**
- Prefix: `fancyProjectName`
- Class names currently used by Quasar: `.q-list` / `.q-item` / `.q-pa-sm` / `.q-mt-lg` / `.text-h1` / `.text-center` / `.bg-secondary`
- Class names after the proposed change:  `.fancyProjectName-pa-sm` / `.fancyProjectName-mt-lg` / `.fancyProjectName-text-h1` / `.fancyProjectName-text-center` / `.fancyProjectName-bg-secondary`

**Comment by matzeso** [comment]
I also think that for the sake of consistency it would be good to have class prefixes everywhere.

@2x2xplz For Tailwind, I just finished a simple extension that installs tailwindcss. The extension will ask for a class prefix which will then be applied to all Tailwind classes. 
That way there should not be overlapping class names.

See https://github.com/matzeso/quasar-app-extension-tailwindcss or simply `quasar ext add tailwindcss`.

**Comment by gbouteiller** [comment]
It's closed now but we didn't get any answer about the prefix consistency. Will it be applied?

**Comment by pdanpdan** [comment]
From my point of view the classes are good as they are, considering that:
- Quasar is expected to be the base framework in the application
- the non `.q-` qualified class names are mainly related to things that cannot be interpreted in another way (like `.text-center`)
- the classes are documented and it would be a major compatibility break
- the gain would be minimal

And adding a custom prefix for CSS classes would be a performance killer, a maintenance nightmare and pretty pointless.

**Comment by razbakov** [comment]
Is it possible to disable typography css like h1, h2, etc?

**Comment by timesignature** [comment]
> The first problem would be why tailwind :D I want ...wind...
> 
> The second one is what tailwind provides and quasar doesn't?

tailwind is simple and its fun that quasar styling

**Comment by timesignature** [comment]
> `@apply` is just `@extend` renamed, which is a native to Stylus and SASS.
> 
> http://stylus-lang.com/docs/extend.html
> https://sass-lang.com/documentation/at-rules/extend
> 
> What I can agree on is the CSS purge, which we are researching.
> 
> I'll leave the ticket open, but replacing the internal CSS in Quasar with some external framework is a no go.

how about giving your developers an option to choose wch styling framework they want,rather than make them focus on one thing because believe me brother i believe quasar is a great project just lacking some flexibility

**Comment by PollieDev** [comment]
I have some projects which I would like to port to Quasar to be able to build them into an app and a website at the same time. All these sites are written with the use of Tailwind. Next to that, since Tailwind UI came out I use it quite often as I'm not the best with UX / UI.

Having to rename all the classes with a prefix is mission impossible.
After building the quasar app, if I simply remove the following line in `client-entry.js`:
```js
// We load Quasar stylesheet file
import 'quasar/dist/quasar.sass'
```
It all works like a charm!

I'm not requesting you to replace the quasar framework with Tailwind. But it would be nice to simply have an option to disable default styling. There are so many web devs that could potentially jump to quasar if they can use the tooling they are used to. But forcing them into your stylesheet will be a big downside if not a reason to not use Quasar at all (at least this is the case for me).

**Comment by idc77** [comment]
I don't understand why you can't provide quasar without the UI components, just the base framework.

**Comment by IlCallo** [comment]
If you don't need the components, you can simply not use them and use everything else, no one is stopping you from doing that

CSS utility classes are part of "just the base framework": changing them would require breaking changes and efforts that we're spending on other features
