### ISSUE TITLE
Always sanitize unless explicitly told not to

### ISSUE THREAD

**Issue by moander** [quasarframework/quasar#5625]
I want Quasar to be secure by default so I'm starting this discussion to get options like `display-value-sanitize` deprecated in favor of `no-display-value-sanitize`. 

In the [security](https://quasar.dev/security/dos-and-donts#QSelect) section you read stuff like

> If you are not customizing menu-related scoped-slots (i.e. option scoped slot), DO prevent the component from rendering HTML in the labels and sublabels with one or more of the sanitize properties. 

and 
> Many developers have asked that the Loading plugin be able to display HTML, so this was enabled by default, but if you are worried, DO add sanitize: true and you removed the vector.

You can also read that components that are made for displaying user-supplied data like [QChatMessage](https://quasar.dev/security/dos-and-donts#QChat-%26-Emoji) is allowing XSS attacts by default.

This is in my opinion crazy. It will give Quasar a bad reputation because most developers don't read docs for intuitive frameworks unless they see a problem. Forgetting to sanitize is in most cases an invisible problem but seeing plain text html when you want it to render is not.

**Comment by rstoenescu** [comment]
Hi,

In theory, I agree with what you are saying. But this would be a breaking change on the v1, so holding this off for v2 instead.

**Comment by moander** [comment]
@rstoenescu a deprecation warning is not a breaking change. Why not leave this issue open for a few days so more people can have their opinion?

**Comment by rstoenescu** [comment]
It would have been ideal for the majority to actually look at the tickets, at twitter announcements or #announcements on Discord, but the reality is that they rarely do these. Can't make such a change "while the engine is running".

In the past there's been a similar discussion (on an adjacent topic) where I tried to include all the community so that they can agree on leaving as is or removing the ability to render HTML on some component (can't remember which). Everyone that participated agreed on removing. Then hell broke loose on Github because even more people complained about the change :)

Anyway, depending on Vue 3 release date, we're not too far away from Quasar v2 (which will be v1 ported on Vue 3, with no breaking changes).

**Comment by rognstad** [comment]
I'm strongly in favor of a breaking change on this with Quasar v2.

At a minimum, it seems like the QSelect and QChatMessage docs should have a huge red warning at the top of the page that they are insecure by default.

**Comment by rstoenescu** [comment]
@rognstad Done. Quasar 2 (with Vue 3) will sanitize by default unless not told to.
