### ISSUE TITLE
Upgrade postcss-loader to v2 ?

### ISSUE THREAD

**Issue by damosse31** [quasarframework/quasar#566]
Hi, 

I don't know if it's a bug but I tried to [upgrade postcss-loader](https://github.com/postcss/postcss-loader) npm package (from v1.3.3 by default in Quasar to latest v2.0.5) but after upgraded, error there is an error "**No PostCSS Config found in (...)**" when compiling with _quasar dev

![screenshot_4](https://cloud.githubusercontent.com/assets/16171524/26024075/3e4c667e-37ca-11e7-8f29-1c9cabd76b91.png)

The problem is solved when I downgrade postcss-loader to v1

I think postcss-loader configuration have changed a lot from v1 to v2, but maybe if you want to improve this package in Quasar for futures releases.

**Comment by rstoenescu** [comment]
Hi, this is a ticket for https://github.com/quasarframework/quasar-template-default repo and not Quasar repo itself, so will close it here.

v2 (must have been released a few days ago) contains breaking changes (by semver convention), so it can't work by default with current configuration. The default Quasar template is regularly updated to use latest and greatest, so no thing to worry about.

What you can do to speed things up (as I'm overloaded on v0.14 work) is to investigate and apply the changes in a PR pls? Otherwise it will take some time as this is not a "must do" in the Quasar todo queue.

Thanks!
