### ISSUE TITLE
Upgrading to 1.5.1 from 1.2.7

### ISSUE THREAD

**Issue by Rolanddoda** [quasarframework/quasar#5727]
**Describe the bug**

I had the following versions:

"quasar": "^1.2.7"
"@quasar/extras": "^1.2"

I ran the following commands:

```
npm install quasar@latest
npm install @quasar/extras@latest
```
**Expected behavior**
Everything should work fine.

**What really happened**
![image](https://user-images.githubusercontent.com/18482346/69803511-aa8bfe00-11dc-11ea-92db-b3a5aa1f710c.png)

**Platform (please complete the following information):**
OS: Win 10
Node: 12.13.0
NPM: 6.12.0

**Comment by MartinManev** [comment]
Hi. Are you by any chance using Vue CLI 3?

**Comment by Rolanddoda** [comment]
Hi @MartinManev. The answer is YES. Should I update `vue-quasar-plugin` too ?

**Comment by MartinManev** [comment]
There is a problem with Vue CLI 3 where a cache is created in `node_modules/.cache` and that cache does not invalidate when you update your dependencies. Can you try deleting this folder and running your app again? Here is the original issue: https://github.com/vuejs/vue-cli/issues/4438

Vue CLI 4 is out and I think the issue is fixed but I haven't verified it myself yet.

**Comment by Rolanddoda** [comment]
That seems to be working.

**Comment by MartinManev** [comment]
For anyone wondering whether the issue is fixed in Vue CLI 4 - I can confirm that as of today it is **not**.

**Comment by pdanpdan** [comment]
@MartinManev Did you use version 2 of the plugin (the one for Vue CLI 4)?

**Comment by MartinManev** [comment]
@pdanpdan The problem is caused by using `transpileDependencies` in the vue cli configuration. Quasar is one such package we want to transpile, but not the real reason behind the problem. I did my testing without the quasar plugin, but the plugin doesn't change anything.

Here is the repo if you are interested in performing the test yourself: https://github.com/MartinManev/npm_problem
1. Clone
2. Install dependencies `npm install` - Quasar is `1.0.5` in `package-lock.json`
3. Run tests `npm run test:unit` - everything is ok - this creates the cache
4. Update dependencies `npm update` - Quasar becomes `1.5.7`
5. Run tests again - lots of errors for missing components show up
6. Delete `node_modules/.cache`
7. Run tests again - everything is ok

**Comment by rstoenescu** [comment]
For Vue CLI 4 use vue-cli-plugin-quasar v2+.
Due to a bug in Vue CLI (v3 for sure, might have been fixed in v4), it is required that you clean up cache. Not Quasar's fault.
Quasar is added to the transpileDependencies list automatically by the vue-cli-plugin-quasar.
