### ISSUE TITLE
q-tooltips and "title" attribute not working now in q-btn-toggle

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#5771]
**Describe the bug**
    Pkg quasar........ v1.5.2
    Pkg @quasar/app... v1.3.1
Windows 10 / Chrome Latest

Somewhere in 1.5.1 or 1.5.2 I've noticed that the "title" attribute was not rendering anymore on my custom-slot q-btn-toggle tag (usually when I mouse over in Chrome I can see the text).  I tried to add a tooltip and noticed that those don't work for me either.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/robert123789/pen/QWwWWbW?editors=1010

**To Reproduce**
The codepen is my copy of the "Button Toggle" quasar page with some edits.  Search for the word "dude" to see where I added things.  Mouse over the custom buttons (the ones with icons).  Two separate but probably related issues: 1) You can't see either the tooltips on the second group. and 2) The `title` attribute will not show up now when I hover

**Expected behavior**
Title and tooltips working.  Ideally both but I can live with tooltips only.  

Quasar rocks!

**Comment by pdanpdan** [comment]
Due to a change in how QBtn works you'll have to add a `all-pointer-events` or `q-anchor--skip` class to the elements inside a QBtn that you want to allow pointer event interaction.

If you add `all-pointer-events` then the alement and all its children will allow pointer event interactions (you must use this for `title` attributes), but if you click on QBtn type="a" you might get the element you clicked on as target in the `@click` event, and push buttons in IE11 will not react by showing the push down when you press on these elements.

With `q-anchor--skip` you must add it to all element parents of the QTooltip, will have no side effects like the ones above, but will not make `title` work.

Check here for example: https://codepen.io/pdanpdan/pen/vYEYNjP?editors=1010

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.5
