### ISSUE TITLE
iOS swipe back

### ISSUE THREAD

**Issue by nulele** [quasarframework/quasar#5777]
Hello, any chance to get the navigation go back on swiping on iOS?

Thanks

**Comment by ibrainventures** [comment]
hi @nulele 

are you requesting this for the pwa / added to home-screen style or the pure-browser-app version?

On the browser app versions, the behaviour is mostly controlled by the qdrawer options, 

https://quasar.dev/layout/drawer#QDrawer-API

`no-swipe-open`
> Disables the default behavior where drawer can be swiped into view; Useful for iOS platforms where it might interfere with Safari's 'swipe to go to previous/next page' feature

and is e.g. working nicely on our app. (slide left and right <-> browser back and forward)

on the pwa i cant check, because of no pwa, but since 12.2 it may should work (as the safari changenotes) are showing this.

on the pure - added to home-screen - there is the outside->innerside swipe ignored.
I am unsure is this prevented by quasar or is this inside a non-pwa-but-homescreen-added app possible.

**Comment by nulele** [comment]
Hi @ibrainventures 

my request is for the pwa... sorry I didn't specify.

I'll give a chance to `no-swipe-open` then...

Thank you
