### ISSUE TITLE
QMenu open on hover

### ISSUE THREAD

**Issue by jd-0001** [quasarframework/quasar#5787]
**Is your feature request related to a problem? Please describe.**
If I want to show QMenu/Dropdown on hover I can not do it using Quasar way.

**Describe the solution you'd like**
There should be hover like prop to enable showing QMenu on hover
Any example of using QMenu with hover and span??

**Describe alternatives you've considered**
Currenly I use @onmouseenter and @mouseleave along with v-model but this is a bit buggy.

**Additional context**
Here's my codepen example: [CodePen](https://codepen.io/jd-0001/pen/GRRVxLZ)

**Comment by metalsadman** [comment]
@jd-0001 buggy in what sense? you can also use a methods show/hide.

**Comment by jd-0001** [comment]
I mean what I have done for my feature request is buggy not QMenu.

In my example I have used js events for opening it on hover. So, according to that `event` it open the `QMenu` but when I try to select any item from `QMenu` it disappear because or `mouseleave` event on text.

So, is there any way I can keep open my `QMenu` open on both `span/text` hover and `QMenu` content hover?

Please try selecting any option from QMenu in my codepen example.

~ Regards

**Comment by hawkeye64** [comment]
@jd-0001 I did an example for QBtnDropdown -- you can see it's handled here: https://codepen.io/Hawkeye64/pen/OqBjxM

**Comment by jd-0001** [comment]
@hawkeye64 Thanks for your efforts but I want to display span/text instead of button.
My usage: 
![chrome-capture](https://user-images.githubusercontent.com/47495003/70143892-c30b8500-16c2-11ea-9b1d-2910fed91bc2.gif)
So there will be no button. Flat button is also not an option.

**Comment by jd-0001** [comment]
Thanks so much @hawkeye64 I got my desired result :+1: 
Here's working [codepen](https://codepen.io/jd-0001/pen/GRRVxLZ)

**Comment by hawkeye64** [comment]
@jd-0001 Looks good! Congrats on resolving!

**Comment by Tofandel** [comment]
Could we maybe have something natively in quasar that implements this behavior, like a open-on-hover prop ?
I feel this is something worth adding

**Comment by Tofandel** [comment]
I made myself a headless wrapper component:
```vue
<template>
  <slot
    :activator-attr="activatorAttr"
    :menu-attr="menuAttr"
    :prevent="preventFn"
    :unprevent="unprevent"
  />
</template>

<script setup lang="ts">
import { debounce } from 'quasar';
import { computed, provide, inject, ref, watch, nextTick } from 'vue';

const props = defineProps({
  disable: Boolean,
  debounceTime: {
    type: Number,
    default: 50,
  },
});

const activatorHover = ref(false);
const menuHover = ref(false);
const menu = ref(false);
let prevent = false;
let menuProxy = false;
let activatorProxy = false;

const checkMenu = () => {
  menu.value = !props.disable && (activatorHover.value || menuHover.value);
};

const emit = defineEmits(['open', 'close']);

const parentMenu = inject('QMenuHoverPrevent', null);

watch(menu, (open) => {
  emit(open ? 'open' : 'close');
  if (open) {
    parentMenu?.prevent();
  } else {
    parentMenu?.unprevent();
  }
});

const preventFn = () => {
  prevent = true;
  parentMenu?.prevent(); // Cascade up
};

const unprevent = () => {
  prevent = false;
  activatorHover.value = activatorProxy;
  menuHover.value = menuProxy;
  parentMenu?.unprevent(); // Cascade up
};

provide('QMenuHoverPrevent', {
  prevent: preventFn,
  unprevent,
});

const debounceMenu = debounce(checkMenu, props.debounceTime);

watch(menuHover, (hover) => {
  if (hover) {
    checkMenu();
  } else {
    debounceMenu();
  }
});
watch(activatorHover, (hover) => {
  if (hover) {
    checkMenu();
  } else {
    debounceMenu();
  }
});

const activatorAttr = computed(() =>
  props.disable
    ? {}
    : {
      onFocus: () =>
        prevent ? (activatorProxy = true) : (menu.value = true),
      onBlur: () =>
        nextTick(() =>
          prevent ? (activatorProxy = false) : (menu.value = false),
        ),
      onMouseenter: () =>
        prevent ? (activatorProxy = true) : (activatorHover.value = true),
      onMouseleave: () =>
        prevent ? (activatorProxy = false) : (activatorHover.value = false),
    },
);
const baseAttrs = {
  modelValue: false,
  noParentEvent: true,
  noFocus: true,
  noRefocus: true,
};

const menuAttr = computed(() =>
  props.disable
    ? baseAttrs
    : {
      ...baseAttrs,
      onHide: unprevent,
      //onShow: (e) => console.log(e),
      modelValue: menu.value,
      'onUpdate:modelValue': (v) => (menu.value = v),
      onMouseenter: () =>
        prevent ? (menuProxy = true) : (menuHover.value = true),
      onMouseleave: () =>
        prevent ? (menuProxy = false) : (menuHover.value = false),
    },
);
</script>
```

Usage:
```vue
<template>
<QMenuHover>
    <template #default="{activatorAttr, menuAttr}">
         <QBtn v-bind="activatorAttr">
            Hover me
            <QMenu v-bind="menuAttr">
               ....
            </QMenu>
         </QBtn>             
     </template>
</QMenuHover>
</template>
```

Inspiration can be taken to integrate this into the core

**Comment by ssendev** [comment]
With this the menu opens immediately and only closing is debounced which allows longer times without being annoying and without flashing the menu.
```js
watch(menuHover, (hovered) => {
  if (hovered) {
    menu.value = true
  } else {
    debounceMenu()
  }
})
watch(activatorHover, (hovered) => {
  if (hovered) {
    menu.value = true
  } else {
    debounceMenu()
  }
})
```

**Comment by teajaysee** [comment]
Hi @Tofandel , I don't suppose you'd have time to extend your solution that it works with sub menus. At the moment if you add a submenu, the whole menu will close when try to use it as obviously the mouseleave for main menu is called.

**Comment by Tofandel** [comment]
I actually did but I don't think I have seen your comment, I updated the code on the previous comment, I think at this point I should publish it as an npm package

Just a note that the menu is not very accessible though, it will open correctly on focus now but tabbing or arrows will not select the first menu element, so if anyone wishes to improve on this go ahead

Usage:

```vue
<template>
<QMenuHover>
  <template #default="{ activatorAttr, menuAttr }">
    <QBtn v-bind="activatorAttr">
      Hover me
      <QMenu v-bind="menuAttr">
        <QList>
          <QMenuHover>
            <template #default="{ activatorAttr, menuAttr }">
              <QItem v-bind="activatorAttr" dense>
                <QItemSection>
                  <QItemLabel>Chapitres</QItemLabel>
                </QItemSection>

                <QMenu
                  anchor="top right"
                  self="top left"
                  v-bind="menuAttr"
                >
                  <QList><QItem>Sub menu</QItem></QList>
                </QMenu>
              </QItem>
            </template>
          </QMenuHover>
        </QList>
      </QMenu>
    </QBtn>
  </template>
</QMenuHover>
</template>
```

**Comment by Flamenco** [comment]
I took a different approach to this.  Here is a rough draft.

```ts
<script>
const isHover = ref(false)
function onHover() {
  // close other menus, set timers, debounce, etc
  isHover.value = true
}
</script>
```

```vue
<my-component @mouseenter='onHover'>
  <q-menu v-model='isHover'>This is a menu</q-menu>
</my-component>
```

If you want to be composable:

```ts
<script>
type MenuHoverOpts = {
}

function useMenuHover() {
  const isHover = ref(false)
  function onHover(opts?: MenuHoverOpts) {
    // close other menus, set timers, debounce, etc
    isHover.value = true
  }
  return {isHover, onHover}
}

const {isHover, onHover} = useHover()
</script>
```

**Comment by Tofandel** [comment]
I don't think this qualifies as a different approach, I used mouseenter and mouseleave events on a parent renderless component that handles the vModel and events of the QMenu and on your draft you are also using mouseenter in the same way but there is no mouseleave handling so it will never close when you leave it. Just stick with the already worked out and battle tested solution that also handles nested menus because you'll just be reinventing the wheel and hitting all the same problems I already hit

**Comment by Flamenco** [comment]
@Tofandel 

You are requiring both components to be wrapped by another element.  IMHO that is a different approach.  Instead of using composition, you are using templates. 

The worked out battle should be migrating your code into a composable model....

See [https://vueuse.org/core/useElementHover/#useelementhover](https://vueuse.org/core/useElementHover/#useelementhover).  They already fought your battle :)

**Comment by Tofandel** [comment]
They didn't though, QMenu is a very special element because it has an activator (the link/button which you need to hover or focus to open the menu), the actual menu and possibly submenus and it needs to be considered hovered if any of the activator, menu or submenus have the mouse over it, and close when the mouse leaves all of them without being in a new submenu.

As such QMenuHover is a very specialized headless component for QMenu, it also handles focus on the activator, not just mouseenter (because not everyone uses a mouse to navigate)

Composition does not fit the use case, because inject provide is necessary to handle the nested QMenu, and that only works the way it should work with a headless component, with composition it would look like this

```js
const { menuAttrs: menuAttrs1, activatorAttrs: activatorAttrs1, provide: inject1 } = useMenuHover();
 
const { menuAttrs: subMenuAttrs1, activatorAttrs: subActivatorAttrs1 } = useMenuHover({}, inject1);
```

A headless component IS composition but directed at the template to not pollute the component's scope, if you look at the code, you'll see that it's very easy to turn it into composition by just returning menuAttrs and activatorAttrs, everything is already self contained, but I didn't do that because a headless component is simply better suited, and inject/provide to handle submenus is cleaner than injecting via composition.

Otherwise if you had 20 menus you'd need to have 20 different `useHoverMenu` a rename each variable, there everything is handled by the component and passed via template props which never make it to the component scope

But if you still think this is better then go ahead. Can't say I didn't warn you though
