### ISSUE TITLE
Store instance in pages/component is not effected by client run of boot files

### ISSUE THREAD

**Issue by Khan294** [quasarframework/quasar#5795]
**Platform:**
OS: Windows 10
Node: 10.16.0
NPM: 6.9.0
Browsers: Chrome

**Bug**
Store instance (this.$store) in pages and components is not effected by the changes made when boot files run on the client side.

**Description**
I am trying to initialize some default store states which I will be using throughout the site. To do this I have some code in a boot file (initiate.js) which runs twice, first for the server and then client side. On client side there can be other calculations which will modify some of these states again.

This is from my boot file
![2019-12-04 17_33_58-](https://user-images.githubusercontent.com/36960116/70142999-4ecde300-16bc-11ea-9a22-5708b37cf52f.png)

Server log for that state shows the expected value
![2019-12-04 17_05_35-Window](https://user-images.githubusercontent.com/36960116/70142854-057d9380-16bc-11ea-94b0-234b73b98f8a.png)

First log on client is also according to the expected output. 
But state log on page shows the output from the server as if client side boot changes are not effecting data for home page.
![2019-12-04 17_05_56-Window](https://user-images.githubusercontent.com/36960116/70142860-09111a80-16bc-11ea-9cdf-fc1c4c3256de.png)

**Comment by rstoenescu** [comment]
Hi,

Your description requires more details, but regardless, putting some thoughts of what I think may be a problem with your code:

* Should you need, you can set boot files to run only server-side or only client-side (if you fill vuex state from server-side then there's no need to redo it from client-side)
```js
// quasar.conf.js
boot: [
  {
    server: false, // run on client-side only!
    path: '<name>' // references /src/boot/<name>.js
  },
  {
    client: false, // run on server-side only!
    path: '<name>' // references /src/boot/<name>.js
  }
]
```

* if your vuex action is asynchronous (store.dispatch(...)) then you need to wait for it to be fulfilled; boot files allow you to have asynchronous operations; if the vuex action is async and you don't wait for it, then your vuex state will not be in good condition;
```js
export default ({ .... }) {
  // ...
  return /* a Promise */ store.dispatch(....).then(() => { /* ...the rest... */ })
}
```
OR
```js
export default async ({ .... }) {
  // ...
  await store.dispatch(.....)
  // ...the rest...
}
```

**Comment by Khan294** [comment]
Still not working.

Tried both thing on a fresh installation with these configurations
![2019-12-05 21_01_35-Window](https://user-images.githubusercontent.com/36960116/70255240-40f58c00-17a8-11ea-9597-84361d44b31e.png)

First I created my store like this
![2019-12-05 21_39_33-Window](https://user-images.githubusercontent.com/36960116/70255272-51a60200-17a8-11ea-8236-94fe2923c750.png)

Then added a client side boot file
![2019-12-05 21_41_24-Window](https://user-images.githubusercontent.com/36960116/70255371-7bf7bf80-17a8-11ea-9c2a-0420ed08e40f.png)

And consoled before and after waiting for dispatch to return results
![2019-12-05 21_39_49-Window](https://user-images.githubusercontent.com/36960116/70255313-6a161c80-17a8-11ea-8a17-54642234963f.png)

And finally consoled state in page mounted function
![2019-12-05 21_40_01-Window](https://user-images.githubusercontent.com/36960116/70255453-a5b0e680-17a8-11ea-8734-e9b5ef4f3281.png)

But no luck same result
![2019-12-05 21_40_42-Window](https://user-images.githubusercontent.com/36960116/70255495-b9f4e380-17a8-11ea-974f-4c600e257db6.png)

Code is available [here](https://github.com/Khan294/quasartest)

**Comment by rstoenescu** [comment]
Fix will be available in “@quasar/app” v 1.3.8

**Comment by doorkey** [comment]
Thank you so much.

**Comment by dmitry** [comment]
@rstoenescu after this change our application will have an issue, because we are using apollo as our `store` and it initialized only while the boot.

I see that normally `store` initialized before all the boot files, but apollo cannot be initialized because we need `router` and `ssrContext` which are only can be accessed in the boot. For this trick `store` wrapper is initialized inside the `store.js` and then it continues to initialize completely inside the boot file `apollo.js`.

One of the solutions might be to use different `replaceState(window.__INITIAL_STATE__)` when not using `store` at all, but in that case the problem is template, which is not allowing to add `__INITIAL_STATE__` or other variable inside the template in the `HEAD` tag. [Solution](https://github.com/quasarframework/app-extension-apollo/issues/13#issuecomment-528342240) doesn't work completely fine, especially when starting to use cordova (it shows javascript data before the splashscreen).

Would be really great to be on the edge of quasar for our application, but this change is breaking our apollo integration. Please, lets find the solution to it.

**Comment by dmitry** [comment]
One of the easiest solutions might be to hydrate data manually, instead of automatic way before the boot files. So would be great to have some flag, which can switch on/off the data hydration inside the `client-entry.js`.
