### ISSUE TITLE
[Request] Support for HTML Server Side Includes

### ISSUE THREAD

**Issue by Wenish** [quasarframework/quasar#5863]
**Is your feature request related to a problem? Please describe.**
At the moment the Development Server dose not support HTML Server Side Includes.

**Describe the solution you'd like**
As a developer i want to be able to use [HTML Server Side Includes ](https://de.wikipedia.org/wiki/Server_Side_Includes)in the `index.template.html` file.

**Describe alternatives you've considered**
Add a config.json file into the statics folder. Which gets generated on the release pipeline for each environment. This is not really nice since on some cloud providers for change a simple configuration you have to push the hole app. 

**Additional context**
Environment specific configuration should not be backed into the Build.
So on a CI / CD Pipeline i can build my code once and push the artifact to the all my diffrent environments. Production build is the exactly the same as i tested it on staging.
So on an enviroment i can just change as example in the Environment Variable the ClientID and every new request on my website uses the new ClientId.

**Comment by pdanpdan** [comment]
And who would process this SSIs?

**Comment by Wenish** [comment]
@pdanpdan this would handle the web server.
for quasar there would be an adjustment for the local development webserver so it handles the SSI.
As Example if the cloud service use nginx you can active it over the nginx config file:
http://nginx.org/en/docs/http/ngx_http_ssi_module.html

**Comment by pdanpdan** [comment]
As I understand it SSI is a postprocessing step (macro replacement) done by the web server on the html it serves, so I don't see what quasar should do.
Just put your directives in the HTML and pass it trough your SSI processing web server.

**Comment by Wenish** [comment]
@pdanpdan if i use the command `quasar dev` it starts a webserver. i would like that this webserver which comes by default can handle SSI

**Comment by rfox12** [comment]
@Wenish what you're asking for is out of the ordinary because the webpack server will only be present in development (not when you have code ready for production).  

That being said... you can load webpack plugins in your quasar.conf file.  I haven't tried it but I found https://www.npmjs.com/package/ssi-webpack-plugin

In quasar.conf you can specify a webpack plugin by looking for the `extendWebpack(cfg)` area, potentially doing something like this:
```
extendWebpack(cfg) {
   const SSICompileWebpackplugin = require('ssi-webpack-plugin')
   cfg.plugins.push(
        new SSICompileWebpackplugin({
            publicPath: '',
            localBaseDir: '/',
            minify: false,
            proxy:"",//可以使用代理
            pathRewrite:{
                '^api':"xxx",//支持正则替换
            },
            remoteBasePath:"http://baidu.com",//如果传了此参数，则表示从远程http请求中获取ssi文件的内容
            variable:{
                'QUERY_STRING':"test=1",//如果ssi文件地址里有引用变量,如${QUERY_STRING}，则会用此参数里的对应key的值替换
            }
        })
}
```
pardon the Chinese!
You would also need to install ssi-webpack-plugin as a dev dependency:
`npm install ssi-webpack-plugin --save-dev`

Again I don't use this plugin and can't vouch for it... but that's the basic idea.  Hope it helps.

**Comment by rstoenescu** [comment]
Solution from @rfox12 seems perfectly valid (thanks @rfox12 !).
