### ISSUE TITLE
Should PreventScroll mixin clean up if destroyed while it's preventing a scroll?

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/quasar#5882]
**Describe the bug**
See related issue quasarframework/quasar-ui-qoverlay#21 in which a component in the extension uses the `PreventScroll` mixin. If the component is destroyed before the overlay is dismissed, the prevent-scroll is not cleaned up and you can longer scroll.  
  
Cross posting because I am not sure if it should be an implementation's responsibility to handle this scenario or if the mixin should take care of it. I'm thinking the mixin should do it based on how other mixins clean up (like `Fullscreen` calling `exitFullscreen` in `beforeDestory`). However, I noticed there was a similar issue for `QDialog` in #5798 where it was fixed directly in `QDialog` instead of the mixin so maybe I am wrong on that.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/gordonblahut/pen/dyPGjzM?editors=1111

**To Reproduce**
1. Open https://codepen.io/gordonblahut/pen/dyPGjzM?editors=1111
2. Check off "No scroll" and click "Full Screen"
3. Click the "Exit" button, (which has been changed to kill the q-overlay component to simulate what would happen in a route change)
4. The overlay disappears, but scrolling remains disabled.

**Expected behavior**
Once the overlay is no longer visible, previous scrolling behaviour should be restored.

**Screenshots**
N/A

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

It's rather an incorrect usage of the prevent-scroll mixin.

There's no point in adding additional overhead in the mixin with yet another vue lifecycle hook, since each component who extends the mixin has its particularities/specificities. For example, in QDialog, if the display state when destroying is not "true" it's then guaranteed that prevent scroll was previously disabled already --- through the __cleanup() method, so we avoid the overhead of calling it again, checking if prevent state allows disabling etc etc.

Moreover, I was unaware that these mixins are used in the wild. They are not part of the public API contract and so their implementation may change without any notice.

**Comment by GordonBlahut** [comment]
> Moreover, I was unaware that these mixins are used in the wild. They are not part of the public API contract and so their implementation may change without any notice. 
   
This usage was in an official Quasar extension. Not sure if these extensions are part of "the wild" or if they are ok to use non-public APIs.

I realize you probably don't want to make the Quasar API surface area too large, but having a few mixins could be valuable for public (or at least official extension) use since there's a lot of goodness in your implementations that would likely be missed in custom implementations of similar features. 
  
Scroll prevention for example, could be useful (or maybe as part of the scroll utils) since a custom implementation is unlikely to properly handle things like multiple components concurrently requesting scroll preventing, custom iOS handling, etc. that are handled within your mixin.
