### ISSUE TITLE
[capacitor] Splashscreen is not hidden by Quasar even if quasar.conf.js is set to do it

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#5915]
Description in title.

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v1.4.2.

**Comment by vycoder** [comment]
Hi, I'm having the same issue now. I'm on:
```
quasar - 1.9.8 
@quasar/app - 1.6.0
@quasar/extras - 1.5.2 
```
I'm trying enable these options on `quasar.conf.js`:
```
module.exports = function (ctx) {
  return {
    ...
    capacitor: {
      iosStatusBarPadding: true,
      hideSplashscreen: false // disables auto-hiding the Splashscreen by Quasar CLI
    }
  }
}
```
I tried putting it on `framework.config`. But it doesn't work. It seems to be only working when I put it directly at `capacitor.config.json`

**Comment by rstoenescu** [comment]
@vycoder 
Just for the record: have you set "hideSplashscreen" to `true`? Setting it to `false` means "don't hide".

**Comment by vycoder** [comment]
@rstoenescu yes. I was hiding it manually using capacitor's SplashScreen plugin.

A bit of context, if it will help: I'm seeing a certain delay between hiding the SplashScreen and the actual rendering of my app. I'm not sure if it's because running it on dev mode is slow or there's really just a lag there. So I figured to just hide it manually.
