### ISSUE TITLE
QBtnToggle slot scope

### ISSUE THREAD

**Issue by Propaganistas** [quasarframework/quasar#5925]
I'd like a QBadge component with an option-specific text inside a QBtnToggle:

![image](https://user-images.githubusercontent.com/6680176/71247899-f896ac00-2319-11ea-98ca-071c01446ae0.png)

I understand a slot can be used to provide the badge itself, but how do I provide the slot template with a dedicated slot scope?

The following unfortunately doesn't work:

```html

<q-btn-toggle rounded no-caps v-model="model"
    :options="[
      {label: 'One', value: 'one', slot: 'badge', count: 50 },
      {label: 'Two', value: 'two'},
      {label: 'Three', value: 'three'}
    ]"
>
  <template v-slot:badge slot-scope="props">
    <q-badge color="grey" class="on-right">{{ props.count }}</q-badge>
  </template>
</q-btn-toggle>
```

Note: in the snippet above I've hardcoded the desired count, but of course this should be dynamic by using a computed options property.

**Comment by smolinari** [comment]
Won't this work? https://codepen.io/smolinari/pen/yLyMErW?&editable=true&editors=101

Scott

**Comment by Propaganistas** [comment]
That would work, yes, but when each option needs such a badge it requires a template per option, and hence duplicates equal code?

I'm looking for a simplified way to reuse that template across all options, especially when the options become dynamic..

**Comment by smolinari** [comment]
Like that? https://codepen.io/smolinari/pen/yLyMErW?editors=1010

Scott

**Comment by Propaganistas** [comment]
Yes that's perfect! Thanks a brunch.

I wonder why there's no label slot available scoped to the option object. I feel like that's a motte intuitive Vue-like approach?

**Comment by smolinari** [comment]
Because the options are 100% in devland, so no need to scope them in the slot, as the array/ the data is  available to the template you are adding to the slot. If the options were broken down any by the component itself in some way, then it might make sense to scope them to the slot. If you see slots as "inversion of control" within templates, then it makes total sense and is 100% Vue-like. 😁 

I'm going to go ahead and close this issue. I think we have your problem solved. 😄 

Scott
