### ISSUE TITLE
Quasar and Svelte

### ISSUE THREAD

**Issue by Level0r0s** [quasarframework/quasar#6007]
.
Will there be a fo quasar version with Svelte?

**Comment by smolinari** [comment]
No. There won't be.

Scott

**Comment by rstoenescu** [comment]
Svelte doesn't offer anything significant in return. On the contrary, having to write only html templates instead of using render functions is VERY limiting. Even if we would want to port Quasar to Svelte, we'd have to drop a lot of features. You might say Svelte renders faster, but Vue 3 comes very close in render speed, even surpassing Svelte in many scenarios. Then my final argument would be the resources needed to do this. We are already maintaining the most feature-rich UI library with top-notch support for a LOT of environments (desktop browsers, mobile browsers -- android, **iOS**, cordova, capacitor, ...), a CLI with lots of build modes, starter kits, documentation app, App Extensions. There's not enough companies donating that would allow us to start yet another big big project like a port to Svelte. Our current focus is to add even more components and directives and port Quasar to Vue 3 rather than expanding to Svelte.

**Comment by ansarizafar** [comment]
@rstoenescu  Is amazing Quasar ready for Vue 3? If not then is there an ETA?

**Comment by rstoenescu** [comment]
Q3 2020. But let's first see when final Vue v3.0.0 gets shipped first :)

**Comment by ansarizafar** [comment]
Is there any chance of a preview version of Quasar with Vue v3 support in Q2 2020?

**Comment by smolinari** [comment]
@ansarizafar - No. We are waiting on Vue 3, then there is a lot of work that needs to be done, depending on the direction we take. Q3 is the earliest. 

Scott
