### ISSUE TITLE
q-input send focus event before blur in Quasar v1.6.1

### ISSUE THREAD

**Issue by ggregg** [quasarframework/quasar#6034]
When i leave q-input to over, **focus** event is throwed before **blur** :(

**codepen**
https://codepen.io/ggregg/pen/ExaENLy

**To Reproduce**
1. Go to input a
2. Go to input b
3. and so on

**Expected behavior**
Events : focus A, blur A, focus B, blur B, focus A, blur A, ...
Not Events : focus A, focus B, blur A, focus A, blur B, focus B, ...

**Platform **
OS: window
Browsers : Firefox 73.0b2, Chrome  79.0.3945.117

**Comment by pdanpdan** [comment]
This happens because a timeout is required to check if the blur event in QField and derived components will not be followed by a refocus on the same component.

If you need to have the exact order of events, but with possible duplicated events then you can listen on `@focusin` and `@focusout` - example here: https://codepen.io/pdanpdan/pen/YzPaZPm

**Comment by ggregg** [comment]
Ok, Thank you.
