### ISSUE TITLE
Better "vue ui" integration

### ISSUE THREAD

**Issue by Richie765** [quasarframework/quasar#6079]
I working on many Quasar and Vue projects and I'm using `vue ui` to run and monitor all the `serve` tasks in a single interface. I've found a way to add Quasar projects to the UI but it's not working as good as with Vue projects.

To add Quasar to `vue ui` I first added a serve script to `package.json`.

```json
  "scripts": {
    "serve": "quasar dev"
  },
```

Next I launch `vue ui` and import the project. The serve task shows up in the project and I can start it. However the "Dashboard" and "Analyzer" tabs don't show up. I suspect this is due to the `vue serve` and `quasar dev` giving very different output.

I think it may work when the project is created with vue-cli instead of quasar-cli but it would miss the benefits that it brings.

Perhaps it would be possible to make `quasar dev` pass all the needed info on to `vue ui`.

I'm also curious how others manage running multiple serves at the same time. One way I could imagine is running them all in `tmux` but perhaps there are better ways I'm not aware of.

**Comment by rstoenescu** [comment]
Hi,

Vue CLI is one thing and Quasar CLI is another. Pick only one.
But seems like you just need to run multiple "quasar dev"s simultaneously (on different projects, I hope, otherwise it's kind of pointless). Then open up multiple terminal tabs on each of those projects and run "quasar dev" on each.
