### ISSUE TITLE
Support conditional binding for listeners like v-touch-pan

### ISSUE THREAD

**Issue by gruppler** [quasarframework/quasar#6083]
**Is your feature request related to a problem? Please describe.**
I want to conditionally capture swiping, but currently there doesn't seem to be a way to do this. To be clear, I don't want to capture/prevent touch-starts unless my handler is enabled, because this interferes with scrolling.

**Describe the solution you'd like**
If a handler is null, silently abort and unbind the listener. If the handler changes from null to a function, rebind the listener.

**Describe alternatives you've considered**
I can't think of any other way to accomplish this. Currently, I'm using the following code, which works but produces errors ("ctx.handler is not a function"):
`v-touch-pan.prevent.mouse="board3D ? rotateBoard : null"`

**Additional context**
Vue 2.6 allows for [conditional event binding](https://github.com/vuejs/vue/issues/7349#issuecomment-458405684).

**Comment by metalsadman** [comment]
@gruppler `v-touch-pan.prevent.mouse="isDirective ?handlePan : () => void 0"`

**Comment by gruppler** [comment]
The problem with that solution is it still captures the event even when inactive, preventing scrolling.

**Comment by rstoenescu** [comment]
Starting with future "quasar" v1.7.2, if the handler is a Function, it'll do something with it, otherwise it's gonna be equivalent to not having the touch directive(s) attached.

So this will be perfectly valid:
`v-touch-pan.prevent.mouse="condition ? yourHandler : void 0"`

Again, if handler is not a Function, then it won't interfere with ANY events.

**Comment by gruppler** [comment]
Thank you so much!
