### ISSUE TITLE
[docs] QTable Pagination example on top slot

### ISSUE THREAD

**Issue by ajcastro** [quasarframework/quasar#6103]
I think it is a common UI design for some tables to have pagination on the footer/bottom and on top at the same time. Maybe we can also demo how to do this on the docs?

**Comment by ajcastro** [comment]
Current working solution: https://gist.github.com/ajcastro/83af279e7d7540f82cae791d9bd430f9

**Comment by rstoenescu** [comment]
Same example as here, only with "top-left" slot instead of "pagination": https://github.com/quasarframework/quasar/blob/dev/docs/src/examples/QTable/PaginationSlot.vue
**Note that** there are some additions in Quasar v1.12 (for which this example is written): the firstPage(), lastPage() bits, so ignore them for now. But the principle is the same. Something extra would be to throw in a QSelect and connect it to your pagination.rowsPerPage. Starting with Quasar v1.12 you'll also be able to hide the default pagination controls so you can position them wherever you want.
