### ISSUE TITLE
"scroll" class is not working in scrollToElement function

### ISSUE THREAD

**Issue by sandroden** [quasarframework/quasar#6141]
While using [scrollToElement](https://quasar.dev/quasar-utils/scrolling-utils#Scrolling-to-an-element) I was not able to have proper scrolling if the scrolling area is not the entire page.

I had to manage the offset by hand adding a single line. It may be worthwhile fixing the function or the docs. My final function is:

```
scrollToElement (el) {
  let scrollEl = el.closest('.scroll')  // added to find the offset of the scrolling region
  const target = getScrollTarget(el)
  const offset = el.offsetTop - scrollEl.offsetTop // adjust the scrolling
  const duration = 100
  setScrollPosition(target, offset, duration)
}
```
I show the misbehaviour in this [codepen.it](https://codesandbox.io/s/scrolltoelement-xrtf2) sample

**Comment by rstoenescu** [comment]
Hi,

I fail to see how Quasar is at fault here. You need to keep into account the extra offset of the header by yourself...

**Comment by sandroden** [comment]
Hi @rstoenescu ,

from the docs I was led to think that attaching a "scroll" class to the scrolling area was enough, but it's not! Moreover it seems "scroll" class is useless, if I need to do the computing myself I can do it in any other way (eg: `ref` or `.closest` using other selectors). So what's the role of "scroll"? Also Jeff Galbraith on discord suggested that the key was "scroll" class (that I was already using), I think he was believing as well that "scroll" class was taken into consideration by scrollToElement.

**Comment by rstoenescu** [comment]
There is a gross misunderstanding of how things work here:
* setScrollPosition() sets the scroll position to the offset indicated, nothing more
* getScrollTarget() looks for the first parent (up to body) which has .scroll, .scroll-x, .scroll-y or .overflow-auto classes as described [here](https://quasar.dev/quasar-utils/scrolling-utils#Determine-scrolling-container)
* .scroll class makes the container scrollable (smooth scroll specs on iOS especially), nothing more than CSS

What gave you the impression that some method in Quasar can guess your custom setup and magically determine some area is hidden from view?

**Comment by sandroden** [comment]
I don't understand why you think I have something hidden from the view (have you looked at my
[codesand](https://codesandbox.io/s/scrolltoelement-xrtf2) snippet?).

I think that there's just half line in the docs that in my opinion would help:

```
- const offset = el.offsetTop 
+ const offset = el.offsetTo - target.offsetTop
```
that would take into account that target may have an offset with respect to the page.

Are there cases in which this would be wrong?

**Comment by GordonBlahut** [comment]
@rstoenescu I've noticed similar issue trying to scroll to an element, I think the `scrollToElement` code in the docs does have issues. 

Here's a sample codepen. https://codepen.io/gordonblahut/pen/NWPOpbo?editors=1111

Notice that it does not scroll to the element inside the QCardSection (`#hey`) because QCardSection ends up being an `offsetParent` and so `offsetTop` ends up being really small so the window barely scrolls.

I would expect to have to deal with the QHeader offset, but there's no QHeader in this case.

Not sure if I should make a new issue since this one is only a few hours old.

**Comment by hawkeye64** [comment]
@GordonBlahut If you look at the code to see what is happening, the calculation of `offset` is 21, which is the distance from it's parent (21).
![image](https://user-images.githubusercontent.com/10262924/72680041-74e3f280-3a72-11ea-92b1-57f8b1dfb517.png)

![image](https://user-images.githubusercontent.com/10262924/72680046-8c22e000-3a72-11ea-8709-aedbb313406e.png)
Further, this code:
```js
const target = Quasar.utils.scroll.getScrollTarget(el)
```
returns window. Therefore, it will only scroll 21 pixels from the top of window.
The problem, as I see it here, because only the window is scrollable, then the calculation of the offset it incorrect.

You can fix this with the following:
```js
const offset = el.offsetTop + el.offsetParent.offsetTop
```

**Comment by sandroden** [comment]
> - const offset = el.offsetTop 
> + const offset = el.offsetTo - target.offsetTop
> ```
> 
> that would take into account that target may have an offset with respect to the page.
> 
> Are there cases in which this would be wrong?

yes!! surely it will be wrong if the scrolling element is **positioned**!!!

So, it ends up my mistake was due to the fact that I didn't position the scrolling area so that el.offsetTop (the distance of the element relative to the top of the offsetParent - ie positioned the closest ancestor ) returned the distance to the q-page element.
I don't know if it's better to position the scrolling area or to consider its position in the scrollToElem function, both seem to work for me. 
For noobie people like me in css-positioning it would be useful if you could consider mentioning the role of positioning beside attaching "scroll". I understand this can be considered trivial to more skilled ones...
