### ISSUE TITLE
[docs] Discurage using lambda functions as v-intersection directive handler

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar#6143]
This issue is only to warn who'll get my same problem in the future, maybe a disclaimer could be added to the `v-intersection` page.
Can be closed right away if you think it's not worth a disclaimer.  

As stated in the API regarding the handler return value: `Only value of interest is the Boolean false, in which case observing the element stops`.
Rephrased: if you return false from the handler, the observer stops.

Also, the observer always emit one entry when first attached and you are supposed to check for `entry.isIntersecting`.

Take this snippet

```vue
<img v-intersection.once="entry => entry.isIntersecting && someMethod()" />
```

This could seem like a clean and concise way to express "when intersecting for the first time, execute this method", but `someMethod()` won't actually ever be called (unless the element is already into the view).
The "registration emission" of the observer will return `false` because of the `entry.isIntersecting` and never emit anything else.

Using normal anonymous functions will work, but at this point it's better to just use a Vue method 
and reference that instead. 

```vue
<img v-intersection.once="function(entry) { entry.isIntersecting && someMethod(); }" />
```

**Comment by rstoenescu** [comment]
The title is not accurate.
This works, because it doesn't automatically return the value of the expression.

`entry => { entry.isIntersecting && someMethod() }` translates to `function(entry) { entry.isIntersecting && someMethod(); }`, while `entry => entry.isIntersecting && someMethod()` translates to `function(entry) { return entry.isIntersecting && someMethod(); }`

But the main point is something else entirely. No matter what Vue directives you use (Quasar or not, doesn't matters), if you need to supply a Function, then don't inline it. It'll generate a new function on each render, so the directive will have to process it as if something changes. ALWAYS reference Functions from the `methods: {}`. Same goes for event listeners etc etc. This is if you care about performance.

---

Can you pls PR the rephrasing pls?

**Comment by rstoenescu** [comment]
Updated docs.

**Comment by IlCallo** [comment]
Sorry, could now use a PC for whole weekend, thank you for the explanation and the change!

**Comment by IlCallo** [comment]
Sorry, could now use a PC for whole weekend, thank you for the explanation and the change!
