### ISSUE TITLE
I think Line Awesome icon font would be a great addition.

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#6164]
**Is your feature request related to a problem? Please describe.**

- I like Material Icons but they just don't cover enough use cases.
- I could use Font Awesome but they are an older thicker style (and the wrong size by default in Quasar).

**Describe the solution you'd like**

- I discovered the very cool [Line Awesome](https://icons8.com/line-awesome) set of 1380 icons - a drop in replacement for most Font Awesome icons (same names).  They would be my icon set of choice if made available as a preset in Quasar as I think the thinner line style is much more readable, modern and works well in dark mode. Lots of Devs know the Font Awesome set, switching an existing project to use them should be fairly easy.

- In the past I've steered away from larger font sets due to their download size ... but you've just fixed that!

- Because Line Awesome is pretty much a one-4-one replacement for Font Awesome, I figured the configuration effort to add them as a preset icon set should be less.

- If possible, please set their default icon size to match Material Icons. I've read your notes on #4858 .

**Describe alternatives you've considered**

- Yes! I know you can configure you're own icon set but you'd miss out on new QIcon features like tree shaking.   

**Additional context**

- Line Awesome font is MIT or [Good Boy](https://icons8.com/good-boy-license/) licence.
- Quasar needs to compete with Vuetify on Theme/Styling. This this icon set would IMHO help to tip the balance.

**Comment by tohagan** [comment]
Here's a review of Line Awesome that covers some of the other features of this icon font. 
- https://www.visualpharm.com/articles/line_awesome-font_awesome.html

**Comment by rstoenescu** [comment]
Hi,

1. You can already use whatever icon lib is not supplied out of the box by quasar/extras: Add CDN link in /src/index.template.html then -> https://quasar.dev/vue-components/icon#Custom-mapping
2. Not our fault Font Awesome specifically designed their free icons to be ugly (so that you pay for the Pro version)
3. When you use the webfont variant there's no treeshaking (its full .css and .woff/.woff2 files are needed)
4. Quasar is already waaaay ahead in theming/styling -- we support any icon lib (as per point 1.) and offer much more out of the box (themify, ionicons, eva, ...).
5. Line Awesome (webfont & svg) will be available through Quasar v1.8+ (webfont icon set, svg icon set, unreleased yet) and quasar/extras v1.5+ (released a few minutes ago).

Note that you can also tell Quasar to use your own custom Quasar Icon Set, which works great with the QIcon custom mapping.

**Comment by tohagan** [comment]
Thanks immensely for adding this new font. Yep I totally get the Font Awesome ugliness thing and your other points.

Just yesterday I finally convinced our team to proceed with Quasar on a major internal project but I needed Line Awesome to give it the final finesse. I love Quasar but my buddy at work does not .. thinking that Veutify is up on styling points. 

I think the reason is that they have well deigned Admin Theme kits and sell themes (Quasar has one very poorly done Admin theme kit - not done by your team - but it lowers the perception of what Quasar provides.. Veutify rolled out [this version](https://github.com/vuetifyjs/vuetify/releases/tag/v2.2.0) with 7 theme Presets from the [Material Design Studies](https://material.io/design/material-studies/). 

If you had similar showcases like these (on you home page?) then I think would significantly add to the market perception of your product.  You tick all the feature boxes (I get that!) but you lack the show case to demonstrate your theme capabilities which is often what sets the first impression. My buddy at work could not see this because of this poor "theme" first impression.

**Comment by tohagan** [comment]
Note: Veutify have also got them selves listed on the MD site. Can you join theme? 

- https://material.io/develop/web/
