### ISSUE TITLE
QUploader component does not work on Firefox Focus for Android

### ISSUE THREAD

**Issue by patrickas** [quasarframework/quasar#6217]
Steps to reproduce:
Using "Firefox Focus" for *Android* ( https://support.mozilla.org/en-US/kb/focus )
Go to a web page that has QUploader component ( ex: https://quasar.dev/vue-components/uploader )
Click on the [plus] button to upload a file
Nothing happens
I expect the file upload screen to open like it does in other browsers

PS: confirmed the bug exists in the Android phones (pixel2, pixel3) but seems to work fine on iphone.

**Comment by rstoenescu** [comment]
Hi,

When I wrote the component I tested extensively on mobile browsers (chrome, safari, FF) on both Android and Safari platforms, then on Cordova (with WkWebView) and Capacitor. Worked fine. Based on the fact that the browser itself launches the file picker, then if it doesn't works then there's nothing that we can do in Quasar... While Quasar should work correctly in 99% of the mobile browsers, the official list of supported mobile browsers includes Chrome, Safari, Firefox (the "classic", not FF Focus or their other).

However, due to the heavy load we're currently in, can you help with this a bit pls? Can you confirm that a regular `<input type="file">` works or not in Firefox Focus? Thanks.

**Comment by ibrainventures** [comment]
Its no issue by quasar .. its a open issue by firefox focus on android.

`https://github.com/mozilla-mobile/focus-android/issues/937`

Happens also with the german spinout "firefox klar" and a 100-percent simple <input type="file">.

**Comment by pdanpdan** [comment]
Thank you for investigating, @ibrainventures.

**Comment by ibrainventures** [comment]
upss .. sorry .. browser illness .. my link and confirm that it is a android issue ..

`https://github.com/mozilla-mobile/focus-android/issues/937`

the op told that it should work on ios .. thats may a other issue ..

**Comment by ibrainventures** [comment]
and it works fine with firefox focus / klar and quasar.dev


also works fine without custom header .. 


![IMG_0521](https://user-images.githubusercontent.com/8803626/73159200-41ded600-40e6-11ea-84d6-ec8761a6b851.jpg)

**Comment by pdanpdan** [comment]
TY :)

**Comment by rstoenescu** [comment]
It works on iOS, but the reported problem is for Android.

**Comment by ibrainventures** [comment]
@rstoenescu 
and on android it is a known missing feature:

`https://github.com/mozilla-mobile/focus-android/issues/937`

firefox focus works actually not on android with a pure `<input type="file">`

**Comment by rstoenescu** [comment]
Yes. I've tested it on the initial ticket. Was just writing this for completeness on the current ticket as well so the reporter knows.
