### ISSUE TITLE
Nightly Builds?

### ISSUE THREAD

**Issue by jkirkby91-2** [quasarframework/quasar#624]
Nightly builds were last updated a month ago can we get them enabled? There's some good changes in latest commits but can access them and changing the npm to git repo dev branch doesnt have the builds folder like when you init from the cli tool

**Comment by rstoenescu** [comment]
Nightly build will be resumed as expected after v0.14 release. Currently working on documentation (99% ready) and the starter kit for it. After these are done (probably today or tomorrow) then edge will point to latest of v0.14 build.

There are lots of changes in v0.14 mainly due to tree shaking, so updating edge to it without having a starter kit as example and documentation for it would have been useless, as you cannot simply update npm package to point to v0.14 and expect v0.13 apps to simply work. Having no documentation until now would have been a "no-go" too.

Read about the tremendous effort put into v0.14 and its features here: http://forum.quasar-framework.org/topic/253/future-v0-14-feature-list
