### ISSUE TITLE
Help can't run quasar dev after using quasar create on quasar 1.8.3

### ISSUE THREAD

**Issue by roysdev** [quasarframework/quasar#6243]
This is the error I get.

Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: [BABEL] C:\****\*****\Desktop\testing\.quasar\client-entry.js: Package exports for 'C:\Users\******\Deskt  op\testing\node_modules\@babel\helper-compilation-targets' do not define a '.' subpath (While processing: "C:\\Users\\  ******\\Desktop\\testing\\node_modules\\@quasar\\babel-preset-app\\index.js")

But I ran my old project from Quasar 1.6 and it is working fine. So this is an error on the new quasar 1.8

**Comment by smolinari** [comment]
Hello,

Thank you for your issue report. The information you supplied in this issue is not enough to allow us to reproduce and identify the problem. Please check the required issue template format and fill the information that is relevant to your issue.

The Quasar Team is handling dozens of tickets each day so providing good reproduction information is vital to handling more tickets and satisfying more developers. A good ticket description can lead to a quick fix, otherwise it may create frustration on both sides.

If you'd like, you can add any of the additionally requested information from the issue template in a comment and reopen this issue for further investigation. 

Thank you for your understanding

**Comment by pdanpdan** [comment]
@roysdev Check the nodejs version - use v12 (NOT v13)
