### ISSUE TITLE
Heading margin inconsistency

### ISSUE THREAD

**Issue by Nerderer** [quasarframework/quasar#6376]
**Describe the bug**
When looking at the documentation the h1-h6 elements should render the same as .text-h1-.text-h6, which is also what you expect. But in practice the h1-h6 ones also inherits margin from the browser, on the top and bottom of the text, making them look different than .text-h1-.text-h6.

**Codepen/jsFiddle/Codesandbox (required)**
[https://jsfiddle.net/w2arpe0o/](https://jsfiddle.net/w2arpe0o/)

**To Reproduce**
Use a h1 tag instead of .text-h1

**Expected behavior**
hX and .text-hX should render exactly the same.

**Screenshots**

**Platform (please complete the following information):**
OS: Mac OS X
Node:
NPM:
Yarn:
Browsers: Firefox, Chrome, Safari
iOS:
Android:
Electron:

**Additional context**
Real heading elements should most likely be prefered over divs for semantic reasons. Using them with the current implementation means that you'd have to manually reset the margins before use. It feels natural to have this css reset already in place.

**Comment by rstoenescu** [comment]
Hi,

This is by design. Sometimes you just want the font-size and font-weight and letter spacing applied somewhere, but not the whole thing -- like for eg. on a QItemLabel.

We cannot change it for v1.x even if we wanted because that would be a breaking change.
However if you'd like the two "sets" to match, then just add this:
```
h1, h2, h3, h4, h5, h6 { margin: 0 }
```
