### ISSUE TITLE
QSelect : have the dropdown persistent on route change

### ISSUE THREAD

**Issue by drasill** [quasarframework/quasar#6420]
**Is your feature request related to a problem? Please describe.**

I have a page where the route's query params change, when a form (filter) is updated.
So the user can go back to his previous filter.

This is working all great, but the dropdown of the `QSelect` is closed on route change, which is frustrating as it is a "multiple option" select.

**Describe the solution you'd like**
It would be great to have an option to set the `persistent` option of the `QMenu` component of the `Qselect` to `true`, so that the dropdown does not disappear.

**Comment by drasill** [comment]
I nobody is interested by this, you can close the issue.

My workaround has been to change the route only on `@popup-hide` event.
This a bit of work, but it's ok.

**Comment by smolinari** [comment]
It's hard to understand your use case completely, but in theory, you shouldn't need to reroute the user for every filter change or use that to allow them to go back to prior filter selections (I'm still trying to imagine how that would work). 

You might want to think about that overall design in general. 🤔 

Scott

**Comment by Zoey1988** [comment]
Any plan to add `no-route-dismiss` to `QSelect` API? @smolinari @moander

**Comment by jun3838** [comment]
We have the same needs as drasill , but slightly different use case.
We have a page with table listing, pagination, filter whatnot, when filter applied, selected filters are attached to query, so user could use same url for "filtered list", this is useful like a bookmark

Our problem is the same, when filter applied, query changed, QSelect popup/dialog is dismiss, it would be great if we could pass `persistent` or `no-route-dismiss` to QSelect to prevent that.

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.14.8 through propup-no-route-dismiss prop.

**Comment by ss5nathan** [comment]
Can anybody confirm that this fix works when updating query params like this?
`router.replace({
        path: router.currentRoute.value.fullPath,
        query: { 'queryKey': 'queryValue}
       })`

Locally, when I use `router.replace` with a multi select QSelect and `popup-no-route-dismiss` the popup still closes (on quasar 2.16)

This is as close as I got to reproduce in a jsfiddle, but could not reproduce, assuming because jsfiddle handles query parameters differently than a normal browser?

https://jsfiddle.net/8zcmrkn5/31/

Use case:
Using query params to store the state of q-select

`<template>
  <q-select popup-no-route-dismiss multiple label="Test" v-model="var1" :options="['op1', 'op2']"> </q-select>
  Var1 {{ var1 }}
</template>`

And then watch var1 and update query parameters when it changes

May just be something on my local side, but figured I'd post in case anybody else can confirm

**Comment by rstoenescu** [comment]
@ss5nathan Most likely the current page (or router-view component) gets destroyed and rebuilt, due to how the routes have been configured, so this has nothing to do with Quasar.
