### ISSUE TITLE
Header and footer moving while scrolling 

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#6455]
both header, background and footer moving while scrolling on chat message 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19895516/75089473-6dc07080-5559-11ea-911b-66ddfe297cb2.gif)

**Platform (please complete the following information):**
OS: iOs
Node:
NPM:
Yarn:
Browsers:
iOS: iPhone 6 
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Please supply a codepen or codesandbox with your usage...
Also, what iOS version is the phone using.

**Comment by diadal** [comment]
iPhone 6 iOS 12.4.5 real device and  iPhone XR Max iOS 13 simulator

**Comment by diadal** [comment]
on a fresh project same issue

**Comment by diadal** [comment]
I mean this https://github.com/quasarframework/quasar/blob/dev/docs/src/layouts/gallery/whatsapp.vue

**Comment by rstoenescu** [comment]
The link you gave is using a containerized layout. Due to (already reported and years old) bugs on the iOS platform regarding the fixed positioning (which are ignored completely), there is no technical solution. **Just use regular layouts (and NOT containerized)**. There are lots of bugs that we could overcome on the iOS platform that most developers using Quasar aren't even aware, but we can't do anything about this one.
