### ISSUE TITLE
Hide the menu by clicking the back button in Android

### ISSUE THREAD

**Issue by den67rus** [quasarframework/quasar#6542]
Video example youtube:
[![video youtube](http://img.youtube.com/vi/G6-snsktIvk/0.jpg)](http://www.youtube.com/watch?v=G6-snsktIvk)

This functionality can be implemented using the Vue router navigation hooks.

Something like this:
```
  beforeRouteLeave (to, from, next) {
    if (this.leftDrawerOpen) {
      this.leftDrawerOpen = false
      next(false)
    } else {
      next()
    }
  }
```

**Comment by rstoenescu** [comment]
Hi,

This is baked into Quasar only if app is wrapped with Cordova or Capacitor. However, on a mobile browser or on a desktop browser this cannot be achieved because it cannot cover all the use-cases (just an insignificant part of them). However, it can be achieved individually in each app by the developer (like in your example above). Quasar cannot (and should not) hook into each route (-- an option that would be available only through Quasar CLI anyway) and magically know who to hide or what scope variable (and from what component) to change.
