### ISSUE TITLE
Rules are not reactive

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#6549]
**Describe the bug**
When using i18n plugin (that uses vue-i18n, as described in the documentation), I noticed that the QInput rule's error message is not reactive. Code:
```
    <q-input
      v-model="name"
      :label="$t('yourName*')"
      :hint="$t('nameAndSurname')"
      filled
      lazy-rules
      :rules="[ val => val && val.length > 0 || $t('pleaseTypeSomething')]"
    />
```

The _pleaseTypeSomething_ label does not change when the language is changed via `this.$i18n.locale`.

**Codepen/jsFiddle/Codesandbox (required)**
Source code: https://github.com/tomers/quasar-i18n-example
Demo site: http://quasar-i18.surge.sh/

**To Reproduce**
1. Go to http://quasar-i18.surge.sh/
2. Notice the language is set to English
3. Press 'OK' to submit the form. Notice the "Please type something" error in the name QInput
4. Change language to Hebrew from the language QSelect in the toolbar
5. Notice that the entire interface changes, and all labels change to Hebrew, all but the rule error, which still show in English, although it has Hebrew translation
6. Refresh the page, and submit the form again. Notice that now the rule error is in Hebrew

**Expected behavior**
In step 5, the label is expected to be shown in Hebrew instead of English

**Screenshots**
![image](https://user-images.githubusercontent.com/83443/75919279-ec74b200-5e65-11ea-8cb9-4b5148f50003.png)

**Comment by pdanpdan** [comment]
Can you try to make a computed property for the array of rules and use that computed property in :rules?

**Comment by tomers** [comment]
@pdanpdan , it still doesn't work
```
        <q-card-section>
          <q-input
            v-model="name"
            :label="$t('yourName*')"
            :hint="$t('nameAndSurname')"
            :rules="nameFieldRules"
            filled
            lazy-rules
          />
        </q-card-section>

        <q-card-section>
          <q-input
            v-model="age"
            :label="$t('yourAge*')"
            :rules="ageFieldRules"
            filled
            type="number"
            lazy-rules
          />
        </q-card-section>
```

and

```
  computed: {
    ageFieldRules () {
      return [
        val => (val !== null && val !== '') || this.$t('pleaseTypeYourAge'),
        val => (val > 0 && val < 100) || this.$t('pleaseTypeARealAge')
      ]
    },
    nameFieldRules () {
      return [
        (val => val && val.length > 0) || this.$t('pleaseTypeSomething')
      ]
    }
  },
```

**Comment by tomers** [comment]
I added console prints in the computed properties, and noticed that they are being called as expected, whenever the language changes. The issue is probably that the rules are not re-applied after the rule reactive attribute changed, thus the label does not change.

**Comment by tomers** [comment]
Created a pen:
https://codepen.io/tomers-the-encoder/pen/abOLqdx?editors=1010

**Comment by pdanpdan** [comment]
Thank you. I found the problem: the validation is not rechecked when rules change.

**Comment by rfox12** [comment]
Thanks for the hard work on this... I recently ran into this issue too--it's certainly a "wow factor" to have an app change language dynamically.

**Comment by 1001v** [comment]
A possible temporary workaround is to give your qinput a key which is based on some reactive data. Not a great solution, but it works.

**Comment by rstoenescu** [comment]
New Boolean prop in "quasar" v1.11.0: `reactive-rules`.

**Comment by 1001v** [comment]
@rstoenescu hello! And thanks everybody who was working on this. However, could you please share your thoughts about why this should be a separate property instead of default behavior? In my opinion, in vue ecosystem we expect everything to be reactive by default. Or shouldn't reactive-rules property at least be true by default? I understand that someone could count on that rules are not reactive in their existing apps, but shouldn't you do a breaking change now to provide a better experience in future? Thank you.

**Comment by rstoenescu** [comment]
@1001v It won't be a better experience. It will be a worse experience perf-wise. Which is why a separate prop is needed if you REALLY want this. The reason is simple: most devs declare the rules inline, so a new array is created on each render and supplied to the component which in turn triggers the watcher (cause new memory reference of rules) on each re-render. So essentially this will run whether the rules actually change or not, if Vue determines it should re-render the component, and performance degrades, based on how much it takes to run all the rules.

**Comment by jaenkvf** [comment]
Should you set a handler to active the error validations , If the v-model doesn't change never will read the error-message , or currently is there a way to make it?
