### ISSUE TITLE
copyToClipboard on Android webview

### ISSUE THREAD

**Issue by evazc** [quasarframework/quasar#6566]
**Describe the bug**

When I call `copyToClipboard` in a Android webview. I get an error says 'no permission' .

Maybe In this time we should call `navigator.permissions.query` to get permission.

But Android webview doesn't support [navigator.permissions](https://caniuse.com/#search=navigator.permissions) at all.

I don't know if there's any other way to get permission.

If not, should we only use `navigator.clipboard.writeText` when the `navigator.permissions` is supported?

**Platform (please complete the following information):**
Android: 6.0

**Comment by pdanpdan** [comment]
Shouldn't you set the required permissions in the manifest?
https://stackoverflow.com/questions/30042088/how-do-i-add-uses-permissions-tags-to-androidmanifest-xml-for-a-cordova-projec

**Comment by evazc** [comment]
@pdanpdan

Thanks you for your reply.

I tried to add `<uses-permission android:name="android.permission.WRITE_CLIPS" />` in the manifest.(copy from [stackoverflow](https://stackoverflow.com/questions/34626143/how-to-get-notified-when-user-copied-something-in-android))

![image](https://user-images.githubusercontent.com/26076008/76135108-0a593700-605f-11ea-9de1-f15278b16972.png)


But it doesn't work for me.

And there seems no [document](https://developer.android.com/reference/android/Manifest.permission) related to clipboard permission.

**Comment by hawkeye64** [comment]
@evazc I believe you are using wrong permission names
```
android.permission.READ_CLIPBOARD
android.permission.WRITE_CLIPBOARD
```
You should also be aware of recent changes:
```
Limited access to clipboard data
Unless your app is the default input method editor (IME) or is the app that currently has focus, your app cannot access clipboard data on Android 10 or higher.
```

**Comment by rstoenescu** [comment]
@hawkeye64 @pdanpdan need to add this in docs. too many people opening tickets on this. PR pls

**Comment by hawkeye64** [comment]
That's actually more difficult than you might think. The general permissions are easier to find. Android docs sometimes obfuscate the data and makes it harder to find. Because of this, some sites have popped up to aggregate the data in one place. But, it's still a moving target as with latest Android, Clipboard service got more security. To put it bluntly, if we start putting links on the docs site, we'd be changing them every x months because they keep changing them. For instance, I can't find `android.permission.READ_CLIPBOARD` anywhere on the Android site, but it's documented on dozens of other sites and have used it myself in the past. I'm sure it's there somewhere, but generally, I can't find any clipboard permissions at all (just how to use the clipboard service).

**Comment by Teddir** [comment]
how to add in react native expo
