### ISSUE TITLE
QFabAction button lacks a href property

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#6613]
**Is your feature request related to a problem? Please describe.**

I'm wanting to link a `QFabAction` button to send an Email or SMS using [a URL link](https://digitalfortress.tech/tricks/creating-direct-click-to-call-sms-links/).

`QFabAction.type` supports the type `a` QBtn but AFAIK there's no way to set the `href` property.

**Describe the solution you'd like**

Add a `QFabAction.href` property that is then passed on to the action `QBtn`.

**Describe alternatives you've considered**

**Additional context**

**Comment by smolinari** [comment]
Seems to work (same pen as before). Click on the email action.  

https://codepen.io/smolinari/pen/eYNMvQJ

Scott

**Comment by tohagan** [comment]
Wonderful!  So it must just be missing from the API documentation for QFabAction.

**Comment by rstoenescu** [comment]
Not missing anything, since it's not a property.
QFabAction is a QBtn at its core, and so it inherits lots of its props, including the "type" one ("Define the button HTML DOM type") -- available in the API cards. So, if you say "render it with `<a>`" (instead of default `<button>`), then you can apply all the native DOM attributes of an `<a>` tag. So it's pointless to specify that in the JSON API files since those native attributes are not props of the component.
