### ISSUE TITLE
Discussion Component 

### ISSUE THREAD

**Issue by sirinath** [quasarframework/quasar#6614]
**Is your feature request related to a problem? Please describe.**

Currently, there is no discussion, comment thread, discussion component.

**Describe the solution you'd like**

A Reddit like discussion component.

It can follow something like:

![image](https://user-images.githubusercontent.com/637415/76676539-97196d00-65ea-11ea-91e1-fc29ef39992a.png)

Or

![image](https://user-images.githubusercontent.com/637415/76676555-c7610b80-65ea-11ea-8c8d-ef5777f26a67.png)

With or without a subject in the initial post.

The structure can be like a thread above or linear like a discussion group.

**Describe alternatives you've considered**

https://quasar.dev/vue-components/chat

This does not have threading.

**Comment by rstoenescu** [comment]
Hi,

Sir, what you are requesting is not a component, it's a whole UI. Quasar is a framework, not an application. You've got all the components (from Quasar) needed to build your perfect discussion component. Quasar is a tool which allows you to build any kind of such component that you want. What you are requesting is extremely specific and it has no place in a framework. Maybe in a Quasar App Extension, but not in core. If we start to build such a component, then it would need to have a million properties because some will want the title font with 24px, some will want the upper voting button red, some will want [....insert a million things here...].
