### ISSUE TITLE
Support Service Workers for Mobile

### ISSUE THREAD

**Issue by douglance** [quasarframework/quasar#6651]
Implementing offline mode and sharing code between client and server is difficult. Service Workers make that easier, but are not currently easy to use with Quasar's mobile builds.

I would like build configuration options to allow me to use Service Workers in mobile apps to power offline support and to share code between the app the my server.

**Comment by pdanpdan** [comment]
Do you have some specific things that are hard to do for you, and some suggestions on how could quasar help?

**Comment by pdanpdan** [comment]
@douglance Hello, please provide feedback. Thank you.

**Comment by yusufkandemir** [comment]
@pdanpdan the term `sharing code` in this context seems weird to me, but I guess he wants Service Workers in Cordova/Capacitor builds from what I understand from our Discord discussion.

As the service workers are only get built in PWA mode(and SSR+PWA), mobile builds don't have service workers. I believe this could be implemented like PWA support for SSR builds, adding some keys to `quasar.conf.js` -`framework.config.cordova.pwa` for Cordova, `framework.config.capacitor.pwa` for Capacitor- should suffice for config changes.

**Comment by rstoenescu** [comment]
Service workers have no purpose in a Cordova/Capacitor app. What would be the benefit? The app is always hard-coded in .apk/.app. It's not like you can (as an example) show the user that "there's a new version available - click here" through the service workers. This has purpose only when it's used in a mobile or desktop browser.

**Comment by yusufkandemir** [comment]
@rstoenescu I would say caching network requests is a great benefit. You would need to use some plugins and try to implement the same caching policy that you use in service workers, but with duplicate efforts, and later trying to sync service workers and custom caching code would become a PITA, IMO.
If you only develop for mobile platforms, then no problem because you can just learn to use the plugin and try to be happy with it. But if you are developing to multiple platforms-which Quasar aims to make easier- you will not have a great time.

**Comment by rstoenescu** [comment]
What network requests to cache? Everything is fetched from the .apk/.app. There is no sync with service workers files since those are "static" in mobile apps. Should the mobile app be served directly from a website, that would make sense. Am I missing something?

**Comment by douglance** [comment]
The use case I was trying to use Service Workers for is offline mode. 

If I have a Quasar mobile app and a Node backend, I can share packages between them to implement some business logic, and have service workers that check if the device is offline and route requests accordingly.

**Comment by yusufkandemir** [comment]
@rstoenescu if the app needs to requests some data from a source(REST API, GraphQL, Firebase, any type of external source really), and if you want to make the life easier for users with caching, both for speed and offline access, you need to cache things. And if you already cache things with service workers, you need another mechanism for mobile apps currently. Even if you don't do PWA, I would say the ability to use service workers rather than custom code or plugins could be better, because we all use web technologies here, if we can get away without touching any non-web stuff DX would be so much better.
