### ISSUE TITLE
Instruction not clear :  https://github.com/quasarframework/app-extension-icon-genie/

### ISSUE THREAD

**Issue by nkb-bd** [quasarframework/quasar#6652]
You must replace app-icon.png in the root folder of your project.
 If you plan on building for Cordova/Capacitor, you must also replace the
 app-splashscreen.png image in the same place. I can not find these files

**Comment by rstoenescu** [comment]
Hi.

This should have been reported to the AE's repo (https://github.com/quasarframework/app-extension-icon-genie).

Those two files are injected when you install the AE. It's not possible to not have them if you properly installed the AE. However, if they are missing for some weird reason (pls find out why.. did the installation failed?) there's no problem, since those two files need to be replaced by your own versions anyway. So do that.
