### ISSUE TITLE
dialog plugin button href not working

### ISSUE THREAD

**Issue by rendau** [quasarframework/quasar#6655]
**Describe the bug**
Button in dialog plugin ignores 'href' property. 

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/eybuLn5w/

**To Reproduce**
this.$q.dialog({
  message: 'Go to href link',
  ok: {
    type: 'a',
    href: 'https://google.com',
    label: 'go',
  },
})

**Expected behavior**
Not ignore 'href' attribute, and navigate to href on click

**Additional context**
Quasar v1.9.10

**Comment by pdanpdan** [comment]
Hello.
You you want custom content in your dialog please use a custom component - details here: https://quasar.dev/quasar-plugins/dialog#Invoking-custom-component

**Comment by rendau** [comment]
Then what this options for?
![image](https://user-images.githubusercontent.com/14363719/77299674-06900a80-6d17-11ea-9e01-858e98b70af1.png)

**Comment by pdanpdan** [comment]
For buttons. There is no href prop on QBtn

**Comment by rendau** [comment]
No, there is
![image](https://user-images.githubusercontent.com/14363719/77300449-40addc00-6d18-11ea-8815-be5f1fbcd09a.png)

**Comment by pdanpdan** [comment]
href is not a property, it's a HTML attribute.

**Comment by rendau** [comment]
Type is also HTML attribute, but it works

**Comment by pdanpdan** [comment]
Please check https://quasar.dev/vue-components/button#QBtn-API

**Comment by rendau** [comment]
This is from official documentation
![image](https://user-images.githubusercontent.com/14363719/77301696-56240580-6d1a-11ea-9433-92757eefe7e3.png)

**Comment by rendau** [comment]
What is a purpose of using 'a' type of button, if there is no way to specify 'href'? And just for specify href property of one of dialog buttons - you must create whole content of dialog

**Comment by rendau** [comment]
![image](https://user-images.githubusercontent.com/14363719/77302411-7d2f0700-6d1b-11ea-98ad-1a4334891628.png)

**Comment by rstoenescu** [comment]
@rendau 

Please make the difference between a Vue prop and an attribute. When you use the "type" prop on QBtn, it renders an `<a>` tag, so any attributes that you attach to it will have meaning for an `<a>` tag, like "href".

In your case, just redirect the user manually...

```js
this.$q.dialog({ ... }).onOk(() => { window.location = .... })
```

**Comment by rendau** [comment]
OK, `window.location` - works, thank you. But my href-url is phone number, and documentation suggests to not use `openURL()` (I believe it is same as `window.location=...`)

**Comment by rstoenescu** [comment]
It's more of a "here's a way simpler method that you can use". But you can also call openURL(). If you're building a Cordova/Capacitor app, make sure that you also install the Inappbrowser Cordova extension so that Quasar can tap into that. It might work without it too, but the safest is to install it.

Bottom line: depending on the platforms that you want to support, you need to do some quick tests: does it works with window.location directly with a "tel:" link? does it works with openURL() without installing Inappbrowser? It should definitely work with openURL + Inappbrowser, but that's an option just for Cordova/Capacitor, not for the mobile browser (if that's a platform that you need to support). At least one option should work.
