### ISSUE TITLE
[docs]how can i stop sliding half or a third of the width

### ISSUE THREAD

**Issue by araimbekoff** [quasarframework/quasar#6690]
I have a list. I want the behavior of the list items when sliding to be as follows.
How can this be achieved?

![image](https://user-images.githubusercontent.com/14542690/77720312-c334e500-7011-11ea-8e8f-225dc42ee35a.png)

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

And, if we come to the conclusion, your issue is a bug, we'll ask you to then add an issue here. 

Thanks. 😄 

Scott
