### ISSUE TITLE
QStep - add props :header-class and :body-class

### ISSUE THREAD

**Issue by robert-niestroj** [quasarframework/quasar#6720]
**Is your feature request related to a problem? Please describe.**
I would like to be able to give a `QStep `an CSS Class or an array of classes to tweak it's style. For example i would like to add the `text-uppercase` class. **But** i want the class to be only applied to the Step _Header_. Now when i add it to the Step it also propagates to the Step _body_. 

**Describe the solution you'd like**
Add a prop to give one or an array of classes to the `QStep `like in `q-expansion-item` where i can add a `:header-class` prop like this: `:header-class="['text-uppercase', 'text-h6', 'text-weight-regular']"`

**Comment by pdanpdan** [comment]
Please add a codepen with what you have tried.

**Comment by robert-niestroj** [comment]
Codepen: https://codepen.io/robert-niestroj/pen/LYVvjJx
Feature request clarified

**Comment by pdanpdan** [comment]
Ah, it was about header, now it makes sense.

**Comment by robert-niestroj** [comment]
If this would be implemented there could also a second prop be added: `:body-class`. 
For example i have to add a <div class="bg-white"> in all of my steps. With such a prop i could configure this in the Step, like the header.

**Comment by marco-quintella** [comment]
Feature added in #6727

**Comment by robert-niestroj** [comment]
@marco-quintella why not add the `:body-classes` ?

**Comment by marco-quintella** [comment]
@robert-niestroj  the body is composed of QStep. It can be easily edited. I don't see a real reason to add a prop for the entire body since you can make everything inside QStep.
That`s not the case of the header that has it's style handled by a computed function and has no access from the component.

I can do a body class if the Staff says that it would be a good idea. But for now, I think the header-class should add a good card in hands.

**Comment by rstoenescu** [comment]
`header-class` will be available in v1.9.13.
