### ISSUE TITLE
QStepper - DoneColor

### ISSUE THREAD

**Issue by kevinmelo** [quasarframework/quasar#6801]
**Describe the bug**
Done color not working anymore? After update done-color not getting apply... after you change step he get inactive-color not done color

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pen/?&editable=true&editors=101=https%3A%2F%2Fquasar.dev%2Fvue-components%2Fstepper.

**To Reproduce**
The example is the example in quasar documents
1. Change step
2. done-color is set to deep-orange, but the color applied is the primary (witch is green, and is denifed in inactive-color)
3. Removing inactive-color from qstepper the color change to blue

**Expected behavior**
After an step being done the color mus be applied

**Comment by ddenev** [comment]
I just opened another report (https://github.com/quasarframework/quasar/issues/6822) for this bug because I did not see this one. Closing the one I opened and adding the report here for more info:

**Describe the bug**
The `done-color` prop for QStepper is not taken into account.

**Codepen/jsFiddle/Codesandbox (required)**
No need, just go to the "Coloring" example in QStepper docs (https://quasar.dev/vue-components/stepper#Example--Coloring) and hit the CONTINUE button.
The code says that `done-color` should be `deep-orange` but the actual color that is applied to the done step is the one from the `inactive-color` prop.

In addition, check the "Dark" example a little further down. The `done-color` is set to `secondary` but the one that is actually applied is `primary` and `primary` is never provided to the component.

So there must be something messed up with the QStepper coloring :)

BTW, the same bug happens with QStep - setting `done-color` has no effect as well.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.9.15.
