### ISSUE TITLE
[Docs] Make release notes filterable.

### ISSUE THREAD

**Issue by mortenscheel** [quasarframework/quasar#6840]
**Is your feature request related to a problem? Please describe.**
Coming back to a Quasar project after a few months, it can be quite tedious to navigate through all the individual release notes to get an overview of all the changes.

**Describe the solution you'd like**
I think it would make sense to allow users to filter the release notes by repository, version and/or release date. Being able to scroll through all the relevant release notes in chronological order would make it much easier to catch up.

**Describe alternatives you've considered**
N/A

**Additional context**
Another small annoyance with the current implementation is that the navigation pane for the releases (the left scroll pane)  doesn't highlight the currently displayed version.

**Comment by pdanpdan** [comment]
I don't understand the request - the release notes are split by package, version and release date in chronological order - and you can search - what is the feature request?
The current displayed version is marked on the left menu by a blue line (on the right).

**Comment by philfontaine** [comment]
I definitely agree with the last point mentioned by OP.

Here for instance, 1.9.14 is selected, but it is barely noticeable imo, the only difference is that the opacity is at 1 instead of 0.85. Sure there is the blue bar, but you don't notice it until you actually click another version.

![image](https://user-images.githubusercontent.com/16233697/79871524-7515c600-83b2-11ea-8ee8-aae8700b4493.png)

The text of the non-selected versions should be gray, something like what you do in the APIs section:

![image](https://user-images.githubusercontent.com/16233697/79871606-970f4880-83b2-11ea-98a5-dcaeb52a67e8.png)

Last point, maybe you would want to change `Highlight...` for `Search...`. This is maybe a reason why the OP did not see the search bar.

**Comment by rstoenescu** [comment]
Improved the page. And also fixed an issue with the filter.
Will be available on next docs deployment.
