### ISSUE TITLE
Qbtn with stretch

### ISSUE THREAD

**Issue by kevinmelo** [quasarframework/quasar#6841]
**Describe the bug**
When applying `stretch` attribute on **QBtn** the button lose border-radius.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Tydroth/pen/GRpZGez?editors=1010

**To Reproduce**
See codepen

**Expected behavior**
When applying the stretch attribute, i expect the button not lose border and other css attributes

**Additional context**
The only work around is setting an css `border-radius: 4px !important;`
Class `rounded-borders` doesn't work

**Comment by pdanpdan** [comment]
Why do you want to use the stretch prop - the only change over the default is to make the border radius 0
https://codepen.io/pdanpdan/pen/JjYXBKZ?editors=1010

**Comment by kevinmelo** [comment]
Then is missing this observation on documents, no?

When used on flexbox parent, button will stretch to parent's height **and lose boder-radius**

**Comment by pdanpdan** [comment]
`stretch` prop is a leftover from a long time ago.
A button in a row flex will stretch by default if there is no `items-xxx` class on the container.
And if there is you can:
- add `self-strech` class on button
- add `stretch` prop on button (or add `self-stretch no-border-radius` class)

**Comment by rstoenescu** [comment]
@kevinmelo it makes perfect sense to have `stretch` as a **convenience** prop. Take for example the toolbars (even Quasar docs website) and the top right menu. Notice the effect? And the story with this prop is much deeper but it's useless to elaborate. Bottom line, what it does is exactly what it's designed for. If you want something else, there are alternatives like Dan indicated in the above post. I don't understand the complaining since a simple inspection with dev tools reveals that the prop is specifically designed this way.
