### ISSUE TITLE
@quasar/dev (implicitly) prohibits upgrading node to v14

### ISSUE THREAD

**Issue by ddenev** [quasarframework/quasar#6884]
**Describe the bug**
I upgraded my node.js to v14.0.0. When doing `yarn install` I get an error about missing python which is because node is trying to compile node-sass for the new node version and fails since I do not have python installed (nor do I want to install it).

Now, there is a [newer version of node-sass](https://github.com/sass/node-sass/releases) - v4.14.0 which supports node 14 but `yarn install` does not install it. I suspect that the reason is because the `package.json` file of `@quasar/dev` explicitly depends on node-sass: 4.13.11 (exact version) and this effectively does not allow upgrading node-sass to 4.14.0.

Is there a reason to fix node-sass to 4.13.11?

NB: I know that I can set node-sass in my package.json but I would want to avoid this if there is no particular reason to lock to 4.13.11 in `@quasar/dev`.

**Comment by rstoenescu** [comment]
Not only it would be a security risk to blindly fetch the latest versions of all quasar/app deps, it would also pose a risk to break your app "suddenly". We've had countless scenarios in the past on this. So we upgrade the deps once every two weeks (sometimes faster) after we thoroughly test that nothing gets broken. Our philosophy is that you, the developer using Quasar, should have the best experience possible and not have to allocate time for these processes. It's enough that we do it on a regular schedule.

Node 14 has just been released for a few days. But anyway, since this would be a major problem, we'll run our tests and upgrade all deps then do a new release shortly.

The package that you need upgraded will be available in "@quasar/app" v1.7.4.

**Comment by rstoenescu** [comment]
"@quasar/app" v1.7.4 is available.

**Comment by ddenev** [comment]
Thank you for explaining, I understand now!

After upgrading `@quasar/app` to 1.7.4 everything works - I am able to upgrade node to v14. Thank you again!

**Comment by yoavTenny** [comment]
is it o.k now to use quasar cli with node version 14 ?
is the warning in this link  https://quasar.dev/quasar-cli/installation    is out of date ?

**Comment by rstoenescu** [comment]
Node v14 cannot be used explicitly because of Webpack v4 not supporting it correctly in one of their sub-dependencies.
We are making efforts to first bring Webpack v5 to Quasar v2. We cannot upgrade Webpack to v5 for Quasar v1 because this would be the mother of breaking changes.

**Comment by thewebartisan7** [comment]
@rstoenescu Quasar 2.0.0-beta.4 support node 14+ ?

**Comment by rstoenescu** [comment]
It'll come (along with the upgrade to Webpack 5) at some point in the life of the beta. You'll have to be patient until we reach that point.

**Comment by umonaca** [comment]
> Node v14 cannot be used explicitly because of Webpack v4 not supporting it correctly in one of their sub-dependencies.

May I ask which one is it?  
I have been using Node v14.15.1 with two large Quasar v1 projects and I have not seen any bugs or dependency errors in the Webpack. Do I have to downgrade to Node v12?

**Comment by rstoenescu** [comment]
@umonaca

Due to the Webpack v4 and its dependencies, it's recommended that you use Node.js 12 for Quasar v1. The file change detection will not be working correctly or efficiently (this has impact over HMR !). It doesn't mean that newer Node.js versions won't somewhat appear to work, but you'll most likely get a lot of headaches as time goes by because almost all webpack plugins might get in trouble with newer Node.js (as they will not get the needed updates). All focus in the webpack world is now on Webpack 5 (which Qv2 supports).

Best way is to upgrade to Quasar v2 or stick with Node.js 12 for Qv1 for a painless experience.
