### ISSUE TITLE
QTable: add new selection mode "range"

### ISSUE THREAD

**Issue by nahuel** [quasarframework/quasar#6897]
Add a new `selection` mode to QTable: `"range"`, same as `multiple` but you can select range of items by using shift-click on the selection checkbox.

**Comment by metalsadman** [comment]
@nahuel you can add event listener for keys, but imo, this is harder than just adding listener for dragging mouse for multiple selections, since you will have to take note of bounds and first selection to end, check also if the selection is from bottom to top and vice versa, check indices etc...

example multiple selection using mouse events https://codepen.io/metalsadman/pen/wvKPWov

**Comment by nahuel** [comment]
@metalsadman  thanks for the dragging example, but I think shift-click to mark ranges and ctrl-click to mark/unmark an item in a range is the standard and established idiom in all desktop GUI's and advanced web data tables like ag-grid, so it will be nice to have it.

**Comment by pdanpdan** [comment]
Now we have examples in the docs on how to do it: https://quasar.dev/vue-components/table#Example--Custom-multiple-selection

**Comment by nahuel** [comment]
great! thanks!
