### ISSUE TITLE
Support for Multiple Apps in a Single Codebase

### ISSUE THREAD

**Issue by halostatue** [quasarframework/quasar#6936]
Quasar looks _really_ good and I’d like to consider it, but I have an existing pair of applications built from the same codebase (two different root `App.vue` nodes with different routers). I don’t see any way in the Quasar documentation that what Webpack calls multiple entry points can be supported. From an SPA perspective, I believe that this feature is imported. I posted on the forum [last night](https://forum.quasar-framework.org/topic/5790/multiple-spa-entry-points-with-a-single-codebase?) and referenced an [older post](https://forum.quasar-framework.org/topic/4139/multiple-entry-points) that had some suggestions that don’t work for me.

**Describe the solution you'd like**
I want the ability to have multiple Vue app entry points built from a single codebase. For my use case, I don’t care about generating a separate HTML file (which is, IIRC, the typical Webpack approach) because I am serving the JS and CSS from endpoints on an already existing server.

qyloxe on the forum suggested the ability to return an array from the configuration, which is very similar to what Rollup does and how we use Rollup with our current build process:

```javascript
export default [
  {
    input: 'src/customer.js',
    output: {
      file: __dirname + '/public/customer.js',
      format: 'cjs',
      name: 'customer'
    }
  },
  {
    input: 'src/employee.js',
    output: {
      file: __dirname + 'public/employee.js',
      format: 'cjs',
      name: 'employee'
    }
  }
]
```

**Describe alternatives you've considered**
I have no alternatives as I have just come to Quasar, and while I like what I see, I’m not sure that I can use it because there are no guidelines for this particular use case. Any suggestions for how this can be done would be appreciated if this can be done some other way.

**Comment by rstoenescu** [comment]
Hi,

You can add entry points to the webpack config through quasar.conf.js > build > extendWebpack() or chainWebpack(). 

* https://quasar.dev/quasar-cli/cli-documentation/handling-webpack
* https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build

**Comment by halostatue** [comment]
Thank you. That seems easy enough, especially with `chainWebpack`. However, I do have another question. The default `entry` is:

```javascript
{ entry: { app: [ '<project_folder>/.quasar/client-entry.js' ] } }
```

Looking at `.quasar/client-entry.js`, is there a way to have _two_ of those generated/managed by Quasar CLI, since it’s a generated file? Specifically, the line `import createApp from './app.js'` would need to be one of two different app roots for the wanted Webpack entries.

It feels like things are _really_ close to what I need, but not _quite_ what I need, or I’m simply not understanding the right way to do things.

**Comment by diejsel** [comment]
Hi. You can describe it in more detail (it is possible that the assembly was still in different folders), thanks.

**Comment by tigerbook73** [comment]
> Thank you. That seems easy enough, especially with `chainWebpack`. However, I do have another question. The default `entry` is:
> 
> ```js
> { entry: { app: [ '<project_folder>/.quasar/client-entry.js' ] } }
> ```
> 
> Looking at `.quasar/client-entry.js`, is there a way to have _two_ of those generated/managed by Quasar CLI, since it’s a generated file? Specifically, the line `import createApp from './app.js'` would need to be one of two different app roots for the wanted Webpack entries.
> 
> It feels like things are _really_ close to what I need, but not _quite_ what I need, or I’m simply not understanding the right way to do things.

Did you solve the issues? I have the similar scenario and did not find easy way to do it from the internet. What I'm doing now is to create multiple project and build them to different sub folder.

**Comment by halostatue** [comment]
It did not, but the project that I was looking at using Quasar for was also cancelled, so I never got to explore it further.

**Comment by ghost** [comment]
hi @halostatue,
Could you please share how did you change entry point from `quasar.config.js`?
using `chainWebpack` but how?

**Comment by halostatue** [comment]
As I [said](https://github.com/quasarframework/quasar/issues/6936#issuecomment-1152424337), I didn’t and the project was cancelled, so I don’t have an answer on how this would actually work, nor am I using Quasar for anything.

**Comment by onexdata** [comment]
To modify anything in client-entry.js (the generated quasar file that loads your app), just do this:

1. ```npm i modify-source-webpack-plugin``` which will install [this](https://www.npmjs.com/package/modify-source-webpack-plugin)
2. Import ModifySourcePlugin, and ConcatOpetation and/or ReplaceOperation, at the start of your quasar.conf.js file, like this:
```
const { ModifySourcePlugin, ConcatOperation, ReplaceOperation } = require('modify-source-webpack-plugin')
```
3. Finally, under your build section in quasar.conf.js file, under ```extendWebpack (cfg) {``` add this:
```
// This will replace "start()", the thing that actually starts Qusar, with a custom function,
// so that you can start Qusar after the fact, with window.startQuasar()
        cfg.plugins.push(
          new ModifySourcePlugin({
            rules: [
              {
                test: /client-entry\.js$/,
                operations: [
                  new ConcatOperation(
                    'start',
                    '// Modified to support the SDK method.\n\n'
                  ),
                  new ReplaceOperation(
                    'once',
                    'start()', // Replace this (it's only called once at the end of the file)
                    '//start()\nwindow.startQuasar=function(){\nstart()\n}' // With this
                  )
                ]
              }
            ]
          })
        )
```
Of course, modify the above to suit your specific need, but copy-pasta this code and read through it to see how it works 👍 

Since this introduces generic concat and replace operations, you could modify ```/.quasar/client-entry.js``` any way you want.

*Note: This works for both dev and build mode. I.e. it works while you're using webpack, and also replaces the code during the build process as well*

**Comment by onexdata** [comment]
If you want multiple apps in a single page (without iframes), quasar hard-codes "q-app" as the entry point, and stores this in app.el during the boot process, so you'll need to replace app.el with a boot file to something you've configured, like this:

Create a new file in /src/boot and reference it in ```quasar.conf.js```, then, in the new boot file, add this:
```
export default (quasar) => {
  // Set this to any css selector besides "#q-app" and it will work!
  quasar.app.el = "#my-specific-entry-point"
}
```

...because boot files are called *before* vue is bound to the DOM root element for quasar, this works just fine. This will let you load quasar many times into many different DOM ids. You just have to solve for CSS bleed with postCSS if your apps use the same css, or if your apps configure different base CSS items like app colors, and, you'll need to avoid using the vue router (since two apps trying to change the url params at once will be problematic), otherwise you're good.
