### ISSUE TITLE
Get click event of icon in Notify

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#6973]
**Is your feature request related to a problem? Please describe.**
I show a notification when the app has an update, the notification has a reload icon and the first instinct is to clickit. I want to reload the page when is click.

**Describe the solution you'd like**
Can attach function to events in icon or avatar

**Describe alternatives you've considered**
Another generic icon and an action with "Reload", but this solution is more customizable

**Comment by smolinari** [comment]
You can do this yourself. See here: 
https://github.com/quasarframework/quasar/blob/5f5504aee34a2667b5b93d792fbd5c0684031787/docs/src-pwa/register-service-worker.js

In the future, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

And, if we come to the conclusion, your issue is a bug or a good suggestion, we'll ask you to then add an issue here. 

Thanks. 😄 

Scott
