### ISSUE TITLE
QPageSticky does not work when ios onscreen keyboard shows up

### ISSUE THREAD

**Issue by anubhavkamath** [quasarframework/quasar#6989]
**Describe the bug**
I am trying to use a q-page-sticky component in my app with a q-toolbar containing a q-input field. I noticed this worked fine in using the browsers dev tools but when I loaded the app on an actual ios device and tried typing in the q-input field the onscreen keyboard comes up. At this point if I scroll any list in the page the q-page-sticky component is no longer sticky. It scrolls up along with the list. To see if it was something in my app, I started with a fresh Quasar cli project and created a page that has some redundant test components (just to allow scrolling) and loaded this on the ios device. The same behavior is exhibited. 

**Codepen/jsFiddle/Codesandbox (required)**
Code sandbox is here. 

https://r088j.sse.codesandbox.io/

You can see the problem by opening the the link above in a mobile browser. The header is fixed when scrolling the list but as soon as you set the focus in the text field and the onscreen keyboard is shown, the header is no longer fixed and scrolls up out of view along with the list. 

**To Reproduce**
1. Click on the "Search Groups" text field below the header (in a mobile device)
2. Scroll up on the list.

**Expected behavior**
The contents within the q-page-sticky component should stay fixed even if the on screen keyboard is showing. 

**Screenshots**
See Codesandbox

**Platform (please complete the following information):**
OS:  9.0.0 (cordova-lib@9.0.1)
Node: 10.16.3
NPM: 6.9.0
Yarn: N/A
Browsers: Chrome but problem is on mobile device
iOS: 12.0.1
Android: Haven't tested
Electron: N/A

**Additional context**
None

**Comment by rstoenescu** [comment]
There is A LOT of work done for the iOS compatibility, many of the things devs are not even aware until they have a project without Quasar. But this particular item cannot be solved due to heavy iOS limitations. When keyboard pops-up, the CSS positioning is not working anymore. It has been reported to Apple for years and years and years, but they have chosen not to fix it. We are frustrated about this.

However, we do recommend installing the ionic webview which is far better than the standard webview (but it comes with its own small limitations of its own) -> https://quasar.dev/quasar-cli/developing-cordova-apps/preparation#Switching-to-iOS-WkWebView

**Comment by anubhavkamath** [comment]
Thanks for the info. Maybe at least mention this in the quasar docs. I spent hours trying to figure this out. So, what is the best way to show a search field in a tool bar? Would you recommend using the main header itself? I'm trying to do something like this...
![220DC569-EF08-46C0-BF03-8A58FA37DD41_4_5005_c](https://user-images.githubusercontent.com/18087493/81443730-8fce9580-913b-11ea-8024-dfdaa9377495.jpeg)
