### ISSUE TITLE
QStepper Label Slot

### ISSUE THREAD

**Issue by jjjrmy** [quasarframework/quasar#6992]
Add a slot to the QStepper for the Label (Title and Caption).
Similar to Vuetify: https://vuetifyjs.com/en/components/steppers/

**Comment by rstoenescu** [comment]
May I ask why a slot for title and caption are necessary? What is your use-case?

**Comment by rstoenescu** [comment]
Quasar's stepper is a bit more powerful than the one indicated by you because it supports both vertical and horizontal modes **with same html template**. This however hinders the ability to use a "title" and "caption" slots. However, since these two props can be dynamically binded, there is little reason to add slots for them. This is why I was asking about your use-case. Sorry for any inconveniences. If I get some details on your use case then I can point you in the right direction on how to achieve what you want.

**Comment by jjjrmy** [comment]
I'd like to add buttons and other things into the Step label

**Comment by jjjrmy** [comment]
@rstoenescu 
![Example](https://imgur.com/jU7cHIs "Example")

**Comment by rstoenescu** [comment]
Hi,

Due to the reasons I mentioned above, QStepper can't support the slots that you are mentioning. However, why not use QTabs + QTabPanels for this?
