### ISSUE TITLE
Scroll Area showing default browser scroll bar

### ISSUE THREAD

**Issue by chrislandeza** [quasarframework/quasar#7011]
**Describe the bug**
Scroll Area showing default browser scrollbar when you scroll to the end of the content. This is also happening on the layout builder https://quasar.dev/layout-builder

**To Reproduce**
1. Go to https://quasar.dev/layout-builder
2. Disable right drawer and navigation tabs
![image](https://user-images.githubusercontent.com/4858242/81679143-9f741400-9484-11ea-8442-305ead603049.png)

3. Go to the layout configurations and choose the following setup:
![image](https://user-images.githubusercontent.com/4858242/81679389-c6cae100-9484-11ea-862d-ff684e7ff739.png)

4. Scroll the left sidebar to the end and the default browser scrollbar will appear
![image](https://user-images.githubusercontent.com/4858242/81679600-e9f59080-9484-11ea-8dce-eefee2c5bb37.png)

**Platform**
OS: Windows 10
Browsers: Chrome Version 81.0.4044.138
Inner Window Size: 1280x690
Outer Window Size: 1280x587

**Comment by pdanpdan** [comment]
Sorry, I cannot reproduce it. Try to ad in the report the exact size of the window, maybe it helps on reproducing.

**Comment by chrislandeza** [comment]
Hi @pdanpdan can you try it again with window size: 1280x690

**Comment by pdanpdan** [comment]
I suppose this is the resolution of your screen, because by looking at the picture the ratio between the scrollbar and the total height is bigger when the window is 690.
But I still cannor reproduce it. Maybe someone else can.

**Comment by TobyMosque** [comment]
i weren't able to reproduce as well

![image](https://user-images.githubusercontent.com/13981214/81691553-62cbfc80-9433-11ea-9b0f-17d213a46570.png)

**Comment by rstoenescu** [comment]
This is not a bug in Quasar.

Don't use QScrollArea when the Drawer is not in a fixed position (uppercase "L") -- because it makes no sense. Lowercase "l" means the drawer goes with the flow of the page. If it's bigger than the page, then it influences the scroll of the page, obviously. Kind of like -> the total scroll size is whatever's bigger: the drawer's height or the page's height. This is one of the strengths of QLayout but in this case it's not represented correctly by Layout builder. I'll deploy a fix to the Layout builder page in docs. (Will tag this ticket on the commit)

Thanks for reporting.
