### ISSUE TITLE
[Request] - Ant Design Theme

### ISSUE THREAD

**Issue by go4cas** [quasarframework/quasar#703]
It would be great if you could extend the current Material Design and iOS theme set, by adding an [Ant Design](https://ant.design/) option. Similar to the [iView](https://www.iviewui.com/overview-en) library, but as a standard Quasar theme.

**Comment by smolinari** [comment]
There is a lot of program logic currently within Quasar, in order to get the two themes to work seamlessly together and dependent on the device used. So, what may seem like a fairly easy task, is quite difficult and probably won't be done in the near future. There have, for instance, already been several requests to add Bootstrap's design to Quasar. 

What I'd like to see is any theming logic abstracted out and given to userland so they can build their own designs with Quasar. In other words, I like to see the community build a Bootstrap or Ant or any other custom design and offer it as a plug-n-play extension to Quasar. I'm not sure if it is possible, but it would certainly be cool and I'd bet money it would catapult Quasar ahead of all other FE frameworks, simply because the devs/ users could pick and choose as to what designs to use. 

Scott

**Comment by rstoenescu** [comment]
Hi, I'm sorry but I am going to close this one as the resources currently do not allow to add a new theme to Quasar. @smolinari's suggestion is really great and will make everything possible to make it happen.

**Comment by smolinari** [comment]
@rstoenescu - should I put that idea in a different issue, since this one is closed?

Scott

**Comment by AdsonCicilioti** [comment]
@smolinari I saw the same thing when I looked at the quasar theme structure ... It really looks like it was not meant to get another theme except for customizing variables. Yes I believe it is a good way, other design adapt to quasar through Plugins. But Quasar itself could stimulate the community as a documentation of a themes plugin scaffold with other Designs framework.

I have not tested it yet, but quasar is by far the smartest Framework I've ever seen. But his style does not please everyone and it does not make sense to be caught up in two themes.
