### ISSUE TITLE
Quasar component able to set data (amount of time) from a timer, stopwatch, etc.

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#7071]
Let's say I ask you how much time you spend on physical activity each day.
Does it make sense that a clock appears for you to select the time of a clock?
I need how many minutes, hours (amount of time) and not the time of a clock.

**First idea (limited to max of 24 hours):**
A new prop in the QTime component where you can define a mask for the label in the header.

A new prop like `<q-time header-label-mask="HH[h]:mm[m]" ...`

Example:

![image](https://user-images.githubusercontent.com/9668277/82379814-f0908480-99fd-11ea-9e6c-24fa919c6eac.png)

Or only a prop of type boolean: `<q-time stopwatch-style ...`

![image](https://user-images.githubusercontent.com/9668277/82379853-fdad7380-99fd-11ea-928a-139f448ec9a4.png)

![image](https://user-images.githubusercontent.com/9668277/82379871-03a35480-99fe-11ea-9068-d07141142fec.png)

**Second idea (limited to max of 99 hours)**
I think a new component called QTimer is the most ideal for this purpose. 
With this design used by the Clock App on Android phones to set amount of time in the Timer:

![image](https://user-images.githubusercontent.com/9668277/82491299-d8326f80-9aba-11ea-9f23-52fba5c71def.png)

**Comment by pdanpdan** [comment]
In my opinion having to pick things on a dial instead of typing the values on the keyboard, and blocking the expected copy/paste would be totally against usability.
For setting a timer maybe the Apple like interface would be good, but not for entering a duration on a pc it would be very bad.
Check here: https://github.com/quasarframework/quasar-ui-qscroller
