### ISSUE TITLE
Suggestion to allow fixing of lower electron-builder version

### ISSUE THREAD

**Issue by siauderman** [quasarframework/quasar#7106]
Because of https://github.com/electron-userland/electron-builder/issues/4629, I cannot build for Windows on Mac High Sierra if I use the latest electron-builder version. I have to use 21.2.0.

As a result, I had to manually edit the builder script file to stop it from installing the latest electron-builder.

I would like to suggest that the electron builder script perform a check if electron-builder is already installed, then install it only if it is not already installed. That way, we can use a lower version of electron-builder if it is necessary to circumvent bugs.

**Comment by rstoenescu** [comment]
Hi,

What is the error being reported?
Just fixed a bug regarding electron-builder compatibility and wondering if this will also solve your problem.

**Comment by siauderman** [comment]
The error being reported is an unidentified symbol __chkstk_darwin, this is a known issue in the latest electron-builder running on MacOS High Sierra (I would upgrade to Catalina but Apple says I can't install it) and the fix is to downgrade electron-builder to 21.2.0 which works perfectly.

I would like to suggest either of the following:
1. Do not reinstall electron-builder if it is already installed (this would have the benefit of saving the user's time during a build as well); or
2. Create an option to force the version of electron-builder to a particular version

**Comment by rstoenescu** [comment]
1. We can't have the major version of electron-builder or electron-packager not being checked. Because Quasar App CLI is the one using its API. Major version change might mean its programmatic usage might have changed -- and **it happened twice** since Electron mode was added. In the end this would result in a broken app, which is what we try to avoid.
2. The electron-builder (or electron-packager) is first checked if it's installed and its major version matches what we know to be working (currently version "12"). Otherwise it doesn't gets installed. So saying "it always gets installed" is not correct. It is just an effect of you installing another major version of it.

Your scenario is an unfortunate one. However, I really recommend you to do something to keep the OS updated -- otherwise you might bump into other issues as well given the current pace at which Electron and the bundlers are evolving.

Regardless of everything, will add a way to skip the major version check (with a warning that it may simply not work due to their programmatic usage API changes). Pondering on the best way to do this in a future-proof manner. Will post updates here.

**Comment by siauderman** [comment]
Thanks Razvan!

**Comment by rstoenescu** [comment]
"@quasar/app-v1.9.5" will no longer force the version of electron-packager or electron-builder. However, when their programmatic usage will have a breaking change, we'll need to make a new release to support it.

**Comment by customautosys** [comment]
FYI, this issue no longer exists. I just built a universal (Apple Silicon included) dmg using my High Sierra mac on electron-builder 22 and electron 12. So feel free to force the version of the electron-packager or electron-builder.
