### ISSUE TITLE
this.$q.lang.set(Quasar.lang['en-us']); does not work in 1.11.0 to 1.11.3

### ISSUE THREAD

**Issue by patrickas** [quasarframework/quasar#7108]
Using : 
this.$q.lang.set(Quasar.lang['en-us']);
stopped working between 1.10.5 and 1.11.0

https://jsfiddle.net/5en1c6j9/

This fiddle shows that setting language to 'en-us' does not work while using quasar 1.11.x
But the exact same code works if you just load 1.10.5 instead of 1.11.3

**To Reproduce**
1. Go to https://jsfiddle.net/5en1c6j9/
2. Click on 'Set EN-US' nothing happens.

**Expected behavior**
I expect a notification to tell me that language is now 'en-us'.

**Platform :**
Using chrome 84 with Quasar UMD on windows 10

**Additional context**
The exact same code works on version 1.10.5 ( can be tested in the jsfiddle )

**Comment by rstoenescu** [comment]
Hi,

`Quasar.lang['en-us']` does not exists if the tag for it is not embedded. So calling `Quasar.lang.set(Quasar.lang['en-us'])` is perfectly equivalent to `Quasar.lang.set()` -- behavior which was indeed removed in v1.11 (for perf reasons). BUT, since en-us is always part of the Quasar UMD version, it makes sense to re-enable the old behavior of being able to not use any params so that developers won't need to duplicate the en-us language pack (adding it once more through its specific tag).

Having said that, your usage will work with v1.12 -- but just mentioning again that Quasar.lang['en-us'] is undefined :)
