### ISSUE TITLE
CSS align elements in .q-field__control

### ISSUE THREAD

**Issue by SharpBCD** [quasarframework/quasar#7116]
**Icons and others are not aligned when the using oversized elements like chips**
See picture attached.
![image](https://user-images.githubusercontent.com/31144210/82962008-a001c400-9fc7-11ea-989e-880b3b697f28.png)

**All it needs is simple:**
add `align-items: center;` and it will work

![image](https://user-images.githubusercontent.com/31144210/82962037-be67bf80-9fc7-11ea-8387-a47453733d6c.png)

**Comment by pdanpdan** [comment]
Codepen showing the problem.

**Comment by SharpBCD** [comment]
https://codepen.io/SharpBCD/pen/gOaJoRB

yeah, it's QSelect.

**Comment by pdanpdan** [comment]
The solution is to add a specific class to the control and set the style to the desired vertical align for the items in the field container when they are inside fields with that class (the commented part in codepen).

**Comment by SharpBCD** [comment]
:)
I'm aware of that. I thought it could be useful to fix it at the framework level.
But ok, your call. You may close it if you think it's fine like that.

**Comment by rstoenescu** [comment]
It's designed correctly as it is now. Not aligning to middle when the field can grow because that would produce undesirable effects: imagine a textarea where you append some things to it; now those would not even be visible on screen if textarea is tall enough; not to mention that it would look really weird when compared to the other QInput/QSelect/etc.
