### ISSUE TITLE
A way to allow build despite Eslint/TS errors

### ISSUE THREAD

**Issue by TeNNoX** [quasarframework/quasar#7236]
**Is your feature request related to a problem? Please describe.**
In general I feel it's good to have a way to build despite lint errors.

I can't `quasar build` a project with any Typescript errors. The build fails with (filenames removed from output):
> TS2322: Type 'null' is not assignable to type 'Options'.
> TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
> TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
> 
>  App · ⚠️  [FAIL] Build failed with 71 errors. Check log above.

**Describe the solution you'd like**
This are Lint errors - not compilation errors. I know I should fix them, but I'd like to be able to **build** without doing that.

**Describe alternatives you've considered**
I tried in a lot of ways to disable linting, errors, anything - via **tsconfig.json**, **.eslintrc.js**, **quasar.conf.js** > `supportTS.tsCheckerConfig`, ..... 

The only way I could make it work is by replacing `fork-ts-checker-webpack-plugin` with a dummy module (`echo 'module.exports = { apply: () => { } }' > node_modules/fork-ts-checker-webpack-plugin/index.js`) - but thats... just... urgh...

Is there any option I'm missing?

**Comment by rstoenescu** [comment]
Hi,

This depends on the type ("error" or "warning") being reported by TS or ESLint packages. If it's warning then build will go, otherwise halt on errors. This is not something that we can easily change...

**Comment by wsw70** [comment]
> @rstoenescu  This depends on the type ("error" or "warning") being reported by TS or ESLint packages. If it's warning then build will go, otherwise halt on errors. This is not something that we can easily change...

I have the same problem:
- code that throws errors in `quasar dev` but the application builds and works (the errors are minor and will be fixed later)
- I needed a draft build version for some tests, but `quasar build` on the same code breaks and refuses to create the (imperfect) distribution code

I believe that since the app works with `quasar dev` (and somehow managed to go through the ESLint errors), it could also generate the actual code during a build (I assume that the in-memory build generated during the life of a `quasar dev` session is generally speaking the same that for `quasar build` (in its essence - I know that there are optimizations, etc.))

Note: there is the nuclear option to add `/src` to  `.eslintignore` - which is fine for my one-shot case but not really an option in the longer term

**Comment by tennox** [comment]
I found that it's now possible (at least with vite app):
In `quasar.config.js`:
```js
eslint: {
  warnings: false,
  errors: false,
```

will completely skip the eslint plugin.
