### ISSUE TITLE
QScrollArea content hidden if height is not provided

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#7248]
**Describe the bug**
When you don't specify a height on a QScrollArea but you do set a min-height, the content in the scrollarea is hidden somehow. This is very weird and unexpected behaviour because if you inspect the dom you see every element and that is has height etc. Only they are not visible! This is the kind of thing that can drive you nuts ;)

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Evertvdw/pen/NWxbexw?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fscroll-area

**To Reproduce**
Codepen has two lists, one with min-height and one with height. The one with min-height is not visible.

**Expected behavior**
Min-height and height should both be valid. 

**Additional context**
If height is necessary for this component, and min-height is impossible this should be stated in a warning box of sorts in the docs. But I'm 90% positive we used this with min-height on a previous version and there it worked. We recently upgraded and we use this on a not so often viewed component so we did not immediately notice.

**Comment by pdanpdan** [comment]
I know it's very strange, and I'll look for a fix for that case just for the sake of having that fixed, but what is the point of using the `max-height`? The height stays at the minimum always because inside there are only absolutely positioned elements.

**Comment by Evertvdw** [comment]
I'm using it in a QDialog which I want to have a max height. In there I use some header and bottom buttons and the rest should be a scroll-area. But preferably the scroll area should shrink to the content if not all the height is necessary. Can that be done?

**Comment by pdanpdan** [comment]
There is a solution for that, but it's very complex - it involves having the content twice to allow the dialog to change the height.
Here is a sample using 2 columns side by side: https://codepen.io/pdanpdan/pen/jOWVXvQ?editors=1000

**Comment by Evertvdw** [comment]
Ok, I will see if we absolutely need that. Thanks for the example atleast!

**Comment by TheTyrius** [comment]
I was just facing the same issue: I have a qscrollarea that occupies all leftover space in a flex container.
It has class "col" to grow, and visually it does (the scrollarea fills the space and the scrollbar has the correct size for the content), but the content is invisible. Setting "height: 1px" makes it appear without actually changing the size of the scrollarea, which is quite confusing to me.

I'm not quite sure how exotic this usage of qscrollarea is, but without this issue I would not have been able to find a workable solution.

**Comment by zeodtr** [comment]
@Evertvdw You can solve the problem without duplicating the content.  
Add QResizeObserver to your content and on the resize event of the QResizeObserver set the height of QScrollArea (for example, by changing the value of a ref variable that is referenced by the dynamic style attribute) to the event's argument value's height property.

Actually I think that this behaviour can be incorporated into QScrollArea with an additional prop with a name, for example, 'autoHeight'.

**Comment by stefanvanherwijnen** [comment]
> @Evertvdw You can solve the problem without duplicating the content. Add QResizeObserver to your content and on the resize event of the QResizeObserver set the height of QScrollArea (for example, by changing the value of a ref variable that is referenced by the dynamic style attribute) to the event's argument value's height property.
> 
> Actually I think that this behaviour can be incorporated into QScrollArea with an additional prop with a name, for example, 'autoHeight'.

Thanks, here is a CodePen which implements this:
https://codepen.io/stefanvh/pen/NWJzdxg

**Comment by Razikus** [comment]
isnt there an other way that using q-resize-observer? for me it looks like workaround and its shitty

**Comment by jeremyVignelles** [comment]
I had some success with container units, but this only works in firefox; chromium-based browser still put a 0 size to the scroll area. Maybe a chromium bug ?

```html
  <q-page class="column" style="container-type: size">
    <q-scroll-area style="height: 100cqh">
```

See https://stackblitz.com/edit/quasarframework-uhvulo?file=src%2Fpages%2FIndexPage.vue

EDIT: same with a div: https://stackblitz.com/edit/quasarframework-p4kegs?file=src%2Fpages%2FIndexPage.vue
Things start to get weird: in chrome when you set an explicit size like `90vh` to the q-page, the `100cqh` can be computed, but not when you set it to a computed value like `calc(100vh-50px)`

**Comment by pdanpdan** [comment]
I suppose you want something like this (from your example).
https://codepen.io/pdanpdan/pen/ZENaGpR?editors=1010

**Comment by jeremyVignelles** [comment]
Wow thanks a lot, it indeed fixes the issue I'm having!
https://stackblitz.com/edit/quasarframework-ckr8c3?file=src%2Fpages%2FIndexPage.vue

Didn't think it was that simple, I thought that when using `contain:strict`, you HAD TO set a specific value for height and couldn't let the browser figure it out.

I can now remove my boilerplate code to watch the size of the container...

**Comment by pdanpdan** [comment]
But please check in chrome/Firefox/safari, each of them have funny quirks when talking about flex

**Comment by 46319943** [comment]
After referring to this solution, I realized that the issue is caused by the `percentage value` of `flex-basis`. In Quasar, the `col` sets the `flex-basis` to `0%`, meaning it refers to the parent value that is specified explicitly (i.e., it does not depend on content height). When the parent value is not set explicitly, this `0%` has no meaning and will compute to `auto`.

This `auto` value is fine for the `scrollarea` itself but not for its child element, `container`. The `container` includes only a child with an `absolute` position, so its content has no height. The height of `container` is set with a percentage value of `100%`, but its parent, `scrollarea`, has no explicit value (it's `auto` actually), so this `100%` has no meaning and will be regarded as `auto`. Since the content height of `container` is 0, the `container` will have 0 height.

This is how the issue occurs.

There are three potential solutions:

1. Specify the height for the parent of `scrollarea`, so that the `flex-basis` will not compute to `auto`, but `0px`. Then, the height of the `scrollarea` will be decided by the parent flex.
2. Manually set the `flex-basis` to a specific value, such as `1px` or `0px`, similar to what @pdanpdan did.
3. Specify a height value (not a percentage if the parent has no height) for the `scrollarea`, which will make the percentage height of the child work.

You can find the code to illustrate this here:
[CodePen Example](https://codepen.io/yang-piao/pen/OJebLGE)

Refer to MDN for percentage value behavior:
[MDN Documentation on CSS Height](https://developer.mozilla.org/en-US/docs/Web/CSS/height)

**Comment by 46319943** [comment]
> I suppose you want something like this (from your example). https://codepen.io/pdanpdan/pen/ZENaGpR?editors=1010

After referring to this solution, I realized that the issue is caused by the `percentage value` of `flex-basis`. In Quasar, the `col` sets the `flex-basis` to `0%`, meaning it refers to the parent value that is specified explicitly (i.e., it does not depend on content height). When the parent value is not set explicitly, this `0%` has no meaning and will compute to `auto`.

This `auto` value is fine for the `scrollarea` itself but not for its child element, `container`. The `container` includes only a child with an `absolute` position, so its content has no height. The height of `container` is set with a percentage value of `100%`, but its parent, `scrollarea`, has no explicit value (it's `auto` actually), so this `100%` has no meaning and will be regarded as `auto`. Since the content height of `container` is 0, the `container` will have 0 height.

This is how the issue occurs.

There are three potential solutions:

1. Specify the height for the parent of `scrollarea`, so that the `flex-basis` will not compute to `auto`, but `0px`. Then, the height of the `scrollarea` will be decided by the parent flex.
2. Manually set the `flex-basis` to a specific value, such as `1px` or `0px`, similar to what @pdanpdan did.
3. Specify a height value (not a percentage if the parent has no height) for the `scrollarea`, which will make the percentage height of the child work.

You can find the code to illustrate this here:
[CodePen Example](https://codepen.io/yang-piao/pen/OJebLGE)

Refer to MDN for percentage value behavior:
[MDN Documentation on CSS Height](https://developer.mozilla.org/en-US/docs/Web/CSS/height)

**Comment by fahmiegerton** [comment]
apologise, I have the same issue, I tried everything (except QResizeObserver) but didn't work, I tried to implement the QScrollArea inside the QCardSection, currently only work with specifying the height in QScrollArea

**Comment by macrogreg** [comment]
> I suppose you want something like this (from your example). https://codepen.io/pdanpdan/pen/ZENaGpR?editors=1010

Thank you, [pdanpdan](https://github.com/pdanpdan). The "`<q-scroll-area style="flex: 1 1 1px">`"-approach worked for me.

However, I am really surprised to see this issue being closed without a permanent resolution.  
It seems to me that the use case discussed in this issue is very common. It took me several hours to resolve this and I bet many others are in the same boat. If this cannot be resolved by a framework change, a description of this caveat and a solution should really be included on https://quasar.dev/vue-components/scroll-area.

**Comment by AlexanderNow** [comment]
Solution that worked for me: **using CSS position: sticky**.

Hi everyone,
I wanted to implement something similar — a QCard inside a QDialog, with a QSection at the top, QCardActions fixed at the bottom, and scrollable content in between.
Initially, I tried solving this with a QScrollArea, but fixed heights caused some layout issues.
Now I’ve used CSS position: sticky for the top and bottom sections, and it works great.
Maybe this could also be achieved using QLayout.

P.S. Now I have a Problem with Scrollbar :-D
