### ISSUE TITLE
Custom component wrapping QInput won't trigger validation on form submit with reactive rules

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/quasar#7305]
**Describe the bug**
A custom component wrapping QInput and using rules defined with a computed property, won't get validation triggered when submitting a form. 
Spreading the computed property will make it work again.
Specifying the rules directly will work.
However, adding `hint` prop will also prevent validation from being triggered, maybe due to occupying the same space?

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dwarfhq/pen/BajZVxw

**To Reproduce**
1. Don't input anything in any field
2. Click on "Submit"
3. All 6 fields should be marked with a validation error
4. See that Computed and Fixed Hint fields have not been validated

**Expected behavior**
Regardless of how rules are assigned (using `reactive-rules` if necessary), or hints being added, form validation should be triggered on components wrapping QInput.

**Screenshots**
![quasar-qinput-validations](https://user-images.githubusercontent.com/1186125/85746200-9377a500-b706-11ea-8e5c-a570266a0159.png)

**Comment by pdanpdan** [comment]
There is something very strange with how Vue generates the VNodes for the components:
- a component rendering a simple QInput renders the QInput without a wrapper
- a component rendering a QInput with hint prop or a not inlined rule prop renders as a wrapper $vnode with the name of the component

**Comment by rstoenescu** [comment]
When you wrap a Quasar form component you need to also passthrough the "validate()" method.

**Comment by pdanpdan** [comment]
An example with validation added: https://codepen.io/pdanpdan/pen/eYJEmmd?editors=0010

**Comment by shazadan** [comment]
The codepen link is not working. Can you please re-share  an example of how to pass-through and handle the validate function.

**Comment by canturgay** [comment]
+1, I would really appreciate if someone could build an example for this

**Comment by joshstrange** [comment]
In Quasar 1 you need to implement a `validate()` function on your custom component that calls the inner component

```
<template>
    <q-input ref="myInput" ...>

</template>

....

validate() {
    return this.$refs.myInput.validate();
}

```

I *think* this might only be an issue if your your quasar input is at the root level (if it's in a div inside your component I *think* it just works).

In addition, if you have a completely custom component (not wrapping a quasar component) then you can still implement a `validate()` function BUT for it to be called you need to add the class `q-validation-component` to the top-level element in your custom component. This is because quasar only looks for thiat class when looking for components to validate. [Here is that check in the source code](https://github.com/quasarframework/quasar/blob/v1/ui/src/components/form/QForm.js#L170). Of course in a completely custom component you are responsible for printing/showing the error message after you return `false` to stop the form from submitting.
