### ISSUE TITLE
Attach to "keydown" instead of "keyup" in "/src/utils/escape-key.js"

### ISSUE THREAD

**Issue by tmcdos** [quasarframework/quasar#7335]
**Is your feature request related to a problem? Please describe.**
I am facing the following situation (on Windows):
- there is a QDialog open on the screen, and one of its QInput elements has the focus
- I switch with Alt+Tab to another application (Total Commander)
- I press F3 in Total Commander to see a text file in the built-in Lister
- I press ESC in the Lister to close its window
- apparently it reacts on WM_KEYDOWN Windows message and closes as soon as I press the ESC key
- it happens so that the browser is the next application in the Alt+Tab circular queue, and as soon as the Lister closes its window the browser becomes the top-most application and thus receives the keyboard focus
- all of the above happens so quickly that at the moment I release the ESC key the WM_KEYUP message from Windows is received from the browser and consequently by the handler in `/src/utils/escape-key.js` - and thus the QDialog is closed without my intention

Obviously this behavior is annoying.

**Describe the solution you'd like**
I have patched the Quasar source code (line 8 in `/src/utils/escape-key.js`) to listen for `keydown` event instead of `keyup` - it solves my case and hopefully does not break anyone else's case.

**Describe alternatives you've considered**
I am unable to come up with an alternative - this seems like the only possible solution.

**Additional context**
Screenshots will not help - but if requested, I can record a screencast (although it can not show the keyboard events and thus it seems not useful).

**Comment by pdanpdan** [comment]
Hello. Keydown instead of keyup would not be good because it would be a change from how it is now, unexpected and imposible to cancel. But I think checking if the keydown was caught before the keyup should be ok.

Please do a small test form me: replace in package.json "quasar": "^1...." with "quasar": "https://github.com/pdanpdan/quasar#quasar-v1.12.8-test.3-gitpkg" and report here if it fixes the problem.

Cleanup node_modules and yarn.lock / package-lock.json and do yarn/npm install.

**Comment by tmcdos** [comment]
Yes, your fix solves my issue. Thank you!

**Comment by webnoob** [comment]
Will be available in 1.12.9
