### ISSUE TITLE
QTable loader inside table body

### ISSUE THREAD

**Issue by nateiler** [quasarframework/quasar#7392]
**Is your feature request related to a problem? Please describe.**
It would be nice to add skeleton data inside a table while data is loading.  At this moment, the loading scope is outside the table: https://quasar.dev/vue-components/table#Example--Custom-loading-state 

**Describe the solution you'd like**
Perhaps is a new scope like 'loading-body' which would appear inside the table body

**Describe alternatives you've considered**
Since the table body does not show if data is not present, I thought of hacking together a computed property which would show 'dummy' data to get the table body to appear and then checking a loading property to show the skeleton columns. 

![Screen Shot 2020-07-09 at 1 11 39 PM](https://user-images.githubusercontent.com/1892443/87081590-dc3f5b80-c1e6-11ea-8f4d-a56f4e119340.png)

**Comment by hawkeye64** [comment]
I am closing the issue for inactivity. If this is still a concern, please create a conversation in the Discussions area or feel free to reopen.

**Comment by JoaoHCopetti** [comment]
I have the same issue, I think the issue isn't clear enough, the problem here is that when that `data` prop of QTable is empty, the `body` slot doesn't shows up, which leads to the issue above, we can't set Skeletons as `td` and `tr`. 

The workaround would be put some fake data on `data` prop until the real data is loaded to trigger the `body` slot to be shown, but I think that's too much hacky.

Another option is to check for some `loading` variable inside `no-data` slot and make a skeleton using `grid-flex` layout, but still, not consistent.

I think  `body` slot should always be shown, independently of the `data` prop being empty or not.

**Comment by JoaoHCopetti** [comment]
Here's a simple solution I'm using:

```js
const rows = computed(
   () => loading.value 
       ? [{name: 'dummy'}] 
       : data.value
)
```

Check for loading state, if it's loading return some dummy data just to trigger the `body` slot to show, when it stops to loading you return your real data, that can be empty, which will also trigger the `no-data` slot if the data is empty.

**Comment by cmcleese** [comment]
I think the issue that also when loading is complete and no data is return as a result, the body will still not be shown and thus no custom content could be added.
Not always in the bottom footer for no-data a preferred area.
