### ISSUE TITLE
Bootstrap theme

### ISSUE THREAD

**Issue by yieme** [quasarframework/quasar#74]
Any potential for a Bootstrap based theme?

**Comment by rstoenescu** [comment]
There is potential, just don't know when I'll have time for it. I'm currently struggling with money and I'll probably make a fundraising for this one. If enough money will be raised I'll focus on it. Unfortunately this is the situation :(

Please note though that Quasar's current themes can totally replace Bootstrap. You have everything you need in them plus even more.

**Comment by odranoelBR** [comment]
Hello Quasar guys. You doing a great job. Tks
About the bootstrap theming.
On my company, we had a lot of modules whit bootstrap css.
When i pluged one of this modules whit Quasar and debuged on QPlay, the bootstrap grid / responsiv didint work well. But everything worked, all features.
If you guys can make an 100% match whit the css..... i guess you will be marvelous.

**Comment by rstoenescu** [comment]
Will defer this to post v1.0.

**Comment by smolinari** [comment]
On the point of theming. How difficult would it be to build out a new theme for Quasar, like using Bootstrap css (and not the JS part)? Getting the theme creation process down to something fairly simple (even if it is a good bit of work) could be important for acceptance. If it is fairly simple now, maybe it just needs to be clearly documented?

You know the saying? 

>Give a man a fish, he can eat for a day. Teach a man how to fish, and he can eat for a lifetime. 

This discussion about theming is a give a fish or teach how to fish kind of proposition and I think we can all agree, a good framework really should be offering ways to fish, not just offer fish. 😄 

Scott

**Comment by rstoenescu** [comment]
Key points on how hard it would be to make a Bootstrap theme:

* Well, as you probably already know, Quasar is focused on performance. So if a CSS-only solution to a problem exists then it is preferred before a JS solution. As a result, many of the problems are solved by CSS. Furthermore, sometimes the CSS itself allows the JS to make run as few instructions as possible in order to solve a problem. This cannot be achieved if you take Bootstrap's CSS alone.
* There are a lot of responsive components written for Quasar that are simply not covered by Bootstrapp.

This can be applied to any other CSS framework. For perfomance and low footprint, Quasar implemented its own CSS framework that optimizes all components and features to the near maximum. There's a lot to talk about these optimizations and will probably write an article about them, but it will take time (at least a day) that I currently don't have to spend. This will happen after the v1.0 release though.

Cheers.
