### ISSUE TITLE
Notify.create({   ...  }) is error

### ISSUE THREAD

**Issue by Plaudern** [quasarframework/quasar#7485]
![image](https://user-images.githubusercontent.com/40253092/88250786-38bc7380-ccdb-11ea-8211-737ce7811bf2.png)
![image](https://user-images.githubusercontent.com/40253092/88250816-4a058000-ccdb-11ea-9434-cf3bd4235031.png)
what heppend?

**Comment by pdanpdan** [comment]
For help requests please head to oud discord channel or to the forum. And read the docs, first title in notify.

**Comment by F145h** [comment]
pdanpdan, Thanks for you time and great help, but you know quasar documentation state.
So, by you docs:
install quasar from vuecli, steps from documentation:

```
vue create my-app
cd my-app
vue add quasar
```

ok, page works
from quasar docs quasar-plugins/notify next linex added for vue-cli:

```
import {  Quasar,  Notify } from 'quasar'
Vue.use(Quasar, {
  plugins: {   Notify  },
  config: {
    notify: {}
  }
})
```

call Notify:
```
Notify.create({message: 'Hello world!')
```

as reslut: **Cannot read property 'add' of undefined**

**Comment by rstoenescu** [comment]
This is because you're installing Quasar twice.
Notice this in the default main.js:

```
// src/main.js
import Vue from 'vue'
import App from './App.vue'
import './quasar' // <<<<<<<<<<<<<<< THIS
```

The contents of the /src/quasar.js file is (just an extract of it):

```
// src/quasar.js
// .....

Vue.use(Quasar, {
  config: {},
  plugins: {
  }
 })
```

This is the place where you should add the plugins (and whatever else you need). Otherwise just delete src/quasar.js, remove the import statement for it from main.js and write it all in main.js :)
