### ISSUE TITLE
[docs] Quasar App Flow

### ISSUE THREAD

**Issue by PickleNik** [quasarframework/quasar#7528]
The Quasar App Flow section in Quasar CLI / Boot Files is missing a few steps. From logging to the console you can see that Vue Router is like a first boot file, its import goes before files from /boot and its export executes right before files from /boot as well. I believe it is important to mention that in steps 6 and 7 or add additional steps for that. 

Also, I think the App Flow is very important and should have it's own section in the docs with prefetch option included and a reference to the config file where various imports that affect the initial steps are made. That would help developers to better understand how they can optimize their app and what advantages Quasar gives them :)

![quasarBootLogs](https://user-images.githubusercontent.com/31113245/88862037-47b88f80-d1cd-11ea-8507-149541e22d81.png)

![Qboot](https://user-images.githubusercontent.com/31113245/88861791-b5b08700-d1cc-11ea-9f40-c45c36031bdf.png)

**Comment by IlCallo** [comment]
@PickleNik 

I can confirm VueRouter is a special case, as is Store, because it must be accessible to boot files so it must be evaluated before them.
The order is: Store (if present), Router, other boot files in the order defined into `quasar.conf.js > boot` array.

`preFetch` lifecycle is explained into its [own docs](https://quasar.dev/quasar-cli/prefetch-feature#Installation) and is not bound to the Quasar startup lifecycle, but on the route change lifecycle.

Can you send a PR adding the VueRouter initialization step between Store and boot files ones?
Not sure about a dedicated page explaining the Quasar app flow, even if I feel it could help new users, especially if not written by us, which already know most of that flow and see many details as obvious.

If you want to give it a try, do it in a separated PR, so we can discuss it there and see if it provides enough additional value to be worth the change.

If you have particular questions while writing the second one, ask here and we'll try to give you detailed answers :)

**Comment by yusufkandemir** [comment]
I guess this issue can be closed now.
