### ISSUE TITLE
QEditor - model value is not cleared

### ISSUE THREAD

**Issue by evgeniy-arapov** [quasarframework/quasar#7534]
The value in the model does not match the one displayed in the editor.
With a seemingly empty editor, the value still contains `<div> <br> </div> or <br>`.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/pen/?&editable=true&editors=101=https%3A%2F%2Fquasar.dev%2Fvue-components%2Feditor

**To Reproduce**
Steps to reproduce the behavior(`<div> <br> </div>`): 
1. Focus editor
2. Press enter
3. Press backspace

OR

Steps to reproduce the behavior(`<br>`):
1. Focus editor
2. Press 1
3. Press enter
4. Press 1
5. Press enter
6. Press backspace
7. Press CMND + A (select all)
8. Press backspace
9. See error

**Expected behavior**
Clear model

**Screenshots**
https://take.ms/hu2Km
https://take.ms/IMGWn

**Platform (please complete the following information):**
OS: OS X Catalina 10.15.5
Node: 12.18.2
NPM: 6.14.5
Browsers: Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by pdanpdan** [comment]
Hello. QEditor uses the browser's native contenteditable and the way it interprets html. Sorry, if you need something more advanced use a full editor.

**Comment by dsl101** [comment]
I know this is really old, but I just ended up here trying to work out why selecting all and deleting didn't result in zero-length string in the model. The reason the browser's native element is doing this is because QEditor uses a contentedtiable `div`. If you change that for a `span`, no additional `<br>` is inserted. So Quasar _could_ potentially fix this...

Obviously much of the CSS & layout of QEditor likely depends on the behaviour of a `div`, so it's probably not a trivial change unfortunately.

EDIT: In case anyone else ends up here, I just made a simple wrapper around QEditor as a workaround for this specific thing, and defaulting to use paragraph tags:
```vue
<template>
  <q-editor
    :model-value="model"
    paragraph-tag="p"
    v-bind="$attrs"
    @update:model-value="v => $emit('update:model-value', v === '<br>' ? '' : v)"
  />

</template>

<script setup>
  const model = defineModel({ type: String })
  defineEmits([ 'update:model-value' ])
</script>
```
