### ISSUE TITLE
"quasar upgrade --install" gives "Vue packages version mismatch"

### ISSUE THREAD

**Issue by ronfak** [quasarframework/quasar#7677]
Hi,

I updated Quasar by following the documentation :

```
$ quasar upgrade
$ quasar upgrade --install
```

Before the update i had:

```
@quasar/extras: 1.9.3 → 1.9.4
quasar: 1.12.13 → 1.13.1
@quasar/app: 2.0.6 → 2.0.8
```

Since the update, I have a lot of errors (41) when I try to make run the project.  But basically, these are two errors that keep repeating themselves over and over again.

```
Module build failed (from ./node_modules/vue-loader/lib/index.js):
  TypeError: Cannot read property 'parseComponent' of undefined
  
  - parse.js:15 parse
    [pro-office-pondera]/[@vue]/component-compiler-utils/dist/parse.js:15:23
  
  - index.js:67 Object.module.exports
    [pro-office-pondera]/[vue-loader]/lib/index.js:67:22
```

and the second error:

 ```
@ ./src/router/routes.js 32:21-52
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

 error  in ./src/App.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.11 (D:\dev\Pondera\clients2\pro-office-pondera\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\dev\Pondera\clients2\pro-office-pondera\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

I tried a few tricks to solve it, but everything failed. I'm afraid that if I dig deeper and make more changes (eg. force the version), I'll break something for the future and I'll have more problems.

if i do a "npm ls vue" i get:
```
+-- @quasar/app@2.0.8
| `-- vue@2.6.12
`-- vue-global-var@1.0.0
  `-- vue@2.6.11
```

quasar upgrade returns:
Congrats! All Quasar packages are up to date.

Can someone guide me on how to solve this problem and be able to lead the project again?

Thank you.

**Comment by ronfak** [comment]
**npm install** didn't do anything, so I forced the installation of vue@2.6.12 with **npm install vue@2.6.12** and everything works now.

I don't know, however, why it wasn't upgraded with quasar directly.

**Comment by rstoenescu** [comment]
Hi,

The problem lies in the fact that vue-global-var package also installs vue (and also vuex)... It should treat them as external deps given the scope of that package. Just took a look at what vue-global-var is supposed to do. If you just want something available everywhere within Vue, just create a boot file and say Vue.prototype.something = itsvalue (then you can reference this.something)... I fail to understand why you'd need such a convoluted system when this functionality is available out of the box in Vue.

If you manually install vue/vuex, you're just set for trouble later. My recommendation is to drop vue-global-var and simply use the equivalent native Vue feature.
