### ISSUE TITLE
[bug]QTable props card-class, did the opposite of the description

### ISSUE THREAD

**Issue by wowissu** [quasarframework/quasar#7708]
**Describe the bug**
https://quasar.dev/vue-components/table#QTable-API

`card-class` 
Description
CSS classes to apply to the card (when in grid mode)

Did the opposite of the description
ex: 
`<q-table  :grid="false" card-class="table-card-class">`
`table-card-class` is display with `grid="false"` but not `grid="true"`

**Screenshots**
![image](https://user-images.githubusercontent.com/12434914/91840020-96e95880-ec82-11ea-9ae4-5b4560ad6364.png)

**Platform (please complete the following information):**
```
Operating System - Darwin(19.6.0) - darwin/x64
NodeJs - 13.13.0

Global packages
  NPM - 6.14.4
  yarn - 1.21.1
  @quasar/cli - 1.1.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 1.13.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.0.8 -- Quasar Framework local CLI
  @quasar/extras - 1.9.5 -- Quasar Framework fonts, icons and animations
```

**Comment by rstoenescu** [comment]
The feature works as expected. The API description can be enhanced though (which I just did).
"CSS style/classes to apply to the card (when in grid mode) **or container card (when not in grid mode)**"

The card-class/card-style is applied as explained above. When in grid mode, it is applied directly to each card. When not in grid mode, it is applies to the container card (of the table). This is for design consistency.

You are looking only at the container, so that's why it seems it does the exact opposite.
