### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by MatanYed** [quasarframework/quasar#773]
The most used css library now is sass ( scss syntax )
Quasar should support it

**Comment by murbanowicz** [comment]
No. Stylus is like SASS on steroids. You can write SASS in Stylus and it will work

**Comment by rstoenescu** [comment]
You can use whatever CSS preprocessor you like. All you need is to add the right webpack loader for it. More info in documentation (Guide).

**Comment by myknbani** [comment]
But that makes it impossible for SASS to access Stylus variables right?

**Comment by smolinari** [comment]
You can't have your cake and eat it too. [Learn Stylus](http://stylus-lang.com/).[ It's better than Sass for a number of reasons](https://webdesign.tutsplus.com/articles/why-i-choose-stylus-and-you-should-too--webdesign-18412). 

Scott

**Comment by myknbani** [comment]
@MatanYed  

It is a lot of work and out of scope for this project to have a SASS port and LESS port and whatnot 😁 

But if I understand correctly, you're thinking about Bootstrap having less and sass versions, so that you can easily theme Bootstrap using your favorite CSS preprocessor and tweak those branding colors and sizes, etc.  Note that bootstrap also has some unofficial port of Bootstrap to Stylus.  

The most logical approach would be to also use Stylus.  Keeping a `some-variables.scss` file and a `some-variables.styl` file in sync is not pretty.
