### ISSUE TITLE
Add quasar App extension in vue cli or add jquery datatable search filter in qtable

### ISSUE THREAD

**Issue by muzammil17** [quasarframework/quasar#7816]
hey,
Im working on a buisness application using quasar plugin in vue project. So the application is all about data and display data on tables. I need a search filter in tables which can search multiple values in different columns just like datatable of jquery. so I need one of the two things, I also watched the qgrid which have search filter on every column.
1. Enable quasar extensions to be worked in vue cli. I saw qgrid quasar app extension and was a perfect match for my app.
2. Add datatables search filter method in quasar qtable which searches multiple columns together

PS: I dont want to use quasar cli

**Comment by rstoenescu** [comment]
Hi,

The Quasar App Extensions are tailored for Quasar CLI. They use the inner workings of our CLI and cannot be used with Vue CLI. The Vue CLI does not have the features that we need, which is why we supply our CLI in the first place. However, if QGrid owner would be using the Quasar UI kit then that will also supply a standalone package that can be imported in any type of project.

**Comment by muzammil17** [comment]
Is it not possible for you to build a search bar in q-table like a search bar in jquery data table.  It searches in different columns together 
[https://datatables.net/](url)

![Screenshot (13)](https://user-images.githubusercontent.com/30322831/94332109-9b87ff00-ffeb-11ea-884b-a51b2755bdc3.png)
