### ISSUE TITLE
Css classes not obvious

### ISSUE THREAD

**Issue by khudia** [quasarframework/quasar#7857]
First i have to say that i'm not rookie with quasar) And i've made a lot of projects with it from personal to b2b and mobile apps. 
I really like it very much. Thanks again for your product a lot!!! But last time as more i use it as more i started to notice that css classes are not obvious and there are not enough of them to make most of things in layout and styling. May be you can think of something close to "tailwind css"  in terms of amount and names of css classes. Thanks a lot! It would be grate for any answer

**Comment by rstoenescu** [comment]
Hi,

First of all, thanks for the appreciation!

Quasar CSS is not meant to encapsulate everything in the CSS world. The reason is simple: we are very careful on the footprint (in KB) of both js and css. Encapsulating everything possible can only mean adding hundreds and hundreds of KB to the CSS while most devs will likely use 5% of it. So, Quasar CSS encapsulates only what it uses for its own components (which covers a lot, but not everything). I think we can agree that shipping 1MB of minified (and mostly unused) CSS code is not something that anyone wants when they use Quasar (unless they want a score of 0 in overall performance).

Should you feel the need of a certain border set of classes (giving out an example) you can add them to the app.scss/sass/styl file then you can apply the classes wherever you need them.

Regards,
Razvan

**Comment by khudia** [comment]
I fully share your position on optimization and I consider your proposal to use the styles I need to be justified and most likely I will do so. What about using "purge" at the build stage to remove unnecessary styles but have ability to at development?

**Comment by rstoenescu** [comment]
We've tried numerous strategies with purge, but it requires a LOT of manual configuration in order to work correctly. It slows down development by a very significant amount because you need to tweak the config on a regular basis. Moreover, while developing and because of the above, you get the feeling if Quasar even works or not :) From a pragmatic perspective, it's unfeasible at this point in time.

**Comment by khudia** [comment]
I see! Thanks again. I will use method as you said before.
