### ISSUE TITLE
Quasar CLI warns about deprecated coffee-script

### ISSUE THREAD

**Issue by rowild** [quasarframework/quasar#7859]
**Describe the bug**
When updating to the latest quasar cli, npm issues a warning message:
`npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)`

**Codepen/jsFiddle/Codesandbox (required)**
Not possible, because CLI related; just install the cli

**To Reproduce**
1. install the quasar cli

**Expected behavior**
no warning

**Screenshots**

**Platform (please complete the following information):**
OS: MacOS
Node: 14.9.0
NPM: 6.14.8 
Yarn: --
Browsers: --
iOS: --
Android: --
Electron: --
Terminal: Mac terminal

**Additional context**
(Within the bug report "skin", you should probably respect reports that concern the CLI; in that case a codepen is not possible and can therefore not be required...)

**Comment by rowild** [comment]
This is not a bug, but I had no idea, which other section to use to report a CLI problem. Maybe you can offer a separate category for that?

**Comment by rstoenescu** [comment]
Hi,

1. The ticket has been logged to the appropriate repo because:
2. We have a mono-repo where multiple packages are present. Creating one "feature" and one "bug" for each would make the process of logging a bug more difficult than the benefits that it would provide. So relying on the common sense of the reporters. Of course supplying a codepen or jsfiddle for "@quasar/cli" and "@quasar/app" is ludicrous, so just remove that section.
3. We are not using coffeescript, but some deep dependency requires it. Welcome to the NPM jungle! Just ignore it. We can't do anything about it (and it's not under our control).

**Comment by rowild** [comment]
@rstoenescu Understood! Thank you for your response! :-)
