### ISSUE TITLE
304 error after update and app is not loaded

### ISSUE THREAD

**Issue by Amosss** [quasarframework/quasar#7863]
**Describe the bug**
I'm not sure to what it is related so I will just write the facts as I experienced them:
Everything was working fine. 
Quasar app 2 came out and I followed all the instructions.
In order to start clean, I deleted node_modules folder and npm installed from scratch.
When I `quasar dev` my app, it was not showing and I got `304 status codes` in the network tab (see screenshot below).
I reverted back to the backup from before the update. Did the same exact steps without deleting node_modules. Everything was working great. I was told to try with yarn instead of npm.
Finally I had some time to check it so I deleted node_modules folder, yarn everything but the same happened.
Though the problem started as part of upgrading to app 2, It could be not related because it works as long as I don't delete node_modules folder and install everything again. The thing is, I don't understand what it can be related to.

**Codepen/jsFiddle/Codesandbox (required)**
Irrelevant

**To Reproduce**
simply delete node_modules and npm install/yarn install.

**Expected behavior**
The app should start with code 200 and show itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/17168621/95012466-745fac00-0641-11eb-83b5-4e3ee377e627.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: v12.16.3
NPM:6.14.4
Yarn:1.22.5
Browsers: Firefox/Chrome

**Comment by rstoenescu** [comment]
Hi,

There's nothing wrong with Quasar. Please check your environment again (maybe clear cache?). Are you developing a PWA? Maybe you've had something else previously installed that tampers with the page? If that's the case, then uninstall the service worker (check Application tab). If you're not developing a PWA or have not previously installed a PWA on that URL, then I can assure you it's got nothing to do with quasar/app. Please visit our https://chat.quasar.dev and request for help from the community (if you haven't already). Bottom line, HTTP code 304 means "resource has not changed since it was last cached". The symptoms that you have described have nothing to do with yarn, node_modules & friends. It is definitely something related to your browser (maybe a config, maybe a browser extension, something...).

**Comment by Amosss** [comment]
Yes, PWA. From what I read, 304 means something on the server side so maybe it's related to `quasar dev` command? I mean something that runs behind the scenes and is broken in some way? You wrote 
> then uninstall the service worker (check Application tab)

What should I look for there? Where can I read on how to uninstall (and install) the service worker?
I will also try the chat but if you can give me just this hint, it might help, thanks

**Comment by rstoenescu** [comment]
Look for the registered service worker. And click "Unregister".

![pwa](https://user-images.githubusercontent.com/4665641/95072894-9fff9680-0714-11eb-9158-b3d85028bbf7.png)

**Comment by Amosss** [comment]
Thanks, will give it a try

**Comment by Amosss** [comment]
There are no errors in the console, how can I debug it using the debugger?
![image](https://user-images.githubusercontent.com/17168621/95083788-a5191180-0725-11eb-9e33-b0a7ed9a31a3.png)
