### ISSUE TITLE
Cannot use outlined icons on route tab

### ISSUE THREAD

**Issue by chaosKP** [quasarframework/quasar#7865]
**Describe the bug**
It is possible to get a material icon outlined on an q-icon if the class="material-icons-outlined" is added. But if this is tried on a q-route-tab / q-tab or other components that can recieve icons the normal version of the icon is shown

**Codepen/jsFiddle/Codesandbox (required)**
Not showing the outlined q-icon because I don't know how to add 'material-icons-outlined' to the quasar.conf.js extras
https://jsfiddle.net/2fpzaeo0/1/

**Comment by rstoenescu** [comment]
It's right there in the docs, man...

If you're using UMD then use https://quasar.dev/start/umd to get all the necessary tags.
Otherwise, if you're using Quasar CLI, then add: quasar.conf.js > extras > 'material-icons-outlined' then the outlined icons are prefixed with "o_" (example: "o_monetization_on").

https://quasar.dev/vue-components/icon#Webfont-usage

**Comment by chaosKP** [comment]
Sorry, my bad, somehow I overlook the o_ ...
Thanks!
