### ISSUE TITLE
Setting cordova->id in quasar.conf.js does not affect src-cordova/config.xml

### ISSUE THREAD

**Issue by uvizhe** [quasarframework/quasar#7883]
Setting `cordova->id` in quasar.conf.js does not affect `src-cordova/config.xml`.
Other variables (`version`, `description` and `android-versionCode`) propagate as [expected.](https://quasar.dev/quasar-cli/developing-cordova-apps/configuring-cordova#quasar.conf.js)

```
quasar=v1.14.1
@quasar/app=2.1.1
cordova=10.0.0
cordova-android=9.0.0
node=v10.19.0
npm=6.14.4
```

My build command is: `quasar build -m cordova -T android`

**Comment by rstoenescu** [comment]
Hi,

"id" cannot be updated due to the inner-workings of Cordova projects (the `src-cordova` folder). It cannot be in Quasar's powers to workaround this behavior. This is why when adding the Cordova (or Capacitor) modes it asks you what "id" you'd want to use. If you'd like to change the "id", you'd have to remove the Cordova mode then add it back --- be mindful if you've made changes to Cordova's files (they'll be lost in the process).

**Comment by uvizhe** [comment]
Hmm, I used to set "id" programmatically with Quasar v1.
Like 
```
cordova: {
  id: ctx.dev
    ? 'com.example.myapp_dev'
    : 'com.example.myapp
}
```
This stopped to work when I switched to v2 and I did not update Cordova as far as I remember.

**Comment by rstoenescu** [comment]
Yes, it's one of the long awaited needed changes in q/app v2. Unfortunately, due to how Cordova works, there's no way around it.
