### ISSUE TITLE
q-menus can't be nested properly

### ISSUE THREAD

**Issue by whatda** [quasarframework/quasar#7894]
**Describe the bug**
q-menus lose their style when nested. Implementing nested menus like on YouTube is not possible right now, since width and position change according only to current contents instead of all contents. While changing the width might be hard to avoid, the position should definitely not change.

**Codepen/jsFiddle/Codesandbox (required)**
Example 1 uses two q-menus: https://jsfiddle.net/shqLfv6y/
Example 2 uses just one q-menu and one q-list: https://jsfiddle.net/15y6hu04/

**To Reproduce**
1. Open fiddles
2. Click on button
3. Click on menu items

**Expected behavior**
Width and position stay equal

**Platform (please complete the following information):**
Browsers: Firefox, don't know about others

**Comment by rstoenescu** [comment]
Hi,

The position does not change. The menus are positioned with CSS with top/left coordinates. The problem is that we can't add "watchers" to see when menu content changes (that would add huge overhead), so it is needed to be done manually. Assign a vue ref to the QMenu and call updatePosition() on it whenever you make a change to the content that affects its width/height.

**Comment by whatda** [comment]
Hi,
thank you. There's still some unexpected position change, though: https://jsfiddle.net/fp0nohur/
If you click the first item back and forth, you'll notice that the initial margin to the right disappears. I noticed it first in my project (which doesn't use float: right), so it's not just in the fiddle.
