### ISSUE TITLE
PWA manifest.json and icons causing 404 error when used in SSR mode

### ISSUE THREAD

**Issue by nfleury** [quasarframework/quasar#7909]
**Describe the bug**
When running quasar in PWA + SSR mode we have a manifest.json + icons with the following link :

```
<link rel="manifest" href="manifest.json">
<link rel=apple-touch-icon href=icons/apple-icon-120x120.png>
<link rel=apple-touch-icon sizes=152x152 href=icons/apple-icon-152x152.png>
```

This isn't an issue when running in PWA mode only but when running in SSR + PWA mode because this url is always relative to current url. Some bots when crawling an actual existing url such as myapp.com/a will also check myapp.com/a/manifest.json that doesn't exists (same goes for the icons).

**Codepen/jsFiddle/Codesandbox (required)**

https://codesandbox.io/s/angry-burnell-zqxqb

**To Reproduce**
1. Open https://codesandbox.io/s/angry-burnell-zqxqb
2. Check the web output with curl for example :  curl https://zqxqb.sse.codesandbox.io/ | grep "manifest"

**Expected behavior**
Url for manifest.json and icons should be:

```
<link rel="manifest" href="/manifest.json">
<link rel=apple-touch-icon href="/icons/apple-icon-120x120.png">
<link rel=apple-touch-icon sizes=152x152 href="/icons/apple-icon-152x152.png">
```

So that it doesn't cause any 404 issue

**Platform (please complete the following information):**
OS: Ubuntu 16.06
Node:  v12.16.3
NPM: 6.14.4
Browsers: All browsers

**Comment by rstoenescu** [comment]
That's why there's a `<base>` tag injected by Quasar. I just retested everything and there's no problems. Are you sure that you understand the workflow of workbox (u haven't specified the workbox version) and have configured it to your expectations? I see that the workboxOptions property in your quasar.conf.js > pwa is empty.

By reading your description, I think that you actually meant configuring it along the following lines:

```js
workboxOptions: {
        cleanupOutdatedCaches: true,
        skipWaiting: true,
        clientsClaim: true
}
```

There's nothing I can do since I can't reproduce the issue.

**Comment by rstoenescu** [comment]
Please reopen with comments.
