### ISSUE TITLE
cannot read property 'platform' of undefined

### ISSUE THREAD

**Issue by 793405936** [quasarframework/quasar#7934]
**Describe the bug**
in VuePress, use QTabs, when build report Cannot read property 'platform' of undefined

**Codepen/jsFiddle/Codesandbox (required)**
in enhanceApp.js
import Quasar from 'quasar';
import '@quasar/extras/material-icons/material-icons.css';
import lang from from 'quasar/lang/zh-hans/';
import 'quasar/dist/quasar.styl';
export default ({
   Vue,
   isServer
}) => {
   Vue.use(Quasar, {
   lang,
   config: {}
})
}

**To Reproduce**
1. in VuePress
2. use QTabs in .vue
3. npm run build

**Platform (please complete the following information):**
OS: windows10
Node: 12.9.0
NPM: 6.14.8
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
The problem is that VuePress needs to be configured properly first. What I mean is the webpack configuration needs to be correct in regards to Quasar. You can check how this is done with the [vue-cli-plugin-quasar](https://github.com/quasarframework/vue-cli-plugin-quasar), which is the closest in terms of what might be needed for VuePress. We currently don't have enough bandwidth to support an official Quasar plugin for VuePress.
