### ISSUE TITLE
Build process removes icons generated by Icon Genie v2

### ISSUE THREAD

**Issue by pavel-mironchik** [quasarframework/quasar#7937]
**Describe the bug**
The Icon Genie documentation states:
>Your CI/CD will not need it as **it is a one-time process** and the output files (images) will be added directly to your project folder.

But the quasar build command removes the `public` folder with all its content, including the icons created by Icon Genie.

**To Reproduce**
1. Run `icongenie generate` with your options, it will create icons in the `/public/icons` folder and the `/public/favicon.ico` file.
2. Run `quasar build`, it will say `Cleaned build artifact: ... /public` and then remove the `/public` folder with all its content, including the icons created by Icon Genie. Then it will compile all resources, but the icons will be lost.

**Expected behavior**
Build process should keep the `/public/icons` folder intact. A developer doesn't need to run the `icongenie generate` command after every build process.

**Platform (please complete the following information):**
OS: Linux
Node: 12.18.1
NPM: 6.14.5

**Additional context**
Icon Genie v1 was an extension and ran as a part of the build process, so there was no such issue.

**Comment by rstoenescu** [comment]
Hi,

This can only mean one thing. Your destination folder for production builds is set to /public. This is not right. In order to ensure that the destination folder doesn't gets bigger and bigger over time (adding more and more file while most become unused/obsolete), Quasar needs to delete the folder and only then build upon it.

What you can do is set the destination folder to something else then copy it to your desired /public destination. But again, /public is used for static assets in the context of a Quasar CLI app... it makes no sense to highjack its use for something else.
