### ISSUE TITLE
<q-input> ignores `bottom-slots` prop when used together with `rules` prop

### ISSUE THREAD

**Issue by wujekbogdan** [quasarframework/quasar#7966]
**Describe the bug**

I'd like to use custom validators, but I don't want the error message to be displayed. So I used `:bottom-slots="false"` prop to disable bottom slots. No matter what is the value of `:bottom-slots` the error message is displayed under the input.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/wujekbogdan/pen/ZEOvdKL

**To Reproduce**
1. Create `<q-input>`
2. Add `rules=[your, roules, go, here]`
3. Add `:bottom-slots="false"`
4. Enter an invalid string

**Expected behavior**
The input should turn red but the error message should not be displayed.

**Screenshots**
The input turns red but the error message is displayed. I tried `:bottom-slots="false"`, `:bottom-slots="null"` and other falsy values.

**Platform (please complete the following information):**
OS: macOS 10.15.6
Node: `12`
NPM: `6.14.5`
Yarn: `1.22.5`
Browsers: Chrome `86.0.4240.111 `

**Comment by rstoenescu** [comment]
Hi,

This is the whole point with `rules` props. Notice for each rule that you need to return `true` or a string.
What you actually want is the external validation where you can supply `error` (Boolean) and optional `error-message` (String). https://quasar.dev/vue-components/input#External-validation

Also notice that each rule function already receives the value as param. So you don't need to look up `this.input`. That's a highly ineffective way to use a computed prop. The best performance (due to how Vue works) is to cache the whole rules array --- and to not touch the model since it is received as param so it basically does the same thing, but in your case the rules are recomputed for every model change.

**Comment by wujekbogdan** [comment]
So it would be good to make it clear in docs. Otherwise it's confusing. I know how `rules` prop work and that it is supposed to be used together with validation messages, but I use `rules` as a workaround - I use `lazy-rules` in order to prevent validation from happening before a user focuses out, but I don't want the validation messages to show up.

I could use the `error` prop, but if I did that I would have to implement `lazy-rules` on my own, by listening to `@blur` event or use an external tool (like `vuelidate`) for validation.
