### ISSUE TITLE
Dialog No Route Dismiss didn't work

### ISSUE THREAD

**Issue by Nisgrak** [quasarframework/quasar#7970]
**Describe the bug**
The option noRouteDismiss didn't make any differences

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/silent-pine-9cyh4?file=/src/pages/Index.vue

**To Reproduce**
1. Create a dialog with `noRouteDismiss`
2. Change the route of the app
4. The dialog still stays

**Expected behavior**
If the option `noRouteDismiss`is set as false the dialog will close when the route change

**Comment by rstoenescu** [comment]
Hi,

"noRouteDismiss" means "no route dismiss" as in "don't dismiss on route change". It's the exact opposite. The sole purpose of that prop is to not dismiss even when route changes, otherwise don't use that prop for the default behavior (which is what you want).

**Comment by Nisgrak** [comment]
If I set to true the result it's the same

**Comment by rstoenescu** [comment]
Reopening so I don't forget to reply tomorrow. 2:50AM here :)

**Comment by webnoob** [comment]
@Nisgrak The reason your test isn't working is because of the 404 (invalid route). I've just been running some tests on this and if you provide a valid route, the property works as expected. `noRouteDismiss: true` will cause the dialog to remain if the route changes, whereas setting it to `false` will cause it to dismiss (default behaviour).

I'm going to hazard a guess as this is some nuance with portals but @rstoenescu will confirm if this behaviour is desired or not.

For now I'm closing the ticket as I would expect a valid route to be present. If this is indeed your valid scenario where you want the modal to remain open even when an invalid route is passed ping us for review.
