### ISSUE TITLE
QInput - Native attributes like a prop in extend component

### ISSUE THREAD

**Issue by jeangomes** [quasarframework/quasar#7975]
**Is your feature request related to a problem? Please describe.**

I have many fields (q-input) with the same characteristics/props, for less code and better reuse, I started extend QInput.
Example:
https://codepen.io/jean-gomes-pereira/pen/oNLqaYg

But the step is native attribute, so I can't set a default.
I tried many ways, without success.

**Describe the solution you'd like**
Step be a standard prop

**Describe alternatives you've considered**
Or another option coming from you.

**Additional context**
The component receive a prop, but native element html not.

**Comment by metalsadman** [comment]
use a wrapper instead of extending.

**Comment by jeangomes** [comment]
I wouldn't like to wrapper, there is another alternative?
What is a better/official way to wrapper quasar components? and keep data, behaviors, events, etc...
I read some article and posts on forum, but I have a doubt.

**Comment by Saeid-Za** [comment]
I'd also prefer wrapping a component and passing all the events & props. Here's how i would do it, here's a sample on how to wrap `q-select` component. hope it helps:
There are 3 aspects that should be covered, props, events and slots.
TS file (i'm using typescript in vue, you can change the code to normal `option-based` component - instead of `class-based`)

```ts
import { QSelect as QuasarSelect } from "quasar";
import { Component, Vue } from "vue-property-decorator";

@Component({
  components: {
    QuasarSelect
  }
})
export default class Select extends Vue {
  options = [
    {
      value: "1",
      label: "First Option"
    },
    {
      value: "2",
      label: "Second Option"
    },
    {
      value: "3",
      label: "Third Option"
    }
  ]
}
```

Template File : 
```vue
<template>
  <QuasarSelect v-bind="$attrs"
    v-on="$listeners">
    <template v-for="(_, name) in $scopedSlots"
      :slot="name"
      slot-scope="slotData">
      <slot :name="name"
        v-bind="slotData" />
    </template>
  </QuasarSelect>
</template>
```
and finally, the usage sample:

```vue
<template>
  <Select :options="options"
    v-model="value"
    label="My Select !">
    <template v-slot:append>
      <q-icon name="cancel"
        v-if="value"
        @click.stop="value = null"
        class="cursor-pointer" />
    </template>
  </Select>
</template>
```
Note that this only works on vue version 2. there's a small change that should be applied to support vue version 3.
More info [here](https://stackoverflow.com/questions/50891858/vue-how-to-pass-down-slots-inside-wrapper-component).

**Comment by pdanpdan** [comment]
Hello.
Please us the discord channel or the forum for help requests.
Thank you
