### ISSUE TITLE
Property position of QDialog is breaking with QScrollArea if set to "bottom" or "top"

### ISSUE THREAD

**Issue by Medhyena** [quasarframework/quasar#8018]
**Describe the bug**
If you create a QDialog with property position set to "bottom"/"top" it works fine till you add the QScrollArea. The result is just the backdrop screen appearing, not the dialog itself.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/medhyena/pen/zYBmRNZ

**To Reproduce**
1. Go to https://codepen.io/medhyena/pen/zYBmRNZ
2. Click on open dialog button
3. QDialog doesn't appear
4. Remove attribute position
5. Go to step 2 (this time it works)

**Expected behavior**
It should appear normally just like if position was set ro right/left/standard except it should appear at the bottom/top

**Screenshots**
When dialog is "opened"
![image](https://user-images.githubusercontent.com/17769074/98551665-ddb88780-229d-11eb-8b38-69decc703360.png)
When dialog isn't opened
![image](https://user-images.githubusercontent.com/17769074/98551700-e4df9580-229d-11eb-8758-9ff511acda75.png)

**Comment by webnoob** [comment]
QScrollArea requires a height in order to work.

It's not that the dialog isn't show, it's that the height is zero because it has no content. If you add some other content, it works: https://codepen.io/webnoob/pen/bGemmBy OR if you set a height on the ScrollArea it works: https://codepen.io/webnoob/pen/XWKxxNN

**Comment by Medhyena** [comment]
Ok, weird, but fine !
