### ISSUE TITLE
QDialog - Main scrolling breaks when rendering a dialog

### ISSUE THREAD

**Issue by zv3** [quasarframework/quasar#8035]
**Describe the bug**
Scrolling breaks when opening a `QDialog` with lots of content.

**Codepen/jsFiddle/Codesandbox (required)**

https://codesandbox.io/s/sleepy-black-ir5fe?file=/src/pages/Index.vue

**To Reproduce**
1. Go to this page on iPhone (Safari) -- https://ir5fe.sse.codesandbox.io/
2. Scroll down until the **Show Dialog** button is visible and the browser's bottom bar disappears.
3. Click on the **Show Dialog** button.
4. Wait till the dialog shows up and is done rendering, and click on the X button to close the dialog.
5. Once the dialog is removed, try to scroll down the main page.

**Expected behavior**
The scroll position to return back to the previous location and the scrolling to function as expected once the dialog is closed.

**Screenshots**

https://streamable.com/ato6sj

**Platform (please complete the following information):**
Quasar: 1.14.3
Browsers: Safari
iOS: 13.7 (most likely affecting all iOS versions)

**Additional context**
This most likely happens when the content to render in the dialog is heavy (has too many images for example) that Safari isn't able to render the browser's bottom bar in time when [this line](https://github.com/quasarframework/quasar/blob/5dd94dfd7461a89e09a3128e7ad985ea62209e5e/ui/src/components/dialog/QDialog.js#L220) is evaluated, causing the `window.visualViewport.height` to report a larger value than the one reported by `document.scrollingElement.scrollHeight` in [this line](https://github.com/quasarframework/quasar/blob/5dd94dfd7461a89e09a3128e7ad985ea62209e5e/ui/src/components/dialog/QDialog.js#L225), which then causes a negative value in the subtraction and an infinite loop in the rAF callback due to the `scrolltop` and the `document.scrollingElement.scrollTop` values failing the equality check [here](https://github.com/quasarframework/quasar/blob/5dd94dfd7461a89e09a3128e7ad985ea62209e5e/ui/src/components/dialog/QDialog.js#L234).

**Comment by seanaye** [comment]
getting same issue

**Comment by rstoenescu** [comment]
Thanks for reporting. Fix will be available in Quasar v1.14.4.

Some comments on the supplied code (that you might be aware of, but writing them here for completeness):
- using uncontainerized QLayout in QDialog (referring to QDialog "container" prop; also note that due to long ago reported and not fixed bugs in iOS the header/footer for containerized QLayout might "jump" incorrectly along with scrolling the "page" content --- no way around it)
- using QPageContainer with no QPage in it; and applying height directly on QPageContainer (instead of on the missing QPage)
