### ISSUE TITLE
QDatetime in version 0.14 is diverging the dates

### ISSUE THREAD

**Issue by rogeriomq** [quasarframework/quasar#814]
### Software version

Quasar: 0.14.0
OS: Fedora 26
Node: 8.3.0
NPM: 5.3.0
Browsers: Google Chrome

The QDatetime  component is changing my date based on a timezone that was not defined by me. What happens:
  - I have an object coming from the database via sequelize with a given property (obj.brithday) with the value '1985-09-10', just that, without timezone and time.
- By using obj.brithday in the v-model of QDatetime, it simply introduces the day 09! I thought it was strange, so I created a span that would display the date modified by QDatetime (<span> {{obj.brithday}} </ soan>).
- The result of the span was: 1985-09-10T21: 00: 00.000-03: 00, timezone -03: 00 and time 21? When sending to the database 1985-09-10T21: 00: 00.000-03: 00, he is recording in the database 1985-09-11 (day 11 and not 10) ....
PS: QDatetime has the format = "DD / MM / YYYY" property to view.

**Comment by rstoenescu** [comment]
It's not QDatetime at fault here. The model, if supplied by a string, gets transformed to a javascript `new Date()`. If the string does not have timezone, then the local browser timezone is taken into account. This is a browser behavior. In order to stick to avoid timezone confusion, it's best that you feed QDatetime with the full ISO string containing also timezone, like `1985-09-10T21:00:00.000-03:00`.

**Comment by rogeriomq** [comment]
In http://beta.quasar-framework.org/components/datetime.html#The-Model, shows in the example that it is possible to receive '1985-09-10' as the value for modelQDatetime ... and in doing so the date to be shown should be '1985-09-10' and not 1985-09-09. Anyway I will try to "format" this date on the server side so that it gets ready to my client model
