### ISSUE TITLE
QCarousel arrows are not automatically hidden

### ISSUE THREAD

**Issue by aprilahijriyan** [quasarframework/quasar#8220]
**Expected behavior**
It will look something like the https://quasar.dev/vue-components/carousel#Introduction documentation. If he clicks the next slide, a left arrow appears. But not in my case.

**Screenshots**
![Cuplikan layar dari 2020-12-17 02-15-36](https://user-images.githubusercontent.com/37798612/102396488-1707b400-400f-11eb-88d0-148e787c6cbf.png)

**Platform (please complete the following information):**
OS: ubuntu
Node: v14.8.0
NPM: 6.14.7
Yarn:1.22.4
Quasar: 1.1.2
Browsers: chrome

**Comment by pdanpdan** [comment]
Hello. For help requests please use our discord channel or the forum.

**Comment by hawkeye64** [comment]
@pdanpdan I think he's trying to say this is a bug and we should re-open this for the time being. When it is on the first slide, the left arrow is still showing.

However, to investigate this further, @aprilahijriyan needs to proivide more information. We have nothing to go on.

Typically, on first slide, or even going to second and coming back, it should look like this:
![image](https://user-images.githubusercontent.com/10262924/102537290-0172a880-4068-11eb-882b-5d39c89dd9f4.png)

**Comment by rstoenescu** [comment]
The exact details of what the reporter is doing with QCarousel are needed. Otherwise, the underlying Quasar panels just work correctly from my point of view. Maybe there's an exotic case of QCarousel children in the template that I'm not aware of. In which case a reproduction case would be great. Until then this ticket should stay closed.
