### ISSUE TITLE
[docs] How to eject Quasar CLI in favour of Vue + Quasar UMD

### ISSUE THREAD

**Issue by lopes-gustavo** [quasarframework/quasar#8346]
I'm using Quasar for SPA only. We started our project using `quasar create`. But now, we don't need all the things that come with Quasar CLI and the limitations it has on the final build.

Is there a way to eject Quasar CLI and start using Vue + Quasar UMD?

Basically, stop using `quasar dev` and start using `vue serve`?

**Comment by TobyMosque** [comment]
Personally, i don't think Quasar CLI had any limitation when compared to the Vue CLI, as well, i don't know anyone who moved from Quasar CLI to the Vue CLI.

Any way, instead of the Quasar UMD, u would pick the Quasar as a plugin to the Vue CLI ([Vue CLI Quasar Plugin](https://quasar.dev/start/vue-cli-plugin#Introduction)).

Maybe I'm wrong and someone who already did it before can offer u alternative, but i think u'll need to create a new project using the vue cli, add quasar as a plugin, so move the source from u current project to the one (paying attention for the architectural differences between both projects).

**Comment by hawkeye64** [comment]
@lopes-gustavo I agree with @TobyMosque , use Quasar as a Vue plugin for a Vue CLI project so at least you get some tree-shaking. Using UMD gives you everything, even if you are not using it.
https://quasar.dev/start/vue-cli-plugin

**Comment by lopes-gustavo** [comment]
UMD was simply an example. I just need to eject the vue project.
I'm trying to use [single-spa](https://single-spa.js.org/) but Quasar makes it a little bit harder, as I don't have much control over what it builds.
But it seems I cannot do it, unfortunately.
Thank you guys
