### ISSUE TITLE
style with sass and @mediar error

### ISSUE THREAD

**Issue by javierrodrigogomez** [quasarframework/quasar#8457]
With v2.0.0-beta3 following fails to compile:

```
<style lang="sass">
  .q-toolbar__title
    font-size: 30px
    @media (max-width: $breakpoint-xs-max)
      text-align: center
  .q-footer
    .q-tab__icon
      font-size: 30px
</style>
```

giving following error:
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Nothing may be indented beneath a @import rule.
╷
3 │ .q-toolbar__title
│ ^
╵
src\layouts\MainLayout.vue 3:3 root stylesheet
```
If I remove the @media instructions, it compiles. I added the // $ at the beginning of the style and it does compile but it is not producing any effect.

If I change to scss, it works fine

```
<style lang="scss">
  .q-toolbar__title{
    font-size: 30px;
    @media (max-width: $breakpoint-xs-max){
      text-align: center;
    }
  }
</style>
```

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta3
@quasar/app Version: v3.0.0-beta.3
Quasar mode:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS: windows 10
Node: v14.15.1
NPM: 6.14.8
Yarn: 1.22.10
Browsers: chrome
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
Hi,

Nothing changed in regards to Sass/SCSS. But I noticed something in your template. Which is that you have indentation right below the `<style lang="sass">`. In .sass, indentation matters. Remove those first 2 space indentation because that's the root cause. Whatever you put inside the starting and ending `<style>` tags, think of it "would this be valid Sass syntax if I'd just copy-paste the content as is?".

Wrong 👎 :

```html
<style lang="sass">
  .q-toolbar__title
    font-size: 30px
    @media (max-width: $breakpoint-xs-max)
      text-align: center
  .q-footer
    .q-tab__icon
      font-size: 30px
</style>
```

Good 👍 :

```html
<style lang="sass">
.q-toolbar__title
  font-size: 30px
  @media (max-width: $breakpoint-xs-max)
    text-align: center
.q-footer
  .q-tab__icon
    font-size: 30px
</style>
```

Explanation: Due to the fact that you are using Quasar Sass variables (`$breakpoint-xs-max`) this forces Quasar App CLI to prepend your content with an `@import` statement (which has no indentation). So the subsequent content (your content) has indentation, which confuses the Sass parser.

**Comment by javierrodrigogomez** [comment]
You are right! It works!

Thanks
