### ISSUE TITLE
Sometimes QModal::close doesn't work.

### ISSUE THREAD

**Issue by ababo** [quasarframework/quasar#848]
This happens on Chrome (OSX) while debugging. An intermittent error.

**Comment by rstoenescu** [comment]
It's due to HMR and QModal's feature to mingle with window history in order for the back button to work. Cannot happen in production build.

**Comment by ababo** [comment]
But it's still a bug, isn't it? Why do you close the issue?

**Comment by ababo** [comment]
It prevents me to work normally since I just cannot close my Login dialog.

**Comment by ababo** [comment]
Can I do something in order to suppress this?

**Comment by rstoenescu** [comment]
There's currently nothing that can be done to overcome this for dev builds other than disabling this feature entirely.

What you can do is this though, BUT only for dev builds.

```js
// in main.js:
import { Platform } from 'quasar'
Platform.has.popstate = false
```

**Comment by ababo** [comment]
What does it do and why I should avoid that in production? Thanks.

**Comment by rstoenescu** [comment]
It overrides the detection of [popstate event](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) and sets it to false regardless of the environment where the website/app is running under.

In order for Quasar to provide a feature no other framework has, it stretches the capabilities of both Vue and Webpack's HMR. When you open a QModal it adds an entry in the window [History](https://developer.mozilla.org/en-US/docs/Web/API/History_API) and registers for popstate event so that when you hit back the QModal will get closed rather than your website/app navigate to the previous route (while Modal is still opened at the top). Now, when HMR kicks in, it destroys and recreates the modal, but there's no way to safely remove the history entry (added before when modal first got opened) and still display the modal. So the end result is that each HMR action adds another history entry. You can close the modal if you hit the same amount of HMR actions that took place + 1, or hit browser refresh button (and modal goes away so you need to open it again).

The code indicated above is guarded by `if (DEV)` so when building for production it completely removes those lines (automatically).

**Comment by ababo** [comment]
Thank you.
