### ISSUE TITLE
q-img @load firing too early

### ISSUE THREAD

**Issue by xariusdesai** [quasarframework/quasar#8509]
**Describe the bug**
The @load event on q-img seems to fire before the src has actually been loaded.

**Codepen/jsFiddle/Codesandbox (required)**
You can see the problem here: [https://codepen.io/xariusdesai/pen/eYBRwmE](https://codepen.io/xariusdesai/pen/eYBRwmE)

If you uncomment line 19 in the JS, the url is revoked before the image is loaded by q-img and never shows. This works fine if I use a normal img element, but it doesn’t have the nice other features that q-img does.

**To Reproduce**
1. Add q-img with @load event linked to revokeURL function
2. Change q-img src through a q-file using URL.createObjectURL
3. revokeURL is fired from @load
4. q-img has not yet loaded the url, but it has already been revoked in previous function

**Expected behavior**
When @load event fires - the underlying image should have already loaded from src

**Platform (please complete the following information):**
Quasar Version: 1.15.3
@quasar/app Version: "^2.0.0"
Quasar mode:
SPA

OS: MacOS
Node: v12.17
NPM: 6.14.8
Browsers: chrome

**Comment by pdanpdan** [comment]
`@load` event is emitted when the image is loaded in the temporary Img element for processing.
The problem is that it is then displayed as a background image using CSS, so there is no way to detect when the it was finished loading.
I think the best approach would be to revoke the URL in a setTimeout: https://codepen.io/pdanpdan/pen/YzpxPLN?editors=1010

Also for Quasar 2 (Vue 3) QImg internals have changed, and I don't think a change of it in Quasar 1 makes sense (also because it's more of a timing issue, and you can delay some execution after the event but you cannot make it execute earlier in case you need it)
