### ISSUE TITLE
For navigation, how to get selected row index in q-table

### ISSUE THREAD

**Issue by jove4015** [quasarframework/quasar#8542]
**Is your feature request related to a problem? Please describe.**

As stated here : https://forum.quasar-framework.org/topic/6120/get-the-row-index-in-q-table

Quasar has removed the ability to get the current row index of a q-table.  This was done because:

> Thing is, the row index will change, if the user reorders or filters (if you have those features in use) the table. That’s why you should work with your own data id field and not the row index of the table.

I understand that one should not rely on the row index in order to update or work with data at all. However, my goal is to actually navigate through the q-table using arrow / page keys. I found a great example of how to do that here: 
 https://github.com/quasarframework/quasar/pull/6598/commits/06289f5b1a9d27ee5188b9f85cce3177b7bb3cb6 (see onKey method).

The problem is, it doesn’t work because computedData isn’t there any more, and there is no suitable replacement for “computedData.rowsNumber”.

I fully understand and appreciate the desire to encourage better coding practices by prompting developers to work with their rows by ID. However, not allowing one to get the index of the current selected row prevents the developer from providing any such navigational shortcuts. The ID of the row does not help me determine which row is shown before or after it on screen. I specifically want to know about the order in which the rows are displayed and change the current selection to the previous or next row.

Since I’m using virtual scrolling, I can’t simply move the user through the dom, because (particularly on next row it seems) the elements are rerendered and thereafter the element I scrolled into view is no longer there, or is assigned to a different row.

**Describe the solution you'd like**

If quasar has decided it’s too dangerous to allow us to provide this navigational feature to our users, perhaps you could add keyboard navigation as a feature of the table so that we have no need to implement it ourselves? Or perhaps just put the row index back in so this example can work and let developers sink or swim with their own decisions?

**Describe alternatives you've considered**

I've really tried to come up with one but I'm falling short.

**Additional context**

Also posted here:  https://forum.quasar-framework.org/topic/7899/for-navigation-how-to-get-selected-row-index-in-q-table

**Comment by pdanpdan** [comment]
I suppose it is related to Quasar 2, because in Q1 it is unchanged?

**Comment by Nerderer** [comment]
Related to this, the keyboard navigation demo on q-table is now broken in Quasar 2.

[https://next.quasar.dev/vue-components/table#keyboard-navigation](https://next.quasar.dev/vue-components/table#keyboard-navigation)

**Comment by rstoenescu** [comment]
@jove4015 You can access `computedRows` which is the same thing as `computedData` in Qv1. Then you have `rowIndex` (Row/Item's index (0 based) in the filtered and sorted table) and `pageIndex` (Row/Item's index (0 based) in the current page of the filtered and sorted table) in the slot param

**Comment by zvolsky** [comment]
Hi, Can find `computedRows`, but cannot find `rowIndex, pageIndex`. What means "in the slot param"?

**Comment by brakop** [comment]
I found this discussion and figured out a solution, but didn't see a posting about it... so here you go!

The problem is that your QDataTable is defined using a big array of things, but your user can custom sort the display of that array and so [0] from your data may not (and probably isn't) [0] for what your user sees. To resolve this, you can access filteredSortedRows using a reference to the Q-Table. 

The key is to add a ref="MyTableName" to your q-table component, and then either in a watcher or method you can access the filteredSortedRows, something like this:

`
//This is a watcher for the Check All button, it then will check ONLY items on the visible page according to the users sorting:  
bCheckAll: function() {  
  var x;  
  if(!this.bUpdatingCheckAll)  //Careful because checkAll watcher can be triggered by checking a box
    for(x=0;x<this.FridgePagination.rowsPerPage;x++) {  
      if(typeof this.$refs.QFridgeTable.filteredSortedRows[x] !='undefined')  
            this.$refs.QFridgeTable.filteredSortedRows[x].selected=this.bCheckAll;  
        }  
    },  
`
 
Now a lot of people are going to say, WHY do you need this? The QTable already has a check all button that checks only the items on the current page? In my case I needed it because I was trying to combine the Checkbox example with the expanding rows example and the two seem to be mutually exclusive (I think because of the template slot process required for the expanding row?) Not sure. Anyway, this helped me, so enjoy!

**Comment by MilosPaunovic** [comment]
Keep track of this PR: https://github.com/quasarframework/quasar/pull/14243.
It's intention is to introduce `fields` top-level property into a documentation; it will list properties you're talking about
https://github.com/quasarframework/quasar/blob/70319f5f33c6ead76c5e0f14a128be6235b2b7ca/ui/src/components/table/QTable.json#L2419
