### ISSUE TITLE
Q-Chat-Message component using wrong class with the bg-color property

### ISSUE THREAD

**Issue by CarlosWosiak** [quasarframework/quasar#8545]
**Describe the bug**
Q-Chat-Message component using wrong class with the bg-color property

**Codepen/jsFiddle/Codesandbox (required)**
The wrong class set can be found in the file
ui/src/components/chat/QChatMessage.js
line 35

**To Reproduce**
1. Go into the file in question and see the messageClass method

**Expected behavior**
The class should be 'bg-${this.bgColor}' instead of 'text-${this.bgColor}'

**Screenshots**
![image](https://user-images.githubusercontent.com/29006379/109318015-1ae45d80-782c-11eb-9998-df06788bc9a5.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  [x ] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
If you wish, I can submit a PR changing the class.

**Comment by rstoenescu** [comment]
Hi,

I'd appreciate if tickets were logged after checking out if it is really a bug. Otherwise, you may read the code and not fully grasp all the details. In this case, we're using currentColor a lot to make the CSS classes as customizable as possible (lowest possible selector classes).

I understand and really appreciate the desire to help. But logging something without checking it means lost time both for you and us and it's not really helping.

**Comment by rstoenescu** [comment]
https://quasar.dev/vue-components/chat#Example--Text-and-background-color
