### ISSUE TITLE
Vuex or Vue Apollo

### ISSUE THREAD

**Issue by Vladislav-wn** [quasarframework/quasar#8574]
Hi,
Why there is no choice when creating a project Quasar CLI: Vuex or Vue Apollo (https://v4.apollo.vuejs.org/) ?

Thanks

**Comment by TobyMosque** [comment]
Since apollo and graphql are very opnative, that can be more than quasar cli would handle.
In this kind of scenario we encourage the use of extensions, in this case u'd @quasar/apollo.

so, just create a new project without vuex and after that, u can add the @quasar/apollo. you can read more in the following links:
https://dev.to/quasar/quasar-and-apollo-client-state-without-vuex-2iii
https://github.com/quasarframework/app-extension-apollo

**Comment by Vladislav-wn** [comment]
Many thanks! :-)
