### ISSUE TITLE
The spanish language does not work

### ISSUE THREAD

**Issue by MandingaRadi** [quasarframework/quasar#8635]
in quasar.conf.js:

framework: {config: {lang: 'es'}} 
it does not work in mode PWA.
the browsers offer me to translate the application.
(I have another app in quasar v1 and yes it does.)

the problem appears for example in Edge for iOS.
Thanks

**Comment by rstoenescu** [comment]
The language packs work exactly the same with Quasar v1 and v2. If there's a problem in v2 then it means it has to be able to get replicated with v1 also. But the issue itself sounds like a browser bug rather than a Quasar one.

Can you open up the devtools (can be on a desktop browser too) and screenshot the html markup there pls? Especially the `<html>` tag attributes. Thanks.

**Comment by MandingaRadi** [comment]
Dear stoenescu, thank you for answering.

Already solved!
I was putting 'lang:' es '' inside 'config: {}'

Now it works well.

I take this opportunity to congratulate you on this excellent framework and we will continue testing Quasar v2.

Greetings!

**Comment by rstoenescu** [comment]
Glad you figured what the problem was! Cheers for the nice words.
