### ISSUE TITLE
dynamic imports router

### ISSUE THREAD

**Issue by 972784674t** [quasarframework/quasar#8649]
I get my route (json format) from the server. 
```js
export function handleJsonRouterToAsyncRouter (jsonRouter, t) {
  t = jsonRouter.map(item => {
    if (item.component === 'Layout') {
      item.component = _layout
    } else {
      // Lazy loading of components
      item.component = handleComponent(item.component)  // item.component : "pages/home/home.vue"
    }
    return item
  })
  for (const item of t) {
    if (item.children) {
      item.children = handleJsonRouterToAsyncRouter(item.children)
    }
  }
  return t
}

function handleComponent (component) {
  return () => import('src/' + component)   // component : "pages/home/home.vue"
}
```

When I use dynamic import, it can be compiled and used normally, but the warning in the picture keeps appearing. How to eliminate the warning

![在这里插入图片描述](https://img-blog.csdnimg.cn/20210320153603235.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxOTEyMzk4,size_16,color_FFFFFF,t_70#pic_center)

**Comment by 972784674t** [comment]
if i use
```js
function handleComponent (component) {
  return () => import('src' + component)
}
```
The warning will be eliminated, but the dynamic import cannot be performed normally

![在这里插入图片描述](https://img-blog.csdnimg.cn/20210320154241229.png#pic_center)

**Comment by rstoenescu** [comment]
Hi,

Doing an `import('src/' + someVar)` is very inefficient and forces Webpack to create a chunk for ALL your files in the "/src" folder. Be as specific as possible in your import statement. A better way: `import('src/pages/' + page + '.vue')` so that Webpack can limit the number of files that match.

The full explanation of how Webpack works: https://next.quasar.dev/quasar-cli/lazy-loading#caveat-for-dynamic-imports
