### ISSUE TITLE
Typescript ssrContext & store bootParams untyped

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#8794]
**Describe the bug**
When using `import { boot } from "quasar/wrappers";` to export a function in a boot file the `ssrContext` and `store` parameters are untyped.

**To Reproduce**
Create new project from the latest starter. Select TS as option and also vue-i18n. When finished go to the i18n.ts boot file and add either `store` or `ssrContext` in the object parameter of the `boot` function. 

**Expected behavior**
Type should be inferred correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/5757159/113720012-81dc1880-96ee-11eb-8cd3-d208c5c17c00.png)

**Comment by Evertvdw** [comment]
I figured out why this happens, the default starter has no `store-flag.d.ts` when you did not run the project yet. Same goes for the `ssr-flag.d.ts` which is only added when you add SSR mode. I guess the store flag should be added immediatly when you select Vuex in the starter options to avoid confusion. As for the ssrContext, maybe a comment above the `boot` function in the typings can clarify, so that atleast when you hover over boot you can see some text explaining that typings for this function depend on SSR being active in your project.

**Comment by IlCallo** [comment]
Yeah, TS flags are created either when adding the "mode" or when building the project.
We chose this way to enforce their generation to automatically migrate older codebases.
Store is a special case as it's half a mode and half a thing on its own.
We didn't want to duplicate the flags files between the main repo and the starter kit one (which is on another repo entirely) so we settled on this compromise.
Let apart some sporadic questions, this doesn't seem to have caused much problems in the past year, so I'm a bit reluctant to change the behaviour and duplicate the store flag.

Do you have any other ideas which could solve the problem without causing duplication? The project generation is managed by the global CLI and the starter kit, while the flag autogeneration is managed by the app package, so launching it at the end of project generation isn't straighforward either.

---

The lack of `ssrContext` instead is intentional: it forces you to search why it's missing, instead of trying to use it without adding SSR mode. We could add a TSDoc on the wrapper, but it may easily fall out of sync.
Maybe we could add a note on the docs? Do you want to try adding one where you feel it would have helped you the most?

**Comment by Evertvdw** [comment]
I would have liked something like this: 
![image](https://user-images.githubusercontent.com/5757159/114018765-e376c100-986d-11eb-987f-f0ac273fab55.png)

**Comment by IlCallo** [comment]
`Some arguments are available only if you enable the related mode: `store` when using the Store, `ssrContext` when using SSR, etc`

May be good?

**Comment by Evertvdw** [comment]
Yes exactly 👍

**Comment by IlCallo** [comment]
Added https://github.com/quasarframework/quasar/commit/8ea7ad32011ed2b4ff6c0b0fff1705c5bbf3acaf
