### ISSUE TITLE
QSearch not emitting event when cleared

### ISSUE THREAD

**Issue by d-levin** [quasarframework/quasar#895]
No event is emitted when a QSelect field is cleared.

A common use case is to enter a search term, dispatch an API call to get results, then clear the search term and dispatch another API call that fetches non-filtered results.

Currently there is no way to get back to the unfiltered stage.

### Software version

Quasar: 0.14.3

### What did you get as the error?
Clearing QSelect does not emit a change event

### What were you expecting?
Clearing QSelect should emit a change event

### What steps did you take, to get the error?
Enter value into QSearch field
Clear the value

**Comment by rstoenescu** [comment]
Just tested it. The `@change` event is successfully emitted.
* Typed something - event emitted.
* Then erased the input - event emitted
* Type something again, hit the "clear" button - event emitted.

```vue
<template>
  <div>
     <q-search v-model="model" @change="onChange" />
  </div>
</template>

<script>
export default {
  data () {
    return {
      model: ''
    }
  },
  methods: {
    onChange (v) {
      console.log('v ->', v)
    }
}
```

The description is confusing. Are you having trouble with QSearch or QSelect? Because you mix them both as if only component is at fault.

If you are using QSelect, are you sure you are using the `@change` event? Please reopen if you are certain there is something wrong. Thanks!

**Comment by d-levin** [comment]
Not sure why I said QSelect, I meant QSearch 😄 

I figured out the issue. This does not emit a change event when the field is cleared:
```
<q-search
          :debounce="500"
          :value="searchTerm"
          @change="emitSearch"
          :placeholder="$t('searchBy')"
        ></q-search>
```

However, using v-model instead of :value does.
```
<q-search
          :debounce="500"
          v-model="searchTerm"
          @change="emitSearch"
          :placeholder="$t('searchBy')"
        ></q-search>
```
