### ISSUE TITLE
q-row, q-col as an alternative to <div class="row", <div class="col"

### ISSUE THREAD

**Issue by vanillamasonry** [quasarframework/quasar#9087]
**Is your feature request related to a problem? Please describe.**
It is not always clear when you read the code if you have a col or a row or a simple div

**Describe the solution you'd like**
Introduction of q-row and q-col as an alternative in Qv1 and Qv2  - this will make the code far more explicit

Thank you very much,
Paul

**Comment by rstoenescu** [comment]
Hi,

It might sound like a good idea, but this adds unnecessary runtime overhead and opens up a Pandora's box for unexperienced developers -- from a maintainer perspective (and experience), any downfall of flexbox will result in Github tickets opened. Both us and the developers using Quasar will get frustrated and lose a lot of time with the tickets going back and forth. Furthermore, in order to support all the flexbox features this would mean creating a massive number of properties for each of the two components -- this will also result in a bump in Quasar's js footprint (KB-wise) while the benefits are really not that great imho.

But there is hope if you really want this. You can create your own components which mainly wrap the "row" and "col" CSS class and then use them.
