### ISSUE TITLE
Use sideEffects flag in package.json to enable tree shaking in other bundlers

### ISSUE THREAD

**Issue by Trinovantes** [quasarframework/quasar#9157]
**Is your feature request related to a problem? Please describe.**

Right now quasar relies on its CLI to perform tree shaking on unused components (from a custom webpack hook?). Other bundlers (vite, esbuild, snowpack etc.) have to load everything from the compiled bundle `dist/quasar.esm.prod.js` which results in larger bundles than necessary.

![before2](https://user-images.githubusercontent.com/458691/116960530-a46e3c80-ac6e-11eb-848b-282aac218e54.png)

**Describe the solution you'd like**
1. Use the `sideEffects: false` flag (or `sideEffects: [files that do have side effects]`) in the distributed `package.json`
2. Export another `Quasar` object in `src/index.all.js` that does not reference `components`:
```
export const QuasarBasic = {
  version: __QUASAR_VERSION__,
  install (app, opts, ssrContext) {
    installQuasar(
      app,
      { ...opts }, // No reference to components and directives
      ssrContext
    )
  },
  lang,
  iconSet
}
```

3. Advanced users will need to alias `quasar` to `quasar/src/index.all` and add the necessary build configs:
```
resolve: {
        alias: {
            quasar: 'quasar/src/index.all',
        }
},
plugins: [
    new DefinePlugin({
        __QUASAR_VERSION__: JSON.stringify('Custom v2'),
        __QUASAR_SSR__: JSON.stringify(false),
        __QUASAR_SSR_CLIENT__: JSON.stringify(false),
        __QUASAR_SSR_SERVER__: JSON.stringify(false),
        __QUASAR_SSR_PWA__: JSON.stringify(false),
    }),
]
```

Doing this results in noticeably smaller bundles for me

Before:
![before](https://user-images.githubusercontent.com/458691/116959866-df6f7080-ac6c-11eb-9c59-c16a043caa5e.png)

After:
![after](https://user-images.githubusercontent.com/458691/116959864-df6f7080-ac6c-11eb-9c11-8e81c9c6f384.png)

**Alternative to step 3:**
Instead of requiring users to set up a custom build config, separate `dist/quasar.esm.prod.js` into their original modules so that tree shaking can be performed.

**Comment by stalniy** [comment]
Also an issue for me! Do you need some help with this issue?

**Comment by bompus** [comment]
I'm also seeing this with vite. I'm hoping this can be addressed while the team is working on vite support ( #10398 ), or that the official vite support added will automatically take care of this.

**Comment by hspaay** [comment]
I'm running into this as well using Vite. 
For some reason "quasar.esm.prod.js" is included in the bundle when using dialog composable with useDialogPluginComponent in the dialog. This adds about 450K to the bundle. Without it, tree shaking work fine.

**Comment by ParsonsProjects** [comment]
I have not fully tested this solution but I have found a way of tree shaking quasar when using Vue CLI. In fact this should work with any setup not just Vue CLI.

### Step 1
Where you are currently importing the quasar library, likely to be in your main.js or ts file. The below line:
`export { Quasar } from 'quasar';`
Can be replaced with:
`export { Quasar } from 'quasar/src/index.all';`

### Step 2 (if you are using typescript)
Add a new decleration file at the root of the project `src/shims-quasar.d.ts` and add the below into the file.
`declare module 'quasar/src/index.all'`

### Step 3
This is a bit more of a hacky approach, go into the quasar file you are now pointed at 
`node_modules/quasar/src/index.all`
Inside this file replace everything with the below:
```
import installQuasar from './install-quasar.js'
import lang from './lang.js'
import iconSet from './icon-set.js'

export const Quasar = {
  version: __QUASAR_VERSION__,
  install (app, opts, ssrContext) {
    installQuasar(
      app,
      { ...opts },
      ssrContext
    )
  },
  lang,
  iconSet
}
```

### Step 4
In order to make sure these changes are applied whenever a fresh installation is made, you will need to use the npm library [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by rstoenescu** [comment]
This is a non-issue.

For Quasar CLI -> nothing to be done. Works out of the box.
For Vue CLI -> use "vue-cli-plugin-quasar" https://quasar.dev/start/vue-cli-plugin
For Vite -> use "@quasar/vite-plugin" https://quasar.dev/start/vite-plugin

**Comment by ParsonsProjects** [comment]
@rstoenescu The Vue CLI plugin does not tree shake quasar and you end up with the bundled file all 500kb in the build output. Unless I am missing something?!

**Comment by stefanvanherwijnen** [comment]
I've spent a few hours looking into this.

By default, Rollup does not tree shake modules. However, @rollup/plugin-node-resolve looks for the `sideEffects` property in package.json and applies `moduleSideEffects: false` to the resolved module.
The problem here is that when building from src (e.g. for SSR support), the easiest workaround is to alias the package to `src/index.all.js` folder and in that case node-resolve is skipped, thus no tree shaking. Also, all components are imported that way.
The only solution for this at the moment, in my knowledge, is a Vite plugin similar to:

```js
    {
      name: 'quasar-virtual-modules',
      enforce: 'post',
      config: async (config, env) => ({
        resolve: {
          alias: [
            { find: new RegExp('^quasar$'), replacement: 'virtual:quasar' },
          ]
        }
      }),
      resolveId (id) {
        switch (id) {
          case 'virtual:quasar-plugins':
            return 'virtual:quasar-plugins'
          case 'virtual:quasar':
            return { id: 'virtual:quasar', moduleSideEffects: false }
          default:
            return;
        }
      },
      load (id) {
        if (id === 'virtual:quasar-plugins') {
          // const plugins = ['Dialog'] // import from quasar.conf
          return `export { ${plugins.join(',')} } from 'quasar'`
        } else if (id === 'virtual:quasar') {
          return `export * from 'quasar/src/plugins.js';
          export * from 'quasar/src/components.js';
          export * from 'quasar/src/composables.js';
          export * from 'quasar/src/directives.js';
          export { default as Quasar } from 'quasar/src/vue-plugin.js'`
        }
        return null
      }
    }
```

The only other way to support all builds (SSR and PWA) is if Quasar would distribute separate bundles for each mode or find a way to create an universal bundle without the __QUASAR__ constants (https://github.com/quasarframework/quasar/blob/e05ac28ea9b235b95b2376e8396ab5c5060d778b/ui/src/plugins/Platform.js#L6-L12).
A different option is to explicitely import from `src` (e.g. `import QBtn from 'quasar/src/components/btn/QBtn.js'`), but for example unplugin-vue-components does not work like this.

For a better ESM experience, it would be nice to have a `index.js` file in the src folder similar to the virtual module and `sideEffects: false` in package.json.

https://github.com/antfu/unplugin-vue-components/issues/332

**Comment by rstoenescu** [comment]
Hi,

Like I said, this is a non-issue. Tree-shaking is handled automatically, unless you are doing something that we don't officially support anyway (like totally custom build system etc).

If using Quasar CLI, our Vite plugin or our Vue CLI plugin and it does not works, please post a repo with minimal reproduction, or directly attach a .zip file here.

Can't change to sideEffects because it will break most people's setups.

**Comment by stefanvanherwijnen** [comment]
Thanks Razvan,

It would be nice to have better support for e.g. unplugin-vue-components, but if that breaks existing setups that's obviously a no-go.
Maybe it can be added to the road map for a a future version.

The vite plugin has its limitations at the moment (no SSR)  so unfortunately that's not a solution for everyone that wants to use their own vite configuration. (which understandingly has a lower priority than official supported methods such as the CLI).  I'm working on a solution but it requires some workarounds such as in the previous post.
