### ISSUE TITLE
Plugin Notify, on debug not showing other components

### ISSUE THREAD

**Issue by franfrLor** [quasarframework/quasar#9176]
Chen I had Notify plugin I no longer see the components of my application, how can I solve this problem?

![Notify](https://user-images.githubusercontent.com/64161955/117132846-b3a2d680-ada3-11eb-9494-638ce186da7e.jpg)

**Comment by hawkeye64** [comment]
@franfrLor There are several components that use a Quasar Portal (dialog, QMenu, QTooltip, etc), that are outside the Vue container, but inside the body tag. These won't show up when you expect them in Vue Dev Tools because they are outside of the "mounted" element. But, you can see them on the browser dev tools "Elements" tab, down by the bottom of the </body> closing tag.

**Comment by rstoenescu** [comment]
If something doesn't shows up it's a vue-devtools bug.

**Comment by hawkeye64** [comment]
@rstoenescu The new one doesn't show Quasar portal components. It's still in beta, so I presume to give it time.

**Comment by rstoenescu** [comment]
The OP refers to the app components.

**Comment by pdanpdan** [comment]
The vue debugger for cure has a selector for the app.
Use it to select one of the root apps.
