### ISSUE TITLE
No 'quasar create' page

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar#9198]
I tried to use the framework after a while that I was not using it. I wanted to know how to start a new project. Browsed to https://quasar.dev/, pressed 'Quasar V2 Beta', and wanted to see a simple 'Getting Started' page with an instruction that will instruct me to run `quasar create`. Instead I am led into the Upgrade Guide. I think it would be better if it would go to Getting Started.
Anyway, I opened the collapsible Getting Started section in the side bar. Mind you I was looking for a simple `quasar create` directive. Instead I only see 'Pick Quasar Flavour' sub-section. As a simple user, I really don't care to read about different flavors. I just want to be up and running in the shortest time possible. I don't really care about all options possible in using Quasar.

I think users should be pointed to a page that will instruct them to use two commands:

```
$ npm install -g @quasar/cli
$ quasar create
```
That's it. These lines should even show on the front page of https://quasar.dev/.

I find the website to be over-informative and very hard to reason about, and to not welcoming for new users. I think my suggestion above would help new audiences to use and enjoy the framework.

**Comment by yusufkandemir** [comment]
Hi @tomers! Thanks for the suggestions. Your first point is solved because we passed the "initial migration phase", now there is a `Get Started` button on the landing page that directs users to the related page. About the other points, we agree with this, and have plans for a website revamp that covers this and more stuff. There are no details about it here, but please see it on our roadmap:
https://github.com/quasarframework/quasar/blob/dev/ROADMAP.md#q4-2021
