### ISSUE TITLE
Allow SASS `@use` and `@forward` rules 

### ISSUE THREAD

**Issue by tomukasas** [quasarframework/quasar#9202]
**Is your feature request related to a problem? Please describe.**
Background: [sass is gradually going to phase out `@import` rule](https://sass-lang.com/documentation/at-rules/import)

Giving the above, I am trying to use sass `@use` and `@forward` rules, but don't have much luck. Stuck with an error:

`SassError: @use rules must be written before any other rules.`

The error is always on a line 2, which got me digging into more details. It seems that quasar is adding `@import` rule [here](https://github.com/quasarframework/quasar/blob/dev/app/lib/webpack/loader.quasar-sass-variables.js) which causes a problem. 

**Describe the solution you'd like**
Ideally the hardcoded `@import` rules in the `loader.quasar-sass-variables.js` should be added as variables.

**Describe alternatives you've considered**
I did try to use `chainWebpack` inside `quasar.conf.js` which didn't help either:

`chainWebpack (chain) {
      chain.module.rule('quasar-sass-variables-loader')
        .test(/\.sass$/)
        .use('sass-loader')
        .loader('./src/webpack/loader.sass-variables.js');
    }`

**Additional context**
![snip](https://user-images.githubusercontent.com/8329500/117540852-12b55500-b009-11eb-813f-d39783372dcf.png)

**Comment by rstoenescu** [comment]
Will be available through "@quasar/app" v3.0.0-rc.1 (for Quasar UI v2).

We cannot upgrade the dart-sass module due to #9362 -- solving it would require multiple things that eventually would lead to breaking changes in the usage. This behavior change in Sass is really depressing. It requires us to use `@use 'sass:math'` in Quasar's CSS which in turn means changing the Quasar's css build system. That wouldn't be so bad, but then it means also changing how Quasar's sass file is imported (to take into account for /src/css/quasar.variables.{sass|scss}) then how the auto-import of these variables (and Quasar's) works in every SFV with style lang="sass". The `@use` syntax in Sass is extremely limiting and it's like a snowflake eventually causing an avalanche of needed breaking changes.

For those using vue-cli-plugin-quasar -> please stay with "sass" v1.32.12. Do not upgrade further. It is what it is due to Sass changing things on the fly in the same major release (v1).
