### ISSUE TITLE
QChat component should support #label slot, #name slot, #stamp slot and #arrow slot

### ISSUE THREAD

**Issue by lyle45** [quasarframework/quasar#9243]
**Is your feature request related to a problem? Please describe.**
QChat component should support #label slot, #name slot, #stamp slot and #arrow slot

self explanatory :)

With arrow slot I mean the small arrow that points to the avatar. Might be a bit tricky to slot it since one might perfer it from the top or middle, maybe slot the entire space between message and avatar user can put what he wants there

**Comment by rstoenescu** [comment]
New slots ("name" and "stamp") will be available in Quasar v1.15.14 and Quasar v2.0.0-beta.16
Don't know what you are referring to when you say the "label" slot. Also, the arrow is displayed through CSS, so no slot for it.

**Comment by lyle45** [comment]
@rstoenescu 
thats great,

re label, in QChat component you have a label prop with specific behavior. i mean a slot for that (centralized text with specific margins)

re arrow makes sense, maybe there could be some customizable props like arrow-location: 'bottom' | 'top' | 'middle' | 'none'? (might actually be avatar-location with arrow following)

2 more suggestions I have for the chat component

max-size - self explanatory
selected boolean prop - for selection overlay look (similar to whatsapp) and possibly a @selection event triggered by long tap/double click event

**Comment by rstoenescu** [comment]
Added "label" slot. Available in Quasar v1.15.15 and Quasar v2.0.0-beta.17.

Not adding max-size or arrow props or because these can be achieved easily through CSS. The "selected" feature can easily be achieved through [TouchHold](https://quasar.dev/vue-directives/touch-hold).

We're not going to add redundant props or props for every possible CSS thing that you can do, as long as there's an easy CSS customization alternative. Not only we'd end up with 500+ props components (imagine searching or inspecting a component's API card in this scenario!), but performance and memory consumption would be hell. There's also the framework's footprint (KB-wise) to bear in mind (even if tree-shaking is active).

In any case, thank you for this ticket!

**Comment by lyle45** [comment]
Great thanks man really appreciated, understand considerations re css props, that's all on my suggestions list
except maybe  surrounding component to QChatMessage called QChatList with built in behavior for scroll behavior for list (InfiniteScroll with reverse + scrollToBottom for item change if already scrolled to bottom etc) general chat features usually required with chat message. just a suggestion :)
