### ISSUE TITLE
When load quasar in the html header, it shows: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by fisher030712** [quasarframework/quasar#9386]
When I load quasar.js in the html header,  it shows: Cannot read property 'appendChild' of null.

I have to load quasar.js at the bottom of body.

**Comment by rstoenescu** [comment]
Hi,

Yes, it needs to be in the body after the target upon which the app is mounted. Having script tags in the body near its end is also a best practice in web development. We won't change this behavior, and not only because of this, but also because adding support in the header would introduce a small overhead that 95% of devs using Quasar would not benefit from at all.
