### ISSUE TITLE
Typescript files cannot resolve as '.js'

### ISSUE THREAD

**Issue by josh-hemphill** [quasarframework/quasar#9464]
**Describe the bug**
In typescript proper, you can opt into always using file extensions (which is enforced by `eslint/import`) but since typescript doesn't let you have '.ts' in your import statements, quasar's pre-resolving results in IDE linting/syntax errors if you use `.ts` or extensionless and can't resolve at all if you use `.js` as typescript suggests.

**To Reproduce**
1. Use some `.ts` files like router
2. Add `eslint/import` plugin
3. Try importing with `.js` extension as the typescript syntax error hint suggests
4. See error `Module not found: Can't resolve imported dependency "./routes.js"`

**Expected behavior**
To resolve the same way as typescript or provide a way around getting syntax errors.

**Additional context**

Typescript's handling of file extensions is kind of awful, so I'd certainly be happy with Quasar getting it's own LSP that just proxies to the typescript LSP except for differentiating syntax, letting us have imports with proper extensions.

**Comment by yusufkandemir** [comment]
> In typescript proper, you can opt into always using file extensions **(which is enforced by `eslint/import`)**

It doesn't enforce such rule unless you specifically enable the rule by adding the code below to your rules:
```js
'import/extensions': [
  'error',
  'ignorePackages' // or 'all' which wouldn't make any sense because it even breaks importing from `quasar/wrappers` for example
]
```

After this point, you will start getting `Missing file extension "ts" for 'src/router/routes' eslint(import/extensions)` errors, and when you try to add `.ts` extension you would get the `try xyz.js instead` message, to overcome the error telling you to add .ts extension, you can just disable the rule for .ts files specifically for ts files like this:
```js
'import/extensions': ['error', 'ignorePackages', { ts: 'never' }]
```
Note: This rule comes completely disabled by default in `standard` and `airbnb` rule sets which are offered by Quasar Starter Kit.

So, I think your reproduction steps are not sufficient and detailed, we are probably doing different things because of the uncertainty(_e.g. `Add eslint/import plugin` is really vague_). Besides, I don't see much point in trying to achieve this while you can disable the rule for the `.ts` extension, because this way you can still get protected by this rule for other file extensions while overcoming the fact that the Typescript team doesn't implement correctly handling of importing with the `.ts` extension. Unless you have a really really good point for trying to achieve the thing you have mentioned, I don't think we can do more.
