### ISSUE TITLE
layout height wrong

### ISSUE THREAD

**Issue by chuoke** [quasarframework/quasar#9469]
**Describe the bug**
When there is no header, the page will overflow about 5px up the visual range.

**Codepen**
https://codepen.io/chuoke/pen/dyvVQRR?editors=101

**To Reproduce**
see the codepen example

**Expected behavior**
Do not overflow and display normally

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.19
@quasar/app Version:
Quasar mode:
  - [*] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by MilosPaunovic** [comment]
Hello @chuoke,

After checking out your [codepen example](https://codepen.io/chuoke/pen/dyvVQRR?editors=101), it seems that the issue is caused by `q-gutter-sm` class added to first child of `q-page` element.

My suggestion is to re-evaluate if the class in question is needed on that particular place.

Hope this helps a little bit 😄

**Comment by hawkeye64** [comment]
@chuoke As @MilosPaunovic mentioned, it's because of the `q-gutter-sm` which adds negative positioning.
here is the fixed pen: https://codepen.io/Hawkeye64/pen/xxqPPLV?editors=101

**Comment by chuoke** [comment]
Thanks
