### ISSUE TITLE
QImg with native-context-menu interferes with swipe (no way to put draggable="false" on native img tag)

### ISSUE THREAD

**Issue by lyle45** [quasarframework/quasar#9495]
**Describe the bug**
QImg with native-context-menu interferes with swipe (no way to put draggable="false" or any native attrs on native img tag)

Possibly bug is unknown props are not propagated to native element

**Codepen/jsFiddle/Codesandbox (required)**
self explanatory

**To Reproduce**
self explanatory

**Expected behavior**
Unknown props should propagate to native element
maybe native-context-menu should be renamed to use-native-element or something, was a bitch to debug 

**Platform (please complete the following information):**
Quasar Version: 1 & 2
@quasar/app Version: 1.15.19
Quasar mode:
  - [ X] SPA
  - [ ] SSR
  - [X ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X ] SPA
  - [ ] SSR
  - [X ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

**Comment by rstoenescu** [comment]
Makes sense. Starting with Quasar v2.0.0-rc.1 all attributes (non-props) will passthrough to the native image. But for draggable in particular, it makes even more sense to add it as a Boolean prop so that the default value can be "false".

**Comment by rstoenescu** [comment]
A few more things related to Quasar v2. I wanted to rewrite this component in a much more efficient way for a long time but it simply wasn't possible due to IE11 support. However, Vue 3 (which is the base for Quasar v2) dropped support for IE11 so I could finally do it, so it works in a completely different (and better) way, with `<img>` tags regardless of props.

Unfortunately, for Quasar v1, there's nothing that I can do without introducing breaking changes and affecting performance.

**Comment by lyle45** [comment]
@rstoenescu Thanks man you're great, sorry about version mixup
