### ISSUE TITLE
QTabPannels swipeable failed when animated = false

### ISSUE THREAD

**Issue by 1508816494** [quasarframework/quasar#9537]
**Describe the bug**
QTabPannels swipe failed when swipeable = true && animated = false，I need to swipe twice to take effect in browser of iPhone, while android and Macbook is success. During debug, I found  function of getTouchTarget() in utils/touch.js return document when ios get touch target, I changed it to target and it was success. I hope to know how do you considered this part of logic for iOS, and please fix the bug of swipe failed or provide solution.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/1508816494/pen/zYZWOod

**To Reproduce**
1. first swipe is success, while second is failed, and swipe twice can take effect 

**Expected behavior**

**Platform (please complete the following information):**
Quasar Version: 1.15.14

**Comment by rstoenescu** [comment]
Hi, a few things:

1. The `animated` prop is Boolean, so its default value is "false". Specifying `:animated="false"` is redundant.
2. The getTouchTarget() was working around an old bug in Safari (more details: #5532). Which seems to have been fixed by Apple. So indeed, removing this is the way to go.

Will be available in Quasar v2.0.0-rc.1 and v1.15.19
