### ISSUE TITLE
Upgrade guide v2 Video BUGS

### ISSUE THREAD

**Issue by andrey-hilux** [quasarframework/quasar#9705]
Recently my friends have difficulties with these upgrades, and I'm even had to make this video to help them, it hard to explain in few words! And I hope this ["BUGS Upgrade Guide Quasar V2 to V3"](https://andrey-hilux.github.io/video/docs/bugs-upgrade-guide-quasar-v-2-to-v-3.html#git-hub-video-player-1) helps you too!

**Comment by rstoenescu** [comment]
Hi,

Thanks for creating a video and helping devs upgrade. I have a few comments though:

1. The title is misleading. It is saying "Quasar v2 to v3". There is only Quasar v1 (with Vue 2) and Quasar v2 (with Vue 3). You are actually talking about the "@quasar/app" package (the Quasar App CLI), which is v2 for Quasar v1 and v3 for Quasar v2.
2. The vue-loader templateLoader.js error should be reported to https://github.com/vuejs/vue-loader (mentioning vue-loader v16.2.0). It is not a Quasar issue and outside of our reach. As a general rule of thumb, it's best to report issues to the owners of the respective packages rather than trying to workaround them.
3. Regarding quasar.conf.js/framework/cssAddon: we don't see any issues with it. There is no need for a workaround? Especially that the suggested changes are setting up your auditory for failure in the long run. Why lazy loading directly from Quasar's src files when the Quasar App CLI does this anyway. Also not quite ok to specify a "js" file instead of a stylesheet file for quasar.conf/css.
