### ISSUE TITLE
SSR async components $q.screen reactivity

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#9711]
**Describe the bug**
When using SSR and some conditional class based on `$q.screen.something` in an async component this conditional class is not updated. 

Example component:
```vue
<template>
        <q-input outlined bg-color="red" label="test" :class="$q.screen.gt.xs ? '' : 'fit'"/>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  created() {
    console.log(this.$q.screen.gt.xs);
  },
  mounted() {
    console.log(this.$q.screen.gt.xs);
  },
})
</script>

```
Upon initial load this input field will still have the `fit` class applied to it until you interact with the input.

**Codepen/jsFiddle/Codesandbox (required)**
There is no Codesandbox available yet for SSR in Quasar v2.

**To Reproduce**
1. Create new quasarv2 project
2. Add the a component `AsyncComp.vue` to the components file with the content above.
3. Add `AsyncComp: defineAsyncComponent(() => import('src/components/AsyncComp.vue'))` to `Index.vue`'s components declaration. Also add `import {defineAsyncComponent} from 'vue'` to this file.
4. Add the `<async-comp/>` somewhere in the html.
4. Run with SSR mode `quasar dev -m ssr`
5. F5 on the index page and see.

**Expected behavior**
Upon hydration the `$q.screen.something` should be reactive and the conditional class updated. At the mounted() hook this property already has the correct value, I don't know why it won't update.

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: v2.0.0-rc.3
@quasar/app Version: v3.0.0-rc.3
Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by Evertvdw** [comment]
Any comment on this issue? This used to work in QuasarV1 so it should also work in V2.

**Comment by hawkeye64** [comment]
@Evertvdw I would suggest putting your `$q.screen` test in a computed and return the proper class. Then use that in your html. There could be an issue with reactivity and inline code like the way you have it.

**Comment by rstoenescu** [comment]
Is this still happening for you while using latest Quasar (v2.2.0)?

**Comment by Evertvdw** [comment]
@rstoenescu Yes, I just created a new starter project and followed the reproduction steps and it still does not work correctly. It has the `fit` class still applied when hydration is done even though the console.log of `$q.screen.gt.xs` is true on both the `created` and `mounted` hook client side. Once you click on the q-input the class is removed.

**Comment by Evertvdw** [comment]
I checked to see if this issue still persists, I can still reproduce it. Here is a reproduction example: 
https://codesandbox.io/s/async-surf-ftpfs?file=/src/components/AsyncComp.vue

To reproduce:
1. Make sure the browser window in the sandbox is above the `xs` breakpoint
2. Refresh the page, the red input field now has full width (has 'fit' class applied)
3. Click inside the input field, the input field will now shrink ('fit' class removed)
4. Notice in the console that the value of `$q.screen.gt.xs` is correct on `created` and on `mounted` client side but the dynamic classes are not updated correctly

**Comment by JeRabix** [comment]
In quasar v 2.7.5
I always have the same console.log() in SSR mode, regardless of the device
xs: true
width: 0
height: 0

Is this how it should be? q.screen doesn't work in SSR or is it a bug?
![image](https://user-images.githubusercontent.com/46298617/177567510-d80a483b-0f25-42d9-9c22-4cfd07e8ba71.png)
![image](https://user-images.githubusercontent.com/46298617/177567539-6462abf8-73b8-41eb-8e2b-13ac5faed895.png)

**Comment by pdanpdan** [comment]
It is run in the create phase, so on the server you'll get always the same thing

**Comment by JeRabix** [comment]
> It is run in the create phase, so on the server you'll get always the same thing

Can I somehow get the width/height of the device on the server side?

**Comment by pdanpdan** [comment]
Never on first request/response cycle
When all the planets align, something might work:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Viewport-Width
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Width
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH

So as a short answer: no

**Comment by JeRabix** [comment]
> Never on first request/response cycle When all the planets align, something might work:
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Viewport-Width https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Width https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH
> 
> So as a short answer: no

Thanks!

**Comment by juliendu11** [comment]
Same problem on my side, in ssr mode with components loaded with `defineAsyncComponent` the $q.screen does not work, by removing `defineAsyncComponent` it works.

I specify that I am on quasar v3.3.3 I do not know if this problem has been resolved with the updates

Example code where I have the problem:

```vue
<div class="row q-col-gutter-sm" :class="{'q-col-gutter-y-md': !$q.screen.gt.sm}">
```

`q-col-gutter-y-md` is not injected if component loaded with `defineAsyncComponent`

Another example, here I load a layout component dynamically which will wrap the component rendered by the route

```vue
<template>
  <component :is="getComponent">
    <router-view v-slot="{ Component }">
      <keep-alive :include="cachedViews" :max="2">
        <component :is="Component"/>
      </keep-alive>
    </router-view>
  </component>
</template>

<script>
export default {
  components: {
    MainLayout: defineAsyncComponent(() =>
      import('src/layouts/MainLayout.vue')),
    AuthLayout: defineAsyncComponent(() =>
      import('src/layouts/AuthLayout.vue')),
  },
  computed: {
    getComponent() {
      if (this.$route.meta.layout === 'auth-layout') {
        return 'AuthLayout';
      }

      return 'MainLayout';
    },
  },
}
</script>
```

The $q.screen works for all views rendered by the router if I remove the `defineAsyncComponent` from the layouts

```vue
<template>
  <component :is="getComponent">
    <router-view v-slot="{ Component }">
      <keep-alive :include="cachedViews" :max="2">
        <component :is="Component"/>
      </keep-alive>
    </router-view>
  </component>
</template>

<script>
import MainLayout from 'layouts/MainLayout.vue';
import AuthLayout from 'layouts/AuthLayout.vue';

export default {
  components: {
    MainLayout,
    AuthLayout,
  },
  computed: {
    getComponent() {
      if (this.$route.meta.layout === 'auth-layout') {
        return 'AuthLayout';
      }

      return 'MainLayout';
    },
  },
}
</script>
```

**Comment by rstoenescu** [comment]
Hi,

1. $q.screen cannot be inferred on server-side because there is no information that we can use to know the window size where the content will get rendered. No HTTP header, nothing (security reasons included). We'd wish there was a way, but it isn't and don't think there ever will be.

So, $q.screen starts from a default value which doesn't change on server-side (obviously) and then the client-side starts from the same default value and when hydration ends it accesses the browser API to update to the correct value.

Now, this ticket issue occurs because Vue handles defineAsyncComponent() differently on server-side and on client-side:
* Server-side: it renders the component in one go.. it has to
* Client-side: it gets the rendered output from the server-side then it runs the same code which sees the async components so it waits for the import to complete. But while the wait occurs, the client has already passed the hydration step (which waits for the root component to get mounted) and, by the time it renders the async component, it's already in the "hydrated" state (so $q.screen has been updated to the correct value), so the content will NOT match what the server has supplied, essentially producing a hydration error.

The conclusion is that we cannot account for the way that Vue itself handles defineAsyncComponent(). One solution would be to not use the async loading of components. The second solution would be to tap into Quasar's post-hydration state and manually trigger it ([for q/app-vite](https://quasar.dev/quasar-cli-vite/developing-ssr/configuring-ssr#manually-triggering-post-hydration) | [for q/app-webpack](https://quasar.dev/quasar-cli-webpack/developing-ssr/configuring-ssr#manually-triggering-post-hydration))... but when you have multiple async components you'd need to ensure that all have been imported and mounted (or like in the case above, trigger it when Index.vue component got mounted). In any case, you can get the gist of it.
