### ISSUE TITLE
QImage has big height during loading

### ISSUE THREAD

**Issue by DiaaEddin** [quasarframework/quasar#9716]
**Describe the bug**
default QImg height is very big compared to its width during loading and it strangely maintains the same ratio. this was not the default behavior  in the previous versions 

**Codepen/jsFiddle/Codesandbox (required)**
[https://codepen.io/DiaaEddin/pen/RwpdBLW?editors=101](https://codepen.io/DiaaEddin/pen/RwpdBLW?editors=101)

**Comment by rstoenescu** [comment]
Hi,

The QImg in Qv1 works very differently from Qv2, the latter taking full advantage of newer browser APIs. One of the downsides, if you can call it that, is that when using lazy-loading (default behavior) it needs an initial size otherwise the loading is not triggered. So, QImg needs an initial ratio. It is set to 1/2 (so height = 2x width) but indeed it would be better if this value would be 16/9. The main point is that an initial ratio is needed (unless width and height props are set).

Having said this, adding a new prop (`initial-ratio`) with the default value of `16/9`.
Will be available in Quasar v2.0.0 stable
