### ISSUE TITLE
Pull to refresh position

### ISSUE THREAD

**Issue by reitbauer** [quasarframework/quasar#9751]
After disable and enable the pull-to-refresh component, the icon appears on the left top corner and not in the middle of the top

**Comment by khirvy019** [comment]
I have this same problem, in my case the cause was with not having `width: ##px` in the div with `q-pull-to-refresh__puller-container` class.

I think it's unable to get width value from this line:
https://github.com/quasarframework/quasar/blob/dev/ui/src/components/pull-to-refresh/QPullToRefresh.js#L93
