### ISSUE TITLE
Cannot use import in actions.js

### ISSUE THREAD

**Issue by bangdragon** [quasarframework/quasar#9813]
In the file store/auth/actions.js I try 
import { getAuth, signOut } from "firebase/auth";
but not work.
How to use getAuth and signOut in actions.js
Thanks

**Comment by hawkeye64** [comment]
@bangdragon Please provide more info
Quasar v1 or v2?

If Quasar v1, then 
```js
<script>
import { mapActions } from 'vuex'
.
.
.
methods: {
  ...mapActions('auth', [
    'getAuth,
    'signOut'
  ])
}
```
Now you can access via `this.getAuth` and `this.signOut`

If you are using Quasar v2, then you will need to go look at Vuex docs and see what has changed because there is no longer "this" available with Composition API.

Also, moving this to discussions...
