### ISSUE TITLE
Http Loaded Quasar Components

### ISSUE THREAD

**Issue by lewweiming** [quasarframework/quasar#9857]
Is there a way to use Q-components as a Http loaded Vue file?

In my Vue application,

```
<template>
<my-component />
</template>

<script>
export default ({
components: {
    'my-component': Vue.defineAsyncComponent( () => loadModule('Example.vue', options))
}
...
</script>
```

And then in Example.vue

```
<template>
<q-btn label="Hello World" />
</template>
```

But this does not work as <q-btn> is output as raw tags in the rendered HTML. 

Sorry for my english as I'm not sure how best to express my question.

**Comment by yusufkandemir** [comment]
Hi, @lewweiming 👋 First of all, please follow our issue templates when creating issues. Judging from `defineAsyncComponent`, you are using Vue 3, thus Quasar v2. You should be able to include Quasar components in the `components` option like this:

```html
<template>
  <q-btn label="Hello World" />
</template>

<script>
import { QBtn } from 'quasar'

export default {
  components: {
    QBtn
  }
}
</script>
```

I hope that helps, if not, since there is no context of why, how, and what you are trying to achieve, I don't think we can help more than this.
