### ISSUE TITLE
Command: 'quasar new component NewComponent' generating V1 code

### ISSUE THREAD

**Issue by Guactoshi** [quasarframework/quasar#9925]
quasar components generated through the command:

`quasar new component NewComponent'

generate documents compliant to V1. 

This is due to not using 

import { defineComponent } from 'vue'

export default defineComponent({
  ...
})

Not a major issue just might trip some people out.

**Comment by yusufkandemir** [comment]
Hi @Guactoshi, thanks for pointing that out. First of all, it would be great if you can follow the issue report template next time.

`defineComponent` is used in all TS versions(options, composition, and class API), but it's not used in standard js component creation. You can take a look at [`quasar new` command's documentation](https://quasar.dev/quasar-cli/commands-list#new) to check out the list of the formats. The reason is that it's not really mentioned/used much in Vue 3 docs, please take a look at these links:
https://v3.vuejs.org/guide/introduction.html
https://v3.vuejs.org/guide/composition-api-introduction.html

But it's mentioned in [Vue 3's Typescript support documentation](https://v3.vuejs.org/guide/typescript-support.html#defining-vue-components), and that's the reason we are including it in TS versions.

So, an everyday JS developer and Vue user that follows Vue documentation may find `defineComponent` disorienting at first, that's the reason that's not included. Some users may even think that `defineComponent` actually does something(_[which was renamed from `createComponent`](https://github.com/vuejs/vue-next/pull/549)_) and not just a no-op function to provide IntelliSense.
